from typing import overload

import numpy as np
import numpy.typing as npt

def key_number_to_key_name(key_number: int) -> str: ...
def key_name_to_key_number(key_string: str) -> int: ...
def mode_accidentals_to_key_number(mode: int, num_accidentals: int) -> int: ...
def key_number_to_mode_accidentals(key_number: int) -> tuple[int, int]: ...
def qpm_to_bpm(
    quarter_note_tempo: float, numerator: int, denominator: int
) -> float: ...
@overload
def note_number_to_hz(note_number: float) -> float: ...
@overload
def note_number_to_hz(
    note_number: npt.NDArray[np.floating],
) -> npt.NDArray[np.float64]: ...
@overload
def hz_to_note_number(frequency: float) -> float: ...
@overload
def hz_to_note_number(
    frequency: npt.NDArray[np.floating],
) -> npt.NDArray[np.float64]: ...
def note_name_to_number(note_name: str) -> int: ...
def note_number_to_name(note_number: int) -> str: ...
def note_number_to_drum_name(note_number: int) -> str: ...
def drum_name_to_note_number(drum_name: str) -> int: ...
def program_to_instrument_name(program_number: int) -> str: ...
def instrument_name_to_program(instrument_name: str) -> int: ...
def program_to_instrument_class(program_number: int) -> str: ...
def pitch_bend_to_semitones(pitch_bend: int, semitone_range: float = 2.0) -> float: ...
def semitones_to_pitch_bend(semitones: float, semitone_range: float = 2.0) -> int: ...
