/**
 * catalogProviders — the app's ONE provider registry: the id, the label and
 * the palette behind every "who made this track?" in the UI.
 *
 * A provider is the service the audio came from: theDAW's own Stable Audio
 * generations, Suno, Udio, an import — or `thedaw` itself, for the things
 * theDAW makes without a model (a DJ performance set, VJ media). There used to
 * be TWO answers to that question — a DETECTED provider the backend reads out of the file's own
 * embedded metadata (`entry.provider` / `providerLabel` / `providerIsAi` /
 * `providerId`) and a DERIVED one guessed here from `model` + `source`. They
 * are one answer now:
 *
 *   inferProvider(entry) = entry.provider, when the backend sent one
 *                        = the derivation below (model, then source) otherwise
 *
 * The backend fills `provider` with exactly that same precedence, so on a
 * current backend the derivation is only a fallback — for an older backend,
 * and for entry-shaped objects that carry no provider at all (a lineage node
 * knows a `source` and nothing else). It is never a second opinion.
 *
 * That one id feeds the badge, the filter dropdown, the client-side search and
 * the server's `provider=` parameter, so the value a user picks in one place
 * means the same thing in all of them.
 *
 * Display names come from `entryProviderMeta`, which prefers the label the
 * backend sent: this table cannot know the name of a provider it has never
 * heard of, and the backend can.
 *
 * IMPORTANT: the Tailwind badge classes below are LITERAL strings, never
 * runtime-built. Tailwind's compiler purges any class name it can't see as a
 * literal in source, so `text-${color}-300` would vanish in production.
 */

export interface ProviderMeta {
  id: string;
  label: string;
  /** Tailwind color-family stem (e.g. 'purple') keyed into BADGE_CLASSES. */
  color: string;
}

/**
 * The provider-bearing shape of a library entry. Every field is optional so a
 * partial, entry-shaped object (a lineage node, a filter-bar probe) answers
 * the same functions a full `LibraryEntry` does.
 */
export interface ProviderEntryFields {
  /** The backend's detected slug; wins over the derivation. */
  provider?: string | null;
  /** The backend's display name for that slug. */
  providerLabel?: string | null;
  /** Whether the backend calls this provider an AI generation service. */
  providerIsAi?: boolean | null;
  /** The provider's own track id, when the file carried one. */
  providerId?: string | null;
  model?: string | null;
  source?: string | null;
}

/** Built-in providers. Extend freely; unknown ids fall back gracefully. */
export const KNOWN_PROVIDERS: Record<string, ProviderMeta> = {
  'stable-audio': { id: 'stable-audio', label: 'Stable Audio', color: 'purple' },
  // Made IN theDAW, not generated by a model: a DJ performance set, VJ stills
  // and clips, and anything the derivation cannot place. Neutral palette,
  // because it is not an AI generation service.
  thedaw: { id: 'thedaw', label: 'theDAW', color: 'zinc' },
  suno: { id: 'suno', label: 'Suno', color: 'orange' },
  'gemini-magenta': { id: 'gemini-magenta', label: 'Magenta', color: 'sky' },
  magenta: { id: 'magenta', label: 'Magenta', color: 'sky' },
  udio: { id: 'udio', label: 'Udio', color: 'pink' },
  riffusion: { id: 'riffusion', label: 'Riffusion', color: 'teal' },
  // INT-002: theDAW's embedded Lyria 3 Pro sidecar, whose generations are
  // registered as first-class entries by `backend/modules/lyria/importer.py`.
  // The backend sends `provider`/`providerLabel`/`providerIsAi` for every one
  // of them (`library.provider`'s own `lyria` rule), so this row only supplies
  // the palette and the name a partial, entry-shaped object would miss.
  lyria: { id: 'lyria', label: 'Lyria 3 Pro', color: 'emerald' },
  import: { id: 'import', label: 'Imported', color: 'zinc' },
  unknown: { id: 'unknown', label: 'Unknown', color: 'zinc' },
};

/** Display metadata for any provider id (dynamic-safe). */
export const providerMeta = (id: string | null | undefined): ProviderMeta => {
  if (!id) return KNOWN_PROVIDERS.unknown;
  const key = id.toLowerCase();
  if (KNOWN_PROVIDERS[key]) return KNOWN_PROVIDERS[key];
  // Unknown provider: title-case the id and use the neutral color so it still
  // renders a sensible badge.
  const label = id.replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  return { id, label, color: 'zinc' };
};

/**
 * Static badge class strings per color. MUST be literal (not interpolated) so
 * Tailwind's compiler keeps them. Add a row here when introducing a new color.
 */
const BADGE_CLASSES: Record<string, string> = {
  purple: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
  orange: 'text-orange-300 bg-orange-500/10 border-orange-500/30',
  sky: 'text-sky-300 bg-sky-500/10 border-sky-500/30',
  pink: 'text-pink-300 bg-pink-500/10 border-pink-500/30',
  teal: 'text-teal-300 bg-teal-500/10 border-teal-500/30',
  emerald: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
  zinc: 'text-zinc-300 bg-zinc-500/10 border-zinc-500/30',
};

/** Tailwind classes for a provider badge (text + subtle bg/border). */
export const providerBadgeClass = (id: string | null | undefined): string => {
  const { color } = providerMeta(id);
  return BADGE_CLASSES[color] ?? BADGE_CLASSES.zinc;
};

/** A possibly-absent string field, trimmed down to '' or its content. */
const trimmed = (v: unknown): string => (typeof v === 'string' ? v.trim() : '');

/**
 * THE provider id of an entry.
 *
 * The detected slug wins whenever the backend sent one — it read the file's
 * own metadata, which beats any guess made from a model name. With no detected
 * slug the historical derivation answers, unchanged:
 *   model contains 'suno' / 'chirp'      → 'suno'
 *   model contains 'lyria'               → 'lyria'
 *   model contains 'magenta' / 'gemini'  → 'gemini-magenta'
 *   model contains 'udio' / 'riffusion'  → that engine
 *   source === 'import'                  → 'import'
 *   source === 'generate' / 'studio'     → 'stable-audio'
 *   everything else                      → 'thedaw'
 *
 * The detected slug is passed through as the backend spelled it (trimmed
 * only): the same string is compared against other entries' ids AND sent back
 * as `provider=`, so re-casing it here could stop the server matching its own
 * stored value.
 */
export const inferProvider = (e: ProviderEntryFields): string => {
  const detected = trimmed(e.provider);
  if (detected) return detected;
  const hay = `${e.model ?? ''}`.toLowerCase();
  // `source === 'suno'` is the backend's own legacy-Suno arm (db.py infer_provider,
  // rule 2). It has to be here too: a promoted Suno song's model is `chirp-*`, not
  // "suno", and a lineage node carries `source` and nothing else -- without this
  // arm every Suno song in a lineage fell through to the Stable Audio default.
  // `chirp` is Suno's model family (`chirp-v3`, `chirp-v4`, `chirp-crow`, ...)
  // and the only thing an exported Suno song's model column says. Backend twin:
  // `_PROVIDER_BY_MODEL_SUBSTRING` and the SQL fallback (schema step 11).
  if (`${e.source ?? ''}`.toLowerCase() === 'suno' || hay.includes('suno') || hay.includes('chirp')) return 'suno';
  // Lyria is checked before the Gemini arm: its model ids are Google's
  // (`google/lyria-3-pro-preview`) but the songs are not Magenta output.
  // Backend twin: `_legacy_lyria` in provider.py and the db.py substring row.
  if (hay.includes('lyria')) return 'lyria';
  if (hay.includes('magenta') || hay.includes('gemini')) return 'gemini-magenta';
  // "udio" must not be found inside "audio": `stable-audio-3` is not Udio. The
  // backend strips the same word before it looks (db.py, the same rule).
  if (hay.replace(/audio/g, '').includes('udio')) return 'udio';
  if (hay.includes('riffusion')) return 'riffusion';
  if (e.source === 'import') return 'import';
  // theDAW's native generations, plus a studio bounce of one, are Stable Audio.
  if (e.source === 'generate' || e.source === 'studio') return 'stable-audio';
  // Everything else theDAW makes. This arm used to BE 'stable-audio', which
  // badged every DJ performance set and every VJ still/clip "Stable Audio
  // (AI)" — they are made in theDAW, not generated by a model.
  return 'thedaw';
};

/**
 * Display metadata for an ENTRY: this table's row for its id, except that a
 * label the backend sent wins. A provider the table has never heard of is the
 * whole reason — the backend knows its name, we only know the slug.
 */
export const entryProviderMeta = (e: ProviderEntryFields): ProviderMeta => {
  const id = inferProvider(e);
  const base = providerMeta(id);
  const sent = trimmed(e.providerLabel);
  // Never mutate the shared table row: spread into a new object.
  return sent && sent !== base.label ? { ...base, label: sent } : base;
};

/**
 * The ids this file can name that ARE an AI generation service — every id the
 * derivation produces except `import`, `thedaw` and `unknown`.
 */
const AI_PROVIDER_IDS = new Set([
  'stable-audio', 'suno', 'lyria', 'gemini-magenta', 'magenta', 'udio', 'riffusion',
]);

/**
 * Is this entry's provider an AI generation service?
 *
 * The backend's `providerIsAi` is the answer whenever it sent one: it can tell
 * an AI service from a store or a host, and it ships that flag with every
 * provider it detects. Without a flag, the engines above are AI — so every
 * derived id is, except an import, `thedaw` and the unknown bucket — and a
 * slug this app has never heard of is not CLAIMED to be AI on a guess.
 */
export const entryProviderIsAi = (e: ProviderEntryFields): boolean => {
  if (typeof e.providerIsAi === 'boolean') return e.providerIsAi;
  return AI_PROVIDER_IDS.has(inferProvider(e).toLowerCase());
};

/** A reasonable default provider list to seed filter dropdowns before
 *  entries exist / to guarantee the common platforms are always offered. */
export const DEFAULT_PROVIDER_ORDER = [
  'stable-audio', 'thedaw', 'suno', 'lyria', 'gemini-magenta', 'udio', 'riffusion', 'import',
];
