export const EXTRACT_ELEMENT_DESCRIPTION = "Type of element — interactive OR not (e.g., knob, button, slider, toggle, switch, meter, display, waveform, xypad, frame, panel, backplate, label, text, readout, icon, logo, led, graphic)";

export function buildDetectionPrompt(thresholdLevel: string): string {
  return `Analyze this image and identify EVERY distinct UI element — ANYTHING that reads as part of the interface, whether it is interactive or not. This absolutely includes, and you must NOT skip: interactive controls (knobs, buttons, sliders, faders, switches, toggles), meters, displays, readouts, waveforms, XY pads, AND the non-interactive elements — frames / panels / module backplates, text and labels (titles, value readouts, units, captions, any lettering), icons, logos, LEDs, and decorative graphics. Frames and text are first-class UI elements that we WANT: never omit, merge away, or discard an element just because it is a frame, a piece of text/a label, or otherwise non-interactive. Rule of thumb: if it looks like it could be a UI element, include it. ${thresholdLevel} Break down complex groups into their individual components. You must return their precise bounding boxes. Coordinate values (ymin, xmin, ymax, xmax) must be exactly normalized floats between 0.000 and 1.000. Be extremely thorough. Provide a short, descriptive label for each (e.g., 'Reverb Knob', 'Sync Button', 'FREEZE Frame', 'Mix Label', 'Filter Icon').`;
}

export function buildPanelPrompt(thresholdLevel: string): string {
  return `Analyze this audio-plugin UI image and identify every distinct MODULE PANEL / FRAME — any visually grouped section that sits on its own background plate or is enclosed by a border/frame (e.g. 'KAOSS PAD', 'FREEZE CHAMBER', 'OUTPUT'). ${thresholdLevel} Capture the section whether or not it contains interactive controls: a panel that groups controls, a purely decorative frame/backplate, a header / title / branding plate, and a text- or display-only section are ALL wanted — never skip a framed region just because it holds only text, a logo, or a readout and no knobs/buttons. The ONLY thing to exclude is a single loose control on its own (an individual knob, button, or slider that is not a framed section) — those are handled by the per-element pass. A section does NOT need a title to qualify. Return the panel's visible title verbatim, or a short descriptive name if it is untitled/decorative/text-only, and its precise bounding box. Coordinate values (ymin, xmin, ymax, xmax) must be exactly normalized floats between 0.000 and 1.000 and must include the panel's full backplate/frame edge-to-edge.`;
}

