/**
 * Mount test for EDIT's Meter and tempo panel (EditTimeMapPanel.tsx) against
 * the real editor store.
 *
 * The sequence a user makes: add a 7/8 3+2+2 change at bar 9, try groups that
 * do not add up, change its unit, remove it; move the edit cursor, add a tempo
 * change there, type its tempo, make it a ramp, move it to bar 5; add a
 * fermata; select a MIDI clip and take its tempo and meter; press Escape.
 * Every field is a native control with its own label.
 *
 *   cd frontend && npx tsx src/components/audio/EditTimeMapPanel.test.tsx
 */
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';

const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost/', pretendToBeVisual: true });
const win = dom.window;
for (const [key, value] of Object.entries({
  window: win,
  document: win.document,
  navigator: win.navigator,
  HTMLElement: win.HTMLElement,
  Element: win.Element,
  Node: win.Node,
  localStorage: win.localStorage,
  getComputedStyle: win.getComputedStyle.bind(win),
  requestAnimationFrame: win.requestAnimationFrame.bind(win),
  cancelAnimationFrame: win.cancelAnimationFrame.bind(win),
  IS_REACT_ACT_ENVIRONMENT: true,
})) {
  Object.defineProperty(globalThis, key, { value, configurable: true, writable: true });
}
(win.HTMLElement.prototype as unknown as { scrollIntoView: () => void }).scrollIntoView = () => {};

const React = await import('react');
const { act } = React;
const { createRoot } = await import('react-dom/client');
const { EditTimeMapPanel } = await import('./EditTimeMapPanel.tsx');
const { useEditorStore } = await import('../../state/editorStore.ts');
const { sanitizeRollTempoMap } = await import('../../lib/rollTempo.ts');

const st = () => useEditorStore.getState();
const step = (fn: () => void) => act(async () => { fn(); });
const valueSetter = Object.getOwnPropertyDescriptor(win.HTMLInputElement.prototype, 'value')!.set!;
const selectSetter = Object.getOwnPropertyDescriptor(win.HTMLSelectElement.prototype, 'value')!.set!;
const type = (el: HTMLInputElement, text: string) => {
  valueSetter.call(el, text);
  el.dispatchEvent(new win.InputEvent('input', { bubbles: true, inputType: 'insertText', data: text.slice(-1) }));
};
const key = (el: HTMLElement, k: string) => el.dispatchEvent(new win.KeyboardEvent('keydown', { key: k, bubbles: true }));
const choose = (el: HTMLSelectElement, value: string) => {
  selectSetter.call(el, value);
  el.dispatchEvent(new win.Event('change', { bubbles: true }));
};
const byLabel = <T extends HTMLElement>(text: RegExp): T => {
  const label = [...document.querySelectorAll('label')].find((l) => text.test(l.textContent ?? ''));
  assert.ok(label, `a label matching ${text}`);
  const el = document.getElementById(label.htmlFor);
  assert.ok(el, `the control for "${label.textContent}"`);
  return el as T;
};
const button = (text: RegExp): HTMLButtonElement => {
  const b = [...document.querySelectorAll('button')].find((x) => text.test(x.textContent ?? '') || text.test(x.getAttribute('aria-label') ?? ''));
  assert.ok(b, `a button matching ${text}`);
  return b as HTMLButtonElement;
};
const alertText = () => document.querySelector('[role="alert"]')?.textContent ?? '';
const meters = () => st().meterMap.map((s) => `${s.bar}:${s.meter.num}/${s.meter.den}${s.meter.groups.length ? ` ${s.meter.groups.join('+')}` : ''}`);
const beats = () => st().tempoMap.map((e) => (e.fermata ? `${e.beat} hold` : `${e.beat}:${e.bpm}${e.curve === 'linear' ? ' ramp' : ''}`));

st().loadProject({
  tracks: [{ id: 't1', name: 'Strings', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff' }],
  clips: [],
  bpm: 120,
  timeSignature: { num: 4, den: 4 },
});
st().setTempoMap([{ beat: 0, bpm: 120 }]);

let closed = 0;
const sought: number[] = [];
const host = document.createElement('div');
document.body.appendChild(host);
const root = createRoot(host);
await step(() => root.render(<EditTimeMapPanel headingId="etm-h" onClose={() => { closed += 1; }} onSeek={(sec) => { sought.push(sec); }} />));

// Every native field has an id, a name and a label that points at it.
for (const el of [...document.querySelectorAll('input, select')] as HTMLInputElement[]) {
  assert.ok(el.id && el.name, `${el.outerHTML.slice(0, 60)} has an id and a name`);
  assert.ok(document.querySelector(`label[for="${el.id}"]`), `${el.id} has a label`);
}
assert.equal(document.getElementById('etm-h')?.textContent, 'Meter and tempo');

// ── meter ────────────────────────────────────────────────────────────────
await step(() => type(byLabel(/^Add at bar$/), '9'));
await step(() => type(byLabel(/^Meter$/), '7/8 3+2+2'));
await step(() => { (button(/^Add meter$/).form as HTMLFormElement).requestSubmit(); });
assert.deepEqual(meters(), ['0:4/4', '8:7/8 3+2+2'], 'Add meter puts 7/8 3+2+2 at bar 9');

const groups = byLabel<HTMLInputElement>(/^Groups from bar 9/);
await step(() => type(groups, '3+3'));
await step(() => key(groups, 'Enter'));
assert.match(alertText(), /add up to 7/, 'groups that do not add up are refused with a reason');
assert.deepEqual(meters(), ['0:4/4', '8:7/8 3+2+2'], 'and change nothing');

await step(() => choose(byLabel<HTMLSelectElement>(/^Beat unit from bar 9/), '16'));
assert.deepEqual(meters(), ['0:4/4', '8:7/16 3+2+2'], 'the unit select writes at once');

const barField = byLabel<HTMLInputElement>(/^Bar the 7\/16/);
await step(() => type(barField, '1'));
await step(() => key(barField, 'Enter'));
assert.match(alertText(), /bar 2 or later/);
await step(() => type(byLabel<HTMLInputElement>(/^Bar the 7\/16/), '5'));
await step(() => key(byLabel<HTMLInputElement>(/^Bar the 7\/16/), 'Enter'));
assert.deepEqual(meters(), ['0:4/4', '4:7/16 3+2+2'], 'typing a bar moves the change');

await step(() => button(/Remove the 7\/16 3\+2\+2 change at bar 5/).click());
assert.deepEqual(meters(), ['0:4/4']);
await step(() => st().undo());
assert.deepEqual(meters(), ['0:4/4', '4:7/16 3+2+2'], 'the remove is one undo step');
await step(() => st().undo());
assert.deepEqual(meters(), ['0:4/4', '8:7/16 3+2+2']);
await step(() => st().setMeterMap([{ bar: 0, meter: { num: 4, den: 4, groups: [] } }]));

// ── tempo ────────────────────────────────────────────────────────────────
await step(() => st().setEditCursor(4)); // beat 8 at 120 BPM
await step(() => button(/^Add tempo change at edit cursor$/).click());
assert.deepEqual(beats(), ['0:120', '8:120']);
const bpm = byLabel<HTMLInputElement>(/^Tempo at bar 3/);
await step(() => type(bpm, '9'));
assert.deepEqual(beats(), ['0:120', '8:120'], 'a half-typed tempo is not applied');
await step(() => type(bpm, '90'));
await step(() => key(bpm, 'Enter'));
assert.deepEqual(beats(), ['0:120', '8:90']);
await step(() => type(byLabel<HTMLInputElement>(/^Tempo at bar 3/), '400'));
await step(() => key(byLabel<HTMLInputElement>(/^Tempo at bar 3/), 'Enter'));
assert.match(alertText(), /20-300 BPM/);
assert.deepEqual(beats(), ['0:120', '8:90']);
await step(() => choose(byLabel<HTMLSelectElement>(/^How the tempo at bar 3 reaches the next/), 'linear'));
assert.deepEqual(beats(), ['0:120', '8:90 ramp']);
const tBar = byLabel<HTMLInputElement>(/^Bar of the tempo change at bar 3/);
await step(() => type(tBar, '5'));
await step(() => key(tBar, 'Enter'));
assert.deepEqual(beats(), ['0:120', '16:90 ramp'], 'bar 5 of 4/4 is beat 16');
const startBpm = byLabel<HTMLInputElement>(/^Tempo at bar 1,/);
await step(() => type(startBpm, '100'));
await step(() => key(startBpm, 'Escape'));
assert.equal(st().bpm, 120, 'Escape drops a typed value');
await step(() => type(byLabel<HTMLInputElement>(/^Tempo at bar 1,/), '100'));
await step(() => key(byLabel<HTMLInputElement>(/^Tempo at bar 1,/), 'Enter'));
assert.equal(st().bpm, 100, 'the start row is the BPM field');
await step(() => button(/^Add fermata at edit cursor$/).click());
// 4 s at 100 BPM is beat 6.67, on the roll's 960 ticks to the quarter.
assert.deepEqual(beats(), ['0:100', `${Math.round((4 * 100 / 60) * 960) / 960} hold`, '16:90 ramp'], 'a fermata at the edit cursor');
await step(() => button(/Remove the fermata/).click());
assert.ok(!st().tempoMap.some((e) => e.fermata));

// ── Go to bar: bars of the meter map at the tempo map's seconds ─────────
await step(() => {
  st().setMeterMap([{ bar: 0, meter: { num: 4, den: 4, groups: [] } }, { bar: 2, meter: { num: 7, den: 8, groups: [3, 2, 2] } }]);
  st().setTempoMap([{ beat: 0, bpm: 120 }, { beat: 8, bpm: 60 }]);
});
await step(() => type(byLabel<HTMLInputElement>(/^Go to bar$/), '4'));
await step(() => { (button(/^Go$/).form as HTMLFormElement).requestSubmit(); });
assert.deepEqual(sought, [7.5], 'bar 4 after a 7/8 bar at 60 BPM is 7.5 s');

// ── from a MIDI clip ─────────────────────────────────────────────────────
assert.match(document.body.textContent ?? '', /Select a MIDI clip/);
await step(() => {
  st().addClipToTrack({
    id: 'm1', trackId: 't1', label: 'Horns', audioBlob: new Blob([]), mimeType: 'audio/wav', sourceDuration: 8,
    offsetIntoSource: 0, durationSec: 8, startSec: 0, color: '#fff', sourceKind: 'piano-roll', sourceBpm: 72,
    sourceTempoMap: sanitizeRollTempoMap([{ beat: 0, bpm: 72 }, { beat: 8, bpm: 132 }], 72),
    sourceMeterMap: [{ bar: 0, meter: { num: 5, den: 4, groups: [] } }],
    sourcePianoRoll: [{ id: 'n', note: 60, step: 0, length: 4, velocity: 90 }],
  });
  st().setSelected('m1');
});
assert.match(document.body.textContent ?? '', /"Horns": 5\/4, 72-132 BPM/);
await step(() => button(/^Use its tempo and meter from 0:00\.00$/).click());
assert.deepEqual(meters(), ['0:5/4']);
assert.deepEqual(beats(), ['0:72', '8:132']);
assert.ok(button(/^Use its tempo and meter/).disabled, 'nothing left to take');

await step(() => key(document.getElementById('etm-h') as HTMLElement, 'Escape'));
assert.equal(closed, 1, 'Escape closes the panel');

await step(() => root.unmount());
console.log('EditTimeMapPanel: ok');
