/**
 * ExportDialog: the UI over `exportDialogModel` (T25c).
 *
 * Pins the three things the ticket cares about: every option the model
 * offers is rendered AND selectable (what / range / format / destination /
 * name / tail), the dialog's opening defaults reproduce the previous
 * hardcoded COMMIT EDIT export exactly (`mixdownRequest()`'s fidelity flags,
 * `mixdown` kind, `both` destination, `range: null`), and the plan handed to
 * `onExport` is exactly `buildRenderRequest(state)`'s own output — the
 * dialog does not add or drop a field.
 *
 * Ids are generated by `useId()`, so they carry an unpredictable prefix; every
 * query below matches on the fixed SUFFIX this component builds them from
 * (`-what-stems`, `-range-custom`, `-track-t1`, …) rather than the id whole.
 *
 * Run: `npx tsx src/components/audio/ExportDialog.b12.test.tsx`
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';
import type { ExportDialogState, ExportRenderPlan } from '../../lib/render/exportDialogModel';
import type { ImportRequest, LibraryEntry } from '../../state/libraryEntry';
import type { RenderJob } from '../../state/renderJobs';

async function main(): Promise<void> {
  const { ExportDialog } = await import('./ExportDialog.tsx');
  const { rangeFromSeconds } = await import('../../lib/render/renderRange.ts');
  const exportDialogModel = await import('../../lib/render/exportDialogModel.ts');
  const {
    mixdownRequest, deliverExport, runExportPlan, runExportPlanItem,
  } = await import('./WaveformEditor.tsx');
  const { useRenderJobs, startRenderRunner } = await import('../../state/renderJobs.ts');
  const { useLibraryStore } = await import('../../state/libraryStore.ts');

  const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', {
    url: 'http://localhost/',
    pretendToBeVisual: true,
  });
  const g = globalThis as unknown as Record<string, unknown>;
  for (const key of [
    'window', 'document', 'HTMLElement', 'HTMLInputElement', 'HTMLSelectElement', 'HTMLButtonElement',
    'Node', 'Event', 'KeyboardEvent', 'getComputedStyle',
  ]) {
    Object.defineProperty(g, key, {
      value: (dom.window as unknown as Record<string, unknown>)[key],
      configurable: true,
      writable: true,
    });
  }
  g.IS_REACT_ACT_ENVIRONMENT = true;

  const React = await import('react');
  const { createRoot } = await import('react-dom/client');
  const { act } = React;
  const doc = dom.window.document;
  const host = doc.getElementById('root')!;

  const byIdSuffix = (root: ParentNode, suffix: string): HTMLElement => {
    const el = Array.from(root.querySelectorAll<HTMLElement>('[id]')).find((e) => e.id.endsWith(suffix));
    assert.ok(el, `an element with id ending "${suffix}" renders`);
    return el!;
  };
  const setNativeValue = async (el: HTMLInputElement | HTMLSelectElement, value: string): Promise<void> => {
    const proto = el instanceof dom.window.HTMLSelectElement ? dom.window.HTMLSelectElement.prototype : dom.window.HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, 'value')!.set!;
    await act(async () => {
      setter.call(el, value);
      el.dispatchEvent(new dom.window.Event(el instanceof dom.window.HTMLSelectElement ? 'change' : 'input', { bubbles: true }));
    });
  };

  type Captured = { plan: ExportRenderPlan; state: ExportDialogState };

  /** Mounts a fresh dialog instance and returns handles into it plus the
   *  props' onExport/onClose call log — every case gets an untouched dialog,
   *  since useId/opening state are computed once at mount. */
  const mount = (props: {
    projectEndSec: number;
    selectionSec: { startSec: number; endSec: number } | null;
    tracks: { id: string; name: string }[];
    selectedClipIds: string[];
    defaultName?: string;
  }) => {
    const exported: Captured[] = [];
    let closedCount = 0;
    const root = createRoot(host);
    const rerender = async () => act(async () => {
      root.render(
        React.createElement(ExportDialog, {
          ...props,
          onClose: () => { closedCount += 1; },
          onExport: (plan: ExportRenderPlan, state: ExportDialogState) => { exported.push({ plan, state }); },
        }),
      );
    });
    return { root, rerender, exported, closedCount: () => closedCount };
  };

  const findButton = (dialog: ParentNode, text: string): HTMLButtonElement => {
    const btn = Array.from(dialog.querySelectorAll<HTMLButtonElement>('button')).find((b) => b.textContent === text);
    assert.ok(btn, `a button labelled "${text}" renders`);
    return btn!;
  };
  const clickSubmit = (dialog: ParentNode): HTMLButtonElement => findButton(dialog, 'Export');

  /* ── every option the model offers is rendered and selectable ───────────── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: { startSec: 5, endSec: 15 },
      tracks: [{ id: 't1', name: 'Drums' }, { id: 't2', name: 'Bass' }],
      selectedClipIds: ['c1', 'c2'],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    assert.ok(dialog, 'the dialog renders into a role="dialog" container');
    assert.equal(dialog.getAttribute('aria-modal'), 'true');

    // what: mix / stems / clips, each a selectable radio.
    for (const suffix of ['-what-mix', '-what-stems', '-what-clips']) {
      const input = byIdSuffix(dialog, suffix) as HTMLInputElement;
      assert.equal(input.type, 'radio');
      assert.equal(input.disabled, false, `${suffix} is selectable — a selection exists`);
    }
    // range: project / selection / custom, each selectable (a selection exists).
    for (const suffix of ['-range-project', '-range-selection', '-range-custom']) {
      const input = byIdSuffix(dialog, suffix) as HTMLInputElement;
      assert.equal(input.type, 'radio');
      assert.equal(input.disabled, false, `${suffix} is selectable`);
    }
    // format: every EXPORT_FORMATS entry (the two WAVs and MIDI), as a real, changeable <select>.
    const formatSel = byIdSuffix(dialog, '-format') as HTMLSelectElement;
    assert.equal(formatSel.tagName, 'SELECT');
    assert.deepEqual(Array.from(formatSel.options).map((o) => o.value), ['wav16', 'wav32', 'midi']);
    // destination: all three ExportDestination values.
    const destSel = byIdSuffix(dialog, '-destination') as HTMLSelectElement;
    assert.deepEqual(Array.from(destSel.options).map((o) => o.value), ['both', 'library', 'download']);
    // name + tail: real, changeable text/number inputs.
    const nameInput = byIdSuffix(dialog, '-name') as HTMLInputElement;
    assert.equal(nameInput.type, 'text');
    const tailInput = byIdSuffix(dialog, '-tail') as HTMLInputElement;
    assert.equal(tailInput.type, 'number');

    // Every native field has a real label association (project accessibility rule).
    for (const id of [formatSel.id, destSel.id, nameInput.id, tailInput.id]) {
      const label = dialog.querySelector(`label[for="${id}"]`);
      assert.ok(label, `#${id} has a <label for>`);
    }

    await act(async () => m.root.unmount());
  }

  /* ── defaults reproduce the previous hardcoded WAV export exactly ───────── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: null,
      tracks: [],
      selectedClipIds: [],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await act(async () => { clickSubmit(dialog).click(); });

    assert.equal(m.exported.length, 1, 'confirming with untouched defaults exports exactly once');
    const { plan } = m.exported[0];
    assert.equal(plan.rangeError, null);
    assert.equal(plan.items.length, 1, 'the default "mix" export builds one item');
    const [item] = plan.items;
    assert.equal(item.kind, 'mixdown');
    assert.equal(item.label, 'my session.wav');
    assert.equal(item.range, null, 'the default range is the whole project — no range object');
    assert.equal(item.destination, 'both', 'library + download, same as commitEdit\'s importEntry + saveFile');
    assert.deepEqual(
      item.request,
      { ...mixdownRequest(), tailSec: 0 },
      "matches WaveformEditor's mixdownRequest() exactly (not a transcribed literal — F/finding-10: a literal keeps "
      + 'passing after mixdownRequest() itself changes, and gives no protection) — master + every track\'s rack, '
      + 'automation, mute AND solo, 16-bit',
    );
    assert.equal(m.closedCount(), 1, 'confirming closes the dialog');
    await act(async () => m.root.unmount());
  }

  /* ── forces an explicit blank name to pin the `canExport` guard itself.
   *  The app never actually PASSES `defaultName: ''` — the real call site
   *  is `defaultName={mixdownName.trim() || undefined}`, so an untyped
   *  mixdown name reaches this dialog as `undefined` and resolves to
   *  `defaultExportState`'s own default ('mixdown'), not ''. That wiring is
   *  covered separately, below. This block only proves Export stays
   *  disabled until a name is typed, never silently writing "<blank>.wav" ── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: null,
      tracks: [],
      selectedClipIds: [],
      defaultName: '',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    const nameInput = byIdSuffix(dialog, '-name') as HTMLInputElement;
    assert.equal(nameInput.value, '', "opens with the app's real default: an untyped mixdown name");
    assert.equal(clickSubmit(dialog).disabled, true, 'Export is disabled with no name typed — finding 2\'s ".wav" bug');
    await act(async () => { clickSubmit(dialog).click(); });
    assert.equal(m.exported.length, 0, 'a disabled Export click exports nothing, even with untouched defaults');

    await setNativeValue(nameInput, '   ');
    assert.equal(clickSubmit(dialog).disabled, true, 'a whitespace-only name does not re-enable Export');

    await setNativeValue(nameInput, 'my session');
    assert.equal(clickSubmit(dialog).disabled, false, 'typing a real name re-enables Export');
    await act(async () => { clickSubmit(dialog).click(); });
    assert.equal(m.exported.length, 1);
    assert.equal(m.exported[0].plan.items[0].label, 'my session.wav');
    await act(async () => m.root.unmount());
  }

  /* ── a selection range is honoured when one exists ───────────────────────── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: { startSec: 5, endSec: 15 },
      tracks: [],
      selectedClipIds: [],
      defaultName: 'ranged',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await act(async () => { (byIdSuffix(dialog, '-range-selection') as HTMLInputElement).click(); });
    await act(async () => { clickSubmit(dialog).click(); });

    const { plan } = m.exported[0];
    assert.equal(plan.rangeError, null);
    const expectedRange = rangeFromSeconds(5, 15, { tailSec: 0 });
    assert.deepEqual(plan.items[0].range, expectedRange, 'the built range matches rangeFromSeconds(5, 15) exactly');
    await act(async () => m.root.unmount());
  }

  /* ── stems: selecting tracks changes what is exported ────────────────────── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: null,
      tracks: [{ id: 't1', name: 'Drums' }, { id: 't2', name: 'Bass' }],
      selectedClipIds: [],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await act(async () => { (byIdSuffix(dialog, '-what-stems') as HTMLInputElement).click(); });
    // Export disabled with no track picked yet.
    assert.equal(clickSubmit(dialog).disabled, true, 'stems with no track picked cannot be exported');
    await act(async () => { (byIdSuffix(dialog, '-track-t1') as HTMLInputElement).click(); });
    assert.equal(clickSubmit(dialog).disabled, false, 'picking a track re-enables Export');
    await act(async () => { clickSubmit(dialog).click(); });

    const { plan } = m.exported[0];
    assert.equal(plan.items.length, 1, 'one item for the one track picked');
    assert.equal(plan.items[0].kind, 'stem');
    assert.equal(plan.items[0].trackId, 't1');
    assert.equal(plan.items[0].label, 'my session — t1.wav');
    await act(async () => m.root.unmount());
  }

  /* ── clips: the current clip selection is what gets exported ─────────────── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: null,
      tracks: [],
      selectedClipIds: ['c1', 'c2'],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await act(async () => { (byIdSuffix(dialog, '-what-clips') as HTMLInputElement).click(); });
    await act(async () => { clickSubmit(dialog).click(); });

    const { plan } = m.exported[0];
    assert.equal(plan.items[0].kind, 'selection');
    assert.deepEqual(plan.items[0].request.scope, { kind: 'selection', clipIds: ['c1', 'c2'] });
    await act(async () => m.root.unmount());
  }

  /* ── format and destination changes flow straight into the plan ──────────── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: null,
      tracks: [],
      selectedClipIds: [],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await setNativeValue(byIdSuffix(dialog, '-format') as HTMLSelectElement, 'wav32');
    await setNativeValue(byIdSuffix(dialog, '-destination') as HTMLSelectElement, 'library');
    await act(async () => { clickSubmit(dialog).click(); });

    const { plan } = m.exported[0];
    assert.equal(plan.items[0].request.float32, true, 'wav32 sets float32');
    assert.equal(plan.items[0].destination, 'library');
    await act(async () => m.root.unmount());
  }

  /* ── MIDI: the notes as one file, no tail, saved where the user chooses ─── */
  {
    const m = mount({
      projectEndSec: 120,
      selectionSec: { startSec: 8, endSec: 24 },
      tracks: [{ id: 't1', name: 'Strings' }, { id: 't2', name: 'Horns' }],
      selectedClipIds: [],
      defaultName: 'symphony',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await setNativeValue(byIdSuffix(dialog, '-format') as HTMLSelectElement, 'midi');
    // The destination select gives way to a Save As note: a MIDI file is not a library take.
    assert.equal(dialog.querySelector('[id$="-destination"]'), null, 'no destination select for MIDI');
    assert.match(dialog.textContent ?? '', /Save As: where you choose/);
    // The tail has nothing to ring out: it is disabled and says why.
    const tail = byIdSuffix(dialog, '-tail') as HTMLInputElement;
    assert.equal(tail.disabled, true, 'the tail is disabled for MIDI');
    const tailNote = doc.getElementById(tail.getAttribute('aria-describedby') ?? '');
    assert.match(tailNote?.textContent ?? '', /no tail/);
    // WHAT names one file for every choice.
    assert.match(dialog.textContent ?? '', /Selected tracks — one file holding those tracks/);
    await act(async () => { (byIdSuffix(dialog, '-what-stems') as HTMLInputElement).click(); });
    await act(async () => { (byIdSuffix(dialog, '-track-t2') as HTMLInputElement).click(); });
    await act(async () => { (byIdSuffix(dialog, '-range-selection') as HTMLInputElement).click(); });
    assert.match(dialog.textContent ?? '', /symphony\.mid — Save As/, 'the preview names the file');
    await act(async () => { clickSubmit(dialog).click(); });
    const { plan, state } = m.exported[0];
    assert.deepEqual(plan.items, [], 'MIDI renders no audio');
    assert.deepEqual(plan.midiItems, [{ label: 'symphony.mid', scope: { kind: 'tracks', trackIds: ['t2'] }, rangeSec: { startSec: 8, endSec: 24 } }]);
    assert.deepEqual(plan, exportDialogModel.buildRenderRequest(state), 'the plan is the model’s, unmodified');
    // Every word of the dialog is 12px or larger.
    const sized: Element[] = Array.from(dialog.querySelectorAll('[class*="text-["]'));
    for (const el of sized) {
      const sizes = (el.getAttribute('class') ?? '').match(/text-\[(\d+)px\]/g) ?? [];
      for (const s of sizes) assert.ok(Number(s.replace(/\D/g, '')) >= 12, `${s} is under 12px`);
    }
    await act(async () => m.root.unmount());
  }

  /* ── the dialog passes the model's output through unmodified ─────────────── */
  {
    const m = mount({
      projectEndSec: 90,
      selectionSec: null,
      tracks: [],
      selectedClipIds: [],
      defaultName: 'take two',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await setNativeValue(byIdSuffix(dialog, '-tail') as HTMLInputElement, '4');
    await act(async () => { clickSubmit(dialog).click(); });

    const { plan, state } = m.exported[0];
    const rebuilt = exportDialogModel.buildRenderRequest(state);
    assert.deepEqual(plan, rebuilt, "onExport's plan is exactly buildRenderRequest(state) — nothing added, nothing stripped");
    await act(async () => m.root.unmount());
  }

  /* ── Cancel closes without exporting; an empty custom range disables Export ── */
  {
    const m = mount({
      projectEndSec: 90,
      selectionSec: null,
      tracks: [],
      selectedClipIds: [],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    const cancelBtn = findButton(dialog, 'Cancel');
    await act(async () => { cancelBtn.click(); });
    assert.equal(m.closedCount(), 1, 'Cancel closes the dialog');
    assert.equal(m.exported.length, 0, 'Cancel never exports');
    await act(async () => m.root.unmount());
  }
  {
    const m = mount({
      projectEndSec: 90,
      selectionSec: null,
      tracks: [],
      selectedClipIds: [],
      defaultName: 'my session',
    });
    await m.rerender();
    const dialog = doc.body.querySelector('[role="dialog"]')!;
    await act(async () => { (byIdSuffix(dialog, '-range-custom') as HTMLInputElement).click(); });
    const start = byIdSuffix(dialog, '-range-start') as HTMLInputElement;
    const end = byIdSuffix(dialog, '-range-end') as HTMLInputElement;
    await setNativeValue(start, '10');
    await setNativeValue(end, '10');
    assert.equal(clickSubmit(dialog).disabled, true, 'an empty custom range disables Export');
    await act(async () => { clickSubmit(dialog).click(); });
    assert.equal(m.exported.length, 0, 'a disabled Export click exports nothing');
    await act(async () => m.root.unmount());
  }

  /* ── deliverExport: destination gating + atomicity (T25c findings 3 & 6) ── */
  {
    const realFetch = globalThis.fetch;
    const calls: { url: string }[] = [];
    globalThis.fetch = (async (input: RequestInfo | URL) => {
      const url = typeof input === 'string' ? input : String(input);
      calls.push({ url });
      if (url === '/api/storage/pick-save') {
        return new Response(
          JSON.stringify({ path: null, cancelled: true }),
          { status: 200, headers: { 'Content-Type': 'application/json' } },
        );
      }
      return new Response('', { status: 404 });
    }) as typeof fetch;
    const realImportEntry = useLibraryStore.getState().importEntry;
    const blob = new Blob(['x']);

    // library-only: importEntry runs, saveFile's network path is never reached.
    {
      let imported: string | null = null;
      useLibraryStore.setState({
        importEntry: async (req: ImportRequest) => { imported = req.filename; return {} as LibraryEntry; },
      });
      calls.length = 0;
      await deliverExport(blob, 1, { label: 'a.wav', kind: 'mixdown', destination: 'library' });
      assert.equal(imported, 'a.wav', 'library destination calls importEntry with the item label');
      assert.equal(calls.length, 0, "library-only never touches saveFile's Save As");
    }

    // download-only: saveFile reaches the network, importEntry is never called.
    {
      let importCalled = false;
      useLibraryStore.setState({ importEntry: async () => { importCalled = true; return {} as LibraryEntry; } });
      calls.length = 0;
      await deliverExport(blob, 1, { label: 'b.wav', kind: 'stem', destination: 'download' });
      assert.equal(importCalled, false, 'download-only never calls importEntry');
      assert.ok(calls.some((c) => c.url === '/api/storage/pick-save'), "download-only reaches saveFile's Save As");
    }

    // both, library import fails: the download half must still run (finding 6)
    // — a failing library half must never cancel the other, and deliverExport
    // itself must not reject (the caller has no .catch around it).
    {
      let importAttempted = false;
      useLibraryStore.setState({
        importEntry: async () => { importAttempted = true; throw new Error('disk full'); },
      });
      calls.length = 0;
      await assert.doesNotReject(
        deliverExport(blob, 1, { label: 'c.wav', kind: 'selection', destination: 'both' }),
        'a failing library import must not reject deliverExport',
      );
      assert.ok(importAttempted, 'the library import was attempted');
      assert.ok(
        calls.some((c) => c.url === '/api/storage/pick-save'),
        'the download half still ran after the library half threw — the two halves are independent',
      );
    }

    useLibraryStore.setState({ importEntry: realImportEntry });
    globalThis.fetch = realFetch;
  }

  /* ── runExportPlan routes each item onto the RIGHT RenderJobKind (T25c
   *  findings 3, 4, 5): a mix or clip-selection item must land on the NEW
   *  'export' kind — never 'mixdown' (always both destinations, and touches
   *  the remembered Save-As target the dialog never should) and never
   *  'selection' (hands the blob to MAKE and switches tabs) — while a stem
   *  item keeps using the existing 'stem' kind and still delivers once its
   *  job settles. Proven against the REAL queue (`startRenderRunner`,
   *  `useRenderJobs`) with only the render itself stubbed out — `runRenderJob`
   *  needs a real/stand-in `OfflineAudioContext` this seam doesn't reach, so
   *  `runExportJob`'s own render+encode body stays covered by TypeScript and
   *  manual QA only, not this suite. ─────────────────────────────────────── */
  {
    const realFetch2 = globalThis.fetch;
    globalThis.fetch = (async () => new Response(
      JSON.stringify({ path: null, cancelled: true }),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )) as typeof fetch;

    const seenJobs: Array<Pick<RenderJob, 'kind' | 'destination' | 'exportItemKind' | 'label' | 'trackId'>> = [];
    const stop = startRenderRunner({
      run: async (job: RenderJob) => {
        seenJobs.push({
          kind: job.kind, destination: job.destination, exportItemKind: job.exportItemKind,
          label: job.label, trackId: job.trackId,
        });
        return { blob: new Blob(['x']), durationSec: 1 };
      },
    });
    const realImportEntry = useLibraryStore.getState().importEntry;
    const imported: string[] = [];
    useLibraryStore.setState({
      importEntry: async (req: ImportRequest) => { imported.push(req.filename); return {} as LibraryEntry; },
    });

    const base = (name: string) => exportDialogModel.defaultExportState({ projectEndSec: 10, selectionSec: null, name });
    const mixPlan = exportDialogModel.buildRenderRequest({ ...base('mix'), destination: 'library' });
    const stemPlan = exportDialogModel.buildRenderRequest({
      ...base('stem'), what: { kind: 'stems', trackIds: ['t1'] }, destination: 'both',
    });
    const clipPlan = exportDialogModel.buildRenderRequest({
      ...base('clip'), what: { kind: 'clips', clipIds: ['c1'] }, destination: 'both',
    });
    const plan: ExportRenderPlan = {
      rangeError: null,
      items: [mixPlan.items[0], stemPlan.items[0], clipPlan.items[0]],
      midiItems: [],
    };

    runExportPlan(plan);
    // `runExportPlan` fires every item without awaiting between them; wait for
    // the queue (one job at a time) to settle all three.
    const deadline = Date.now() + 5000;
    while (seenJobs.length < 3 && Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 10));
    }
    assert.equal(seenJobs.length, 3, 'all three plan items reached the queue');

    assert.equal(seenJobs[0].kind, 'export', "a mix export item must not enqueue RenderJobKind 'mixdown'");
    assert.equal(seenJobs[0].destination, 'library', "the mix item's chosen destination reaches the job");
    assert.equal(seenJobs[0].exportItemKind, 'mixdown');

    assert.equal(seenJobs[1].kind, 'stem', 'a stem item still uses the existing stem job kind, unchanged');
    assert.equal(seenJobs[1].trackId, 't1');

    assert.equal(seenJobs[2].kind, 'export', "a clip-selection export item must not enqueue RenderJobKind 'selection' (misroutes to MAKE)");
    assert.equal(seenJobs[2].destination, 'both');
    assert.equal(seenJobs[2].exportItemKind, 'selection');

    // The stem item's delivery is driven by `runExportPlanItem` itself (after
    // its job settles), so it is the one item whose `deliverExport` call our
    // stubbed runner's `run` never reaches — confirm it still happened.
    const stemDeadline = Date.now() + 2000;
    while (imported.length < 1 && Date.now() < stemDeadline) {
      await new Promise((r) => setTimeout(r, 10));
    }
    assert.ok(imported.some((f) => f.includes('t1')), 'the stem item still delivers to the library after its job settles');

    useLibraryStore.setState({ importEntry: realImportEntry });
    globalThis.fetch = realFetch2;
    stop();
  }

  /* ── the `|| undefined` wiring at the real call site (T25c finding 2's
   *  follow-up). Nothing renders `WaveformEditor` in any suite, so this is a
   *  source-level assertion rather than a rendered one: it pins that an
   *  untyped `mixdownName` ('') reaches `ExportDialog` as `undefined`, not
   *  '', so `defaultExportState` falls through to its own 'mixdown'
   *  default instead of opening on a blank name. ──────────────────────── */
  {
    const waveformEditorPath = fileURLToPath(new URL('./WaveformEditor.tsx', import.meta.url));
    const source = readFileSync(waveformEditorPath, 'utf8');
    assert.ok(
      source.includes("defaultName={mixdownName.trim() || undefined}"),
      "WaveformEditor must pass ExportDialog's defaultName as `mixdownName.trim() || undefined`, "
      + "not a raw '' — an untyped mixdown name must resolve through defaultExportState's own "
      + "'mixdown' default, never open the dialog on a blank name",
    );
  }

  console.log('ExportDialog: all assertions passed');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
