// Run with: npx tsx src/components/audio/insertAllStemsStore.test.ts
/**
 * F14, proven against the REAL editor store (audit MINOR #5): folder track +
 * every stem track/clip + muting the parent all land as ONE undo step, and
 * one `undo()` restores everything — not asserted from reading the code, but
 * from actually calling the store's own `undo()` and checking the document.
 *
 * `applyAllStemsInsert` is the store-mutation core `insertAllStemsBesideClip`
 * delegates to after its fetch/decode I/O — split out specifically so this is
 * testable without mounting the editor or faking a fetch/AudioContext.
 */
import assert from 'node:assert/strict';
import { applyAllStemsInsert } from './WaveformEditor.tsx';
import { useEditorStore, type AudioClip } from '../../state/editorStore.ts';
import type { StemRef } from '../../lib/djStems.ts';

const st = () => useEditorStore.getState();

const clip = (over: Partial<AudioClip> = {}): AudioClip =>
  ({
    id: 'parent',
    trackId: 'track-parent',
    label: 'Song',
    audioBlob: new Blob(['x']),
    mimeType: 'audio/wav',
    sourceDuration: 10,
    offsetIntoSource: 0,
    durationSec: 10,
    startSec: 0,
    color: '#fff',
    fadeInSec: 0,
    fadeOutSec: 0,
    gain: 1,
    muted: false,
    ...over,
  }) as AudioClip;

const ref = (name: string): StemRef => ({ name, url: `/api/library/stems/${name}/audio` });

const decodedStem = (name: string) => ({
  ref: ref(name),
  blob: new Blob([name]),
  peaks: new Float32Array([0.5]),
  duration: 10,
});

// Reset to a known document: one track, one clip, empty history.
function seed(): void {
  useEditorStore.setState({
    tracks: [{
      id: 'track-parent', name: 'Parent', nameAutoGenerated: false, volume: 1, pan: 0,
      mute: false, solo: false, color: '#fff',
    }],
    clips: [clip()],
    buses: [],
    routing: st().routing,
    _undo: [],
    _redo: [],
  });
}

// --- ONE undo step for the whole operation ----------------------------------
{
  seed();
  const before = st();
  // `seed()`'s own setState is itself a document change (fresh array
  // references for `tracks`/`clips`), so it records its OWN step even
  // though `_undo` was set to `[]` in the same call — the recorder's
  // subscriber fires from the write and appends after. That step is not
  // what is under test; the assertion below is on the DELTA it causes, not
  // on an absolute `_undo.length`.
  const baselineUndoSteps = before._undo.length;
  assert.equal(before.tracks.length, 1);
  assert.equal(before.clips.length, 1);

  const result = applyAllStemsInsert(
    'parent',
    [decodedStem('vocals'), decodedStem('drums')],
    [],
  );
  assert.ok(result);
  assert.equal(result?.parentLabel, 'Song');
  assert.equal(result?.insertedTrackCount, 2);
  assert.deepEqual(result?.skippedAggregates, []);

  const after = st();
  // 1 folder + 2 stem tracks, on top of the original parent track.
  assert.equal(after.tracks.length, 4);
  const folder = after.tracks.find((t) => t.isFolder);
  assert.ok(folder, 'a folder track was added');
  assert.equal(folder?.name, 'Song stems');
  const stemTracks = after.tracks.filter((t) => t.parentTrackId === folder?.id);
  assert.equal(stemTracks.length, 2, 'both stem tracks are parented to the folder');
  assert.deepEqual(stemTracks.map((t) => t.name).sort(), ['Song · drums', 'Song · vocals']);

  // 1 original clip + 2 stem clips.
  assert.equal(after.clips.length, 3);
  const parentClip = after.clips.find((c) => c.id === 'parent');
  assert.equal(parentClip?.muted, true, 'the parent clip is muted');

  // ONE undo step for the whole burst (folder + 2 tracks + 2 clips + mute) —
  // the count grew by exactly 1, not one per track/clip write.
  assert.equal(after._undo.length, baselineUndoSteps + 1, 'exactly one undo step');

  // undo() restores EVERYTHING in one call.
  st().undo();
  const restored = st();
  assert.equal(restored.tracks.length, 1, 'the folder + stem tracks are gone');
  assert.equal(restored.clips.length, 1, 'the stem clips are gone');
  assert.equal(restored.clips[0].muted, false, 'the parent clip is unmuted again');
  assert.equal(restored._undo.length, baselineUndoSteps, 'undo popped exactly the one step');
}

// --- A gone clip: no write, no undo step, null result -----------------------
{
  seed();
  const baselineUndoSteps = st()._undo.length;
  const baselineTracks = st().tracks.length;
  const result = applyAllStemsInsert('does-not-exist', [decodedStem('vocals')], []);
  assert.equal(result, null);
  assert.equal(st()._undo.length, baselineUndoSteps, 'nothing was written');
  assert.equal(st().tracks.length, baselineTracks);
}

console.log('insertAllStemsStore: ok');
