/**
 * Mount test for EDIT's "Empty MIDI part…" dialog (NewMidiPartDialog.tsx)
 * against the real editor store.
 *
 * The sequence a user makes: the arrangement is 4/4 at 96 BPM for four bars,
 * then 7/8 3+2+2 at 72. They open the dialog on bar 5 below every track, read
 * the meter and tempo the part will take, pick Violin, type 8 bars and a track
 * name, and create it; then a drum part; then a part on the cello track, which
 * takes the cello's instrument; a length of 0 is refused; Escape closes.
 * Every field is a native control with its own label.
 *
 *   cd frontend && npx tsx src/components/audio/NewMidiPartDialog.test.tsx
 */
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';

const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost/', pretendToBeVisual: true });
const win = dom.window;
for (const [key, value] of Object.entries({
  window: win,
  document: win.document,
  navigator: win.navigator,
  HTMLElement: win.HTMLElement,
  Element: win.Element,
  Node: win.Node,
  localStorage: win.localStorage,
  getComputedStyle: win.getComputedStyle.bind(win),
  requestAnimationFrame: win.requestAnimationFrame.bind(win),
  cancelAnimationFrame: win.cancelAnimationFrame.bind(win),
  IS_REACT_ACT_ENVIRONMENT: true,
})) {
  Object.defineProperty(globalThis, key, { value, configurable: true, writable: true });
}

const React = await import('react');
const { act } = React;
const { createRoot } = await import('react-dom/client');
const { NewMidiPartDialog } = await import('./NewMidiPartDialog.tsx');
const { useEditorStore } = await import('../../state/editorStore.ts');
const { editBarStartSec } = await import('../../lib/editTimeMap.ts');

const st = () => useEditorStore.getState();
const valueSetter = Object.getOwnPropertyDescriptor(win.HTMLInputElement.prototype, 'value')!.set!;
const selectSetter = Object.getOwnPropertyDescriptor(win.HTMLSelectElement.prototype, 'value')!.set!;
const type = (el: HTMLInputElement, text: string) => {
  valueSetter.call(el, text);
  el.dispatchEvent(new win.InputEvent('input', { bubbles: true, inputType: 'insertText', data: text.slice(-1) }));
};
const choose = (el: HTMLSelectElement, value: string) => {
  selectSetter.call(el, value);
  el.dispatchEvent(new win.Event('change', { bubbles: true }));
};
const byLabel = <T extends HTMLElement>(text: RegExp): T => {
  const label = [...document.querySelectorAll('label')].find((l) => text.test(l.textContent ?? ''));
  assert.ok(label, `a label matching ${text}`);
  const el = document.getElementById(label.htmlFor);
  assert.ok(el, `the control for "${label.textContent}"`);
  return el as T;
};
const hasLabel = (text: RegExp): boolean => [...document.querySelectorAll('label')].some((l) => text.test(l.textContent ?? ''));
const button = (text: RegExp): HTMLButtonElement => {
  const b = [...document.querySelectorAll('button')].find((x) => text.test(x.textContent ?? '') || text.test(x.getAttribute('aria-label') ?? ''));
  assert.ok(b, `a button matching ${text}`);
  return b as HTMLButtonElement;
};
const alertText = () => document.querySelector('[role="alert"]')?.textContent ?? '';

st().loadProject({
  tracks: [{ id: 'vc', name: 'Cello', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', instrumentProgram: 42 }],
  clips: [],
  bpm: 96,
});
st().setMeterAt(4, { num: 7, den: 8, groups: [3, 2, 2] });
st().addTempoEvent({ beat: 16, bpm: 72 });

let closed = 0;
const created: string[] = [];
const host = document.createElement('div');
document.body.appendChild(host);
const root = createRoot(host);
const mount = async (trackId: string | null, atSec: number) => {
  await act(async () => {
    root.render(React.createElement(NewMidiPartDialog, {
      key: `${trackId}-${atSec}-${created.length}-${closed}`,
      headingId: 'np-h',
      trackId,
      atSec,
      onClose: () => { closed += 1; },
      onCreated: (id: string) => { created.push(id); },
    }));
  });
};

// ── a new track at bar 5 ──────────────────────────────────────────────────────
await mount(null, editBarStartSec(st(), 4) + 0.1);
assert.equal(document.getElementById('np-h')?.textContent, 'New MIDI part');
// Every native control has a label that points at it.
for (const el of document.querySelectorAll('input, select')) {
  const id = el.getAttribute('id');
  assert.ok(id, 'every control has an id');
  assert.ok(el.getAttribute('name'), `${id} has a name`);
  assert.ok(document.querySelector(`label[for="${id}"]`), `${id} has a label`);
}
assert.equal(byLabel<HTMLInputElement>(/Starts at bar/).value, '5', 'it starts on the bar the menu was opened in');
assert.match(alertText(), /Bar 5: 7\/8 3\+2\+2 at 72 BPM/, 'and says the meter and tempo the part will take');
assert.ok(hasLabel(/Track name/), 'a new track can be named');
const instrument = byLabel<HTMLSelectElement>(/^Instrument$/);
assert.equal(instrument.querySelectorAll('optgroup').length, 16, 'the sixteen GM families');
assert.equal(instrument.querySelectorAll('option').length, 128);
await act(async () => choose(instrument, '40'));
await act(async () => type(byLabel<HTMLInputElement>(/Length in bars/), '8'));
await act(async () => type(byLabel<HTMLInputElement>(/Track name/), 'Violin I'));
assert.equal(byLabel<HTMLInputElement>(/Track name/).placeholder, 'Violin', 'the placeholder is the instrument');
await act(async () => { button(/Create part/).click(); });
assert.equal(created.length, 1, 'the part was made');
assert.equal(closed, 1, 'and the dialog closed');
const violin = st().clips.find((c) => c.id === created[0])!;
const violinTrack = st().tracks.find((t) => t.id === violin.trackId)!;
assert.equal(violinTrack.name, 'Violin I');
assert.equal(violinTrack.instrumentProgram, 40);
assert.equal(violin.sourceTotalSteps, 8 * 14, 'eight bars of 7/8');
assert.equal(violin.sourceBpm, 72);
assert.ok(Math.abs(violin.startSec - editBarStartSec(st(), 4)) < 1e-6, 'on the bar line of bar 5');
assert.equal(violin.audioBlob, undefined, 'it plays live: nothing rendered');

// ── a drum part ──────────────────────────────────────────────────────────────
await mount(null, 0);
const drums = byLabel<HTMLInputElement>(/Drum part/);
await act(async () => { drums.click(); });
const kit = byLabel<HTMLSelectElement>(/^Kit$/);
assert.ok([...kit.querySelectorAll('option')].some((o) => o.textContent === 'Orchestral kit'), 'the kits, once it is a drum part');
await act(async () => choose(kit, '48'));
await act(async () => { button(/Create part/).click(); });
const drumClip = st().clips.find((c) => c.id === created[1])!;
const drumTrack = st().tracks.find((t) => t.id === drumClip.trackId)!;
assert.equal(drumTrack.isPercussion, true);
assert.equal(drumTrack.instrumentProgram, 48, 'the Orchestral kit');
assert.equal(drumClip.label, 'Orchestral kit');

// ── on the cello track: the cello's instrument, no new track ─────────────────
await mount('vc', 0);
assert.ok(!hasLabel(/Track name/), 'a part on a track needs no track name');
assert.ok(!hasLabel(/Drum part/));
assert.equal(byLabel<HTMLSelectElement>(/^Instrument$/).value, '42', "the track's instrument is the default");
await act(async () => type(byLabel<HTMLInputElement>(/Length in bars/), '0'));
assert.equal(button(/Create part/).disabled, true, 'a length of 0 cannot be made');
assert.match(alertText(), /length of 1-4096 bars/);
await act(async () => type(byLabel<HTMLInputElement>(/Length in bars/), '2'));
const tracksBefore = st().tracks.length;
await act(async () => { button(/Create part/).click(); });
const celloPart = st().clips.find((c) => c.id === created[2])!;
assert.equal(celloPart.trackId, 'vc');
assert.equal(celloPart.instrumentProgram, undefined, 'it follows the cello track');
assert.equal(st().tracks.length, tracksBefore, 'no track was added');

// ── Escape closes ─────────────────────────────────────────────────────────────
await mount(null, 0);
const before = closed;
await act(async () => {
  byLabel<HTMLInputElement>(/Length in bars/).dispatchEvent(new win.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
});
assert.equal(closed, before + 1, 'Escape closes the dialog');

await act(async () => root.unmount());
console.log('NewMidiPartDialog: ok');
