// Run with: npx tsx src/components/audio/TakeLanes.test.ts
//
// The comping UI end to end, from a pointer/key position to what the store ends
// up holding: the disclosure predicate, a row click, a boundary drag, the `[`/`]`
// step, the region menu's three commands, the now-playing hint, and `Flatten
// comp` (both the warp refusal and the round trip through a print).
//
// It drives the REAL store and the REAL helpers in `lib/takeLaneLayout`, in the
// order and with the arguments `TakeLanes.tsx` / `WaveformEditor.tsx` use. It
// does NOT mount the component: TakeLanes' module graph reaches
// `components/ui/ContextMenu` → `state/editThemeStore`, and the editor's own
// module graph reaches `state/playerStore`, which reads `import.meta.env` at
// module scope — Vite-only, and a node test cannot import it at all. What this
// file therefore cannot reach is the JSX wiring itself (which handler sits on
// which element); that is what the manual pass in the ticket's report covers.
//
// The undo-step counts use the same `beginUndoStep()` reset as
// state/editorStore.comp.test.ts: the recorder folds writes closer than 300 ms
// and a test run is faster than that, so each block starts from a reset clock.
import assert from 'node:assert/strict';
import {
  beginUndoStep,
  clipSourceSpanSec,
  useEditorStore,
  type AudioClip,
  type ClipTake,
  type EditorTrack,
} from '../../state/editorStore.ts';
import { isComped, type CompRegion } from '../../lib/clipComp.ts';
import {
  COMP_CROSSFADE_CHOICES_MS,
  compBoundaryHandles,
  compRegionIndexAt,
  compRegionSpans,
  flattenPrintClip,
  laneComp,
  laneSecAtX,
  nearestCompBoundary,
  steppedBoundarySec,
  takeLaneIndexAtY,
  takeLaneRows,
} from '../../lib/takeLaneLayout.ts';

const st = () => useEditorStore.getState();
const steps = (): number => st()._undo.length;
const clipNow = (): AudioClip => st().clips.find((c) => c.id === 'c1') as AudioClip;
const compNow = (): CompRegion[] => clipNow().comp ?? [];
const near = (a: number, b: number, eps = 1e-6): boolean => Math.abs(a - b) <= eps;

/* The lane geometry TakeLanes.tsx lays out with: the clip is 8 s long at 50
   px/s, and the overlay is 60 px tall for three takes. */
const ZOOM = 50;
const LANES_H = 60;
const CLIP_START = 12;
const CLIP_DUR = 8;

const blobOf = (t: string): Blob => new Blob([t]);
const take = (id: string, offsetIntoSource: number): ClipTake => ({
  id, label: id.toUpperCase(), audioBlob: blobOf(id), mimeType: 'audio/wav',
  sourceDuration: 30, offsetIntoSource,
});
const TAKES = (): ClipTake[] => [take('a', 1.5), take('b', 2.5), take('c', 0.25)];

const track: EditorTrack = {
  id: 't1', name: 'Vox', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff',
};

/** A clip with three takes, mirroring take 0 (the `AudioClip.takes` invariant). */
const seed = (over: Partial<AudioClip> = {}): void => {
  const takes = TAKES();
  const active = (over.activeTakeIndex ?? 0) as number;
  const t = takes[active];
  useEditorStore.setState({
    tracks: [track],
    clips: [{
      id: 'c1', trackId: 't1', label: 'vox', color: '#fff',
      startSec: CLIP_START, durationSec: CLIP_DUR,
      audioBlob: t.audioBlob, mimeType: t.mimeType,
      sourceDuration: t.sourceDuration, offsetIntoSource: t.offsetIntoSource,
      fadeInSec: 0, fadeOutSec: 0, gain: 1, muted: false,
      takes, activeTakeIndex: active,
      ...over,
    } as AudioClip],
    _undo: [], _redo: [],
  });
  beginUndoStep();
};

/** The mirroring invariant, re-checked after every action below. */
const assertMirrors = (where: string): void => {
  const c = clipNow();
  if (!c.takes || c.takes.length === 0) return;
  const t = c.takes[c.activeTakeIndex ?? 0];
  assert.equal(c.audioBlob, t.audioBlob, `${where}: blob mirrors the active take`);
  assert.equal(c.mimeType, t.mimeType, `${where}: mimeType mirrors`);
  assert.equal(c.sourceDuration, t.sourceDuration, `${where}: sourceDuration mirrors`);
  assert.equal(c.offsetIntoSource, t.offsetIntoSource, `${where}: offsetIntoSource mirrors`);
};

/* ── 1. The disclosure ─────────────────────────────────────────────────────── */
{
  // The `takes` toggle exists only where there is a choice to make: one take is
  // an ordinary clip, and a row per take would be a lane of one.
  const showsToggle = (c: AudioClip): boolean => (c.takes?.length ?? 0) > 1;
  seed();
  assert.equal(showsToggle(clipNow()), true);
  seed({ takes: undefined, activeTakeIndex: undefined });
  assert.equal(showsToggle(clipNow()), false);
  seed({ takes: [take('a', 1.5)], activeTakeIndex: 0 });
  assert.equal(showsToggle(clipNow()), false);

  // The open set is component state keyed by clip id, so two clips open
  // independently and a closed clip renders no lanes at all.
  const open = new Set<string>();
  const toggle = (id: string): void => { if (!open.delete(id)) open.add(id); };
  toggle('c1'); assert.equal(open.has('c1'), true);
  toggle('c2'); assert.deepEqual([...open].sort(), ['c1', 'c2']);
  toggle('c1'); assert.deepEqual([...open], ['c2']);
}

/* ── 2. What the lanes paint before the first pick ─────────────────────────── */
{
  seed({ activeTakeIndex: 1 });
  const c = clipNow();
  // No comp yet: the lanes show the ACTIVE take across the whole clip, which is
  // exactly the region `setCompRegionAt` seeds on the first pick — so the paint
  // does not jump when the user makes that pick.
  const painted = laneComp(c.comp, c.activeTakeIndex);
  assert.deepEqual(painted, [{ startSec: 0, takeIndex: 1 }]);
  const spans = compRegionSpans(painted, c.durationSec, ZOOM);
  assert.equal(spans.length, 1);
  assert.ok(near(spans[0].widthPx, CLIP_DUR * ZOOM));
  assert.deepEqual(compBoundaryHandles(painted, c.durationSec, ZOOM), []);
  // Three takes, three rows, covering the overlay exactly.
  const rows = takeLaneRows(c.takes?.length ?? 0, LANES_H);
  assert.equal(rows.length, 3);
  assert.ok(near(rows[2].topPx + rows[2].heightPx, LANES_H));
}

/* ── 3. Click a row at time t → setCompRegionAt ────────────────────────────── */
{
  seed();
  // A pointer 150 px into the clip and 25 px down the overlay: row 1, 3.00 s,
  // snapped by the editor's own `snapSec` (1/4 at 120 bpm = 0.5 s).
  useEditorStore.setState({ snap: '1/4', bpm: 120 });
  const c = clipNow();
  const takeIndex = takeLaneIndexAtY(25, c.takes?.length ?? 0, LANES_H);
  const atSec = st().snapSec(laneSecAtX(160, ZOOM, c.durationSec));
  assert.equal(takeIndex, 1);
  assert.ok(near(atSec, 3), 'x=160 at 50px/s is 3.2 s, snapped to 3.0');

  beginUndoStep();
  const before = steps();
  st().setCompRegionAt('c1', atSec, takeIndex as number);
  // The head keeps the ACTIVE take and the pick claims only what was clicked.
  assert.deepEqual(compNow(), [{ startSec: 0, takeIndex: 0 }, { startSec: 3, takeIndex: 1 }]);
  assert.equal(steps() - before, 1, 'a pick is one undo step');
  assert.equal(isComped(clipNow()), true);
  assertMirrors('after a pick');

  // A second pick on the take that is already playing there writes nothing —
  // and therefore records no undo step either.
  const after = steps();
  st().setCompRegionAt('c1', st().snapSec(laneSecAtX(200, ZOOM, c.durationSec)), 1);
  assert.equal(steps(), after);

  // A third take from 5 s: three regions, two boundaries, and their handles
  // land where the spans start.
  st().setCompRegionAt('c1', 5, 2);
  assert.deepEqual(compNow().map((r) => [r.startSec, r.takeIndex]), [[0, 0], [3, 1], [5, 2]]);
  const handles = compBoundaryHandles(compNow(), CLIP_DUR, ZOOM);
  assert.deepEqual(handles.map((h) => h.regionIndex), [1, 2]);
  assert.deepEqual(handles.map((h) => h.xPx), [150, 250]);
  assertMirrors('after three picks');
}

/* ── 4. Drag a boundary: ONE undo step for the whole gesture ───────────────── */
{
  // The pointer-down cuts a fresh step (the clip-drag rule in WaveformEditor),
  // then every move of the drag says `{ coalesce: true }` and folds into it.
  beginUndoStep();
  const before = steps();
  for (const xPx of [160, 170, 185, 191]) {
    const toSec = st().snapSec(laneSecAtX(xPx, ZOOM, CLIP_DUR));
    st().moveCompBoundary('c1', 1, toSec, { coalesce: true });
  }
  assert.ok(near(compNow()[1].startSec, 4), 'the last position of the drag is what stuck');
  assert.equal(steps() - before, 1, 'the whole drag is one undo step');
  assertMirrors('after a boundary drag');

  // Undo takes the whole gesture back to where the pointer went down.
  st().undo();
  assert.ok(near(compNow()[1].startSec, 3));
  st().redo();
  assert.ok(near(compNow()[1].startSec, 4));

  // Dragging onto a neighbour is clamped by the model, not by the UI, and a
  // clamped drag that changes nothing writes nothing.
  st().moveCompBoundary('c1', 1, 99, { coalesce: true });
  assert.ok(compNow()[1].startSec < compNow()[2].startSec, 'never past its neighbour');
  const held = steps();
  const settled = compNow()[1].startSec;
  st().moveCompBoundary('c1', 1, 99, { coalesce: true });
  assert.equal(compNow()[1].startSec, settled);
  assert.equal(steps(), held, 'a drag that moves nothing records nothing');
}

/* ── 5. `[` / `]` move the nearest boundary by one snap step ───────────────── */
{
  seed();
  useEditorStore.setState({ snap: '1/4', bpm: 120, playheadSec: CLIP_START + 3.4 });
  st().setCompRegionAt('c1', 2, 1);
  st().setCompRegionAt('c1', 5, 2);
  assert.deepEqual(compNow().map((r) => r.startSec), [0, 2, 5]);

  // The caret is the playhead, clip-relative: 3.4 s in, so the nearest boundary
  // is the one at 2 s.
  const caret = st().playheadSec - clipNow().startSec;
  const idx = nearestCompBoundary(compNow(), caret);
  assert.equal(idx, 1);

  beginUndoStep();
  const before = steps();
  const stepSec = 0.5; // snapStepSec('1/4', 120)
  const to = steppedBoundarySec(compNow(), idx as number, 1, stepSec, CLIP_DUR);
  assert.ok(near(to as number, 2.5));
  st().moveCompBoundary('c1', idx as number, to as number);
  assert.deepEqual(compNow().map((r) => r.startSec), [0, 2.5, 5]);
  assert.equal(steps() - before, 1, 'a keyboard nudge is its own undo step');

  // `[` walks it back.
  const back = steppedBoundarySec(compNow(), 1, -1, stepSec, CLIP_DUR);
  st().moveCompBoundary('c1', 1, back as number);
  assert.deepEqual(compNow().map((r) => r.startSec), [0, 2, 5]);

  // A clip with no boundary has nothing for the keys to move, and the caller
  // writes nothing rather than calling the store with an index it would refuse.
  st().clearComp('c1');
  assert.equal(nearestCompBoundary(laneComp(compNow(), 0), 3), null);
  assertMirrors('after the keyboard nudges');
}

/* ── 6. The region menu ────────────────────────────────────────────────────── */
{
  seed();
  st().setCompRegionAt('c1', 2, 1);
  st().setCompRegionAt('c1', 5, 2);

  // Right-click 180 px in (3.6 s) lands in region 1, which is the region whose
  // LEADING boundary the crossfade rows set.
  const at = laneSecAtX(180, ZOOM, CLIP_DUR);
  const region = compRegionIndexAt(compNow(), at);
  assert.equal(region, 1);

  beginUndoStep();
  const before = steps();
  st().setCompCrossfade('c1', region as number, 25 / 1000);
  assert.equal(compNow()[1].crossfadeSec, 0.025);
  assert.equal(steps() - before, 1);
  // 0 ms is the butt cut, and it takes the key off the region entirely.
  st().setCompCrossfade('c1', region as number, 0);
  assert.equal('crossfadeSec' in compNow()[1], false);
  assert.ok(COMP_CROSSFADE_CHOICES_MS.includes(0) && COMP_CROSSFADE_CHOICES_MS.includes(100));

  // Region 0 opens at the clip head, which is not a boundary between two takes:
  // the menu never offers a crossfade there, and the store refuses one anyway.
  const headRegion = compRegionIndexAt(compNow(), 0.5);
  assert.equal(headRegion, 0);
  const guarded = steps();
  st().setCompCrossfade('c1', 0, 0.05);
  assert.equal('crossfadeSec' in compNow()[0], false);
  assert.equal(steps(), guarded, 'a refused crossfade records no step');

  // "Keep this take only" is the region's take made active, then the alternates
  // dropped — both existing actions, in that order.
  const keepTake = compNow()[2].takeIndex;
  assert.equal(keepTake, 2);
  const takeCBlob = (clipNow().takes as ClipTake[])[2].audioBlob;
  st().setActiveTake('c1', keepTake);
  assertMirrors('after setActiveTake from the region menu');
  st().keepActiveTakeOnly('c1');
  const kept = clipNow();
  assert.equal(kept.takes, undefined);
  assert.equal(kept.comp, undefined);
  // Nothing was rendered: the clip's media already WAS take C, per the invariant.
  assert.equal(kept.audioBlob, takeCBlob);
  assert.equal(kept.offsetIntoSource, 0.25, 'the clip kept take C’s read head');
  assert.equal(isComped(kept), false);
}
{
  // "Clear comp" un-comps the clip and keeps every take.
  seed();
  st().setCompRegionAt('c1', 2, 1);
  assert.equal(isComped(clipNow()), true);
  beginUndoStep();
  const before = steps();
  st().clearComp('c1');
  assert.equal(isComped(clipNow()), false);
  assert.equal(clipNow().takes?.length, 3, 'the takes stay');
  assert.equal(steps() - before, 1);
  assertMirrors('after clearComp');

  // Next / previous take from the clip menu.
  st().setActiveTake('c1', 1);
  assert.equal(clipNow().activeTakeIndex, 1);
  assertMirrors('after Next take');
  st().setActiveTake('c1', 0);
  assert.equal(clipNow().activeTakeIndex, 0);
  // Off either end is refused, so the menu items can simply be disabled there.
  const guarded = steps();
  st().setActiveTake('c1', -1);
  st().setActiveTake('c1', 3);
  assert.equal(clipNow().activeTakeIndex, 0);
  assert.equal(steps(), guarded);
}

/* ── 7. The now-playing hint ───────────────────────────────────────────────── */
{
  seed();
  st().setCompRegionAt('c1', 2, 1);
  st().setCompRegionAt('c1', 5, 2);
  const c = clipNow();
  const regionUnder = (playheadSec: number): number | null =>
    compRegionIndexAt(c.comp, playheadSec - c.startSec);
  assert.equal(regionUnder(CLIP_START + 0.5), 0);
  assert.equal(regionUnder(CLIP_START + 2), 1);
  assert.equal(regionUnder(CLIP_START + 6), 2);
  // Outside the clip nothing is lit: the caller gates on the playhead being
  // inside the clip box before it asks.
  const inside = (p: number): boolean => p >= c.startSec && p < c.startSec + c.durationSec;
  assert.equal(inside(CLIP_START - 0.1), false);
  assert.equal(inside(CLIP_START + CLIP_DUR), false);
  assert.equal(inside(CLIP_START + CLIP_DUR - 0.001), true);
}

/* ── 8. Flatten comp ───────────────────────────────────────────────────────── */
{
  // Refused while the clip carries warp markers: live plays the active take only
  // for a warped comp, so a flatten would print what preview refuses to play.
  seed({ warpMarkers: [{ sourceSec: 0, targetSec: 0 }, { sourceSec: 4, targetSec: 6 }] });
  st().setCompRegionAt('c1', 2, 1);
  const canFlatten = (c: AudioClip): boolean => isComped(c) && (c.warpMarkers?.length ?? 0) === 0;
  assert.equal(canFlatten(clipNow()), false);
}
{
  seed({ timeStretchRate: 2, gain: 0.4, fadeInSec: 0.3, muted: true });
  st().setCompRegionAt('c1', 2, 1);
  st().setCompCrossfade('c1', 1, 0.025);
  const clip = clipNow();
  assert.equal(isComped(clip), true);

  // The print: rate 1 over every source second the clip reads, with the comp
  // rebased so each region still reads the same source moment.
  const print = flattenPrintClip(clip);
  const span = clipSourceSpanSec(clip);
  assert.ok(near(span, 16), 'a rate-2 clip 8 s long reads 16 s of source');
  assert.ok(near(print.durationSec, span));
  assert.equal(print.timeStretchRate, 1);
  assert.ok(near((print.comp as CompRegion[])[1].startSec, 4));
  assert.ok(near((print.comp as CompRegion[])[1].crossfadeSec as number, 0.05));

  // A render of the clip AS IT SOUNDS is half of what the clip needs: refused,
  // and nothing is written.
  beginUndoStep();
  const before = steps();
  const asItSounds = { blob: blobOf('short'), mimeType: 'audio/wav', durationSec: clip.durationSec };
  st().flattenComp('c1', asItSounds);
  assert.equal(clipNow().takes?.length, 3, 'the refused flatten left the takes alone');
  assert.equal(clipNow().audioBlob, clip.audioBlob);

  // The print the bounce actually produces is accepted, and the clip keeps its
  // own length, gain, fades, rate and mute — every one of those is a property
  // of the CLIP, which now reads the print through them.
  const rendered = { blob: blobOf('print'), mimeType: 'audio/wav', durationSec: span, peaks: new Float32Array([0.5]) };
  st().flattenComp('c1', rendered);
  const flat = clipNow();
  assert.equal(flat.takes, undefined);
  assert.equal(flat.comp, undefined);
  assert.equal(flat.activeTakeIndex, undefined);
  assert.equal(flat.audioBlob, rendered.blob);
  assert.ok(near(flat.sourceDuration, span));
  assert.equal(flat.offsetIntoSource, 0, 'the clip reads its print from the head');
  assert.equal(flat.peaks, rendered.peaks);
  assert.ok(near(flat.durationSec, CLIP_DUR));
  assert.equal(flat.timeStretchRate, 2);
  assert.equal(flat.gain, 0.4);
  assert.ok(near(flat.fadeInSec as number, 0.3));
  assert.equal(flat.muted, true);
  assert.equal(isComped(flat), false);
  assert.ok(steps() - before >= 1, 'the flatten is undoable');
  st().undo();
  assert.equal(clipNow().takes?.length, 3, 'undo brings the takes back');
}
{
  // Rate 1 — the overwhelmingly common clip — needs no rebase at all, and the
  // print is exactly the clip's own length.
  seed();
  st().setCompRegionAt('c1', 2, 1);
  const clip = clipNow();
  const print = flattenPrintClip(clip);
  assert.ok(near(print.durationSec, CLIP_DUR));
  assert.deepEqual(print.comp, clip.comp);
  assert.equal(print.trackId, 't1', 'the bounce still groups the print under a track');
  assert.notEqual(print.id, 'c1');
  st().flattenComp('c1', { blob: blobOf('p'), mimeType: 'audio/wav', durationSec: CLIP_DUR });
  assert.equal(clipNow().takes, undefined);
  assert.equal(clipNow().peaks, undefined, 'peaks describing the old source are cleared');
}

console.log('TakeLanes comping flow: all assertions passed');
