import assert from 'node:assert/strict';

import { handletheDAWActionMessage, handletheDAWActionResult } from './actionHandlers.ts';
import { useEditorStore, type AudioClip, type EditorTrack } from '../state/editorStore.ts';

// Every action answers with {ok, message} through handletheDAWActionResult (the editor tools
// that run through the assistant's tool table answer asynchronously, hence the awaits).
// The panel prints that verbatim,
// so a branch that refused to act MUST say ok:false — the old code discarded
// the string and claimed "Executed action: X" for a miss just as loudly as for
// a hit.

const mkTrack = (id: string, name = id): EditorTrack => ({
  id, name, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff',
});

const mkClip = (id: string, trackId: string): AudioClip =>
  ({
    id,
    trackId,
    label: id.toUpperCase(),
    audioBlob: new Blob(),
    mimeType: 'audio/wav',
    sourceDuration: 8,
    offsetIntoSource: 0,
    durationSec: 4,
    startSec: 2,
    color: '#fff',
  }) as AudioClip;

const fresh = (): void => {
  useEditorStore.getState().loadProject({
    tracks: [mkTrack('a', 'Drums'), mkTrack('b', 'Bass')],
    clips: [mkClip('c1', 'a')],
  });
};

// ── Failures ──────────────────────────────────────────────────────────────
fresh();

const failures: Array<[string, Record<string, unknown> | undefined]> = [
  ['not_a_real_action', undefined],
  ['navigate', { tab: 'nowhere' }],
  ['locate_feature', { feature_id: 'nope' }],
  ['locate_feature', { feature_id: 'feature-tour' }], // declines: no one control to ring
  ['editor_remove_track', { track_id: 'zz' }],
  ['editor_set_track', { track_id: 'a' }], // nothing to change
  ['editor_remove_clip', { clip_id: 'zz' }],
  ['editor_move_clip', { clip_id: 'c1' }], // neither start_sec nor track_id
  ['editor_move_clip', { clip_id: 'c1', track_id: 'zz' }],
  ['editor_split_clip', { clip_id: 'c1' }], // no at_sec
  ['editor_split_clip', { clip_id: 'c1', at_sec: 99 }], // outside the clip
  ['editor_select_clip', { clip_id: 'zz' }],
  ['editor_set_playhead', { seconds: 'soon' }],
  ['editor_set_playhead', { seconds: -1 }],
  ['editor_set_bpm', { bpm: 5 }],
  ['editor_set_bpm', { bpm: 'fast' }],
  ['editor_set_bpm', { bpm: 350 }], // past the app's 300: it said "BPM set to 350" and set 300
  ['editor_set_bpm', { bpm: 19.9 }],
  ['editor_add_marker', { seconds: NaN }],
  ['dj_load_set', {}],
  ['dj_load_set', { name: 'no such set' }],
  ['dj_set_next', {}],
  ['dj_set_next', { label: 'whatever' }], // no active setlist
];

for (const [type, payload] of failures) {
  const result = await handletheDAWActionResult({ type, payload });
  assert.equal(result.ok, false, `${type} ${JSON.stringify(payload)} must report ok:false`);
  assert.ok(result.message.length > 0, `${type} must say why it failed`);
}

// A miss names what it could not find AND what is actually there, so the model
// can retry against a real id instead of guessing again.
const clipMiss = await handletheDAWActionResult({ type: 'editor_remove_clip', payload: { clip_id: 'zz' } });
assert.match(clipMiss.message, /No clip "zz"\. Clips: C1 \(c1\)/);
assert.ok(useEditorStore.getState().clips.some((c) => c.id === 'c1'), 'a failed remove removed nothing');

// ── Successes ─────────────────────────────────────────────────────────────
fresh();

const successes: Array<[string, Record<string, unknown> | undefined]> = [
  ['navigate', { tab: 'edit' }],
  ['locate_feature', { feature_id: 'make' }],
  ['set_prompt', { prompt: 'a dry room kick' }],
  ['editor_add_track', { name: 'Keys' }],
  ['editor_set_track', { track_id: 'a', volume: 0.5 }],
  ['editor_set_playhead', { seconds: 3 }],
  ['editor_set_bpm', { bpm: 128 }],
  ['editor_add_marker', { seconds: 1, name: 'drop' }],
  ['editor_select_clip', { clip_id: 'c1' }],
  ['editor_split_clip', { clip_id: 'c1', at_sec: 3 }],
  ['editor_get_state', undefined],
  ['get_status', undefined],
];

for (const [type, payload] of successes) {
  const result = await handletheDAWActionResult({ type, payload });
  assert.equal(result.ok, true, `${type} ${JSON.stringify(payload)} must report ok:true`);
  assert.ok(result.message.length > 0, `${type} must say what it did`);
}

assert.equal(useEditorStore.getState().bpm, 128, 'a success actually changed the document');

// The app's tempo range, 20-300 with its fraction, is what editor_set_bpm takes and what it sets.
for (const bpm of [20, 24.5, 280, 300]) {
  const result = await handletheDAWActionResult({ type: 'editor_set_bpm', payload: { bpm } });
  assert.equal(result.ok, true, `editor_set_bpm ${bpm}`);
  assert.equal(useEditorStore.getState().bpm, bpm, `${bpm} BPM is set as asked`);
}
const tooFast = await handletheDAWActionResult({ type: 'editor_set_bpm', payload: { bpm: 350 } });
assert.equal(tooFast.ok, false);
assert.match(tooFast.message, /20\.\.300/, 'the refusal names the range');
assert.equal(useEditorStore.getState().bpm, 300, 'a refused tempo changes nothing');

// ── The string wrapper useOrbChat keeps using ─────────────────────────────
fresh();
assert.equal(
  await handletheDAWActionMessage({ type: 'editor_set_bpm', payload: { bpm: 90 } }),
  (await handletheDAWActionResult({ type: 'editor_set_bpm', payload: { bpm: 90 } })).message,
);
assert.equal(typeof (await handletheDAWActionMessage({ type: 'not_a_real_action' })), 'string');

console.log('actionHandlerResult: ok');
