/**
 * The four editor tools that leave the browser, driven against the REAL store
 * with a scripted `fetch`.
 *
 * What is faked is exactly one thing: the HTTP round trip. The clips, the store
 * writes and the arithmetic that turns "make this 125 bpm" into a ratio, or a
 * note's step into a position in an audio file, are the shipping code — those
 * conversions are where this layer can be wrong in a way nobody notices until a
 * part sits 40ms behind a drum take.
 *
 * Run: `npx tsx src/orb-kit/editorToolBridge.test.ts`
 */
import assert from 'node:assert/strict';

import { useEditorStore } from '../state/editorStore';
import type { AudioClip, EditorTrack } from '../state/editorStore';
import type { PianoNote } from '../state/pianoRollStore';
import type { ToolResult } from '../state/editorTools';
import * as bridge from './editorToolBridge';

/* ── harness ─────────────────────────────────────────────────────────────── */

interface Captured {
  url: string;
  form: FormData;
}

let captured: Captured[] = [];

/** A `fetch` that records what it was sent and replies from a script. */
function scripted(reply: (url: string) => Response | Promise<Response>): typeof fetch {
  return (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = String(input);
    captured.push({ url, form: init?.body as FormData });
    return reply(url);
  }) as unknown as typeof fetch;
}

const jsonReply = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });

const okOf = (r: ToolResult, what: string): ToolResult => {
  assert.ok(r.ok, `${what}: expected ok, got error: ${r.error}`);
  return r;
};
const errOf = (r: ToolResult, what: string): string => {
  assert.ok(!r.ok, `${what}: expected an error, got ok: ${r.message}`);
  return r.error;
};

const blob = (bytes = 8): Blob => new Blob([new Uint8Array(bytes)], { type: 'audio/wav' });

const track = (id: string, name: string): EditorTrack => ({
  id,
  name,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#8b5cf6',
});

/** Steps 0, 4 and 8 — at 120 bpm that is 0s, 0.5s and 1.0s into the clip. */
const NOTES = (): PianoNote[] => [
  { id: 'n1', note: 60, step: 0, length: 4, velocity: 100 },
  { id: 'n2', note: 64, step: 4, length: 4, velocity: 100 },
  { id: 'n3', note: 67, step: 8, length: 4, velocity: 100 },
];

const seed = (): void => {
  captured = [];
  useEditorStore.getState().loadProject({
    tracks: [track('t1', 'Keys'), track('t2', 'Drums')],
    clips: [
      {
        id: 'm1',
        trackId: 't1',
        label: 'keys take',
        audioBlob: blob(),
        mimeType: 'audio/wav',
        sourceDuration: 2,
        offsetIntoSource: 0,
        durationSec: 2,
        startSec: 2,
        color: '#8b5cf6',
        sourceKind: 'piano-roll',
        sourcePianoRoll: NOTES(),
        sourceBpm: 120,
        sourceTotalSteps: 16,
      } as AudioClip,
      {
        id: 'a1',
        trackId: 't2',
        label: 'drum take',
        audioBlob: new Blob([new Uint8Array(16)], { type: 'audio/mpeg' }),
        mimeType: 'audio/mpeg',
        sourceDuration: 5,
        offsetIntoSource: 0.25,
        durationSec: 4,
        startSec: 1.5,
        color: '#22d3ee',
        sourceBpm: 100,
      } as AudioClip,
    ],
    bpm: 120,
  });
};

const clipOf = (id: string): AudioClip => useEditorStore.getState().clips.find((c) => c.id === id);

/* ── analyze ─────────────────────────────────────────────────────────────── */

seed();

const ANALYSIS = {
  durationSec: 5,
  sampleRate: 44100,
  channels: 2,
  peakDb: -0.8,
  rmsDb: -14.2,
  tempo: { bpm: 128, confidence: 0.91, beats: Array.from({ length: 200 }, (_, i) => i * 0.46875) },
  onsets: Array.from({ length: 300 }, (_, i) => i * 0.2),
  key: { root: 'F', scale: 'minor', confidence: 0.7 },
};

const analyzed = okOf(
  await bridge.analyzeClip({ clip_id: 'drum take' }, { fetchImpl: scripted(() => jsonReply(ANALYSIS)) }),
  'analyze',
);
assert.equal(captured.length, 1);
assert.equal(captured[0].url, '/api/editor-tools/analyze');
// The upload keeps the clip's real container, so the backend probes what it was
// actually handed rather than trusting a .wav that is an mp3.
assert.equal((captured[0].form.get('file') as File).name, 'clip.mp3');
assert.match(analyzed.message, /"bpm":128/);
assert.match(analyzed.message, /"peakDb":-0.8/);
assert.match(analyzed.message, /"root":"F"/);
// Three hundred onsets would swamp the turn; the count is the fact, the head is
// the illustration.
assert.match(analyzed.message, /"onsetCount":300/);
assert.match(analyzed.message, /"onsetsTruncated":true/);
assert.equal((analyzed.data as { onsets: number[] }).onsets.length, 64);

assert.match(
  errOf(await bridge.analyzeClip({ clip_id: 'nope' }, {}), 'analyze miss'),
  /^No clip "nope"\. Known clips: keys take \(m1\), drum take \(a1\)$/,
);

// A backend refusal reaches the model as the backend's own sentence, not as
// "something went wrong".
seed();
assert.match(
  errOf(
    await bridge.analyzeClip(
      { clip_id: 'a1' },
      { fetchImpl: scripted(() => jsonReply({ detail: 'could not decode the audio: bad header' }, 400)) },
    ),
    'analyze 400',
  ),
  /could not decode the audio: bad header/,
);

// A dead backend is a refusal, never a thrown promise that takes the turn down.
seed();
assert.match(
  errOf(
    await bridge.analyzeClip({ clip_id: 'a1' }, { fetchImpl: (() => Promise.reject(new Error('ECONNREFUSED'))) as never }),
    'analyze offline',
  ),
  /could not reach the backend — ECONNREFUSED/,
);

/* ── detect tempo ────────────────────────────────────────────────────────── */

seed();
const tempo = okOf(
  await bridge.detectTempo(
    { clip_id: 'a1' },
    { fetchImpl: scripted(() => jsonReply({ bpm: 128.5, confidence: 0.9, beats: [0, 0.46, 0.93] })) },
  ),
  'detect tempo',
);
assert.equal(captured[0].url, '/api/editor-tools/detect-tempo');
assert.match(tempo.message, /128\.5 bpm/);
// The answer names its own next step, because a detected tempo that is never
// tagged onto the clip cannot be used by editor_stretch_clip.
assert.match(tempo.message, /editor_set_clip_source_bpm \{clip_id:"a1", bpm:128\.5\}/);

seed();
assert.match(
  errOf(
    await bridge.detectTempo({ clip_id: 'a1' }, { fetchImpl: scripted(() => jsonReply({ bpm: null, confidence: 0, beats: [] })) }),
    'no tempo',
  ),
  /nothing periodic enough/,
);

/* ── compare timing ──────────────────────────────────────────────────────── */

seed();
const compared = okOf(
  await bridge.compareTiming(
    { midi_clip_id: 'm1', audio_clip_id: 'a1' },
    {
      fetchImpl: scripted(() =>
        jsonReply({ medianOffsetSec: 0.042, meanOffsetSec: 0.039, matched: 3, unmatchedNotes: 0, perNote: [] }),
      ),
    },
  ),
  'compare timing',
);
assert.equal(captured[0].url, '/api/editor-tools/compare-timing');
// The audio clip is what gets uploaded — it is the reference.
assert.equal((captured[0].form.get('file') as File).name, 'clip.mp3');
// Note starts land in the AUDIO clip's own source frame, which is where the
// backend's onsets live:
//   step 0/4/8 at 120bpm  -> 0 / 0.5 / 1.0s into the MIDI clip
//   + midi.startSec 2 - audio.startSec 1.5 + audio.offsetIntoSource 0.25
//   = 0.75 / 1.25 / 1.75
assert.equal(captured[0].form.get('noteStartsSec'), '[0.75,1.25,1.75]');
assert.equal(captured[0].form.get('maxMatchSec'), '0.25');
// Audio minus MIDI: a positive median means the notes are early.
assert.match(compared.message, /The MIDI is EARLY — move it later/);
assert.match(compared.message, /editor_nudge_notes \{clip_id:"m1", ms:42\}/);
assert.equal((compared.data as { suggestedNudgeMs: number }).suggestedNudgeMs, 42);

seed();
const late = okOf(
  await bridge.compareTiming(
    { midi_clip_id: 'm1', audio_clip_id: 'a1', max_match_sec: 0.5 },
    { fetchImpl: scripted(() => jsonReply({ medianOffsetSec: -0.017, meanOffsetSec: -0.02, matched: 3, unmatchedNotes: 0, perNote: [] })) },
  ),
  'compare timing late',
);
assert.equal(captured[0].form.get('maxMatchSec'), '0.5');
assert.match(late.message, /The MIDI is LATE — move it earlier/);
assert.match(late.message, /ms:-17\}/);

// A clip with a tempo map sends its notes where EDIT plays them: 60 bpm for
// beat 0, 120 from beat 1 (step 4), so steps 0/4/8 sit at 0 / 1 / 1.5 s into
// the clip, and a sourceBpm retag to 90 scales the whole map (0 / 0.667 / 1).
seed();
useEditorStore.getState().updateClip('m1', { sourceBpm: 60, sourceTempoMap: [{ beat: 0, bpm: 60 }, { beat: 1, bpm: 120 }] });
okOf(
  await bridge.compareTiming(
    { midi_clip_id: 'm1', audio_clip_id: 'a1' },
    { fetchImpl: scripted(() => jsonReply({ medianOffsetSec: 0, meanOffsetSec: 0, matched: 3, unmatchedNotes: 0, perNote: [] })) },
  ),
  'compare timing with a tempo map',
);
//   + midi.startSec 2 - audio.startSec 1.5 + audio.offsetIntoSource 0.25 = +0.75
assert.equal(captured[0].form.get('noteStartsSec'), '[0.75,1.75,2.25]');
seed();
useEditorStore.getState().updateClip('m1', { sourceBpm: 90, sourceTempoMap: [{ beat: 0, bpm: 60 }, { beat: 1, bpm: 120 }] });
okOf(
  await bridge.compareTiming(
    { midi_clip_id: 'm1', audio_clip_id: 'a1' },
    { fetchImpl: scripted(() => jsonReply({ medianOffsetSec: 0, meanOffsetSec: 0, matched: 3, unmatchedNotes: 0, perNote: [] })) },
  ),
  'compare timing with a retagged tempo map',
);
assert.equal(captured[0].form.get('noteStartsSec'), '[0.75,1.417,1.75]');

seed();
assert.match(
  errOf(await bridge.compareTiming({ midi_clip_id: 'a1', audio_clip_id: 'm1' }, {}), 'not midi'),
  /"drum take" is not a piano-roll clip/,
);
seed();
assert.match(
  errOf(await bridge.compareTiming({ midi_clip_id: 'm1', audio_clip_id: 'm1' }, {}), 'same clip'),
  /pass two different clips/,
);
seed();
assert.match(
  errOf(
    await bridge.compareTiming(
      { midi_clip_id: 'm1', audio_clip_id: 'a1' },
      { fetchImpl: scripted(() => jsonReply({ medianOffsetSec: null, meanOffsetSec: null, matched: 0, unmatchedNotes: 3, perNote: [] })) },
    ),
    'nothing matched',
  ),
  /none of "keys take"'s 3 notes landed within 0\.25s of a transient/,
);

// Clips that do not overlap on the timeline are refused before the upload
// rather than reported as "0 matched", which reads like a timing problem.
seed();
useEditorStore.getState().updateClip('a1', { startSec: 400 });
assert.match(
  errOf(await bridge.compareTiming({ midi_clip_id: 'm1', audio_clip_id: 'a1' }, {}), 'no overlap'),
  /none of "keys take"'s 3 notes land inside "drum take"/,
);
assert.equal(captured.length, 0, 'nothing should have been uploaded');

/* ── stretch ─────────────────────────────────────────────────────────────── */

// Ratio maths, before any I/O.
seed();
const ratioOf = (args: Record<string, unknown>) => bridge.resolveStretchRatio(clipOf('a1'), args);
assert.equal(ratioOf({ ratio: 1.25 }).value, 1.25);
// A clip at 100 bpm played at 125 gets SHORTER by 100/125.
assert.equal(ratioOf({ target_bpm: 125 }).value, 0.8);
assert.equal(ratioOf({ target_duration_sec: 2 }).value, 0.5);
assert.match(ratioOf({}).error, /exactly one of ratio, target_bpm or target_duration_sec \(got 0\)/);
assert.match(ratioOf({ ratio: 1, target_bpm: 125 }).error, /\(got 2\)/);
assert.match(ratioOf({ ratio: 8 }).error, /outside the 0\.25x-4x the backend supports/);
assert.match(ratioOf({ target_duration_sec: 0.5 }).error, /outside the 0\.25x-4x/);

// A clip with no declared source tempo cannot be matched to one.
seed();
useEditorStore.getState().updateClip('a1', { sourceBpm: undefined });
assert.match(
  bridge.resolveStretchRatio(clipOf('a1'), { target_bpm: 125 }).error,
  /has no sourceBpm.*editor_detect_tempo then editor_set_clip_source_bpm/s,
);

/**
 * What `/stretch` really sends back: a RIFF/WAVE file of 32-bit float PCM
 * (`-c:a pcm_f32le`). `withList` puts a LIST chunk between `fmt ` and `data`,
 * which is where ffmpeg writes its encoder tag — a parser that assumes `data`
 * sits at byte 36 reads the LIST chunk as audio.
 */
const f32Wav = (seconds: number, { sampleRate = 8000, channels = 2, withList = false } = {}): Uint8Array<ArrayBuffer> => {
  const frames = Math.round(seconds * sampleRate);
  const dataBytes = frames * channels * 4;
  const list = withList ? 4 + 'ISFTLavf61.1.100\0\0'.length + 8 : 0; // 'INFO' + one ISFT sub-chunk
  const buf = new ArrayBuffer(12 + 24 + (withList ? 8 + list : 0) + 8 + dataBytes);
  const v = new DataView(buf);
  let o = 0;
  const tag = (s: string) => { for (let i = 0; i < 4; i += 1) v.setUint8(o + i, s.charCodeAt(i)); o += 4; };
  tag('RIFF'); v.setUint32(o, buf.byteLength - 8, true); o += 4; tag('WAVE');
  tag('fmt '); v.setUint32(o, 16, true); o += 4;
  v.setUint16(o, 3, true); v.setUint16(o + 2, channels, true); v.setUint32(o + 4, sampleRate, true);
  v.setUint32(o + 8, sampleRate * channels * 4, true); v.setUint16(o + 12, channels * 4, true); v.setUint16(o + 14, 32, true);
  o += 16;
  if (withList) {
    tag('LIST'); v.setUint32(o, list, true); o += 4; tag('INFO');
    tag('ISFT'); v.setUint32(o, 18, true); o += 4;
    for (const ch of 'Lavf61.1.100\0\0\0\0\0\0') { v.setUint8(o, ch.charCodeAt(0)); o += 1; }
  }
  tag('data'); v.setUint32(o, dataBytes, true);
  return new Uint8Array(buf);
};

const wavReply = (bytes: Uint8Array<ArrayBuffer>) => () => new Response(bytes, { status: 200, headers: { 'content-type': 'audio/wav' } });

// The header parser, on its own: the length is read from the file, not assumed.
assert.equal(bridge.wavDurationSec(f32Wav(4).buffer), 4);
assert.equal(bridge.wavDurationSec(f32Wav(2.5, { withList: true, sampleRate: 44100 }).buffer), 2.5);
assert.equal(bridge.wavDurationSec(new Uint8Array(64).buffer), undefined, 'not a WAV at all');
assert.equal(bridge.wavDurationSec(f32Wav(1).buffer.slice(0, 30)), undefined, 'truncated inside fmt');

seed();
const stretchedBytes = f32Wav(4);
const stretched = okOf(
  await bridge.stretchAudioClip({ clip_id: 'a1', target_bpm: 125 }, { fetchImpl: scripted(wavReply(stretchedBytes)) }),
  'stretch',
);
assert.equal(captured[0].url, '/api/editor-tools/stretch');
assert.equal(captured[0].form.get('ratio'), '0.8');
const after = clipOf('a1');
// The WHOLE source came back stretched, so the clip's window into it scales by
// the same ratio and the trim survives: 5 -> 4, 4 -> 3.2, 0.25 -> 0.2.
assert.equal(after.sourceDuration, 4);
assert.equal(after.durationSec, 3.2);
assert.ok(Math.abs(after.offsetIntoSource - 0.2) < 1e-9, `offset ${after.offsetIntoSource}`);
// The source tempo moves with the audio, or the next match computes its ratio
// from a number the blob no longer matches.
assert.equal(after.sourceBpm, 125);
assert.equal(after.mimeType, 'audio/wav');
assert.equal(after.peaks, undefined);
assert.equal(after.audioBlob.size, stretchedBytes.byteLength);
assert.match(stretched.message, /x0\.800/);

// V4-1 — ffmpeg's atempo chain does not land on the sample. When the file comes
// back a few ms SHORT of `old x ratio`, the clip must be sized from the file:
// a window that reads past the end of its media fails to decode at playback.
// This clip's window runs to the very end of its 5s source, so the planned
// window (0.2 .. 4.0) overruns the 3.99s that actually came back.
seed();
useEditorStore.getState().updateClip('a1', { durationSec: 4.75 });
okOf(
  await bridge.stretchAudioClip({ clip_id: 'a1', ratio: 0.8 }, { fetchImpl: scripted(wavReply(f32Wav(3.99))) }),
  'short stretch',
);
const short = clipOf('a1');
assert.ok(Math.abs(short.sourceDuration - 3.99) < 1e-9, `sourceDuration is the file's, got ${short.sourceDuration}`);
assert.ok(Math.abs(short.offsetIntoSource - 0.2) < 1e-9);
assert.ok(
  short.offsetIntoSource + short.durationSec <= short.sourceDuration + 1e-9,
  `window ${short.offsetIntoSource}+${short.durationSec} runs past the ${short.sourceDuration}s source`,
);
assert.ok(Math.abs(short.durationSec - 3.79) < 1e-9, `clamped to the media, got ${short.durationSec}`);

// A body whose length cannot be read is refused — sizing the clip from a guess
// is the bug this replaces.
seed();
assert.match(
  errOf(
    await bridge.stretchAudioClip({ clip_id: 'a1', ratio: 0.8 }, { fetchImpl: scripted(wavReply(new Uint8Array(64))) }),
    'unreadable wav',
  ),
  /not a WAV whose length could be read/,
);
assert.equal(clipOf('a1').sourceDuration, 5, 'untouched after an unreadable reply');

// V4-2 — the request takes seconds; the user keeps working. If the clip's window
// moved while the backend ran, writing `old x ratio` would silently undo their
// edit, so the stretch is refused and their edit stands.
seed();
assert.match(
  errOf(
    await bridge.stretchAudioClip(
      { clip_id: 'a1', ratio: 0.8 },
      {
        fetchImpl: scripted(() => {
          useEditorStore.getState().updateClip('a1', { startSec: 9, durationSec: 1 });
          return wavReply(f32Wav(4))();
        }),
      },
    ),
    'edited mid-stretch',
  ),
  /was edited while the backend was stretching it \(startSec, durationSec changed\); nothing was written/,
);
const kept = clipOf('a1');
assert.equal(kept.startSec, 9, "the user's move stands");
assert.equal(kept.durationSec, 1, "the user's trim stands");
assert.equal(kept.sourceDuration, 5, 'the old audio is still in place');

// An edit that does not touch the window (a rename) is not a conflict — and the
// write is built from the CURRENT record, so the new label survives it.
seed();
okOf(
  await bridge.stretchAudioClip(
    { clip_id: 'a1', ratio: 0.8 },
    {
      fetchImpl: scripted(() => {
        useEditorStore.getState().updateClip('a1', { label: 'renamed while stretching' });
        return wavReply(f32Wav(4))();
      }),
    },
  ),
  'rename mid-stretch',
);
assert.equal(clipOf('a1').label, 'renamed while stretching');
assert.equal(clipOf('a1').sourceDuration, 4);

// A MIDI clip must never take this path — it is re-rendered from its notes.
seed();
assert.match(
  errOf(await bridge.stretchAudioClip({ clip_id: 'm1', ratio: 2 }, {}), 'midi to backend'),
  /is a MIDI clip and should have been re-rendered locally/,
);

// An empty body is a failure, not a clip silently replaced with silence.
seed();
assert.match(
  errOf(
    await bridge.stretchAudioClip(
      { clip_id: 'a1', ratio: 2 },
      { fetchImpl: scripted(() => new Response(new Uint8Array(0), { status: 200 })) },
    ),
    'empty stretch',
  ),
  /returned an empty file/,
);
assert.equal(clipOf('a1').sourceDuration, 5, 'the clip must be untouched after a failed stretch');

/* ── waveform peaks ──────────────────────────────────────────────────────── */

seed();
const peaked = okOf(
  await bridge.getWaveformPeaks(
    { clip_id: 'a1', buckets: 8 },
    { computePeaksImpl: async (_b, bins) => ({ peaks: Float32Array.from({ length: bins }, (_, i) => i / 10), duration: 5 }) },
  ),
  'peaks',
);
assert.match(peaked.message, /8 peak bucket\(s\) across 5s/);
assert.deepEqual((peaked.data as { peaks: number[] }).peaks, [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]);
// Nothing was written back into the clip's cache: the timeline renders from it
// at its own bin count.
assert.equal(clipOf('a1').peaks, undefined);

assert.match(errOf(await bridge.getWaveformPeaks({ clip_id: 'a1', buckets: 4000 }, {}), 'too many'), /between 8 and 2048/);
assert.match(errOf(await bridge.getWaveformPeaks({ clip_id: 'a1', buckets: 2 }, {}), 'too few'), /between 8 and 2048/);
assert.match(
  errOf(
    await bridge.getWaveformPeaks(
      { clip_id: 'a1' },
      { computePeaksImpl: async () => { throw new Error('unsupported codec'); } },
    ),
    'undecodable',
  ),
  /could not be decoded — unsupported codec/,
);

console.log('editorToolBridge backend-tool regression passed');
