/**
 * state/appMidiRenderer — the MIDI render queue holds the app's own picker and
 * live plan from the moment the app loads, not from the moment EDIT's module
 * loads.
 *
 * The sequence: the instrument picker is on (soundfonts, program 48) and a
 * part on a track with no instrument holds a render EDIT made so it could be
 * heard. EDIT has not been opened, so before this the queue had no picker and
 * no plan: the assistant's transpose read the picker as off, took the part for
 * one that cannot play live, and rendered it again. With the app's renderer
 * configured (App.tsx does it at load), the queue reads the picker and the
 * plan, the part plays live, and the next note edit drops that render and
 * renders nothing. App.tsx is read to check it configures the queue at load.
 *
 *   cd frontend && npx tsx src/state/appMidiRenderer.test.ts
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import * as tools from './editorTools.ts';
import { midiGlobalVoice, midiLiveIfHeard } from './midiRenderQueue.ts';
import { configureAppMidiRenderQueue } from './appMidiRenderer.ts';
import { useSoundfontStore } from '../lib/soundfontEngine.ts';
import { rollClipFields } from '../lib/rollClip.ts';
import { midiRenderSig } from '../lib/midiRender.ts';
import type { StepNoteRenderer } from '../lib/clipOps/index.ts';

const ed = () => useEditorStore.getState();
const clip = (): AudioClip => ed().clips.find((c) => c.id === 'p')!;

/** The tools' render seam: counts renders, and makes a short WAV-typed blob. */
const renders: Array<number | undefined> = [];
const render: StepNoteRenderer = async (_notes, bpm, totalSteps, opts) => {
  renders.push(opts?.program);
  const duration = (totalSteps * 60) / bpm / 4;
  return { blob: new Blob([new Uint8Array(64)], { type: 'audio/wav' }), duration };
};

const track: EditorTrack = { id: 'vn', name: 'Violin I', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff' };
const fields = rollClipFields({
  notes: [{ id: 'n0', note: 60, step: 0, length: 4, velocity: 100 }, { id: 'n1', note: 64, step: 4, length: 4, velocity: 100 }],
  bpm: 120,
  totalSteps: 16,
  meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }],
  pickupSteps: 0,
  lanes: [{ id: 0, name: 'A', cycleSteps: null }],
  bends: [],
});
const part: AudioClip = {
  id: 'p', trackId: 'vn', label: 'Violin I', mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0, durationSec: 2, startSec: 0,
  color: '#fff', sourceKind: 'piano-roll', ...fields,
  // A render EDIT made so the part could be heard.
  audioBlob: new Blob([new Uint8Array(64)], { type: 'audio/wav' }),
  renderAuto: true,
};
ed().loadProject({ tracks: [track], clips: [{ ...part, renderSig: midiRenderSig(part) }] });
useSoundfontStore.setState({ useSoundfont: true, activeProgram: 48 });

// ── EDIT not opened and nothing configured: the queue has no picker and no plan ──
assert.deepEqual(midiGlobalVoice(), { useSoundfont: false, activeProgram: 0 }, 'an unconfigured queue reads soundfonts as off');
assert.equal(midiLiveIfHeard().has('p'), false, 'and no part as playing live');
const first = await tools.transposeClip({ clip_id: 'p', semitones: 2, render });
assert.ok(first.ok, first.message);
assert.equal(renders.length, 1, 'so the transpose rendered the part again');
assert.equal(clip().renderAuto, true, 'and kept the render made so it could be heard');

// ── the app's renderer, as App.tsx configures it at load ──
configureAppMidiRenderQueue();
assert.deepEqual(midiGlobalVoice(), { useSoundfont: true, activeProgram: 48 }, 'the queue reads the picker');
assert.equal(midiLiveIfHeard().has('p'), true, 'the part plays live on the picker\'s program');
const second = await tools.transposeClip({ clip_id: 'p', semitones: 2, render });
assert.ok(second.ok, second.message);
assert.equal(renders.length, 1, 'the next edit renders nothing');
assert.equal(clip().audioBlob, undefined, 'and drops the render made so the part could be heard');
assert.equal(clip().renderAuto, undefined);
assert.deepEqual(clip().sourcePianoRoll?.map((n) => n.note), [64, 68], 'both transposes are on the notes');

// ── App.tsx configures the queue when the app loads, before App renders ──
const app = readFileSync(new URL('../App.tsx', import.meta.url), 'utf8');
assert.match(app, /^import \{ configureAppMidiRenderQueue \} from '\.\/state\/appMidiRenderer';$/m);
const call = app.search(/^configureAppMidiRenderQueue\(\);$/m);
assert.ok(call > 0, 'a top-level configureAppMidiRenderQueue() in App.tsx');
assert.ok(call < app.indexOf('export default function App'), 'before the App component');

console.log('appMidiRenderer: ok');
