/**
 * state/clipDragOut — EDIT's Ctrl+drag to another surface, replayed against
 * the real editor store, the MIDI render queue (a stand-in synth that counts
 * how many renders run at once) and the external drag store the Chimera stack
 * drops from.
 *
 * The review's sequence: in a score of live parts, Ctrl+click adds parts to
 * the selection. At 057f7499 every Ctrl press queued a render of each selected
 * live part with no render, the render was kept on the part (its header went
 * Rendering then Kept, and it re-rendered after every note edit), and a real
 * drag to another surface still left the parts out, so it took two drags. Now
 * the press renders nothing, and a drag that leaves the timeline renders the
 * parts for that drag alone: the drop takes them as they land, the live parts
 * keep no render, and the decoded audio is freed when the drag ends.
 *
 *   cd frontend && npx tsx src/state/clipDragOut.test.ts
 */
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import { configureMidiRenderQueue, requestMidiRender, useMidiRenderQueue } from './midiRenderQueue.ts';
import { dropPending, useExternalDragStore } from './externalDragStore.ts';
import { beginClipDragOut, dragOutHasContent, planClipDragOut } from './clipDragOut.ts';
import { liveMidiIfHeard } from './liveMixer.ts';
import { rollClipFields } from '../lib/rollClip.ts';
import type { AudioDragItem } from '../lib/audioDnD.ts';
import type { MidiStepRender } from '../lib/midiRender.ts';
import { decodeCacheStats, decodeClipBlob } from '../lib/decodeCache.ts';

const OFF = { useSoundfont: false, activeProgram: 0 };
let active = 0;
let maxActive = 0;
const calls: Array<number | undefined> = [];
const render: MidiStepRender = async (notes, bpm, totalSteps, opts) => {
  active += 1;
  maxActive = Math.max(maxActive, active);
  calls.push(opts.program);
  try {
    await new Promise((r) => setTimeout(r, 2));
    return { blob: new Blob([new Uint8Array(64 + notes.length)], { type: 'audio/wav' }), duration: (totalSteps * 60) / bpm / 4 + 1 };
  } finally {
    active -= 1;
  }
};
configureMidiRenderQueue({
  render,
  computePeaks: async (_b, bins) => ({ peaks: new Float32Array(bins ?? 240) }),
  global: () => OFF,
  ensureReady: async () => true,
  livePlan: liveMidiIfHeard,
});

const ed = () => useEditorStore.getState();
const track = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});
const part = (id: string, trackId: string, pitch: number, over: Partial<AudioClip> = {}): AudioClip => ({
  id, trackId, label: id, mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0, durationSec: 2, startSec: 0, color: '#fff',
  sourceKind: 'piano-roll',
  ...rollClipFields({
    notes: [{ id: `${id}0`, note: pitch, step: 0, length: 4, velocity: 100 }, { id: `${id}1`, note: pitch + 4, step: 4, length: 4, velocity: 100 }],
    bpm: 120, totalSteps: 16, meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }], pickupSteps: 0,
    lanes: [{ id: 0, name: 'A', cycleSteps: null }], bends: [],
  }),
  ...over,
});
const clipOf = (id: string) => ed().clips.find((c) => c.id === id)!;
const pick = (...ids: string[]) => ids.map(clipOf);

async function main(): Promise<void> {
  const audio: AudioClip = {
    id: 'drums', trackId: 'tA', label: 'drums', audioBlob: new Blob([new Uint8Array(16)], { type: 'audio/wav' }),
    mimeType: 'audio/wav', sourceDuration: 1, offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff',
  };
  ed().loadProject({
    tracks: [track('t1', { instrumentProgram: 40 }), track('t2', { instrumentProgram: 42 }), track('t3', { instrumentProgram: 71 }), track('t4'), track('tA')],
    clips: [part('violin', 't1', 60), part('cello', 't2', 48), part('muted', 't3', 72, { muted: true }), part('bare', 't4', 55), audio, part('kept', 't1', 64, { startSec: 4 })],
  });
  await requestMidiRender('kept', 'keep');
  calls.length = 0;
  const undoDepth = ed()._undo.length;

  // ── Ctrl+click on parts: every press plans a drag, and nothing renders ──────
  for (const ids of [['violin'], ['violin', 'cello'], ['violin', 'cello', 'muted'], ['violin', 'cello', 'muted', 'bare', 'drums', 'kept']]) {
    const plan = planClipDragOut(pick(...ids), ed().tracks, OFF);
    assert.ok(dragOutHasContent(plan));
  }
  await new Promise((r) => setTimeout(r, 20));
  assert.deepEqual(calls, [], 'no Ctrl press renders anything');
  assert.equal(useMidiRenderQueue.getState().waiting.length, 0, 'and nothing waits to render');
  for (const id of ['violin', 'cello', 'muted', 'bare']) assert.equal(clipOf(id).audioBlob, undefined, `${id} still holds no audio`);
  assert.equal(ed()._undo.length, undoDepth, 'a press writes nothing');

  // ── the drag leaves the timeline: the audio it has, then the parts as they land ──
  const plan = planClipDragOut(pick('violin', 'cello', 'muted', 'bare', 'drums', 'kept'), ed().tracks, OFF);
  assert.deepEqual(plan.items.map((i) => i.label), ['drums', 'kept'], 'the audio clip and the part with a current render go at once');
  assert.deepEqual(plan.renderIds, ['violin', 'cello', 'muted', 'bare'], 'the rest render once the drag leaves the timeline');
  beginClipDragOut(plan);
  const drag = useExternalDragStore.getState();
  assert.equal(drag.active, true);
  assert.deepEqual(drag.items.map((i) => i.label), ['drums', 'kept']);
  assert.ok(drag.pending, 'the parts are still rendering');
  // The Chimera stack's drop: it adds the audio it has and the parts as they land.
  const dropped: AudioDragItem[] = [...drag.items];
  let landed!: () => void;
  const arrived = new Promise<void>((r) => { landed = r; });
  dropPending((items) => { dropped.push(...items); landed(); }, (reason) => assert.fail(reason));
  await arrived;
  assert.deepEqual(dropped.map((i) => i.label), ['drums', 'kept', 'violin', 'cello', 'muted', 'bare'], 'the drop takes every part, the muted one too');
  assert.ok(dropped.every((i) => i.blob instanceof Blob && i.blob.size > 0));
  assert.equal(maxActive, 1, 'rendered one at a time');
  assert.deepEqual(calls, [40, 42, 71, undefined], 'each through its own voice');
  // The live parts keep no render; the part that cannot play live keeps the one EDIT would make for it.
  for (const id of ['violin', 'cello', 'muted']) assert.equal(clipOf(id).audioBlob, undefined, `${id} holds no render after the drag`);
  assert.ok(clipOf('bare').audioBlob instanceof Blob);
  assert.equal(clipOf('bare').renderAuto, true, 'made so the part can be heard');
  assert.equal(ed()._undo.length, undoDepth, 'the drag wrote no undo step');

  // The drag's renders are decoded by the drop target; ending the drag frees them.
  const fakeCtx = {
    sampleRate: 44100,
    decodeAudioData: async () => ({ numberOfChannels: 2, length: 441, sampleRate: 44100, duration: 0.01, getChannelData: () => new Float32Array(441) }),
  } as unknown as BaseAudioContext;
  const before = decodeCacheStats().entries;
  for (const item of dropped.slice(2)) await decodeClipBlob(fakeCtx, item.blob);
  assert.equal(decodeCacheStats().entries, before + 4);
  useExternalDragStore.getState().end();
  await new Promise((r) => setTimeout(r, 10));
  assert.equal(decodeCacheStats().entries, before + 1, 'the three live parts\' renders are freed; the kept render of the bare part is not');
  assert.equal(useExternalDragStore.getState().active, false);

  // ── a drag with nothing to render starts with what it has, and a drop outside takes nothing ──
  const quick = planClipDragOut(pick('drums', 'kept'), ed().tracks, OFF);
  assert.deepEqual(quick.renderIds, []);
  beginClipDragOut(quick);
  assert.equal(useExternalDragStore.getState().pending, null);
  let outside = 0;
  dropPending(() => { outside += 1; }, () => { outside += 1; });
  useExternalDragStore.getState().end();
  assert.equal(outside, 0);

  console.log('clipDragOut: ok');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
