/**
 * Humanize by section (stage 4.9): lib/clipNotes/humanize humanizeSections,
 * and EDIT's humanizeTracks, which moves several tracks' MIDI together.
 *
 * The sequence: a violin and a cello play the same rhythm through two
 * sections (a timeline marker at 4 s). Humanized together, the two parts'
 * onsets move as one inside each phrase (their shifts correlate), each
 * section leans its own way, the drift is nil where a phrase starts, and the
 * velocities rise toward the phrase's peak and fall at its edges. The same
 * seed plays the same. EDIT's tool reads the tracks' clips through their own
 * clocks, writes every clip in one undo step, and leaves pitch and length
 * alone.
 *
 *   cd frontend && npx tsx src/state/editorTools.humanizeSections.test.ts
 */
import assert from 'node:assert/strict';
import { humanizeSections, type HumanizePart } from '../lib/clipNotes/humanize.ts';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import { humanizeTracks } from './editorTools.ts';
import type { PianoNote } from './pianoRollStore.ts';

// ── The pure core ───────────────────────────────────────────────────────────
const lineOf = (id: string, base: number, peakAt: number): HumanizePart => ({
  id,
  notes: Array.from({ length: 16 }, (_, i) => ({ id: `${id}${i}`, t: i * 0.5, dur: 0.5, velocity: 80 + (i === peakAt ? 20 : 0), note: base + (i % 4) })),
});
const parts = [lineOf('vn', 76, 5), lineOf('vc', 48, 5)];
const out = humanizeSections(parts, { sections: [4], seed: 11, phraseGap: 0.6 });
const shift = (id: string) => (out.get(id) ?? []).map((n, i) => n.t - parts.find((p) => p.id === id)!.notes[i].t);
const a = shift('vn');
const b = shift('vc');
const corr = (x: number[], y: number[]) => {
  const mx = x.reduce((s, v) => s + v, 0) / x.length;
  const my = y.reduce((s, v) => s + v, 0) / y.length;
  let sxy = 0;
  let sxx = 0;
  let syy = 0;
  for (let i = 0; i < x.length; i += 1) {
    sxy += (x[i] - mx) * (y[i] - my);
    sxx += (x[i] - mx) ** 2;
    syy += (y[i] - my) ** 2;
  }
  return sxy / Math.sqrt(sxx * syy);
};
assert.ok(corr(a, b) > 0.8, `the two parts move together (r = ${corr(a, b).toFixed(2)})`);
assert.ok(a.every((s) => Math.abs(s) <= 0.012 * 1.25 + 0.008 + 1e-9), 'within the bias and the drift');
const first = a.slice(0, 8).reduce((s, v) => s + v, 0) / 8;
const second = a.slice(8).reduce((s, v) => s + v, 0) / 8;
assert.ok(Math.abs(first - second) > 1e-4, `each section leans its own way (${(first * 1000).toFixed(2)} ms, ${(second * 1000).toFixed(2)} ms)`);
// Where a phrase starts the drift is nil: the note moves by its section's bias alone, the same for both parts up to their own quarter.
assert.ok(Math.abs(a[0] - b[0]) <= 0.012 * 0.5 + 1e-9, 'a phrase starts together');
const vel = (id: string) => (out.get(id) ?? []).map((n) => n.velocity);
assert.ok(vel('vn')[5] > 100, 'the peak is louder');
assert.ok(vel('vn')[0] < 80, 'the phrase’s start is softer');
assert.deepEqual(humanizeSections(parts, { sections: [4], seed: 11, phraseGap: 0.6 }).get('vn'), out.get('vn'), 'the same seed plays the same');
assert.deepEqual(humanizeSections([], {}).size, 0);

// ── EDIT: two tracks together, one undo step ────────────────────────────────
const track = (id: string, name: string): EditorTrack =>
  ({ id, name, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#8b5cf6', instrumentProgram: 40 }) as EditorTrack;
const notes = (prefix: string, base: number): PianoNote[] =>
  Array.from({ length: 16 }, (_, i) => ({ id: `${prefix}${i}`, note: base + (i % 4), step: i * 2, length: 2, velocity: 80, tick: i * 480, ticks: 480 }));
const clip = (id: string, trackId: string, ns: PianoNote[]): AudioClip =>
  ({
    id,
    trackId,
    label: id,
    mimeType: 'audio/wav',
    sourceDuration: 8,
    offsetIntoSource: 0,
    durationSec: 8,
    startSec: 0,
    color: '#8b5cf6',
    sourceKind: 'piano-roll',
    sourcePianoRoll: ns,
    sourceBpm: 120,
    sourceTotalSteps: 32,
    instrumentProgram: 40,
  }) as AudioClip;
useEditorStore.getState().loadProject({
  tracks: [track('vn', 'Violin'), track('vc', 'Cello')],
  clips: [clip('c1', 'vn', notes('v', 76)), clip('c2', 'vc', notes('c', 48))],
} as never);
useEditorStore.getState().addMarker(4, 'B');
useEditorStore.getState().setSelectedTrackIds(['vn', 'vc']);
const r = await humanizeTracks({ strength: 'strong', seed: 3 });
assert.ok(r.ok, `ok: ${r.ok ? r.message : r.error}`);
assert.match(r.ok ? r.message : '', /Humanized 32 notes across 2 tracks together by section \(strong; 1 section mark\)/);
const after = useEditorStore.getState();
const c1 = after.clips.find((c) => c.id === 'c1')!.sourcePianoRoll!;
const c2 = after.clips.find((c) => c.id === 'c2')!.sourcePianoRoll!;
assert.deepEqual(c1.map((n) => n.note), notes('v', 76).map((n) => n.note), 'pitch untouched');
assert.deepEqual(c1.map((n) => n.length), notes('v', 76).map((n) => n.length), 'length untouched');
assert.ok(c1.some((n, i) => n.step !== i * 2), 'onsets moved');
assert.ok(c1.every((n) => n.tick === Math.round(n.step * 240)), 'the tick follows the step');
const s1 = c1.map((n, i) => n.step - i * 2);
const s2 = c2.map((n, i) => n.step - i * 2);
// Whole ticks and each track's own quarter of the bias blur it a little; it is still one ensemble.
assert.ok(corr(s1, s2) > 0.5, `the two tracks move together in EDIT too (r = ${corr(s1, s2).toFixed(2)})`);
useEditorStore.getState().undo();
const undone = useEditorStore.getState().clips;
assert.deepEqual(undone.find((c) => c.id === 'c1')!.sourcePianoRoll!.map((n) => n.step), notes('v', 76).map((n) => n.step), 'one undo takes the violin back');
assert.deepEqual(undone.find((c) => c.id === 'c2')!.sourcePianoRoll!.map((n) => n.step), notes('c', 48).map((n) => n.step), 'and the cello with it');
const none = await humanizeTracks({ track_ids: [] });
assert.ok(!none.ok, 'no track, nothing to do');

console.log('editorTools.humanizeSections: ok');
