import assert from 'node:assert/strict';
import {
  automationTargetKey, beginUndoStep, sampleLane, useEditorStore,
  type AutomationLane, type AutomationPoint, type AutomationTarget, type EditorTrack,
} from './editorStore.ts';
import { curveShape, type CurvePoint } from '../lib/automationModes.ts';
import type { ChainEntry } from './effectChainStore.ts';

const st = () => useEditorStore.getState();

const near = (a: number, b: number, eps: number, msg: string): void =>
  assert.ok(Math.abs(a - b) <= eps, `${msg} (${a} !~ ${b})`);

/** The store's breakpoint thinning window, mirrored here so the pins can name it. */
const MIN_POINT_DT = 0.02;
/** Where the pre-punch anchor lands for a pass punched in at 5 s. The store nudges
 *  this down by up to an ulp so the punch-in anchor cannot merge into it — at 5 s
 *  the raw `5 - 0.02` leaves a gap of 0.019999999999999574, just under the
 *  threshold, which would have collapsed the two. */
const PRE_T = 5 - MIN_POINT_DT;
/** Times the write pass must not change: everything at or before the pre-punch
 *  anchor. */
const SWEEP = [0, 1, 2, 3, 4, 4.9, PRE_T];

const VOL: AutomationTarget = { kind: 'trackVolume', trackId: 't1' };
const PAN: AutomationTarget = { kind: 'trackPan', trackId: 't1' };
const FX: AutomationTarget = { kind: 'trackFx', trackId: 't1', entryId: 'e1', paramKey: 'mix' };
const MASTER_FX: AutomationTarget = { kind: 'masterFx', entryId: 'm1', paramKey: 'drive' };
/** Targets whose control is gone, so there is no stored value to arm a pass at. */
const ORPHAN_FX: AutomationTarget = { kind: 'trackFx', trackId: 't1', entryId: 'deleted', paramKey: 'mix' };
const ORPHAN_PAN: AutomationTarget = { kind: 'trackPan', trackId: 't-deleted' };

const track = (over: Partial<EditorTrack> = {}): EditorTrack => ({
  id: 't1', name: 'T1', nameAutoGenerated: false, volume: 0.8, pan: 0,
  mute: false, solo: false, color: '#fff', ...over,
});

const lane = (target: AutomationTarget, points: AutomationPoint[], enabled = true): AutomationLane =>
  ({ id: `lane-${automationTargetKey(target)}`, target, points, enabled });

const laneFor = (target: AutomationTarget): AutomationLane | undefined => st().getLaneForTarget(target);
const pointsFor = (target: AutomationTarget): AutomationPoint[] => laneFor(target)?.points ?? [];

/** Put the store in a known document state, then start counting undo steps from
 *  zero. The `_undo` reset is its own `setState` so it touches no tracked slice
 *  and the history recorder skips it; `beginUndoStep` then cuts the 300 ms
 *  coalescing burst the setup itself opened. */
const reset = (over: Partial<Parameters<typeof useEditorStore.setState>[0]> = {}): void => {
  useEditorStore.setState({
    tracks: [track()],
    clips: [],
    masterFxChain: [],
    automationLanes: [],
    automationHolds: {},
    automationMode: 'read',
    ...over,
  } as never);
  useEditorStore.setState({ _undo: [], _redo: [] });
  beginUndoStep();
};

const undoSteps = (): number => st()._undo.length;

// ── sampleLane delegates to the curve sampler ────────────────────────────────

// A lane with no curves samples EXACTLY as it always did. This is the regression
// that matters most: every playback path (native envelope scheduling, the FX
// lookahead writer, the offline bounces, the lane drawing) reads through here.
{
  const legacy = (pts: CurvePoint[], t: number): number | null => {
    if (pts.length === 0) return null;
    if (t <= pts[0].t) return pts[0].v;
    const last = pts[pts.length - 1];
    if (t >= last.t) return last.v;
    let lo = 0;
    let hi = pts.length - 1;
    while (lo + 1 < hi) {
      const mid = (lo + hi) >> 1;
      if (pts[mid].t <= t) lo = mid;
      else hi = mid;
    }
    const a = pts[lo];
    const b = pts[hi];
    return a.v + (b.v - a.v) * ((t - a.t) / Math.max(1e-6, b.t - a.t));
  };
  const pts: AutomationPoint[] = [{ t: 0, v: 0.2 }, { t: 1, v: 0.9 }, { t: 2.5, v: 0.9 }, { t: 4, v: 0 }];
  const l = lane(VOL, pts);
  for (let i = -10; i <= 100; i += 1) {
    const t = i / 20;
    assert.equal(sampleLane(l, t), legacy(pts, t), `sampleLane drifted at t=${t}`);
  }
  assert.equal(sampleLane(lane(VOL, []), 3), null, 'an empty lane still has no opinion');
}

// A per-point curve shapes the segment that starts at that point, and nothing else.
{
  const l = lane(VOL, [{ t: 0, v: 0, curve: 1 }, { t: 2, v: 1 }, { t: 4, v: 0 }]);
  assert.ok(Math.abs((sampleLane(l, 1) as number) - 0.9) < 1e-9, 'curve +1 is 90% there at the midpoint');
  assert.equal(sampleLane(l, 3), 0.5, 'the next segment is untouched and still linear');
  assert.equal(sampleLane(l, 0), 0);
  assert.equal(sampleLane(l, 2), 1);
  const down = lane(VOL, [{ t: 0, v: 1, curve: -1 }, { t: 2, v: 0 }]);
  assert.ok(Math.abs((sampleLane(down, 1) as number) - 0.9) < 1e-9, 'curve -1 leaves the start late');
}

// ── The mode is the only record state ────────────────────────────────────────

// `automationMode` is what every consumer reads. The derived `automationWrite`
// boolean that shadowed it is gone: it could not tell touch from latch from
// write, and "is anything armed?" is `automationMode !== 'read'`.
{
  reset();
  assert.equal(st().automationMode, 'read', 'read is the default: nothing records until asked');
  for (const mode of ['read', 'touch', 'latch', 'write'] as const) {
    st().setAutomationMode(mode);
    assert.equal(st().automationMode, mode);
  }
}

// ── touch: records while held, punches out on release ────────────────────────
{
  reset();
  st().setAutomationMode('touch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }], 'the gesture creates the lane and its first point');
  assert.equal(laneFor(VOL)?.enabled, true, 'a lane born from a gesture is enabled');
  const hold = st().automationHolds[automationTargetKey(VOL)];
  assert.ok(hold, 'the held target is tracked');
  assert.equal(hold.released, false);
  assert.equal(hold.lastT, 1);
  assert.equal(hold.value, 0.5);

  st().moveAutomationTouch(VOL, 1.5, 0.6);
  st().moveAutomationTouch(VOL, 2, 0.7);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 1.5, v: 0.6 }, { t: 2, v: 0.7 }]);
  assert.equal(st().automationHolds[automationTargetKey(VOL)].lastT, 2);

  st().endAutomationTouch(VOL, 2.5);
  assert.deepEqual(st().automationHolds, {}, 'touch punches out: the hold is gone on release');
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 1.5, v: 0.6 }, { t: 2, v: 0.7 }, { t: 2.5, v: 0.7 }],
    'the release writes the final span and stops');
  // Nothing is written after the punch-out, so later playback reads the lane again.
  st().advanceAutomationHolds(9);
  assert.equal(pointsFor(VOL).length, 4);
}

// ── latch: keeps writing the released value until the transport stops ────────
{
  reset();
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  st().moveAutomationTouch(VOL, 2, 0.75);
  st().endAutomationTouch(VOL, 2);
  const held = st().automationHolds[automationTargetKey(VOL)];
  assert.ok(held, 'latch keeps the hold after release');
  assert.equal(held.released, true);
  assert.equal(held.value, 0.75, 'and keeps writing the value it was released at');

  st().advanceAutomationHolds(3);
  st().advanceAutomationHolds(4);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 2, v: 0.75 }, { t: 3, v: 0.75 }, { t: 4, v: 0.75 }]);

  st().endAutomationPass();
  assert.deepEqual(st().automationHolds, {}, 'the pass ends at stop');
  assert.equal(st().automationMode, 'latch', 'latch is not demoted by a stop');
}

// A release followed immediately by a STOP keeps the span it was released over.
// The release writes it rather than leaving it to a frame that never comes.
{
  reset();
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  st().moveAutomationTouch(VOL, 2, 0.75);
  st().endAutomationTouch(VOL, 3);
  st().endAutomationPass(); // stop, with no frame in between
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 2, v: 0.75 }, { t: 3, v: 0.75 }],
    'the release span survives a stop that lands before the next frame');
}

// ...and writing it at the release is idempotent with the frame that DOES follow.
{
  reset();
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  st().moveAutomationTouch(VOL, 2, 0.75);
  st().endAutomationTouch(VOL, 3);
  const afterRelease = pointsFor(VOL);
  st().advanceAutomationHolds(3);
  assert.deepEqual(pointsFor(VOL), afterRelease, 'the next frame at the same time changes nothing');
  assert.equal(st().automationHolds[automationTargetKey(VOL)].lastT, 3);
}

// Switching to READ mid-pass is hands off NOW, not at the next stop. Neither the
// pointer path nor the frame timer re-checks the mode, so the holds have to go.
{
  reset();
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  st().moveAutomationTouch(VOL, 2, 0.75);
  const frozen = pointsFor(VOL);
  st().setAutomationMode('read');
  assert.deepEqual(st().automationHolds, {}, 'read drops every hold');
  const before = useEditorStore.getState();
  st().advanceAutomationHolds(9);
  assert.ok(Object.is(useEditorStore.getState(), before),
    'and the next frame writes nothing, returning the identical state');
  assert.deepEqual(pointsFor(VOL), frozen, 'the lane stopped where the hands left it');
  // A mode that DOES record keeps the pass running.
  reset();
  st().setAutomationMode('touch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  st().setAutomationMode('latch');
  assert.ok(st().automationHolds[automationTargetKey(VOL)], 'touch → latch keeps the gesture alive');
  st().setAutomationMode('write');
  assert.ok(st().automationHolds[automationTargetKey(VOL)], 'and so does latch → write');
}

// A held target OVERWRITES: points it rides over are gone, not left to ramp to.
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0 }, { t: 1, v: 1 }, { t: 2, v: 0 }, { t: 3, v: 1 }, { t: 5, v: 0.5 }])] });
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 1, 0.25);
  st().advanceAutomationHolds(2);
  st().advanceAutomationHolds(3);
  st().advanceAutomationHolds(4);
  assert.deepEqual(pointsFor(VOL), [
    { t: 0, v: 0 }, { t: 1, v: 0.25 }, { t: 2, v: 0.25 }, { t: 3, v: 0.25 }, { t: 4, v: 0.25 }, { t: 5, v: 0.5 },
  ], 'the pass leaves its own ride and nothing else inside the span');
}

// A 200 Hz ride thins rather than piling up: a write closer to the last KEPT
// breakpoint than the minimum spacing replaces it instead of adding one, so the
// lane ends up at roughly one point per MIN_POINT_DT however fast the hand moves.
{
  reset();
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 0, 0);
  for (let i = 1; i <= 40; i += 1) st().moveAutomationTouch(VOL, i * 0.005, i / 100);
  const pts = pointsFor(VOL);
  assert.ok(pts.length <= 11 && pts.length >= 9, `40 moves over 200 ms thinned to ${pts.length} points`);
  for (let i = 1; i < pts.length; i += 1) {
    assert.ok(pts[i].t - pts[i - 1].t >= 0.02 - 1e-9, `breakpoints stayed at least MIN_POINT_DT apart at ${i}`);
  }
  assert.equal(pts[pts.length - 1].v, 0.4, 'and the last one carries the latest value');
}

// ── write: play start arms every enabled lane ────────────────────────────────
{
  const fxEntry: ChainEntry = { id: 'e1', effect: 'owl-pad', params: { mix: 0.4 }, enabled: true };
  const masterEntry: ChainEntry = { id: 'm1', effect: 'owl-pad', params: { drive: 0.7 }, enabled: true };
  reset({
    tracks: [track({ volume: 0.62, pan: -0.3, fxChain: [fxEntry] })],
    masterFxChain: [masterEntry],
    automationLanes: [
      lane(VOL, [{ t: 0, v: 0.1 }, { t: 10, v: 0.9 }]), // has points AND a stored fader
      lane(PAN, [], true),                              // empty: the stored pan
      lane(FX, []),
      lane(MASTER_FX, []),
      lane(ORPHAN_FX, [{ t: 0, v: 0.33 }]),             // no chain entry: only the lane is left
      lane(ORPHAN_PAN, []),                             // no track, no points: nothing to arm at
      lane({ kind: 'trackVolume', trackId: 't-gone' }, [{ t: 0, v: 0.5 }], false), // disabled
    ],
  });
  st().setAutomationMode('write');
  // The breakpoints BEFORE the punch-in. The pass rolls forward from 5 s and may
  // not remove or move anything behind it.
  const volPointsBefore = pointsFor(VOL).filter((p) => p.t < 5);
  /** Every breakpoint that was behind the punch-in is still there, untouched. The
   *  pre-punch anchor is an ADDITION; the shape pin below covers it. */
  const originalsIntact = (when: string): void => {
    for (const p of volPointsBefore) {
      assert.ok(pointsFor(VOL).some((q) => q.t === p.t && q.v === p.v),
        `${when}: the pass removed or moved the breakpoint at t=${p.t}`);
    }
  };
  // ...and what the lane PLAYS there, which is the invariant that actually
  // matters: a write pass may not change a note of what happens before it
  // punches in. Swept at the pre-punch anchor itself and everywhere earlier.
  const volPlayedBefore = SWEEP.map((t) => sampleLane(laneFor(VOL)!, t));
  const sweepUnchanged = (when: string): void => {
    SWEEP.forEach((t, i) => near(
      sampleLane(laneFor(VOL)!, t) as number, volPlayedBefore[i] as number, 1e-12,
      `${when}: the lane changed at t=${t}, which the pass never rolled over`,
    ));
  };
  st().beginAutomationPass(5);
  const holds = st().automationHolds;
  assert.equal(Object.keys(holds).length, 5,
    'every enabled lane with a value to arm at; not the disabled one, not the one with neither');
  // A write pass records WHAT YOU HEAR. During the pass the scheduler leaves held
  // lanes alone and the parameter plays its STORED position, so that is what the
  // hold is seeded with — 0.62, not the 0.5 the lane happens to say at 5 s.
  assert.equal(holds[automationTargetKey(VOL)].value, 0.62, 'the stored fader wins over the lane');
  assert.notEqual(sampleLane(lane(VOL, [{ t: 0, v: 0.1 }, { t: 10, v: 0.9 }]), 5), 0.62,
    'and the two really do differ here, so the precedence is being tested');
  assert.equal(holds[automationTargetKey(VOL)].released, true, 'armed-but-untouched means released-and-holding');
  assert.equal(holds[automationTargetKey(VOL)].lastT, 5);
  assert.equal(holds[automationTargetKey(PAN)].value, -0.3, 'an empty lane is armed at the stored track value');
  assert.equal(holds[automationTargetKey(FX)].value, 0.4, 'an empty FX lane is armed at the stored param');
  assert.equal(holds[automationTargetKey(MASTER_FX)].value, 0.7);
  // The lane is the FALLBACK, for a target with no control behind it any more.
  assert.equal(holds[automationTargetKey(ORPHAN_FX)].value, 0.33,
    'with no stored value the lane is what is left to arm at');
  assert.equal(holds[automationTargetKey(ORPHAN_PAN)], undefined,
    'no stored value and no points: nothing to arm at, so nothing is armed');

  // Arming lays down TWO anchors on a lane whose heard value differs from what it
  // said: the lane's OWN value just before the punch-in, then the heard value AT
  // it. The change becomes a step at `t`, and everything earlier plays untouched.
  {
    const pts = pointsFor(VOL);
    assert.equal(pts.length, 4);
    assert.deepEqual(pts[0], { t: 0, v: 0.1 });
    near(pts[1].t, PRE_T, 1e-15, 'the pre-punch anchor sits one MIN_POINT_DT before the punch-in');
    // What the ORIGINAL 0.1→0.9 ramp said just before 5 s — the lane's own value,
    // not the heard one.
    near(pts[1].v, 0.4984, 1e-12, 'the pre-punch anchor carries the value the lane already had');
    assert.deepEqual(pts[2], { t: 5, v: 0.62 }, 'the punch-in carries the heard value');
    assert.deepEqual(pts[3], { t: 10, v: 0.9 });
    assert.ok(pts[2].t - pts[1].t >= 0.02, 'the two anchors are at least MIN_POINT_DT apart, so neither merged');
  }
  assert.equal(sampleLane(laneFor(VOL)!, 5), 0.62, 'what is heard at the punch-in is what is recorded there');
  originalsIntact('arming');
  sweepUnchanged('arming');
  assert.deepEqual(pointsFor(PAN), [{ t: 5, v: -0.3 }], 'an empty lane is anchored at the stored value');
  assert.equal(sampleLane(laneFor(PAN)!, 0), st().tracks[0].pan,
    'so the empty lane reads as the value the control is actually sitting at');
  assert.deepEqual(pointsFor(ORPHAN_FX), [{ t: 0, v: 0.33 }, { t: 5, v: 0.33 }],
    'values that already agree need no pre-punch anchor');

  // Rolling forward overwrites what the untouched lanes had — but only as far as
  // it has actually rolled, and never behind the punch-in.
  st().advanceAutomationHolds(6);
  st().advanceAutomationHolds(7);
  assert.deepEqual(pointsFor(VOL).slice(2), [{ t: 5, v: 0.62 }, { t: 6, v: 0.62 }, { t: 7, v: 0.62 }, { t: 10, v: 0.9 }],
    'the pass flattened what it rode over; the point at 10 s is still ahead of it');
  originalsIntact('two frames in');
  sweepUnchanged('two frames in');
  st().advanceAutomationHolds(11);
  assert.deepEqual(pointsFor(VOL).slice(2), [{ t: 5, v: 0.62 }, { t: 6, v: 0.62 }, { t: 7, v: 0.62 }, { t: 11, v: 0.62 }],
    'rolling past 10 s takes that point with it');
  originalsIntact('after rolling past the far breakpoint');
  sweepUnchanged('after rolling past the far breakpoint');

  // Touching a control mid-pass takes the target over.
  st().beginAutomationTouch(PAN, 7, 0.9);
  assert.equal(st().automationHolds[automationTargetKey(PAN)].released, false);
  assert.equal(st().automationHolds[automationTargetKey(PAN)].value, 0.9);

  // Stop demotes write to latch, so the NEXT pass does not silently overwrite
  // the whole project again, and clears every hold.
  st().endAutomationPass();
  assert.equal(st().automationMode, 'latch', 'the demotion lands on the mode');
  assert.deepEqual(st().automationHolds, {});
}

// beginAutomationPass is a no-op outside write mode — touch and latch arm on the
// first gesture, not at play start.
{
  for (const mode of ['read', 'touch', 'latch'] as const) {
    reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0.3 }])] });
    st().setAutomationMode(mode);
    st().beginAutomationPass(2);
    assert.deepEqual(st().automationHolds, {}, `${mode} arms nothing at play start`);
    assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0.3 }], `${mode} writes nothing at play start`);
  }
}

// ── read records nothing at all ──────────────────────────────────────────────
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0.3 }])] });
  st().setAutomationMode('read');
  const before = st().automationLanes;
  st().beginAutomationTouch(VOL, 1, 0.9);
  st().moveAutomationTouch(VOL, 2, 0.8);
  st().endAutomationTouch(VOL, 3);
  st().advanceAutomationHolds(4);
  assert.equal(st().automationLanes, before, 'read never touches the lanes');
  assert.deepEqual(st().automationHolds, {});
  // A gesture on a target with no lane must not conjure one either.
  st().beginAutomationTouch(PAN, 1, 0.5);
  assert.equal(laneFor(PAN), undefined);
}

// A move or release with no hold behind it is inert (a stray pointer-up, a
// control released after the pass ended).
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0.3 }])] });
  st().setAutomationMode('latch');
  const before = st().automationLanes;
  st().moveAutomationTouch(VOL, 1, 0.9);
  st().endAutomationTouch(VOL, 2);
  assert.equal(st().automationLanes, before, 'no hold, no write');
}

// ── advanceAutomationHolds is free when nothing is held ──────────────────────
{
  reset();
  assert.deepEqual(st().automationHolds, {});
  const before = useEditorStore.getState();
  st().advanceAutomationHolds(3);
  assert.ok(Object.is(useEditorStore.getState(), before),
    'with no holds the frame timer must return the SAME state object, so no subscriber wakes');
}

// ── Holds are pass state, not document state ─────────────────────────────────
{
  reset();
  st().setAutomationMode('latch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  st().moveAutomationTouch(VOL, 2, 0.6);
  assert.ok(undoSteps() > 0, 'the gesture recorded history');
  for (const snap of st()._undo) {
    assert.deepEqual(
      Object.keys(snap).sort(),
      ['automationLanes', 'bpm', 'buses', 'clips', 'markers', 'masterFxChain', 'masterVstChain', 'meterMap', 'routing', 'tempoMap', 'tracks'],
      'an undo snapshot carries the document slices and nothing else — holds are transient',
    );
  }
  const holdsBefore = st().automationHolds;
  st().undo();
  assert.equal(st().automationHolds, holdsBefore, 'undo does not rewind the live pass');
  st().redo();
  assert.equal(st().automationHolds, holdsBefore);
}

// ── Undo: one gesture is one step, two gestures are two ──────────────────────
{
  reset();
  st().setAutomationMode('touch');
  st().beginAutomationTouch(VOL, 1, 0.5);
  for (let i = 1; i <= 10; i += 1) st().moveAutomationTouch(VOL, 1 + i * 0.1, 0.5 + i * 0.01);
  st().endAutomationTouch(VOL, 2.2);
  assert.equal(undoSteps(), 1, 'a whole gesture folds into ONE undo step');
  const after = pointsFor(VOL).length;
  assert.ok(after > 1);

  st().beginAutomationTouch(VOL, 3, 0.2);
  for (let i = 1; i <= 10; i += 1) st().moveAutomationTouch(VOL, 3 + i * 0.1, 0.2 + i * 0.01);
  st().endAutomationTouch(VOL, 4.2);
  assert.equal(undoSteps(), 2, 'a second gesture is a second step, however fast it follows');

  st().undo();
  assert.equal(pointsFor(VOL).length, after, 'one undo takes back exactly the second gesture');
  st().undo();
  assert.deepEqual(st().automationLanes, [], 'the second undo takes back the first gesture, lane and all');
}

// A write PASS is one undo step too, however many frames it runs for.
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0.1 }, { t: 10, v: 0.9 }])] });
  st().setAutomationMode('write');
  st().beginAutomationPass(0);
  for (let i = 1; i <= 20; i += 1) st().advanceAutomationHolds(i * 0.2);
  st().endAutomationPass();
  assert.equal(undoSteps(), 1, 'a write pass is one undo step');
  st().undo();
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0.1 }, { t: 10, v: 0.9 }], 'undo restores the lane the pass overwrote');
}

// ── Per-point curve on the existing point actions ────────────────────────────

// Moving a point keeps its shape. It used to be rebuilt as a bare {t, v}, which
// silently flattened the segment the point owned.
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0, curve: 0.5 }, { t: 1, v: 1, curve: -0.75 }, { t: 2, v: 0 }])] });
  const id = laneFor(VOL)!.id;
  st().updateAutomationPoint(id, 1, 1.25, 0.8);
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0, curve: 0.5 }, { t: 1.25, v: 0.8, curve: -0.75 }, { t: 2, v: 0 }]);
  // ...including when the move drags it past a neighbour.
  st().updateAutomationPoint(id, 1, 2.5, 0.4);
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0, curve: 0.5 }, { t: 2, v: 0 }, { t: 2.5, v: 0.4, curve: -0.75 }]);
  // A point with no curve still has none afterwards.
  st().updateAutomationPoint(id, 1, 1.5, 0.9);
  assert.deepEqual(pointsFor(VOL)[1], { t: 1.5, v: 0.9 });
}

// Dragging a CURVE-LESS point onto a curved neighbour must not wipe that
// neighbour's shape. "This point has no curve" is not the same instruction as
// "make the curve here zero", so the absent curve is passed through as absent
// and the neighbour keeps its own.
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0, curve: 0.75 }, { t: 3, v: 1 }])] });
  const id = laneFor(VOL)!.id;
  st().updateAutomationPoint(id, 1, 0.005, 0.4); // drag the bare point onto the curved one
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0.4, curve: 0.75 }],
    'the merged neighbour kept its shape and took the dragged value');
  // A point that HAS a curve overrides the neighbour's — including an explicit 0,
  // which says "this segment is linear" rather than saying nothing. (The store
  // never writes `curve: 0` itself; only a hand-edited project has one.)
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0, curve: 0.75 }, { t: 3, v: 1, curve: 0 }])] });
  st().updateAutomationPoint(laneFor(VOL)!.id, 1, 0.005, 0.4);
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0.4 }],
    'an explicit zero curve flattens the merged neighbour, as asked');
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0, curve: 0.75 }, { t: 3, v: 1, curve: -0.5 }])] });
  st().updateAutomationPoint(laneFor(VOL)!.id, 1, 0.005, 0.4);
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0.4, curve: -0.5 }], 'and a real one replaces it');
}

// setAutomationPointCurve clamps, and stores 0 as an ABSENT key so a linear lane
// keeps the exact shape it has always had on disk.
{
  reset({ automationLanes: [lane(VOL, [{ t: 0, v: 0 }, { t: 1, v: 1 }])] });
  const id = laneFor(VOL)!.id;
  st().setAutomationPointCurve(id, 0, 0.5);
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0, curve: 0.5 }, { t: 1, v: 1 }]);
  assert.ok(Math.abs((sampleLane(laneFor(VOL)!, 0.5) as number) - curveShape(0.5, 0.5)) < 1e-12,
    'the stored curve is what playback samples');
  st().setAutomationPointCurve(id, 0, 9);
  assert.equal(pointsFor(VOL)[0].curve, 1, 'clamped to +1');
  st().setAutomationPointCurve(id, 0, -9);
  assert.equal(pointsFor(VOL)[0].curve, -1, 'clamped to -1');
  st().setAutomationPointCurve(id, 0, 0);
  assert.deepEqual(pointsFor(VOL), [{ t: 0, v: 0 }, { t: 1, v: 1 }], 'zero is linear, and linear is no key at all');
  // Out-of-range indices and unknown lanes are inert, not throwing.
  const before = st().automationLanes;
  st().setAutomationPointCurve(id, 99, 0.5);
  st().setAutomationPointCurve('nope', 0, 0.5);
  assert.equal(st().automationLanes, before);
  // A curve edit is its own undo step (it is a discrete choice, not a gesture).
  useEditorStore.setState({ _undo: [], _redo: [] });
  st().setAutomationPointCurve(id, 0, 0.5);
  st().setAutomationPointCurve(id, 0, -0.5);
  assert.equal(undoSteps(), 2, 'two curve edits are two undo steps');

  // A curve DRAG is the exception, and says so: without `coalesce` a pointermove
  // handler would leave one undo entry per frame.
  useEditorStore.setState({ _undo: [], _redo: [] });
  beginUndoStep();
  for (let i = 1; i <= 10; i += 1) st().setAutomationPointCurve(id, 0, i / 20, { coalesce: true });
  assert.equal(undoSteps(), 1, 'ten coalesced curve writes inside 300 ms are ONE undo step');
  assert.equal(pointsFor(VOL)[0].curve, 0.5, 'and the drag still lands on its last value');
  // The next discrete edit is still a step of its own, right after a drag.
  st().setAutomationPointCurve(id, 0, -0.25);
  assert.equal(undoSteps(), 2);
}

// ── The pre-existing point actions still behave ──────────────────────────────
{
  reset();
  st().recordAutomationPoint(VOL, 1, 0.5);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }], 'recordAutomationPoint still creates the lane');
  st().recordAutomationPoint(VOL, 2, 0.6);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 2, v: 0.6 }]);
  const id = laneFor(VOL)!.id;
  st().addAutomationPoint(id, 1.5, 0.55);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 1.5, v: 0.55 }, { t: 2, v: 0.6 }]);
  st().removeAutomationPoint(id, 1);
  assert.deepEqual(pointsFor(VOL), [{ t: 1, v: 0.5 }, { t: 2, v: 0.6 }]);
  st().toggleAutomationLane(id);
  assert.equal(laneFor(VOL)?.enabled, false);
  st().clearAutomationLane(id);
  assert.deepEqual(pointsFor(VOL), []);
  st().removeAutomationLane(id);
  assert.equal(laneFor(VOL), undefined);
}

// ── addAutomationLane: the only way to get a lane WITHOUT riding a control
//    with WRITE armed. UI control lands in T25b; this is the store side (T24). ──
{
  reset();
  assert.equal(laneFor(VOL), undefined, 'no lane exists yet');

  const id = st().addAutomationLane(VOL);
  assert.notEqual(id, '', 'a real id comes back');
  const created = laneFor(VOL);
  assert.ok(created, 'the lane now exists');
  assert.equal(created!.id, id);
  assert.deepEqual(created!.points, [], 'empty — nothing has been recorded');
  assert.equal(created!.enabled, true, 'a freshly added lane starts enabled, same as recordAutomationPoint\'s');
  assert.equal(undoSteps(), 1, 'a discrete structural edit, like addBus');

  // Idempotent: a target that already has a lane hands back the SAME id and
  // creates nothing new — "add automation lane" on an already-armed control is
  // not a second lane for it.
  const before = undoSteps();
  const again = st().addAutomationLane(VOL);
  assert.equal(again, id, 'the existing lane\'s id, not a new one');
  assert.equal(st().automationLanes.filter((l) => automationTargetKey(l.target) === automationTargetKey(VOL)).length, 1);
  assert.equal(undoSteps(), before, 'no undo step for a no-op');

  // A second target gets its own lane, independent of the first.
  const panId = st().addAutomationLane(PAN);
  assert.notEqual(panId, id);
  assert.deepEqual(pointsFor(PAN), []);
  assert.equal(st().automationLanes.length, 2);

  // What `recordAutomationPoint` later writes to a lane `addAutomationLane`
  // created lands on that SAME lane, not a duplicate — the two creators dedupe
  // by the same target key.
  st().recordAutomationPoint(VOL, 3, 0.4);
  assert.equal(laneFor(VOL)!.id, id, 'recordAutomationPoint reused the lane addAutomationLane made');
  assert.deepEqual(pointsFor(VOL), [{ t: 3, v: 0.4 }]);
}

console.log('editorStore.automation.test.ts: all assertions passed');
