// Semantic undo coalescing: the history recorder folds two document writes into
// one undo step only when they are inside the 300 ms window AND carry the same
// COALESCE KEY — the identity of the control being ridden.
//
// Before the key existed the window alone decided, so any two writes that landed
// close enough merged: a fader ride followed within 300 ms by a clip move was one
// undo entry (D7), and a burst of unrelated actions from two surfaces became one
// step (D8). These pins are that defect, frozen.
import assert from 'node:assert/strict';
import {
  beginUndoStep, useEditorStore,
  type AudioClip, type AutomationTarget, type EditorTrack,
} from './editorStore.ts';

const st = () => useEditorStore.getState();
const steps = (): number => st()._undo.length;

const track = (over: Partial<EditorTrack> = {}): EditorTrack => ({
  id: 't1', name: 'T1', nameAutoGenerated: false, volume: 0.8, pan: 0,
  mute: false, solo: false, color: '#fff', ...over,
});

const clip = (over: Partial<AudioClip> = {}): AudioClip =>
  ({
    id: 'c1', trackId: 't1', label: 'take', audioBlob: new Blob(), mimeType: 'audio/wav',
    sourceDuration: 10, offsetIntoSource: 0, durationSec: 10, startSec: 0, color: '#fff',
    fadeInSec: 0, fadeOutSec: 0, gain: 1, muted: false, ...over,
  }) as AudioClip;

const VOL: AutomationTarget = { kind: 'trackVolume', trackId: 't1' };

/** Seat a known document, zero the history, and cut the burst the seating opened.
 *  The `_undo` reset is its own `setState` and touches no tracked slice, so the
 *  recorder skips it. */
const reset = (over: Record<string, unknown> = {}): void => {
  useEditorStore.setState({
    tracks: [track(), track({ id: 't2', name: 'T2' })],
    clips: [clip(), clip({ id: 'c2', trackId: 't2' })],
    masterFxChain: [],
    automationLanes: [],
    automationHolds: {},
    automationMode: 'read',
    markers: [],
    ...over,
  } as never);
  useEditorStore.setState({ _undo: [], _redo: [] });
  beginUndoStep();
};

// ── D7: two different gestures inside one window are two steps ───────────────
{
  reset();
  st().updateTrack('t1', { volume: 0.5 });
  st().updateClip('c1', { startSec: 4 });
  assert.equal(steps(), 2, 'a fader ride then a clip move inside 300 ms are TWO undo steps');
  st().undo();
  assert.equal(st().clips[0].startSec, 0, 'one undo takes back exactly the clip move');
  assert.equal(st().tracks[0].volume, 0.5, 'and leaves the fader where the ride left it');
  st().undo();
  assert.equal(st().tracks[0].volume, 0.8, 'the second undo takes back the ride');
}

// ── Ten frames of ONE fader are still one step ───────────────────────────────
{
  reset();
  for (let i = 1; i <= 10; i += 1) st().updateTrack('t1', { volume: i / 20 });
  assert.equal(steps(), 1, 'ten frames of one fader ride are ONE undo step');
  assert.equal(st().tracks[0].volume, 0.5, 'and the last value is what stuck');
  st().undo();
  assert.equal(st().tracks[0].volume, 0.8, 'one undo takes the whole ride back');
}

// ── D8: two different faders inside one window are two steps ─────────────────
// One pointer rides one fader at a time, so the realistic shape of D8 is two
// bursts back to back with nothing cutting between them. (Undo is a linear stack
// of snapshots, so two gestures whose FRAMES alternate cannot be two steps
// however they are keyed — each alternation is a step. That is the price of the
// key, and it is only reachable with two pointers on two faders at once.)
{
  reset();
  for (let i = 1; i <= 5; i += 1) st().updateTrack('t1', { volume: i / 10 });
  for (let i = 1; i <= 5; i += 1) st().updateTrack('t2', { volume: 1 - i / 10 });
  assert.equal(steps(), 2, 'two faders ridden inside one window are two steps, one each');
  st().undo();
  assert.equal(st().tracks[1].volume, 0.8, 'one undo takes back exactly the second fader');
  assert.equal(st().tracks[0].volume, 0.5, 'the first fader keeps its ride');
}

// Volume and pan on the SAME track are two controls, so two steps.
{
  reset();
  st().updateTrack('t1', { volume: 0.5 });
  st().updateTrack('t1', { pan: -0.5 });
  assert.equal(steps(), 2, 'volume and pan are separate controls');
}

// A discrete track edit never joins the ride next to it.
{
  reset();
  st().updateTrack('t1', { volume: 0.5 });
  st().updateTrack('t1', { mute: true });
  assert.equal(steps(), 2, 'a mute toggle is not part of the fader ride it lands beside');
}

// ── A menu action between two ride frames splits the ride ────────────────────
{
  reset();
  st().updateTrack('t1', { volume: 0.4 });
  st().addMarker(1, 'here');
  st().updateTrack('t1', { volume: 0.6 });
  assert.equal(steps(), 3, 'the user did something else, so the ride is two steps around it');
}

// ── Clip gestures key on the clip ────────────────────────────────────────────
{
  reset();
  for (let i = 1; i <= 5; i += 1) st().updateClip('c1', { startSec: i });
  assert.equal(steps(), 1, 'a clip drag is one step');
  st().updateClip('c2', { startSec: 3 });
  assert.equal(steps(), 2, 'dragging a DIFFERENT clip is a step of its own');
}

// A trim and a stretch of the same clip are one gesture.
{
  reset();
  st().updateClip('c1', { durationSec: 9 });
  st().stretchClipToFit('c1', 8, undefined, { coalesce: true });
  assert.equal(steps(), 1, 'trim + stretch on one clip stay one step');
}

// ── An armed fader ride writes the track AND its lane — still one step ───────
// `writeFader` in the mixer calls `updateTrack` and then `moveAutomationTouch`
// for the SAME control on every frame. Keying the lane write by the control it
// records (not by the slice it lands in) is what keeps that one step instead of
// one step per frame.
{
  reset({ automationMode: 'touch' });
  st().beginAutomationTouch(VOL, 1, 0.5);
  for (let i = 1; i <= 8; i += 1) {
    st().updateTrack('t1', { volume: 0.5 + i / 100 });
    st().moveAutomationTouch(VOL, 1 + i * 0.05, 0.5 + i / 100);
  }
  st().endAutomationTouch(VOL, 1.5);
  assert.equal(steps(), 1, 'an armed fader ride is ONE undo step, control write and lane write together');
}

// ── Hold frames join the gesture that opened them ────────────────────────────
{
  reset({ automationMode: 'latch' });
  st().beginAutomationTouch(VOL, 1, 0.5);
  for (let i = 1; i <= 20; i += 1) st().advanceAutomationHolds(1 + i * 0.05);
  assert.equal(steps(), 1, 'a hold pass driven by the frame timer stays one step');
}

// ── FX knob drags key on the entry ───────────────────────────────────────────
{
  reset({
    masterFxChain: [
      { id: 'e1', effect: 'reverb', params: { mix: 0.2 }, enabled: true },
      { id: 'e2', effect: 'delay', params: { mix: 0.2 }, enabled: true },
    ],
  });
  for (let i = 1; i <= 5; i += 1) st().updateMasterEffectParams('e1', { mix: i / 10 });
  assert.equal(steps(), 1, 'one knob drag is one step');
  st().updateMasterEffectParams('e2', { mix: 0.9 });
  assert.equal(steps(), 2, 'a knob on another entry is its own step');
}

// ── Writes with no key behave exactly as they always did ─────────────────────
// Everything that is not a keyed gesture shares one anonymous identity, so a
// burst of raw document writes still folds — the rule the recorder had before
// keys existed, kept for the cases that relied on it (a record pass placing many
// takes as one step, and the raw `setState` seeding in the sibling suites).
{
  reset();
  useEditorStore.setState({ clips: [clip({ startSec: 1 })] });
  const base = steps();
  useEditorStore.setState({ clips: [clip({ startSec: 2 })] });
  assert.equal(steps(), base, 'two unkeyed writes inside the window are still one step');
}

// A DIFFERENT pair of anonymous actions still folds. This is the deliberate
// residual of keeping `null` a shared identity (a record pass places many takes
// as one step, and the sibling suites seed with raw `setState`): a future change
// that makes every anonymous write unique has to move this pin on purpose.
{
  reset();
  st().addMarker(1, 'here');
  st().removeTrack('t2');
  assert.equal(steps(), 1, 'two anonymous actions inside the window are still ONE step');
}

// ── A key set by an action that writes nothing does not leak ─────────────────
// `moveAutomationTouch` with no hold behind it returns `{}` — zustand still
// notifies, so the recorder must consume the key it set rather than leave it for
// whatever writes next.
{
  reset();
  st().moveAutomationTouch(VOL, 1, 0.5); // no hold: writes nothing
  st().updateTrack('t1', { volume: 0.5 });
  st().updateClip('c1', { startSec: 2 });
  assert.equal(steps(), 2, 'the dropped gesture leaves no key behind for the next writes');
}

// The idle frame timer returns the state object ITSELF, so no subscriber runs at
// all — it must not have armed a continuation nobody consumes.
{
  reset();
  st().advanceAutomationHolds(3); // no holds: inert
  st().addMarker(1, 'here');
  st().updateTrack('t1', { volume: 0.5 });
  assert.equal(steps(), 2, 'an idle frame tick arms nothing');
}

// ── A menu action mid-pass is its own step, and does not swallow the rest ────
{
  reset({ automationMode: 'latch' });
  st().beginAutomationTouch(VOL, 1, 0.5);
  for (let i = 1; i <= 5; i += 1) st().advanceAutomationHolds(1 + i * 0.05);
  st().addMarker(9, 'mid-pass');
  for (let i = 6; i <= 10; i += 1) st().advanceAutomationHolds(1 + i * 0.05);
  assert.equal(steps(), 3, 'the pass, the marker, and the rest of the pass are three steps');
  st().undo();
  assert.deepEqual(st().markers.map((m) => m.label), ['mid-pass'],
    'undoing the tail of the pass leaves the marker alone');
}

// ── Bus strip: volume and pan are separate controls, like a track strip ──────
{
  reset({ buses: [{ id: 'b1', name: 'Drums', fxChain: [], volume: 0.8, mute: false }] });
  for (let i = 1; i <= 4; i += 1) st().updateBus('b1', { volume: i / 10 });
  assert.equal(steps(), 1, 'a bus fader ride is one step');
  st().updateBus('b1', { name: 'Gtrs' });
  assert.equal(steps(), 2, 'a rename is not part of the ride it lands beside');
}

// ── The window still matters: same key, but outside it, is two steps ─────────
{
  reset();
  st().updateTrack('t1', { volume: 0.5 });
  beginUndoStep();
  st().updateTrack('t1', { volume: 0.6 });
  assert.equal(steps(), 2, 'beginUndoStep still cuts a burst that shares a key');
}

// ── A write that changes nothing is not an undo step ─────────────────────────
// A slider reports its value on press (`input`) and again on release (`change`).
// The clip drawer cuts the burst on focus, which lands BETWEEN the two, so the
// identical second write used to record an empty step: the first Ctrl+Z after a
// click on the gain slider undid nothing.
{
  reset();
  beginUndoStep('clip:c1'); // pointer-down on the slider
  st().updateClip('c1', { gain: 1.23 }); // `input`
  beginUndoStep('clip:c1'); // focus arrives
  st().updateClip('c1', { gain: 1.23 }); // `change` on release: the same value again
  assert.equal(steps(), 1, 'press + release on a slider is ONE undo step');
  st().undo();
  assert.equal(st().clips[0].gain, 1, 'and one undo puts the gain back');

  const before = st().clips;
  st().updateClip('c1', { gain: 1, muted: false }); // every field already holds this value
  assert.equal(st().clips, before, 'a no-op write does not even swap the clips array');
  st().updateClip('nope', { gain: 0.5 }); // unknown clip: nothing to change, nothing recorded
  assert.equal(steps(), 0);

  // A skipped write must not leave its key behind for the next, unrelated write.
  st().updateClip('c1', { gain: 1 }); // no-op, keyed clip:c1 if it leaked
  st().updateTrack('t1', { volume: 0.5 });
  st().updateClip('c1', { startSec: 2 });
  assert.equal(steps(), 2, 'the fader ride and the clip move after a no-op are still two steps');
}

// ── …and the same for a track or bus fader held, then released ───────────────
{
  reset({ buses: [{ id: 'b1', name: 'Drums', fxChain: [], volume: 0.8, mute: false }] });
  beginUndoStep();
  st().updateTrack('t1', { volume: 0.5 }); // press
  beginUndoStep(); // stands in for the 300 ms window running out while the fader is held
  st().updateTrack('t1', { volume: 0.5 }); // release reports the same value
  assert.equal(steps(), 1, 'a held track fader is one step, not a ride plus an empty one');
  const tracksBefore = st().tracks;
  st().updateTrack('t1', { volume: 0.5, pan: 0 });
  assert.equal(st().tracks, tracksBefore, 'a no-op strip write leaves the tracks array alone');

  st().updateBus('b1', { volume: 0.4 });
  beginUndoStep();
  st().updateBus('b1', { volume: 0.4 });
  assert.equal(steps(), 2, 'the bus fader likewise: one step for its ride, none for the repeat');
  st().undo();
  assert.equal(st().buses[0].volume, 0.8, 'one undo puts the bus fader back');
}

// ── One drag of SEVERAL clips is one undo step ───────────────────────────────
// The timeline writes every selected clip on every frame of a drag. Keyed per clip those writes
// never folded (the key changes on every call), so two clips dragged for 60 frames left 120 undo
// steps. The drag says `coalesce`, which joins the step its pointer-down opened whatever the key.
{
  reset();
  beginUndoStep(); // pointer-down
  for (let frame = 1; frame <= 5; frame += 1) {
    st().updateClip('c1', { startSec: frame }, { coalesce: true });
    st().updateClip('c2', { startSec: frame + 20 }, { coalesce: true });
  }
  assert.equal(steps(), 1, 'a two-clip drag is ONE undo step');
  st().undo();
  assert.deepEqual(st().clips.map((c) => c.startSec), [0, 0], 'and one undo puts BOTH clips back');

  // Without the flag the same writes are what they always were: separate gestures.
  reset();
  beginUndoStep();
  st().updateClip('c1', { startSec: 1 });
  st().updateClip('c2', { startSec: 21 });
  assert.equal(steps(), 2, 'two clips edited one after the other stay two steps');
}

console.log('editorStore.coalesce.test.ts: all assertions passed');
