/**
 * The assistant's roll-part tools (editor_create_midi_clip, editor_list_roll_parts,
 * editor_get_roll_part, editor_set_roll_part, editor_get_meter_map) and the
 * note tools' write-through to the roll's own notes, replayed against the real
 * editor store.
 *
 * The sequence an agent writing a score runs: the arrangement is 4/4 at 96 BPM
 * for four bars, then 7/8 3+2+2 at 72 BPM. A violin part is made at bar 3, six
 * bars long: its bar lines land on the arrangement's, it sits on a new track
 * holding the violin program, and it plays live with nothing rendered. It is
 * filled with a melody and a looping 7/8 lane, read back, reopened in the piano
 * roll, transposed by the note tools and reopened again: the transposition is
 * in the roll. At 13657cdc there was no tool that made an empty MIDI clip or
 * read a roll part, and a note tool wrote only the notes EDIT plays, so the
 * roll reopened without the edit (and a bent part played the old notes live).
 *
 *   cd frontend && npx tsx src/state/editorTools.rollParts.test.ts
 */
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import type { PianoNote } from './pianoRollStore.ts';
import * as tools from './editorTools.ts';
import type { ToolResult } from './editorTools.ts';
import type { StepNoteRenderer } from '../lib/clipOps/index.ts';
import { encodeWav } from '../lib/wavEncode.ts';
import { clipRenderInput, clipRollLoad, rollClipFields } from '../lib/rollClip.ts';
import { barStartStep } from '../lib/meterMap.ts';
import { stepClock } from '../lib/rollTempo.ts';
import { editBarStartSec } from '../lib/editTimeMap.ts';
import { midiRenderSig, midiRenderState } from '../lib/midiRender.ts';
import { planLiveMidi } from './liveMixer.ts';

const ed = () => useEditorStore.getState();
const clipOf = (id: string): AudioClip => ed().clips.find((c) => c.id === id)!;
const trackOf = (id: string): EditorTrack => ed().tracks.find((t) => t.id === clipOf(id).trackId)!;
const near = (a: number, b: number, msg: string, eps = 1e-6): void => assert.ok(Math.abs(a - b) <= eps, `${msg}: ${a} vs ${b}`);
const okOf = (r: ToolResult | Promise<ToolResult>, what: string): Promise<ToolResult> => Promise.resolve(r).then((res) => {
  assert.ok(res.ok, `${what}: expected ok, got: ${res.error}`);
  return res;
});
const errOf = async (r: ToolResult | Promise<ToolResult>, what: string): Promise<string> => {
  const res = await r;
  assert.ok(!res.ok, `${what}: expected an error, got: ${res.message}`);
  return res.error;
};
type Data = Record<string, unknown>;
const dataOf = (r: ToolResult): Data => (r.data ?? {}) as Data;

/** A stand-in synth that records every render (no Web Audio in node). */
const renders: Array<{ notes: number; program?: number; bends: boolean }> = [];
const render: StepNoteRenderer = async (notes, bpm, totalSteps, opts) => {
  renders.push({ notes: notes.length, program: opts?.program, bends: !!opts?.bends });
  const sr = 8000;
  const duration = (totalSteps * 60) / bpm / 4;
  const frames = Math.max(2, Math.round(duration * sr));
  const buf = { numberOfChannels: 1, sampleRate: sr, length: frames, duration: frames / sr, getChannelData: () => new Float32Array(frames) } as unknown as AudioBuffer;
  return { blob: encodeWav(buf), duration: frames / sr };
};

function arrangement(): void {
  ed().loadProject({ tracks: [{ id: 'vc', name: 'Cello', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#0af', instrumentProgram: 42 }], clips: [], bpm: 96 });
  ed().setMeterAt(4, { num: 7, den: 8, groups: [3, 2, 2] });
  ed().addTempoEvent({ beat: 16, bpm: 72 });
}

async function main(): Promise<void> {
  arrangement();
  const undoBefore = ed()._undo.length;

  // ── make a part at bar 3, six bars long ────────────────────────────────────
  const made = await okOf(tools.createMidiClip({ program: 40, start_bar: 3, bars: 6, track_name: 'Violin I' }), 'create_midi_clip');
  const id = dataOf(made).clipId as string;
  const part = clipOf(id);
  assert.equal(trackOf(id).name, 'Violin I', 'on a new track with the name asked for');
  assert.equal(trackOf(id).instrumentProgram, 40, 'the track holds the violin');
  assert.equal(part.instrumentProgram, undefined, 'the part follows its track');
  assert.equal(part.audioBlob, undefined, 'an empty part holds no audio');
  assert.equal(renders.length, 0, 'and nothing was rendered');
  assert.deepEqual(part.sourcePianoRoll, []);
  assert.deepEqual(part.sourceRollNotes, []);
  assert.equal(part.sourceTotalSteps, 2 * 16 + 4 * 14, 'two bars of 4/4 then four of 7/8');
  assert.deepEqual(part.sourceMeterMap, [
    { bar: 0, meter: { num: 4, den: 4, groups: [] } },
    { bar: 2, meter: { num: 7, den: 8, groups: [3, 2, 2] } },
  ], "the arrangement's meters from bar 3");
  assert.equal(part.sourceBpm, 96);
  near(part.startSec, editBarStartSec(ed(), 2), 'it starts on bar 3');
  const clock = stepClock(part.sourceBpm!, part.sourceTempoMap);
  for (let k = 0; k <= 6; k += 1) {
    near(part.startSec + clock.at(barStartStep(part.sourceMeterMap!, k)), editBarStartSec(ed(), 2 + k), `the part's bar ${k + 1} is the arrangement's bar ${k + 3}`);
  }
  near(part.durationSec, editBarStartSec(ed(), 8) - editBarStartSec(ed(), 2), 'and it ends on bar 9');
  assert.equal(ed()._undo.length, undoBefore + 1, 'one undo step for the track and the part');
  assert.ok(planLiveMidi(ed().clips, ed().tracks, { useSoundfont: false, activeProgram: 0 }).liveClipIds.has(id), 'it plays live');
  assert.equal(midiRenderState(part, trackOf(id), { useSoundfont: false, activeProgram: 0 }), 'current', 'an empty roll has nothing to render');
  assert.match(made.message, /empty 6-bar Violin part at bar 3/);

  // Undo takes the track and the part back together; redo returns both.
  ed().undo();
  assert.equal(ed().clips.length, 0);
  assert.equal(ed().tracks.length, 1, 'only the cello is left');
  ed().redo();
  assert.ok(clipOf(id), 'redo brings the part back');

  // ── fill it: a melody in lane A and a looping 7/8 figure in lane B ─────────
  const melody = [
    { note: 76, step: 0, length: 8, velocity: 96 },
    { note: 74, step: 8, length: 8, velocity: 90 },
    { note: 72, step: 32, length: 6, velocity: 88 }, // bar 3 of the part: the first 7/8 bar
    { note: 67, step: 32, length: 2, velocity: 70, lane: 1 }, // lane B, looping every 7/8 bar
    { note: 69, step: 38, length: 2, velocity: 70, lane: 1 },
  ];
  const filled = await okOf(tools.setRollPart({
    clip_id: id,
    notes: melody,
    lanes: [{ id: 1, name: 'Ostinato', cycle_steps: 14, span_start: 32 }],
    render,
  }), 'set_roll_part');
  assert.equal(renders.length, 0, 'a part that plays live renders nothing when it is written');
  const afterFill = clipOf(id);
  assert.equal(afterFill.audioBlob, undefined);
  assert.equal(afterFill.sourceRollNotes?.length, 5, "the roll's own notes, as written");
  // Lane B loops from step 32 to 88 every 14 steps: 4 cycles of 2 notes.
  assert.equal(afterFill.sourcePianoRoll?.length, 3 + 8, 'the notes it plays: its lane written out');
  assert.equal(dataOf(filled).played, 11);
  assert.equal(ed()._undo.length, undoBefore + 2, 'one undo step');

  // ── read it back ───────────────────────────────────────────────────────────
  const read = await okOf(tools.getRollPart({ clip_id: 'Violin' }), 'get_roll_part');
  const got = dataOf(read);
  assert.equal(got.instrument, 'Violin');
  assert.equal(got.program, 40);
  assert.equal(got.bars, 6);
  assert.equal(got.total_steps, 88);
  assert.equal(got.render, 'none', 'it plays live with no render');
  assert.deepEqual((got.meter_map as Data[]).map((m) => [m.bar, m.label]), [[1, '4/4'], [3, '7/8 3+2+2']], 'bars 1-based');
  assert.deepEqual((got.lanes as Data[]).map((l) => [l.id, l.cycle_steps, l.span_start ?? null]), [[0, null, null], [1, 14, 32]]);
  assert.deepEqual((got.notes as Data[]).map((n) => [n.note, n.step, n.lane ?? 0]), melody.map((n) => [n.note, n.step, n.lane ?? 0]));
  const page = dataOf(await okOf(tools.getRollPart({ clip_id: id, from_bar: 3, to_bar: 3 }), 'get_roll_part bar 3'));
  assert.deepEqual((page.notes as Data[]).map((n) => n.note), [72, 67, 69], 'bar 3 alone');
  const listed = dataOf(await okOf(tools.listRollParts(), 'list_roll_parts'));
  assert.deepEqual((listed.parts as Data[]).map((p) => [p.label, p.instrument, p.start_bar, p.bars, p.notes, p.render]), [['Violin', 'Violin', 3, 6, 5, 'none']]);

  // ── reopen it in the piano roll ────────────────────────────────────────────
  const [, rollNotes, , rollSteps, rollMeter] = clipRollLoad(clipOf(id));
  assert.equal(rollSteps, 88);
  assert.deepEqual(rollNotes.map((n) => [n.note, n.step, (n as PianoNote & { lane?: number }).lane ?? 0]), melody.map((n) => [n.note, n.step, n.lane ?? 0]), 'the roll opens with the lanes as written');
  assert.equal(rollMeter.lanes.find((l) => l.id === 1)?.cycleSteps, 14, 'lane B still loops');

  // ── the note tools write through to the roll ───────────────────────────────
  await okOf(tools.transposeClip({ clip_id: id, semitones: 2, render }), 'transpose_clip');
  assert.equal(renders.length, 0, 'a live part with no render takes the edit at once');
  const [, afterTranspose, , , meterAfter] = clipRollLoad(clipOf(id));
  assert.deepEqual(
    [...new Set(afterTranspose.map((n) => n.note))].sort((a, b) => a - b),
    [69, 71, 74, 76, 78],
    'the roll reopens transposed (the old code reopened it untransposed)',
  );
  assert.ok(afterTranspose.filter((n) => n.note === 69 || n.note === 71).every((n) => (n as PianoNote & { lane?: number }).lane === 1), 'the ostinato stays in lane B');
  assert.equal(meterAfter.lanes.find((l) => l.id === 1)?.cycleSteps, null, 'written out, since every repeat moved');
  assert.deepEqual(
    clipOf(id).sourcePianoRoll!.map((n) => n.note).sort((a, b) => a - b),
    clipRenderInput(clipOf(id), 88).notes.map((n) => n.note).sort((a, b) => a - b),
    'what EDIT plays and what an export renders agree',
  );

  // A note tool on a lane-free edit keeps the loop: velocity on the melody alone.
  await okOf(tools.setRollPart({ clip_id: id, notes: melody, lanes: [{ id: 1, name: 'Ostinato', cycle_steps: 14, span_start: 32 }] }), 'set_roll_part again');
  const played = clipOf(id).sourcePianoRoll!;
  const edited = played.map((n) => (n.note >= 72 ? { ...n, velocity: 60 } : n));
  await okOf(tools.setNotes({ clip_id: id, notes: edited, render }), 'set_notes');
  const [, keptNotes, , , keptMeter] = clipRollLoad(clipOf(id));
  assert.equal(keptMeter.lanes.find((l) => l.id === 1)?.cycleSteps, 14, 'lane B keeps looping: the edit left its notes alone');
  assert.equal(keptNotes.length, 5, 'and the roll keeps its five notes');
  assert.ok(keptNotes.filter((n) => n.note >= 72).every((n) => n.velocity === 60), 'with the new velocities');

  // ── a bent part plays and renders its roll notes: the edit must reach them ─
  const bentFields = rollClipFields({
    notes: [{ id: 'b1', note: 60, step: 0, length: 4, velocity: 100, lane: 1 } as PianoNote, { id: 'b2', note: 64, step: 4, length: 4, velocity: 100 } as PianoNote],
    bpm: 96, totalSteps: 16, meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }], pickupSteps: 0,
    lanes: [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: null }],
    bends: [{ lane: 1, range: 2, points: [{ id: 'p', step: 0, value: 0, shape: 'linear' }, { id: 'q', step: 4, value: 1, shape: 'hold' }] }],
  });
  const bent = ed().addClipToTrack({
    trackId: 'vc', label: 'Cello gliss', mimeType: 'audio/wav', sourceDuration: 2.5, offsetIntoSource: 0, durationSec: 2.5, startSec: 20,
    color: '#0af', sourceKind: 'piano-roll', ...bentFields,
  });
  assert.ok(clipRenderInput(clipOf(bent), 16).bends, 'the part bends, so live playback and export read its roll notes');
  await okOf(tools.transposeClip({ clip_id: bent, semitones: -12, render }), 'transpose the bent part');
  assert.deepEqual(clipRenderInput(clipOf(bent), 16).notes.map((n) => n.note).sort((a, b) => a - b), [48, 52], 'the bent part plays the transposed notes');

  // ── a part that holds a render is re-rendered, and its render is current ───
  ed().applyClipRender(bent, { audioBlob: new Blob([new Uint8Array(8)], { type: 'audio/wav' }), renderedProgram: 42, renderSig: midiRenderSig(clipOf(bent)) });
  const before = renders.length;
  await okOf(tools.transposeClip({ clip_id: bent, semitones: 12, render }), 'transpose a part holding a render');
  assert.equal(renders.length, before + 1, 'rendered once');
  assert.equal(renders.at(-1)?.bends, true, 'with its bend, as live playback plays it');
  assert.equal(midiRenderState(clipOf(bent), trackOf(bent), { useSoundfont: false, activeProgram: 0 }), 'current', 'and the render matches the notes');

  // ── more parts: on the cello track, a drum part, one mid-bar ───────────────
  const cello = dataOf(await okOf(tools.createMidiClip({ track_id: 'Cello', start_bar: 5, bars: 2 }), 'part on the cello track'));
  assert.equal(cello.program, 42, "the track's instrument when none is named");
  assert.equal(clipOf(cello.clipId as string).instrumentProgram, undefined, 'the part follows the track');
  assert.deepEqual(clipOf(cello.clipId as string).sourceMeterMap, [{ bar: 0, meter: { num: 7, den: 8, groups: [3, 2, 2] } }], 'bar 5 is in 7/8');
  assert.equal(clipOf(cello.clipId as string).sourceBpm, 72, 'at the tempo sounding there');
  const drums = dataOf(await okOf(tools.createMidiClip({ percussion: true, bars: 2 }), 'drum part'));
  assert.equal(drums.program, 0, 'the Standard kit');
  assert.equal(trackOf(drums.clipId as string).isPercussion, true);
  assert.equal(clipOf(drums.clipId as string).label, 'Standard kit');
  const midBar = editBarStartSec(ed(), 1) + 0.3;
  const odd = dataOf(await okOf(tools.createMidiClip({ program: 73, start_sec: midBar, bars: 3 }), 'part inside a bar'));
  near(odd.startSec as number, midBar, 'starts where it was asked');
  assert.equal(clipOf(odd.clipId as string).sourceTotalSteps, 3 * 16, 'three bars of the meter sounding there');

  // ── refusals the assistant is likely to meet ───────────────────────────────
  ed().addTrack({ name: 'Empty', nameAutoGenerated: false });
  assert.match(await errOf(tools.createMidiClip({ track_id: 'Empty' }), 'no program'), /pass program.*"Empty" has no instrument/);
  assert.match(await errOf(tools.createMidiClip({ program: 1, start_bar: 2, start_sec: 3 }), 'two starts'), /start_bar or start_sec/);
  assert.match(await errOf(tools.createMidiClip({ program: 128 }), 'bad program'), /0-127/);
  assert.match(await errOf(tools.setRollPart({ clip_id: id, notes: [{ note: 60, step: 90, length: 4, velocity: 90 }], bars: 6 }), 'past the end'), /past the part's end/);
  // Without a length the grid grows to the bar line after the last note, as the roll's own notes do.
  const grown = dataOf(await okOf(tools.setRollPart({ clip_id: id, notes: [{ note: 60, step: 90, length: 4, velocity: 90 }] }), 'a note past the end'));
  assert.equal(grown.totalSteps, 102, 'one more 7/8 bar holds it');
  assert.equal(grown.bars, 7);
  assert.match(await errOf(tools.setRollPart({ clip_id: id, notes: [{ note: 60, step: 0, length: 4, velocity: 90, lane: 5 }] }), 'unknown lane'), /lane 5/);
  assert.match(await errOf(tools.setRollPart({ clip_id: id }), 'nothing to write'), /at least one of/);
  assert.match(await errOf(tools.getRollPart({ clip_id: 'nope' }), 'no clip'), /No clip "nope"/);

  // ── meter and bars on set_roll_part ────────────────────────────────────────
  await okOf(tools.setRollPart({ clip_id: id, meter_map: [{ bar: 1, meter: '5/4' }, { bar: 3, num: 7, den: 8, groups: [2, 2, 3] }], bars: 8 }), 'rewrite the meter');
  const remetered = clipOf(id);
  assert.equal(remetered.sourceTotalSteps, 2 * 20 + 6 * 14, 'two bars of 5/4 then six of 7/8');
  assert.deepEqual(remetered.sourceMeterMap?.map((s) => [s.bar, s.meter.num, s.meter.den, s.meter.groups.join('+')]), [[0, 5, 4, ''], [2, 7, 8, '2+2+3']]);

  // ── the arrangement's meter map, read in full ──────────────────────────────
  for (let bar = 10; bar < 110; bar += 1) ed().setMeterAt(bar, bar % 2 ? { num: 5, den: 8, groups: [3, 2] } : { num: 7, den: 8, groups: [2, 2, 3] });
  const full = dataOf(await okOf(tools.getMeterMap({}), 'get_meter_map'));
  assert.equal((full.meter_map as Data[]).length, ed().meterMap.length, 'every meter change, past the 64 editor_get_state lists');
  assert.ok(ed().meterMap.length > 64);
  assert.equal(full.truncated, false);
  const range = dataOf(await okOf(tools.getMeterMap({ from_bar: 51, to_bar: 55 }), 'get_meter_map range'));
  assert.deepEqual((range.meter_map as Data[]).map((m) => m.bar), [51, 52, 53, 54, 55]);
  const inForce = dataOf(await okOf(tools.getMeterMap({ from_bar: 8, to_bar: 9 }), 'get_meter_map inside a segment'));
  assert.deepEqual((inForce.meter_map as Data[]).map((m) => [m.bar, m.label]), [[5, '7/8 3+2+2']], 'the meter in force where the range starts leads');
  assert.deepEqual((inForce.tempo_map as Data[]).map((e) => [e.bar, e.bpm]), [[5, 72]], 'and the tempo in force there');
  assert.match(await errOf(tools.getMeterMap({ from_bar: 9, to_bar: 3 }), 'backwards range'), /at or after from_bar/);

  console.log(`editorTools.rollParts: ok (${renders.length} render(s) in all)`);
}

await main();
