import assert from 'node:assert/strict';
import { beginUndoStep, freezeSignature, useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';

// Batch 11 workspace state: the time selection, the edit cursor and the
// multi-select live in the store so they survive EDIT being unmounted; none of
// them is document state, so none of them may reach undo. Plus the undoable
// multi-track move and the order-independent freeze signature.

const st = () => useEditorStore.getState();

const mkTrack = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});

const clip = (id: string, trackId: string): AudioClip =>
  ({
    id,
    trackId,
    label: id,
    audioBlob: new Blob(),
    mimeType: 'audio/wav',
    sourceDuration: 4,
    offsetIntoSource: 0,
    durationSec: 4,
    startSec: 0,
    color: '#fff',
  }) as AudioClip;

/** A fresh document with tracks a, b, c and one clip on each of a and b. */
const fresh = (): void => {
  st().loadProject({
    tracks: [mkTrack('a'), mkTrack('b'), mkTrack('c')],
    clips: [clip('ca', 'a'), clip('cb', 'b')],
  });
};

const order = (): string[] => st().tracks.map((t) => t.id);

// Initial values.
{
  fresh();
  assert.equal(st().timeSelection, null);
  assert.equal(st().editCursorSec, 0);
  assert.deepEqual(st().selectedClipIds, []);
  assert.deepEqual(st().selectedTrackIds, []);
}

// setTimeSelection: validation, scope pruning, no undo step.
{
  fresh();
  const undoLen = st()._undo.length;
  st().setTimeSelection({ startSec: 1, endSec: 3, scope: { kind: 'all-tracks' } });
  assert.deepEqual(st().timeSelection, { startSec: 1, endSec: 3, scope: { kind: 'all-tracks' } });
  assert.equal(st()._undo.length, undoLen, 'a time selection is not an undo step');
  assert.equal(st().dirty, false, 'a time selection does not dirty the project');

  for (const [s, e] of [[NaN, 2], [0, Infinity], [-1, 2], [2, 2], [3, 1]]) {
    st().setTimeSelection({ startSec: 1, endSec: 3, scope: { kind: 'all-tracks' } });
    st().setTimeSelection({ startSec: s, endSec: e, scope: { kind: 'all-tracks' } });
    assert.equal(st().timeSelection, null, `[${s}, ${e}) is rejected`);
  }

  st().setTimeSelection({ startSec: 0, endSec: 2, scope: { kind: 'tracks', ids: ['a', 'zz', 'c', 'a'] } });
  assert.deepEqual(st().timeSelection, { startSec: 0, endSec: 2, scope: { kind: 'tracks', ids: ['a', 'c'] } },
    'unknown and duplicate track ids drop out of the scope');
  st().setTimeSelection({ startSec: 0, endSec: 2, scope: { kind: 'tracks', ids: ['zz'] } });
  assert.equal(st().timeSelection, null, 'a scope left empty is no selection');
  st().setTimeSelection({ startSec: 0, endSec: 2, scope: { kind: 'tracks', ids: [] } });
  assert.equal(st().timeSelection, null, 'an empty scope is no selection');
  st().setTimeSelection({ startSec: 0, endSec: 2, scope: { kind: 'all-tracks' } });
  st().setTimeSelection(null);
  assert.equal(st().timeSelection, null, 'null clears');
  assert.equal(st()._undo.length, undoLen);
}

// setEditCursor: clamps at 0, ignores non-finite, no undo step.
{
  fresh();
  const undoLen = st()._undo.length;
  st().setEditCursor(2.5);
  assert.equal(st().editCursorSec, 2.5);
  st().setEditCursor(-4);
  assert.equal(st().editCursorSec, 0, 'clamped at 0');
  st().setEditCursor(7);
  st().setEditCursor(NaN);
  st().setEditCursor(Infinity);
  assert.equal(st().editCursorSec, 7, 'non-finite is ignored');
  assert.equal(st()._undo.length, undoLen, 'the edit cursor is not an undo step');
  assert.equal(st().dirty, false);
}

// Selection setters: dedupe, drop unknown ids, leave selectedClipId alone.
{
  fresh();
  st().setSelected('ca');
  st().setSelectedClipIds(['cb', 'zz', 'cb', 'ca']);
  assert.deepEqual(st().selectedClipIds, ['cb', 'ca']);
  assert.equal(st().selectedClipId, 'ca', 'the single selection is untouched');
  st().setSelectedTrackIds(['c', 'a', 'c', 'nope']);
  assert.deepEqual(st().selectedTrackIds, ['c', 'a']);
  assert.equal(st()._undo.length, 0, 'selection is not an undo step');
}

// removeClip prunes the multi-select and clears an inpaint selection on it.
{
  fresh();
  st().setSelectedClipIds(['ca', 'cb']);
  st().setInpaintSelection({ clipId: 'ca', startSec: 0, endSec: 1 });
  st().removeClip('ca');
  assert.deepEqual(st().selectedClipIds, ['cb']);
  assert.equal(st().inpaintSelection, null, 'inpaint selection on the removed clip is cleared');
  st().setInpaintSelection({ clipId: 'cb', startSec: 0, endSec: 1 });
  beginUndoStep();
  st().addClipToTrack(clip('cx', 'c'));
  st().removeClip('cx');
  assert.deepEqual(st().inpaintSelection, { clipId: 'cb', startSec: 0, endSec: 1 },
    'removing another clip leaves the inpaint selection alone');
}

// removeTrack prunes the track selection, that track's clips, and the scope.
{
  fresh();
  st().setSelectedClipIds(['ca', 'cb']);
  st().setSelectedTrackIds(['a', 'b']);
  st().setTimeSelection({ startSec: 0, endSec: 1, scope: { kind: 'tracks', ids: ['a', 'b'] } });
  st().removeTrack('a');
  assert.deepEqual(st().selectedClipIds, ['cb']);
  assert.deepEqual(st().selectedTrackIds, ['b']);
  assert.deepEqual(st().timeSelection, { startSec: 0, endSec: 1, scope: { kind: 'tracks', ids: ['b'] } });
  st().removeTrack('b');
  assert.equal(st().timeSelection, null, 'a scope emptied by removeTrack becomes no selection');

  fresh();
  st().setTimeSelection({ startSec: 0, endSec: 1, scope: { kind: 'all-tracks' } });
  st().removeTrack('a');
  assert.deepEqual(st().timeSelection, { startSec: 0, endSec: 1, scope: { kind: 'all-tracks' } },
    'an all-tracks selection survives removeTrack');
}

// loadProject resets all workspace state and the inpaint selection.
{
  fresh();
  st().setTimeSelection({ startSec: 0, endSec: 1, scope: { kind: 'all-tracks' } });
  st().setEditCursor(3);
  st().setSelectedClipIds(['ca']);
  st().setSelectedTrackIds(['a']);
  st().setInpaintSelection({ clipId: 'ca', startSec: 0, endSec: 1 });
  fresh();
  assert.equal(st().timeSelection, null);
  assert.equal(st().editCursorSec, 0);
  assert.deepEqual(st().selectedClipIds, []);
  assert.deepEqual(st().selectedTrackIds, []);
  assert.equal(st().inpaintSelection, null);
}

// Undo / redo prune selections of ids the restored document no longer has.
{
  fresh();
  beginUndoStep();
  st().addClipToTrack(clip('cn', 'c'));
  beginUndoStep();
  const tid = st().addTrack();
  st().setSelectedClipIds(['ca', 'cn']);
  st().setSelectedTrackIds(['a', tid]);
  st().setTimeSelection({ startSec: 0, endSec: 1, scope: { kind: 'tracks', ids: [tid] } });
  st().undo(); // takes the new track away
  assert.deepEqual(st().selectedTrackIds, ['a']);
  assert.equal(st().timeSelection, null, 'a scope of only the undone track is dropped');
  assert.deepEqual(st().selectedClipIds, ['ca', 'cn']);
  st().undo(); // takes the new clip away
  assert.deepEqual(st().selectedClipIds, ['ca']);
  st().redo();
  st().redo();
  assert.deepEqual(st().selectedClipIds, ['ca'], 'redo does not re-select');
}

// moveTracks: one undo step, undo/redo, no-op adds nothing, routing untouched.
{
  fresh();
  const routing = st().routing;
  const buses = st().buses;
  const undoLen = st()._undo.length;
  st().moveTracks(['c', 'a'], 'b');
  assert.deepEqual(order(), ['a', 'c', 'b'], 'the block keeps its current relative order');
  assert.equal(st()._undo.length, undoLen + 1, 'exactly one undo step');
  assert.equal(st().routing, routing, 'routing is the same object');
  assert.equal(st().buses, buses, 'buses are the same object');
  st().undo();
  assert.deepEqual(order(), ['a', 'b', 'c'], 'undo restores the order');
  st().redo();
  assert.deepEqual(order(), ['a', 'c', 'b'], 'redo re-applies it');

  const tracksRef = st().tracks;
  const len = st()._undo.length;
  st().moveTracks(['c'], 'b'); // already there
  assert.equal(st().tracks, tracksRef, 'a no-op move writes nothing');
  assert.equal(st()._undo.length, len, 'a no-op move adds no step');

  // Two moves in quick succession are two steps (each begins its own).
  st().moveTracks(['a'], null);
  st().moveTracks(['c'], null);
  assert.deepEqual(order(), ['b', 'a', 'c']);
  assert.equal(st()._undo.length, len + 2);
  st().undo();
  assert.deepEqual(order(), ['c', 'b', 'a']);
}

// moveTracksByOffset: edges and runs.
{
  fresh();
  st().moveTracksByOffset(['a'], -1);
  assert.deepEqual(order(), ['a', 'b', 'c'], 'already at the top');
  assert.equal(st()._undo.length, 0, 'an edge no-op adds no step');
  st().moveTracksByOffset(['c'], 1);
  assert.deepEqual(order(), ['a', 'b', 'c'], 'already at the bottom');
  assert.equal(st()._undo.length, 0);
  st().moveTracksByOffset(['a', 'b'], 1);
  assert.deepEqual(order(), ['c', 'a', 'b']);
  assert.equal(st()._undo.length, 1);
  st().moveTracksByOffset(['b'], -1);
  assert.deepEqual(order(), ['c', 'b', 'a']);
  assert.equal(st()._undo.length, 2);
  st().undo();
  st().undo();
  assert.deepEqual(order(), ['a', 'b', 'c']);
}

// freezeSignature: independent of track ARRAY ORDER, still sensitive to audio.
{
  const doc = (tracks: EditorTrack[]) => ({ clips: [], tracks, masterFxChain: [], masterVstChain: [], bpm: 120 });
  const a = mkTrack('a');
  const b = mkTrack('b');
  const c = mkTrack('c');
  const base = freezeSignature(doc([a, b, c]));
  assert.equal(freezeSignature(doc([c, a, b])), base, 'a reorder does not stale the frozen master');
  assert.equal(freezeSignature(doc([b, c, a])), base);
  assert.notEqual(freezeSignature(doc([a, { ...b, volume: 0.5 }, c])), base, 'volume stales it');
  assert.notEqual(freezeSignature(doc([a, b, { ...c, mute: true }])), base, 'mute stales it');
  assert.notEqual(freezeSignature(doc([a, b])), base, 'removing a track stales it');
}

console.log('editorStore.batch11: ok');
