import { create } from 'zustand';
import { logError, logInfo } from './logStore';
import type { PianoNote } from './pianoRollStore';

export type ToolMode = 'move' | 'cut' | 'split';
export type SnapDivision = 'off' | '1/4' | '1/8' | '1/16';

export type ClipSourceKind = 'audio' | 'piano-roll';

export interface AudioClip {
  id: string;
  trackId: string;
  label: string;
  /** Source audio Blob (the bytes we play / decode peaks from). */
  audioBlob: Blob;
  mimeType: string;
  /** Total length of the source audio in seconds. */
  sourceDuration: number;
  /** Seconds into the source where this clip starts. */
  offsetIntoSource: number;
  /** Length of this clip on the timeline. */
  durationSec: number;
  /** Position on the timeline (start time in seconds). */
  startSec: number;
  color: string;
  /** Cached peaks for waveform rendering; lazy-populated. */
  peaks?: Float32Array;
  /** Optional reference back to a Library entry id, if dropped from the library. */
  libraryEntryId?: string;
  /** How this clip was produced — informs "Edit in Piano Roll" availability. */
  sourceKind?: ClipSourceKind;
  /** When sourceKind === 'piano-roll', the editable note list that produced the audio. */
  sourcePianoRoll?: PianoNote[];
  /** When sourceKind === 'piano-roll', the BPM at render time. */
  sourceBpm?: number;
  /** When sourceKind === 'piano-roll', the grid length at render time. */
  sourceTotalSteps?: number;
}

export interface EditorTrack {
  id: string;
  name: string;
  /** If true, the name was auto-generated and should be replaced by the first clip's label when one lands. */
  nameAutoGenerated: boolean;
  volume: number; // 0..1
  pan: number;    // -1..1
  mute: boolean;
  solo: boolean;
  color: string;
}

interface EditorStoreState {
  tracks: EditorTrack[];
  clips: AudioClip[];
  selectedClipId: string | null;
  tool: ToolMode;
  zoom: number;             // pixels per second
  scrollSec: number;        // horizontal scroll position in seconds
  playheadSec: number;
  isPlaying: boolean;
  snap: SnapDivision;
  bpm: number;              // for snap math

  // Mutations
  addTrack: (overrides?: Partial<EditorTrack>) => string;
  removeTrack: (id: string) => void;
  updateTrack: (id: string, updates: Partial<EditorTrack>) => void;
  toggleSolo: (id: string) => void;

  addClipToTrack: (clip: Omit<AudioClip, 'id'> & { id?: string }) => string;
  updateClip: (id: string, updates: Partial<AudioClip>) => void;
  removeClip: (id: string) => void;
  splitClipAt: (id: string, atSec: number) => string | null;
  cachePeaks: (id: string, peaks: Float32Array) => void;

  setSelected: (id: string | null) => void;
  setTool: (t: ToolMode) => void;
  setZoom: (z: number) => void;
  setScrollSec: (s: number) => void;
  setPlayhead: (s: number) => void;
  setPlaying: (p: boolean) => void;
  setSnap: (s: SnapDivision) => void;
  setBpm: (b: number) => void;

  // Selectors
  getTotalDurationSec: () => number;
  snapSec: (s: number) => number;
}

const DEFAULT_COLORS = ['#8b5cf6', '#a855f7', '#ec4899', '#06b6d4', '#10b981', '#facc15', '#f97316', '#ef4444'];

const uid = (): string =>
  typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `id-${Math.random().toString(36).slice(2)}-${Date.now()}`;

export const useEditorStore = create<EditorStoreState>()((set, get) => ({
  tracks: [
    {
      id: 'track-1',
      name: 'Track 1',
      nameAutoGenerated: true,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      color: DEFAULT_COLORS[0],
    },
  ],
  clips: [],
  selectedClipId: null,
  tool: 'move',
  zoom: 30,        // px per second
  scrollSec: 0,
  playheadSec: 0,
  isPlaying: false,
  snap: '1/16',
  bpm: 120,

  addTrack: (overrides) => {
    const id = `track-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
    set((s) => ({
      tracks: [
        ...s.tracks,
        {
          id,
          name: `Track ${s.tracks.length + 1}`,
          nameAutoGenerated: true,
          volume: 0.8,
          pan: 0,
          mute: false,
          solo: false,
          color: DEFAULT_COLORS[s.tracks.length % DEFAULT_COLORS.length],
          ...overrides,
        },
      ],
    }));
    logInfo('editor', `Added track: ${id}`);
    return id;
  },

  removeTrack: (id) => {
    set((s) => ({
      tracks: s.tracks.filter((t) => t.id !== id),
      clips: s.clips.filter((c) => c.trackId !== id),
      selectedClipId: s.clips.some((c) => c.id === s.selectedClipId && c.trackId === id) ? null : s.selectedClipId,
    }));
    logInfo('editor', `Removed track: ${id}`);
  },

  updateTrack: (id, updates) =>
    set((s) => ({
      tracks: s.tracks.map((t) => (t.id === id ? { ...t, ...updates } : t)),
    })),

  toggleSolo: (id) => {
    const target = get().tracks.find((t) => t.id === id);
    if (!target) return;
    const willSolo = !target.solo;
    set((s) => ({
      tracks: s.tracks.map((t) => ({
        ...t,
        solo: t.id === id ? willSolo : (willSolo ? false : t.solo),
      })),
    }));
  },

  addClipToTrack: (clip) => {
    const id = clip.id ?? uid();
    const full: AudioClip = { ...clip, id };
    set((s) => {
      // If the track's name is still auto-generated and this is its first clip, inherit the clip label.
      const tracks = s.tracks.map((t) => {
        if (t.id !== full.trackId) return t;
        const hasExistingClips = s.clips.some((c) => c.trackId === t.id);
        if (!hasExistingClips && t.nameAutoGenerated && full.label) {
          return { ...t, name: full.label, nameAutoGenerated: false };
        }
        return t;
      });
      return {
        tracks,
        clips: [...s.clips, full],
        selectedClipId: id,
      };
    });
    logInfo('editor', `Added clip "${full.label}" to ${full.trackId} at ${full.startSec.toFixed(2)}s`);
    return id;
  },

  updateClip: (id, updates) =>
    set((s) => ({
      clips: s.clips.map((c) => (c.id === id ? { ...c, ...updates } : c)),
    })),

  removeClip: (id) => {
    const clip = get().clips.find((c) => c.id === id);
    set((s) => ({
      clips: s.clips.filter((c) => c.id !== id),
      selectedClipId: s.selectedClipId === id ? null : s.selectedClipId,
    }));
    if (clip) logInfo('editor', `Removed clip: ${clip.label}`);
  },

  splitClipAt: (id, atSec) => {
    const state = get();
    const clip = state.clips.find((c) => c.id === id);
    if (!clip) return null;
    const relSplit = atSec - clip.startSec;
    // Don't split too close to either edge.
    if (relSplit <= 0.05 || relSplit >= clip.durationSec - 0.05) {
      logError('editor', 'Cut point too close to clip edge');
      return null;
    }
    const newId = uid();
    const left: AudioClip = { ...clip, durationSec: relSplit };
    const right: AudioClip = {
      ...clip,
      id: newId,
      startSec: clip.startSec + relSplit,
      offsetIntoSource: clip.offsetIntoSource + relSplit,
      durationSec: clip.durationSec - relSplit,
      label: `${clip.label}_b`,
    };
    set((s) => ({
      clips: s.clips.flatMap((c) => (c.id === id ? [left, right] : [c])),
      selectedClipId: newId,
    }));
    logInfo('editor', `Split clip at ${atSec.toFixed(2)}s → ${left.label} | ${right.label}`);
    return newId;
  },

  cachePeaks: (id, peaks) =>
    set((s) => ({
      clips: s.clips.map((c) => (c.id === id ? { ...c, peaks } : c)),
    })),

  setSelected: (id) => set({ selectedClipId: id }),
  setTool: (t) => set({ tool: t }),
  setZoom: (z) => set({ zoom: Math.max(5, Math.min(400, z)) }),
  setScrollSec: (s) => set({ scrollSec: Math.max(0, s) }),
  setPlayhead: (s) => set({ playheadSec: Math.max(0, s) }),
  setPlaying: (p) => set({ isPlaying: p }),
  setSnap: (s) => set({ snap: s }),
  setBpm: (b) => set({ bpm: Math.max(40, Math.min(240, b)) }),

  getTotalDurationSec: () => {
    const { clips } = get();
    if (clips.length === 0) return 60; // default empty timeline shows 60s
    return Math.max(...clips.map((c) => c.startSec + c.durationSec), 30);
  },

  snapSec: (s) => {
    const { snap, bpm } = get();
    if (snap === 'off') return Math.max(0, s);
    const beatSec = 60 / bpm;
    const divisor = snap === '1/4' ? 1 : snap === '1/8' ? 2 : 4;
    const step = beatSec / divisor;
    return Math.max(0, Math.round(s / step) * step);
  },
}));

/**
 * Decode an audio Blob and produce a downsampled peak array suitable for
 * rendering. Returns a Float32Array of `bins` values in [0, 1] representing
 * the absolute peak amplitude in each bin.
 */
export const computePeaks = async (blob: Blob, bins = 200): Promise<{ peaks: Float32Array; duration: number }> => {
  const arrayBuf = await blob.arrayBuffer();
  const Ctor = (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext);
  const ctx = new Ctor();
  try {
    const audioBuf = await ctx.decodeAudioData(arrayBuf.slice(0));
    const data = audioBuf.getChannelData(0);
    const out = new Float32Array(bins);
    const samplesPerBin = Math.floor(data.length / bins);
    let max = 0;
    for (let i = 0; i < bins; i += 1) {
      let peak = 0;
      const start = i * samplesPerBin;
      const end = Math.min(start + samplesPerBin, data.length);
      for (let j = start; j < end; j += 1) {
        const v = Math.abs(data[j]);
        if (v > peak) peak = v;
      }
      out[i] = peak;
      if (peak > max) max = peak;
    }
    // Normalize.
    if (max > 0) {
      for (let i = 0; i < bins; i += 1) out[i] /= max;
    }
    return { peaks: out, duration: audioBuf.duration };
  } finally {
    // Don't await close; some browsers GC fine without explicit close.
    try { await ctx.close(); } catch { /* ignore */ }
  }
};
