/**
 * The assistant's note edits, instrument change, bounce and stretch re-render
 * a roll clip with its part's controllers and its lanes' bends.
 *
 * Before: editorTools' commitNotes (set_notes, quantize, nudge, transpose,
 * scale_velocity, humanize, fix_overlaps, filter_notes, set_clip_instrument,
 * bounce_clip) and stretch_clip rendered through clipOps bounceMidiClip and
 * stretchMidiClip with the clip's program, drum flag and tempo map alone. A
 * part imported from an orchestral file lost its pedal, volume, pan,
 * expression and modulation in the new audio, and the write set
 * renderedProgram, so the instrument-sync pass never repaired it; with
 * bounce_clip's flatten the loss was permanent.
 *
 * The roll's own notes (`sourceRollNotes`) render with the bends only while
 * they still play the clip's notes, so a render always plays the edit. EDIT's
 * note tools write the roll notes in step with the played ones, each edited
 * note in its lane (lib/clipRollSync), so an edited part keeps its bends.
 *
 * Driven against the real editor store, with the renderer recording what it
 * was asked for.
 *
 *   cd frontend && npx tsx src/state/editorTools.partControls.test.ts
 */
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import type { PianoNote, RollControl } from './pianoRollStore.ts';
import * as tools from './editorTools.ts';
import type { StepNoteRenderer } from '../lib/clipOps/index.ts';
import type { PolyLane } from '../lib/meterMap.ts';
import type { LaneBend } from '../lib/pitchBend.ts';
import { clipRenderInput } from '../lib/rollClip.ts';

interface Call {
  pitches: number[];
  lanes: Array<number | undefined>;
  keys: string[];
  controls?: readonly RollControl[];
  bent: boolean;
}
let calls: Call[] = [];
const render: StepNoteRenderer = async (notes, bpm, totalSteps, opts) => {
  calls.push({
    pitches: notes.map((n) => n.note),
    lanes: notes.map((n) => (n as { lane?: number }).lane),
    keys: Object.keys(opts ?? {}).sort(),
    controls: opts?.controls,
    bent: !!opts?.bends,
  });
  return { blob: new Blob([new Uint8Array([1, 2, 3, 4])], { type: 'audio/wav' }), duration: (totalSteps * 60) / bpm / 4 };
};

const PEDAL: RollControl[] = [
  { tick: 0, controller: 7, value: 96 },
  { tick: 0, controller: 10, value: 40 },
  { tick: 480, controller: 64, value: 127 },
  { tick: 1920, controller: 64, value: 0 },
  { tick: 1920, controller: 11, value: 80 },
];
const LANES: PolyLane[] = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: null }];
const BENDS: LaneBend[] = [{ lane: 1, range: 2, points: [{ id: 'p0', step: 0, value: 0, shape: 'linear' }, { id: 'p1', step: 8, value: 1, shape: 'hold' }] }];
const note = (id: string, pitch: number, step: number, length: number, lane?: number): PianoNote => ({
  id,
  note: pitch,
  step,
  length,
  velocity: 90,
  tick: step * 240,
  ticks: length * 240,
  ...(lane !== undefined ? { lane } : {}),
});
const OWN = [note('a', 60, 0, 8, 0), note('b', 64, 0, 8, 1), note('c', 67, 8, 8, 1)];
const PLAYED = OWN.map(({ lane: _lane, ...n }) => n);

const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#8b5cf6',
  ...extra,
});
const partClip = (id: string, extra: Partial<AudioClip> = {}): AudioClip => ({
  id,
  trackId: 'pno',
  label: id,
  audioBlob: new Blob([new Uint8Array([1])], { type: 'audio/wav' }),
  mimeType: 'audio/wav',
  sourceDuration: 2,
  offsetIntoSource: 0,
  durationSec: 2,
  startSec: 0,
  color: '#8b5cf6',
  sourceKind: 'piano-roll',
  sourcePianoRoll: PLAYED.map((n) => ({ ...n })),
  sourceRollNotes: OWN.map((n) => ({ ...n })),
  sourceLanes: LANES,
  sourceBends: BENDS,
  sourceBpm: 120,
  sourceTotalSteps: 16,
  instrumentProgram: 0,
  renderedProgram: 0,
  sourceRollPart: { doc: 'd', id: 'pno-part', order: 0, name: 'Piano', program: 0, bank: 0, channel: 1, color: '#8b5cf6', mute: false, solo: false, controls: PEDAL },
  ...extra,
});
const seed = (): void => {
  calls = [];
  useEditorStore.getState().loadProject({ tracks: [track('pno', { name: 'Piano' })], clips: [partClip('keys')], bpm: 120 });
};
const clipOf = (id: string): AudioClip => useEditorStore.getState().clips.find((c) => c.id === id) as AudioClip;

// ── transpose: the render carries the part's controllers, and plays the transposed notes ─
{
  seed();
  const r = await tools.transposeClip({ clip_id: 'keys', semitones: 2, render });
  assert.ok(r.ok, r.ok ? '' : r.error);
  assert.equal(calls.length, 1);
  assert.deepEqual(calls[0].controls, PEDAL, "the transposed render plays the part's pedal, volume, pan and expression");
  // The note tool transposed the roll notes in their lanes with the played notes (lib/clipRollSync), so the render
  // plays the edit and keeps lane B's bend.
  assert.deepEqual(calls[0].pitches, [62, 66, 69], 'the transposed notes');
  assert.equal(calls[0].bent, true, "lane B's bend stays in the transposed audio");
  assert.deepEqual(calls[0].lanes, [0, 1, 1], 'each note in its lane');
  assert.deepEqual(clipRenderInput(clipOf('keys'), 16).controls, PEDAL, 'the clip still holds them for the next render');
}

// ── set_clip_instrument and bounce_clip: the roll notes still play the clip, so the bends come too ─
{
  seed();
  const r = await tools.setClipInstrument({ clip_id: 'keys', program: 48, render });
  assert.ok(r.ok, r.ok ? '' : r.error);
  assert.deepEqual(calls[0].controls, PEDAL);
  assert.equal(calls[0].bent, true, "lane B's bend is in the new instrument's audio");
  assert.deepEqual(calls[0].lanes, [0, 1, 1], 'each note in its lane');
  assert.deepEqual(calls[0].keys, ['bends', 'controls', 'percussion', 'program'], 'no tempo map: the clip has one tempo');

  seed();
  const b = await tools.bounceClip({ clip_id: 'keys', flatten: true, render });
  assert.ok(b.ok, b.ok ? '' : b.error);
  assert.deepEqual(calls[0].controls, PEDAL, 'a flattened bounce keeps them in the audio it leaves');
  assert.equal(clipOf('keys').sourceKind, 'audio');
}

// ── stretch_clip: the controllers stretch with the notes ─────────────────────
{
  seed();
  const r = await tools.stretchClip({ clip_id: 'keys', target_bpm: 60, render });
  assert.ok(r.ok, r.ok ? '' : r.error);
  assert.deepEqual(calls[0].controls, PEDAL, 'the stretched render plays them, each at its tick on the new tempo');
  assert.equal(calls[0].bent, true);
}

// ── a part with no controllers renders with none ────────────────────────────
{
  seed();
  const { controls: _none, ...bare } = clipOf('keys').sourceRollPart!;
  useEditorStore.getState().loadProject({ tracks: [track('pno')], clips: [partClip('keys', { sourceRollPart: bare })], bpm: 120 });
  const r = await tools.transposeClip({ clip_id: 'keys', semitones: -1, render });
  assert.ok(r.ok, r.ok ? '' : r.error);
  assert.equal(calls[0].controls, undefined);
  assert.equal(calls[0].keys.includes('controls'), false, 'no field at all');
}

console.log('editorTools.partControls: ok');
