/**
 * The assistant's note tools and a part's render: why it holds one, and the
 * MIDI render queue's turn.
 *
 * A render a note tool writes keeps the reason the part held one: a part that
 * cannot play live gets a render marked as made so it can be heard, and once
 * the part plays live (set_clip_instrument gives it a program) the tool drops
 * that render instead of rendering it again. A render kept on purpose is
 * re-rendered and stays kept, and the bounce tool's render is kept. Every
 * render a tool makes takes the queue's turn, so a tool never renders while
 * the queue does (at 057f7499 the tools rendered outside the queue while
 * midiRenderQueue said no two renders ever run at once).
 *
 *   cd frontend && npx tsx src/state/editorTools.renderReasons.test.ts
 */
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import * as tools from './editorTools.ts';
import type { ToolResult } from './editorTools.ts';
import { configureMidiRenderQueue, requestMidiRender } from './midiRenderQueue.ts';
import { liveMidiIfHeard } from './liveMixer.ts';
import { rollClipFields } from '../lib/rollClip.ts';
import type { StepNoteRenderer } from '../lib/clipOps/index.ts';
import { encodeWav } from '../lib/wavEncode.ts';
import type { MidiStepRender } from '../lib/midiRender.ts';

const OFF = { useSoundfont: false, activeProgram: 0 };
let active = 0;
let maxActive = 0;
let queueGate: (() => void) | null = null;
const toolRenders: Array<number | undefined> = [];

const wav = (duration: number): Blob => {
  const sr = 8000;
  const frames = Math.max(2, Math.round(duration * sr));
  return encodeWav({ numberOfChannels: 1, sampleRate: sr, length: frames, duration: frames / sr, getChannelData: () => new Float32Array(frames) } as unknown as AudioBuffer);
};

/** The queue's stand-in synth; the first render waits at a gate when one is set. */
const queueRender: MidiStepRender = async (_notes, bpm, totalSteps) => {
  active += 1;
  maxActive = Math.max(maxActive, active);
  try {
    if (queueGate === null) await new Promise((r) => setTimeout(r, 2));
    else await new Promise<void>((r) => { queueGate = r; });
    return { blob: wav((totalSteps * 60) / bpm / 4), duration: (totalSteps * 60) / bpm / 4 };
  } finally {
    active -= 1;
  }
};
/** The tools' stand-in synth (their `render` seam), counting against the same clock. */
const render: StepNoteRenderer = async (_notes, bpm, totalSteps, opts) => {
  active += 1;
  maxActive = Math.max(maxActive, active);
  toolRenders.push(opts?.program);
  try {
    await new Promise((r) => setTimeout(r, 2));
    const duration = (totalSteps * 60) / bpm / 4;
    return { blob: wav(duration), duration };
  } finally {
    active -= 1;
  }
};
configureMidiRenderQueue({
  render: queueRender,
  computePeaks: async (_b, bins) => ({ peaks: new Float32Array(bins ?? 240) }),
  global: () => OFF,
  ensureReady: async () => true,
  livePlan: liveMidiIfHeard,
});

const ed = () => useEditorStore.getState();
const track = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});
const part = (id: string, trackId: string, pitch: number): AudioClip => ({
  id, trackId, label: id, mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0, durationSec: 2, startSec: 0, color: '#fff',
  sourceKind: 'piano-roll',
  ...rollClipFields({
    notes: [{ id: `${id}0`, note: pitch, step: 0, length: 4, velocity: 100 }, { id: `${id}1`, note: pitch + 7, step: 8, length: 4, velocity: 100 }],
    bpm: 120, totalSteps: 16, meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }], pickupSteps: 0,
    lanes: [{ id: 0, name: 'A', cycleSteps: null }], bends: [],
  }),
});
const clipOf = (id: string) => ed().clips.find((c) => c.id === id)!;
const okOf = async (r: ToolResult | Promise<ToolResult>, what: string): Promise<ToolResult> => {
  const res = await r;
  assert.ok(res.ok, `${what}: ${res.error}`);
  return res;
};

async function main(): Promise<void> {
  ed().loadProject({
    tracks: [track('bare'), track('vn', { instrumentProgram: 40 }), track('kit', { isPercussion: true })],
    clips: [part('hum', 'bare', 48), part('violin', 'vn', 60), part('beat', 'kit', 36)],
  });

  // A part with no instrument cannot play live: a note edit renders it, marked as made to be heard.
  await okOf(tools.transposeClip({ clip_id: 'hum', semitones: 2, render }), 'transpose the part with no instrument');
  assert.deepEqual(toolRenders, [undefined], 'rendered through the voice it has');
  assert.ok(clipOf('hum').audioBlob instanceof Blob);
  assert.equal(clipOf('hum').renderAuto, true, 'made so it can be heard');
  // A second edit while it still cannot play live renders it again and keeps the mark.
  await okOf(tools.transposeClip({ clip_id: 'hum', semitones: 1, render }), 'transpose again');
  assert.equal(toolRenders.length, 2);
  assert.equal(clipOf('hum').renderAuto, true);
  // set_clip_instrument gives it a program: it plays live, and the render goes instead of rendering again.
  const r = await okOf(tools.setClipInstrument({ clip_id: 'hum', program: 71, render }), 'give it a clarinet');
  assert.equal(toolRenders.length, 2, 'nothing rendered');
  assert.equal(clipOf('hum').audioBlob, undefined, 'the render made to be heard is dropped');
  assert.equal(clipOf('hum').renderAuto, undefined);
  assert.match(r.message ?? '', /plays live/);
  // Undo brings the render back with its mark, as the dropped audio it was.
  ed().undo();
  assert.ok(clipOf('hum').audioBlob instanceof Blob);
  assert.equal(clipOf('hum').renderAuto, true, 'undo covers the mark');
  ed().redo();
  assert.equal(clipOf('hum').audioBlob, undefined);

  // A render kept on purpose is re-rendered by a note edit and stays kept.
  await requestMidiRender('violin', 'keep');
  const kept = toolRenders.length;
  await okOf(tools.transposeClip({ clip_id: 'violin', semitones: -12, render }), 'transpose the kept part');
  assert.equal(toolRenders.length, kept + 1, 'rendered again');
  assert.deepEqual(toolRenders.at(-1), 40);
  assert.equal(clipOf('violin').renderAuto, undefined, 'still kept');

  // The bounce tool's render is asked for: kept, even on a part that could not play live.
  ed().updateTrack('bare', { instrumentProgram: undefined });
  ed().updateClip('hum', { instrumentProgram: undefined });
  await okOf(tools.transposeClip({ clip_id: 'hum', semitones: 1, render }), 'no instrument again');
  assert.equal(clipOf('hum').renderAuto, true);
  await okOf(tools.bounceClip({ clip_id: 'hum', render }), 'bounce it');
  assert.equal(clipOf('hum').renderAuto, undefined, 'a bounce keeps its render');

  // A tool's render waits for the queue's render ahead of it: never two at once.
  maxActive = 0;
  ed().updateClip('beat', { sourcePianoRoll: clipOf('beat').sourcePianoRoll!.map((n) => ({ ...n, velocity: 90 })) });
  queueGate = () => undefined;
  const queued = requestMidiRender('beat', 'keep'); // a drum part: renders through the queue, held at the gate
  await new Promise((res) => setTimeout(res, 5));
  const tool = tools.transposeClip({ clip_id: 'violin', semitones: 12, render });
  await new Promise((res) => setTimeout(res, 20));
  assert.equal(active, 1, 'the tool waits while the queue renders');
  (queueGate as () => void)();
  queueGate = null;
  await queued;
  await okOf(tool, 'transpose after the queue\'s turn');
  assert.equal(maxActive, 1, 'no two renders ever ran at once');

  console.log('editorTools.renderReasons: ok');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
