/**
 * editorStore, the live-VST half: where a captured plugin state came FROM,
 * where a master plugin's parameters land, and why exploding a clip into stems
 * is one undo step.
 *
 * Three rules are pinned here.
 *
 *  1. STATE ORIGIN. A VST3 state blob is not portable between theDAW's live
 *     host and the offline pedalboard renderer, so a `raw_state` without the
 *     host that wrote it is unusable. The capture paths therefore name their
 *     host, and the ones that do NOT name it are the old sidecar — which is
 *     also every project written before the field existed.
 *  2. MASTER VST PARAMS. A `param` event from a plugin's own editor had
 *     nowhere to land for a masterVstChain entry: the chain had a raw-state
 *     setter and no param setter, so turning a knob in Ozone's window on the
 *     master updated nothing. Like the track/master FX equivalents it is
 *     UNDO-EXEMPT — a plugin emits these at 30 Hz per parameter, and a history
 *     entry per tick would make undo useless.
 *  3. ONE-STEP EXPLODE. "Separate stems → tracks" adds a track and a clip per
 *     stem and then mutes the parent. `updateClip` keys its coalescing on the
 *     clip while `addTrack`/`addClipToTrack` are anonymous, so the mute used to
 *     open a SECOND undo step: one Ctrl-Z left the stems on the timeline with
 *     the parent unmuted, playing everything twice. The explode opts into
 *     `coalesce`, exactly as a stretch drag does.
 *
 * Run: npx tsx src/state/editorStore.vstLive.test.ts
 */
import assert from 'node:assert/strict';

import {
  beginUndoStep,
  useEditorStore,
  type AudioClip,
  type EditorTrack,
} from './editorStore.ts';
import type { ChainEntry } from './effectChainStore.ts';

/** `vstStateHost`'s rule, restated locally: importing effectChainStore beside
 *  editorStore here would evaluate the rack registry mid-cycle under tsx, and
 *  the helper itself is pinned in `effectChainStore.test.ts`. */
const originOf = (vst: { state_host?: string } | undefined): string =>
  vst?.state_host === 'thedaw' ? 'thedaw' : 'pedalboard';

const st = () => useEditorStore.getState();
const steps = (): number => st()._undo.length;

const PLUGIN = { plugin_path: 'C:/VST3/Ozone 11.vst3', plugin_name: 'Ozone 11' };

const track = (over: Partial<EditorTrack> = {}): EditorTrack => ({
  id: 't1', name: 'T1', nameAutoGenerated: false, volume: 0.8, pan: 0,
  mute: false, solo: false, color: '#fff', ...over,
});

const clip = (over: Partial<AudioClip> = {}): AudioClip =>
  ({
    id: 'c1', trackId: 't1', label: 'take', audioBlob: new Blob(), mimeType: 'audio/wav',
    sourceDuration: 10, offsetIntoSource: 0, durationSec: 10, startSec: 0, color: '#fff',
    fadeInSec: 0, fadeOutSec: 0, gain: 1, muted: false, ...over,
  }) as AudioClip;

const reset = (over: Record<string, unknown> = {}): void => {
  useEditorStore.setState({
    tracks: [track()],
    clips: [clip()],
    masterFxChain: [],
    masterVstChain: [],
    automationLanes: [],
    markers: [],
    ...over,
  } as never);
  useEditorStore.setState({ _undo: [], _redo: [] });
  beginUndoStep();
};

const masterVst = (): ChainEntry => {
  const [e] = st().masterVstChain;
  assert.ok(e, 'expected one master VST entry');
  return e;
};

/* ── 1. the master VST chain records which host captured its state ─────────── */
{
  reset();
  st().addMasterVst(PLUGIN);
  const id = masterVst().id;

  st().setMasterVstRawState(id, 'SIDECAR');
  assert.equal(masterVst().vst?.raw_state, 'SIDECAR');
  assert.equal(
    originOf(masterVst().vst),
    'pedalboard',
    'the old editor path names no host, and that IS the sidecar',
  );

  st().setMasterVstRawState(id, 'LIVE', 'thedaw');
  assert.equal(masterVst().vst?.raw_state, 'LIVE');
  assert.equal(masterVst().vst?.state_host, 'thedaw', 'a live capture re-homes the entry');
}

/* ── a track's VST entry records it the same way ───────────────────────────── */
{
  reset();
  st().addTrackVst('t1', PLUGIN);
  const entryId = (st().tracks[0].fxChain ?? [])[0].id;
  const trackVst = () => (st().tracks[0].fxChain ?? []).find((e) => e.id === entryId);

  st().setTrackVstRawState('t1', entryId, 'SIDECAR');
  assert.equal(originOf(trackVst()?.vst), 'pedalboard');
  st().setTrackVstRawState('t1', entryId, 'LIVE', 'thedaw');
  assert.equal(trackVst()?.vst?.state_host, 'thedaw');
  assert.equal(trackVst()?.vst?.raw_state, 'LIVE');
}

/* ── 2. a master VST's parameters land, and open no undo step per tick ─────── */
{
  reset();
  st().addMasterVst(PLUGIN);
  const id = masterVst().id;
  const before = steps();

  st().setMasterVstParams(id, { p0: 0.25 });
  assert.deepEqual(masterVst().params, { p0: 0.25 }, 'the knob the user turned in the plugin landed');

  // 30 events in a burst, exactly as a plugin editor emits them.
  for (let i = 1; i <= 30; i += 1) st().setMasterVstParams(id, { p0: i / 100 });
  assert.deepEqual(masterVst().params, { p0: 0.3 }, 'the last value is what stuck');
  assert.equal(steps(), before + 1, 'a whole editor gesture is at most ONE undo step');

  // The key matches `setMasterVstRawState`, so the state the editor commits at
  // the end of the same gesture folds in with it instead of opening another.
  st().setMasterVstRawState(id, 'AFTER', 'thedaw');
  assert.equal(steps(), before + 1, 'and the state capture that ends it folds in');

  // An id with no entry is a no-op, not a throw: a `param` event can outlive
  // the entry the user just deleted.
  st().setMasterVstParams('gone', { p0: 1 });
  assert.deepEqual(masterVst().params, { p0: 0.3 });
}

/* ── 3. the explode-shaped sequence is exactly one undo step ───────────────── */
{
  reset();
  assert.equal(st().clips[0].muted, false);
  const tracksBefore = st().tracks.length;
  const stepsBefore = steps();

  // The shape `explodeClipToStems` runs after its downloads: one cut, then a
  // track + clip per stem, then the parent mute — with nothing awaited between
  // them, so they all land inside one coalescing window.
  beginUndoStep();
  for (const name of ['vocals', 'drums']) {
    const trackId = st().addTrack({ name, color: '#abc' });
    st().addClipToTrack({
      trackId,
      label: name,
      audioBlob: new Blob(),
      mimeType: 'audio/wav',
      sourceDuration: 10,
      offsetIntoSource: 0,
      durationSec: 10,
      startSec: 0,
      color: '#abc',
      fadeInSec: 0,
      fadeOutSec: 0,
      gain: 1,
      muted: false,
    });
  }
  st().updateClip('c1', { muted: true }, { coalesce: true });

  assert.equal(st().tracks.length, tracksBefore + 2, 'two stem tracks were placed');
  assert.equal(st().clips[0].muted, true, 'and the parent was muted');
  assert.equal(steps(), stepsBefore + 1, 'the whole explode is ONE undo step');

  st().undo();
  assert.equal(st().tracks.length, tracksBefore, 'one undo removes the stem tracks');
  assert.equal(st().clips.length, 1, 'and their clips');
  assert.equal(st().clips[0].muted, false, 'and leaves the parent audible again');
}

/* ── an ordinary clip edit still opens its own step ────────────────────────── */
{
  reset();
  const before = steps();
  st().updateClip('c1', { startSec: 4 });
  assert.equal(steps(), before + 1, 'a plain updateClip is still a step of its own');
  st().updateClip('c1', { muted: true });
  assert.equal(
    steps(),
    before + 1,
    'two writes keyed to the same clip inside the window are one gesture, as before',
  );
}

console.log('editorStore.vstLive: ok');
