/**
 * A frozen master stays current through what happens to a MIDI part's render
 * cache, and goes stale when the part's music changes.
 *
 * The sequence, against the real editor store and MIDI render queue (a
 * stand-in synth whose render rings out 1.2 s past the grid): a score with a
 * live part (no render) and an audio clip is signed as a master freeze signs
 * it. The part's render is kept (Keep rendered audio), dropped, and made again
 * in the background (EDIT's upkeep of a part that cannot play live), and the
 * signature stays the same each time, because a bounce prints the same part
 * either way. A note edit, a trim of the part, a new instrument and a changed
 * audio clip each stale it. At 1efb542c the signature held the render's size
 * and the part's length, so a Keep (a new size and 1.2 s of ring-out) or a
 * background render staled the frozen master and asked for a re-freeze.
 *
 *   cd frontend && npx tsx src/state/freezeSignature.midi.test.ts
 */
import assert from 'node:assert/strict';
import { freezeSignature, useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import { configureMidiRenderQueue, requestMidiRender } from './midiRenderQueue.ts';
import { DROP_RENDER_FIELDS, type MidiStepRender } from '../lib/midiRender.ts';
import { rollClipFields } from '../lib/rollClip.ts';

const PICKER = { useSoundfont: false, activeProgram: 0 };
const RING_OUT = 1.2;
const render: MidiStepRender = async (notes, bpm, totalSteps) => ({
  blob: new Blob([new Uint8Array(64 + notes.length * 16)], { type: 'audio/wav' }),
  duration: (totalSteps * 60) / bpm / 4 + RING_OUT,
});
configureMidiRenderQueue({
  render,
  computePeaks: async (_b, bins) => ({ peaks: new Float32Array(bins ?? 240) }),
  global: () => PICKER,
  ensureReady: async () => true,
});

const ed = () => useEditorStore.getState();
const sign = (): string => {
  const s = ed();
  return freezeSignature({ clips: s.clips, tracks: s.tracks, masterFxChain: s.masterFxChain, masterVstChain: s.masterVstChain, bpm: s.bpm, global: PICKER });
};
const part = (): AudioClip => ed().clips.find((c) => c.id === 'p')!;

const track = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});
const fields = rollClipFields({
  notes: [{ id: 'n0', note: 60, step: 0, length: 4, velocity: 100 }, { id: 'n1', note: 64, step: 4, length: 8, velocity: 100 }],
  bpm: 120,
  totalSteps: 16,
  meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }],
  pickupSteps: 0,
  lanes: [{ id: 0, name: 'A', cycleSteps: null }],
  bends: [],
});
// The whole grid (one 4/4 bar at 120) as the window of a part with no render.
const nominal = 2;
ed().loadProject({
  tracks: [track('vn', { instrumentProgram: 40 }), track('dr')],
  clips: [
    { id: 'p', trackId: 'vn', label: 'Violin I', mimeType: 'audio/wav', sourceDuration: nominal, offsetIntoSource: 0, durationSec: nominal, startSec: 0, color: '#fff', sourceKind: 'piano-roll', ...fields },
    { id: 'a', trackId: 'dr', label: 'drums', audioBlob: new Blob([new Uint8Array(32)], { type: 'audio/wav' }), mimeType: 'audio/wav', sourceDuration: 1, offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff' },
  ],
});
const frozen = sign();

// ── Keep rendered audio: a render with its ring-out on the timeline ──
const kept = await requestMidiRender('p', 'keep');
assert.equal(kept.kind, 'written');
assert.ok(part().audioBlob instanceof Blob, 'the part holds its render');
assert.ok(Math.abs(part().durationSec - (nominal + RING_OUT)) < 1e-9, 'and shows its ring-out');
assert.equal(sign(), frozen, 'Keep leaves the frozen master current');

// ── Drop rendered audio ──
ed().applyClipRender('p', { ...DROP_RENDER_FIELDS });
assert.equal(part().audioBlob, undefined);
assert.equal(sign(), frozen, 'Drop leaves it current');

// ── a background render (EDIT's upkeep of a part that cannot play live) ──
const upkeep = await requestMidiRender('p', 'cache');
assert.equal(upkeep.kind, 'written');
assert.equal(part().renderAuto, true, 'made so the part can be heard');
assert.equal(sign(), frozen, 'a background render leaves it current');

// ── what a bounce prints differently stales it ──
ed().updateClip('p', { sourcePianoRoll: part().sourcePianoRoll!.map((n) => ({ ...n, note: n.note + 2 })) });
const edited = sign();
assert.notEqual(edited, frozen, 'a note edit stales it');
ed().updateClip('p', { durationSec: 1.5 });
assert.notEqual(sign(), edited, 'a trim of the part stales it');
const trimmed = sign();
ed().updateTrack('vn', { instrumentProgram: 42 });
assert.notEqual(sign(), trimmed, 'a new instrument stales it');
const revoiced = sign();
ed().updateClip('a', { audioBlob: new Blob([new Uint8Array(48)], { type: 'audio/wav' }) });
assert.notEqual(sign(), revoiced, 'an audio clip is still signed by its audio');

console.log('freezeSignature.midi: ok');
