/**
 * A frozen master goes stale when a bus, the routing or an automation lane
 * changes, and stays current through a rename.
 *
 * The master freeze prints every bus's VST3 inserts into the frozen master
 * (lib/render/insertPrint), and the master bounce it is made from walks the
 * routing graph and bakes every automation lane. The signature a freeze was
 * stamped with, and the one EDIT's stale badge and the live mixer compared it
 * with, signed none of the three: a new state dialled into a bus plugin, a
 * track moved onto a bus, or a new breakpoint left the frozen master claiming
 * to be current, and the frozen preview played the old mix.
 *
 * The sequence, against the real editor store: a track routed into a bus that
 * holds a plugin is signed as a master freeze signs it
 * (`documentFreezeSignature`, the one call all three make), then each edit is
 * made and the document signed again.
 *
 *   cd frontend && npx tsx src/state/freezeSignature.buses.test.ts
 */
import assert from 'node:assert/strict';
import { documentFreezeSignature, useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import type { ChainEntry } from './effectChainStore.ts';
import { addBus, emptyGraph, ensureTrackNode, setOutput, type RoutingGraph } from './routingGraph.ts';

const PICKER = { useSoundfont: false, activeProgram: 0 };
const ed = () => useEditorStore.getState();
const sign = (): string => documentFreezeSignature(ed(), PICKER);

const track = (id: string): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff',
});
const clip = (id: string, trackId: string): AudioClip => ({
  id, trackId, label: id, audioBlob: new Blob([new Uint8Array(32)], { type: 'audio/wav' }), mimeType: 'audio/wav',
  sourceDuration: 4, offsetIntoSource: 0, durationSec: 4, startSec: 0, color: '#fff',
});
const plugin: ChainEntry = {
  id: 'bv', effect: 'vst3', enabled: true, params: {},
  vst: { plugin_path: 'C:/Plugins/Glue.vst3', plugin_name: 'Glue', raw_state: 'c3RhdGUtMQ==', state_host: 'thedaw' },
};

let g = emptyGraph();
g = ensureTrackNode(g, 't1', 't1');
g = ensureTrackNode(g, 't2', 't2');
g = addBus(g, 'b1', 'Drums');
const routed = setOutput(g, 't1', 'b1');
assert.ok(routed.ok);
ed().loadProject({
  tracks: [track('t1'), track('t2')],
  clips: [clip('c1', 't1'), clip('c2', 't2')],
  bpm: 120,
  routing: routed.graph as RoutingGraph,
  buses: [{ id: 'b1', name: 'Drums', volume: 1, mute: false, fxChain: [plugin] }],
});

let frozen = sign();
ed().setFrozenMaster({ blob: new Blob(['frozen']), sig: frozen });
assert.equal(sign(), frozen, 'an unchanged document signs the same');

const stales = (what: string): void => {
  const now = sign();
  assert.notEqual(now, frozen, `${what} stales the frozen master`);
  frozen = now;
};

// The bus plugin, dialled in its native GUI: a new state on the entry.
ed().updateBus('b1', { fxChain: [{ ...plugin, vst: { ...plugin.vst!, raw_state: 'c3RhdGUtMg==' } }] });
stales('a new state on the bus plugin');

ed().toggleBusEffect('b1', 'bv');
stales('bypassing the bus plugin');

ed().updateBus('b1', { volume: 0.5 });
stales('the bus fader');

ed().updateBus('b1', { mute: true });
stales('muting the bus');

assert.equal(ed().setTrackOutput('t2', 'b1'), null);
stales('routing a second track into the bus');

const lane = ed().addAutomationLane({ kind: 'trackVolume', trackId: 't1' });
ed().addAutomationPoint(lane, 1, 0.5);
stales('a volume breakpoint');

// The bounce reads a lane that is switched on and holds a breakpoint, and no
// other. A lane opened from the lane picker with nothing drawn in it, or an
// edit to a lane that is switched off, is the same mix: calling the frozen
// master stale there sends the user to re-render a file that would not change.
const pan = ed().addAutomationLane({ kind: 'trackPan', trackId: 't2' });
assert.equal(sign(), frozen, 'an empty lane plays nothing');
ed().toggleAutomationLane(lane);
stales('switching a lane with breakpoints off');
ed().addAutomationPoint(lane, 2, 0.25);
assert.equal(sign(), frozen, 'a breakpoint on a lane that is switched off plays nothing');
ed().toggleAutomationLane(lane);
stales('switching it back on');
ed().addAutomationPoint(pan, 1, -0.5);
stales('the first breakpoint on the pan lane');

// Names reach no audio.
ed().updateBus('b1', { name: 'Glue bus' });
assert.equal(sign(), frozen, 'a renamed bus is the same mix');
ed().updateTrack('t1', { name: 'Kick' });
assert.equal(sign(), frozen, 'a renamed track is the same mix');

console.log('freezeSignature.buses: ok');
