// The COMPENSATED timeline: what the playhead draws vs. what the transport is at
// (T16, plan §3.8 step 3b).
//
// Since T09b every track leaves the mixer through a `comp` DelayNode holding
// `max(latency) - own`, so audio entering ANY track's chain at node time `n` is
// heard at `n + latency(X) + comp(X) = n + maxSec`. `maxSec` is therefore a
// single output-wide offset, not a per-track one, and that is what
// `outputLatencySec()` names.
//
// The consequence pinned here: while the transport is at `t`, the speakers are
// playing `t - maxSec`. The moving line is a picture of what is AUDIBLE, so it
// draws `t - maxSec`; every consumer of the transport POSITION
// (`currentTransportSec` — recording anchors, the metronome, automation touch)
// keeps reading `t`, because a source that enters at `t` is heard at `t + maxSec`
// exactly like everything else and so is already placed correctly.
//
// What is pinned:
//
//   1. `outputLatencySec()` is the slowest declared chain — 0 for a project that
//      declares nothing (so nothing about the cursor changes), 6 ms for one
//      carrying the spec's look-ahead compressor. It reads a cache refreshed by
//      `refreshOutputLatency`, which `syncTrackLatency` calls AHEAD of its
//      comp-signature gate, because that signature cannot see this number move.
//   2. `publishPlayhead` — the ONE write of `playheadSec` during playback —
//      subtracts it, and clamps at the pass start so the cursor never runs
//      backwards past where play began.
//   3. `currentTransportSec()` is NOT shifted.
//
// `tick()` itself cannot run here: it is module-private and calls
// `playerStore.getEngineCtx()`, which builds a real AudioContext off `window`.
// So the store write is driven through the exported statement `tick()` is made
// of, the same way `liveMixer.latency.test.ts` drives `syncTrackLatency` through
// `trackCompDelays` + `applyCompDelays`. What `tick()` adds on top is the rAF
// loop and `elapsed = startOffsetSec + (ctx.currentTime - startCtxTime)`.
//
// Run: npx tsx src/state/liveMixer.output.test.ts
import assert from 'node:assert/strict';

import {
  currentTransportSec,
  outputLatencySec,
  publishPlayhead,
  refreshOutputLatency,
  trackCompDelays,
} from './liveMixer.ts';
import { getRackEffect } from '../lib/rackEffects.ts';
import { useEditorStore, type EditorTrack } from './editorStore.ts';
import type { ChainEntry } from './effectChainStore.ts';

/** The compressor's declared look-ahead, straight from the real registry — the
 *  number the whole compensation feature exists to cancel. */
const COMPRESSOR_SEC = 0.006;

const close = (a: number, b: number, eps = 1e-9) => Math.abs(a - b) <= eps;

const entry = (id: string, effect: string): ChainEntry => ({ id, effect, params: {}, enabled: true });

const mk = (id: string, fxChain: ChainEntry[] = []): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 1, pan: 0,
  mute: false, solo: false, color: '#fff', fxChain,
});

/**
 * Run `fn` over a given track list, then put the store (and the cached offset)
 * back exactly as found.
 *
 * The `refreshOutputLatency()` is not test scaffolding — it is the sequencing
 * the mixer really has. `outputLatencySec()` reads a cache, and every path that
 * changes a chain, a bus or the routing lands in `syncTrackLatency`, which
 * refreshes it before it writes a single node. Setting the store without the
 * refresh is a state the mixer never occupies.
 */
function withTracks(tracks: EditorTrack[], fn: () => void): void {
  const beforeTracks = useEditorStore.getState().tracks;
  const beforePlayhead = useEditorStore.getState().playheadSec;
  try {
    useEditorStore.setState({ tracks });
    refreshOutputLatency();
    fn();
  } finally {
    useEditorStore.setState({ tracks: beforeTracks, playheadSec: beforePlayhead });
    refreshOutputLatency();
  }
}

const playhead = () => useEditorStore.getState().playheadSec;

/* ── 1. The offset itself ────────────────────────────────────────────────── */

function nothingDeclaredIsZeroOffset(): void {
  withTracks([], () => {
    assert.equal(outputLatencySec(), 0, 'an empty project has no output latency');
  });
  withTracks([mk('t1', [entry('e1', 'reverb')]), mk('t2')], () => {
    assert.equal(
      outputLatencySec(), 0,
      'a reverb declares nothing, so a project full of them is still at zero',
    );
  });
}

function oneCompressorSetsTheOffset(): void {
  assert.equal(
    getRackEffect('compressor')!.latencySec, COMPRESSOR_SEC,
    'the constant here is the registry’s own number, not a copy that can drift',
  );
  withTracks([mk('drums', [entry('e1', 'compressor')]), mk('bass')], () => {
    assert.ok(
      close(outputLatencySec(), COMPRESSOR_SEC),
      `the slowest chain sets the output offset, got ${outputLatencySec()}`,
    );
  });
}

/** It is `max`, not a sum: two tracks each lagging 6 ms still meet at 6 ms, and
 *  a track with two compressors in series pulls everyone to 12. */
function theOffsetIsTheSlowestChainNotTheTotal(): void {
  withTracks([mk('a', [entry('e1', 'compressor')]), mk('b', [entry('e2', 'compressor')])], () => {
    assert.ok(close(outputLatencySec(), COMPRESSOR_SEC), 'two equal chains meet at one of them');
  });
  withTracks([mk('a', [entry('e1', 'compressor'), entry('e2', 'compressor')]), mk('b')], () => {
    assert.ok(close(outputLatencySec(), 2 * COMPRESSOR_SEC), 'series accumulates on the one track');
  });
}

/* ── 1b. The cached offset follows a chain change ────────────────────────── */

/** `syncTrackLatency` skips its node writes when the per-track comp signature
 *  has not moved. That signature CANNOT stand in for this number, which is why
 *  the refresh sits ahead of the gate rather than behind it: a lone track is its
 *  own meeting point, so its `compSec` is 0 whatever its chain does, while
 *  `maxSec` tracks the chain exactly. Gating on the signature would leave this
 *  project's playhead uncompensated forever. */
function aChainChangeMovesTheOffsetEvenWhenTheCompsDoNot(): void {
  const sigOf = (tracks: EditorTrack[]) =>
    trackCompDelays(tracks).map((r) => `${r.trackId}=${r.compSec}`).join('|');

  const bare = [mk('solo')];
  const latent = [mk('solo', [entry('e1', 'compressor')])];

  assert.equal(sigOf(bare), sigOf(latent), 'the comp signature is identical either way — it is 0 both times');

  withTracks(bare, () => {
    assert.equal(outputLatencySec(), 0, 'a bare lone track has no offset');
  });
  withTracks(latent, () => {
    assert.ok(
      close(outputLatencySec(), COMPRESSOR_SEC),
      `but adding the compressor moves it to 6 ms, got ${outputLatencySec()}`,
    );
  });
}

/** And the cache is a cache, not a snapshot taken once: it follows the store
 *  back down again, and `refreshOutputLatency` hands back what it stored. */
function theOffsetFollowsTheChainBothWays(): void {
  withTracks([mk('a', [entry('e1', 'compressor')]), mk('b')], () => {
    assert.ok(close(refreshOutputLatency(), COMPRESSOR_SEC), 'the refresh returns what it cached');
    useEditorStore.setState({ tracks: [mk('a'), mk('b')] });
    assert.ok(
      close(outputLatencySec(), COMPRESSOR_SEC),
      'the cache holds the old number until something re-aligns the mixer',
    );
    assert.equal(refreshOutputLatency(), 0, 'and the re-align drops it back to zero');
    assert.equal(outputLatencySec(), 0, 'which is what every reader then sees');
  });
}

/* ── 2. The cursor the playhead draws ────────────────────────────────────── */

function theCursorTrailsTheTransportByTheOffset(): void {
  withTracks([mk('drums', [entry('e1', 'compressor')]), mk('bass')], () => {
    const wrote = publishPlayhead(1, 0);
    assert.ok(close(wrote, 1 - COMPRESSOR_SEC), `the cursor trails by 6 ms, got ${wrote}`);
    assert.ok(
      close(playhead(), 1 - COMPRESSOR_SEC),
      `and that is what the store holds, got ${playhead()}`,
    );
  });
}

function withNothingDeclaredTheCursorIsUnchanged(): void {
  withTracks([mk('drums', [entry('e1', 'reverb')]), mk('bass')], () => {
    assert.equal(publishPlayhead(1, 0), 1, 'no declared latency, no shift');
    assert.equal(playhead(), 1, 'so a project that declares nothing draws exactly where it did');
  });
}

/** The shift must never drag the line BEHIND where play started: at the top of a
 *  pass the transport has not yet run `maxSec` seconds, and a cursor at
 *  `fromSec - something` would jump backwards on press. */
function theCursorNeverRunsBeforeThePassStart(): void {
  withTracks([mk('drums', [entry('e1', 'compressor')]), mk('bass')], () => {
    assert.equal(publishPlayhead(0, 0), 0, 'the very first frame sits on the start, not below it');
    assert.equal(publishPlayhead(0.002, 0), 0, 'and stays there until the transport passes the offset');
    assert.ok(
      close(publishPlayhead(0.01, 0), 0.01 - COMPRESSOR_SEC),
      'then it comes off the clamp and trails normally',
    );

    // Same rule for a pass that started mid-timeline (play from the playhead,
    // a seek, or a loop wrap): the floor is where THIS pass began.
    assert.equal(publishPlayhead(5, 5), 5, 'a pass starting at 5 s draws 5 s on its first frame');
    assert.equal(publishPlayhead(5.003, 5), 5, 'still clamped three milliseconds in');
    assert.ok(close(publishPlayhead(5.5, 5), 5.5 - COMPRESSOR_SEC), 'and trails once past the offset');
  });
}

/* ── 3. The transport position is NOT shifted ────────────────────────────── */

/** A take recorded at transport `n` is heard at `n + maxSec` like every other
 *  source, so its anchor is already right and moving it would double-count.
 *  `currentTransportSec()` reads `playheadSec` while stopped — which is the one
 *  window where the cursor and the transport are the same number, because
 *  `pause`/`stop`/`seek` all park the un-shifted value. */
function theTransportPositionIsUnshifted(): void {
  withTracks([mk('drums', [entry('e1', 'compressor')]), mk('bass')], () => {
    useEditorStore.setState({ playheadSec: 1 });
    assert.equal(currentTransportSec(), 1, 'stopped at 1 s, the transport reads 1 s, not 0.994');
    assert.ok(close(outputLatencySec(), COMPRESSOR_SEC), 'with the offset in force the whole time');
  });
}

nothingDeclaredIsZeroOffset();
oneCompressorSetsTheOffset();
theOffsetIsTheSlowestChainNotTheTotal();
aChainChangeMovesTheOffsetEvenWhenTheCompsDoNot();
theOffsetFollowsTheChainBothWays();
theCursorTrailsTheTransportByTheOffset();
withNothingDeclaredTheCursorIsUnchanged();
theCursorNeverRunsBeforeThePassStart();
theTransportPositionIsUnshifted();

console.log('liveMixer.output: ok');
