/**
 * state/midiRenderQueue — piano-roll clips rendered one at a time, replayed
 * against the real editor store with a stand-in synth that counts how many
 * renders run at once.
 *
 * The sequences are the ones EDIT produces: six parts with no instrument ask
 * for a render at the same moment; a part is edited while its render runs; a
 * part is deleted, or trimmed, mid-render; and an export reads a score where
 * one part plays live with no render, one has no instrument, one holds a stale
 * render, one is muted and one is audio. The export renders what it must one
 * clip at a time, leaves the live part without a render, keeps the render of
 * the part that cannot play live, and frees the export-only render's decoded
 * audio afterwards.
 *
 *   cd frontend && npx tsx src/state/midiRenderQueue.test.ts
 */
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from './editorStore.ts';
import type { PianoNote } from './pianoRollStore.ts';
import {
  clearMidiRenderQueue,
  clipWithAudio,
  clipsWithMidiAudio,
  configureMidiRenderQueue,
  requestMidiRender,
  useMidiRenderQueue,
} from './midiRenderQueue.ts';
import { midiRenderSig, midiRenderState, type MidiStepRender } from '../lib/midiRender.ts';
import { rollClipFields } from '../lib/rollClip.ts';
import { decodeCacheStats, decodeClipBlob } from '../lib/decodeCache.ts';

const ed = () => useEditorStore.getState();
const clip = (id: string): AudioClip | undefined => ed().clips.find((c) => c.id === id);

/* ── the stand-in synth ──────────────────────────────────────────────────── */

let active = 0;
let maxActive = 0;
const calls: Array<{ program?: number; percussion?: boolean; notes: number; firstNote?: number }> = [];
/** When set, each render waits for `gate()` before it resolves. */
let gated = false;
const waiting: Array<() => void> = [];
const gate = async (): Promise<void> => {
  for (let i = 0; i < 50 && waiting.length === 0; i += 1) await new Promise((r) => setTimeout(r, 1));
  const next = waiting.shift();
  assert.ok(next, 'a render is waiting at the gate');
  next();
};
let failNext: string | null = null;

const render: MidiStepRender = async (notes, bpm, totalSteps, opts) => {
  active += 1;
  maxActive = Math.max(maxActive, active);
  calls.push({ program: opts.program, percussion: opts.percussion, notes: notes.length, firstNote: notes[0]?.note });
  try {
    if (gated) await new Promise<void>((r) => waiting.push(r));
    else await new Promise((r) => setTimeout(r, 2));
    if (failNext) { const m = failNext; failNext = null; throw new Error(m); }
    const bytes = new Uint8Array(64 + notes.length);
    bytes[0] = opts.program ?? 255;
    return { blob: new Blob([bytes], { type: 'audio/wav' }), duration: (totalSteps * 60) / bpm / 4 + 1.5 };
  } finally {
    active -= 1;
  }
};

let global = { useSoundfont: false, activeProgram: 0 };
configureMidiRenderQueue({
  render,
  computePeaks: async (_blob, bins) => ({ peaks: new Float32Array(bins ?? 240) }),
  global: () => global,
  ensureReady: async () => true,
});

/* ── the document ─────────────────────────────────────────────────────────── */

const note = (id: string, pitch: number, step: number, length = 2): PianoNote => ({ id, note: pitch, step, length, velocity: 100 } as PianoNote);

const track = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});

const part = (id: string, trackId: string, pitch: number, over: Partial<AudioClip> = {}): AudioClip => {
  const fields = rollClipFields({
    notes: [note(`${id}-1`, pitch, 0), note(`${id}-2`, pitch + 4, 4), note(`${id}-3`, pitch + 7, 8, 8)],
    bpm: 120,
    totalSteps: 16,
    meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }],
    pickupSteps: 0,
    lanes: [{ id: 0, name: 'A', cycleSteps: null }],
    bends: [],
  });
  return {
    id, trackId, label: id, mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0, durationSec: 2, startSec: 0, color: '#fff',
    sourceKind: 'piano-roll', ...fields, ...over,
  };
};

const reset = (): void => {
  calls.length = 0;
  active = 0;
  maxActive = 0;
  gated = false;
  failNext = null;
  global = { useSoundfont: false, activeProgram: 0 };
  useMidiRenderQueue.setState({ running: null, waiting: [], done: 0, failed: 0, lastError: null });
};

/* ── six parts ask at once: one render at a time ──────────────────────────── */
{
  reset();
  const tracks = Array.from({ length: 6 }, (_, i) => track(`t${i}`));
  const clips = tracks.map((t, i) => part(`p${i}`, t.id, 48 + i));
  ed().loadProject({ tracks, clips });
  const outcomes = await Promise.all(clips.map((c) => requestMidiRender(c.id, 'cache')));
  assert.equal(maxActive, 1, 'no two renders ever ran at once');
  assert.equal(calls.length, 6, 'each part rendered once');
  assert.deepEqual(outcomes.map((o) => o.kind), Array(6).fill('written'));
  for (const c of clips) {
    const now = clip(c.id)!;
    assert.ok(now.audioBlob instanceof Blob, `${c.id} holds its render`);
    assert.equal(now.renderSig, midiRenderSig(now), `${c.id} records what it was made from`);
    assert.equal(midiRenderState(now, ed().tracks.find((t) => t.id === now.trackId), global), 'current');
    assert.equal(now.peaks?.length, 240, 'with its peaks');
    assert.ok(Math.abs(now.durationSec - (2 + 1.5)) < 1e-9, 'an untrimmed part grows to hold the ring-out');
  }
  const q = useMidiRenderQueue.getState();
  assert.equal(q.running, null, 'the queue is idle again');
  assert.deepEqual(q.waiting, []);
  assert.equal(q.done, 6);
  assert.equal(ed()._undo.length, 0, 'a render is derived audio: no undo step');
}

/* ── a request for a part already waiting shares its job ──────────────────── */
{
  reset();
  ed().loadProject({ tracks: [track('t0'), track('t1')], clips: [part('a', 't0', 60), part('b', 't1', 62)] });
  gated = true;
  const first = requestMidiRender('a', 'cache');
  const b1 = requestMidiRender('b', 'cache');
  const b2 = requestMidiRender('b', 'cache');
  assert.equal(b1, b2, 'the same job, the same promise');
  assert.deepEqual(useMidiRenderQueue.getState().waiting.map((w) => w.clipId), ['b'], 'b waits behind a, once');
  assert.equal(useMidiRenderQueue.getState().running?.clipId, 'a', 'the status names the part rendering now');
  await gate();
  await first;
  await gate();
  await b1;
  assert.equal(calls.length, 2, 'b rendered once');
}

/* ── a part edited while it renders is rendered again from its new notes ──── */
{
  reset();
  ed().loadProject({ tracks: [track('t0')], clips: [part('a', 't0', 60)] });
  gated = true;
  const pending = requestMidiRender('a', 'cache');
  await new Promise((r) => setTimeout(r, 1));
  // The user transposes the part while the first render runs.
  const moved = clip('a')!.sourcePianoRoll!.map((n) => ({ ...n, note: n.note + 12 }));
  ed().updateClip('a', { sourcePianoRoll: moved });
  await gate(); // the first render lands on notes the part no longer has
  await gate(); // so it renders again
  const outcome = await pending;
  assert.equal(outcome.kind, 'written');
  assert.equal(calls.length, 2, 'rendered twice');
  assert.equal(calls[1].firstNote, 72, 'the second render plays the transposed notes');
  assert.equal(clip('a')!.renderSig, midiRenderSig(clip('a')!), 'and the render it keeps matches them');
}

/* ── a part deleted mid-render is skipped; a trimmed one keeps its trim ───── */
{
  reset();
  ed().loadProject({ tracks: [track('t0'), track('t1')], clips: [part('a', 't0', 60), part('b', 't1', 62)] });
  gated = true;
  const gone = requestMidiRender('a', 'cache');
  await new Promise((r) => setTimeout(r, 1));
  ed().removeClip('a');
  await gate();
  const o = await gone;
  assert.deepEqual(o, { kind: 'skipped', reason: 'the clip was removed while it rendered' });

  const trimmed = requestMidiRender('b', 'cache');
  await new Promise((r) => setTimeout(r, 1));
  ed().updateClip('b', { durationSec: 0.75 });
  await gate();
  await trimmed;
  assert.equal(clip('b')!.durationSec, 0.75, 'the trim made during the render is kept');
  assert.ok(Math.abs(clip('b')!.sourceDuration - 3.5) < 1e-9, 'the source is the whole render');
}

/* ── a failed render says why, and the next success clears it ─────────────── */
{
  reset();
  ed().loadProject({ tracks: [track('t0')], clips: [part('a', 't0', 60)] });
  failNext = 'soundfont did not load';
  await assert.rejects(requestMidiRender('a', 'cache'), /soundfont did not load/);
  assert.equal(useMidiRenderQueue.getState().lastError, 'a: soundfont did not load');
  assert.equal(useMidiRenderQueue.getState().failed, 1);
  assert.equal(clip('a')!.audioBlob, undefined, 'the part is left as it was');
  await requestMidiRender('a', 'cache');
  assert.equal(useMidiRenderQueue.getState().lastError, null, 'a render that lands clears the failure');
}

/* ── an export: live, unvoiced, stale, muted and audio clips ──────────────── */
{
  reset();
  global = { useSoundfont: false, activeProgram: 0 };
  const audio: AudioClip = {
    id: 'aud', trackId: 'ta', label: 'drums', audioBlob: new Blob([new Uint8Array(8)], { type: 'audio/wav' }),
    mimeType: 'audio/wav', sourceDuration: 1, offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff',
  };
  const stale = part('stale', 'tStale', 55, {
    audioBlob: new Blob([new Uint8Array(4)], { type: 'audio/wav' }), renderedProgram: 40,
  });
  ed().loadProject({
    tracks: [track('tLive', { instrumentProgram: 40 }), track('tPlain'), track('tStale', { instrumentProgram: 41 }), track('tMute', { instrumentProgram: 42 }), track('ta')],
    clips: [part('live', 'tLive', 60), part('plain', 'tPlain', 64), stale, part('muted', 'tMute', 67, { muted: true }), audio],
  });
  const progress: string[] = [];
  const out = await clipsWithMidiAudio(() => true, (n, total, label) => progress.push(`${n}/${total} ${label}`));
  assert.equal(maxActive, 1, 'the export renders one clip at a time');
  assert.deepEqual(progress, ['1/3 live', '2/3 plain', '3/3 stale'], 'three parts needed audio; the muted one never does');
  const byId = new Map(out.clips.map((c) => [c.id, c]));
  assert.ok(byId.get('live')!.audioBlob instanceof Blob, 'the export reads the live part with its render');
  assert.equal(clip('live')!.audioBlob, undefined, 'and the live part itself still holds none');
  assert.equal(byId.get('live')!.renderedProgram, 40);
  assert.ok(byId.get('live')!.durationSec > clip('live')!.durationSec, 'the export gets its ring-out');
  assert.ok(clip('plain')!.audioBlob instanceof Blob, 'a part with no instrument keeps the render it needs to be heard');
  assert.equal(clip('stale')!.renderedProgram, 41, 'the stale render was replaced and kept');
  assert.equal(byId.get('muted')!.audioBlob, undefined, 'the muted part was not rendered');
  assert.equal(byId.get('aud')!.audioBlob, audio.audioBlob, 'the audio clip is as it was');
  assert.deepEqual(out.transient, [byId.get('live')!.audioBlob], 'one render was made for this export only');
  assert.deepEqual(calls.map((c) => c.program), [40, undefined, 41]);

  // The bounce decodes it; release() frees that decoded audio once the bounce is done.
  const fakeCtx = {
    sampleRate: 44100,
    decodeAudioData: async () => ({ numberOfChannels: 2, length: 44100, sampleRate: 44100, duration: 1, getChannelData: () => new Float32Array(44100) }),
  } as unknown as BaseAudioContext;
  const before = decodeCacheStats().entries;
  await decodeClipBlob(fakeCtx, out.transient[0]);
  await decodeClipBlob(fakeCtx, clip('plain')!.audioBlob!);
  assert.equal(decodeCacheStats().entries, before + 2);
  out.release();
  assert.equal(decodeCacheStats().entries, before + 1, 'the export-only render is freed; the kept one is not');

  // Nothing left to render: a second export renders nothing and holds nothing extra.
  const again = await clipsWithMidiAudio();
  assert.equal(calls.length, 4, 'only the live part renders again for the next export');
  assert.equal(again.transient.length, 1);
  again.release();
}

/* ── an export in one track's scope, and one called off ───────────────────── */
{
  reset();
  ed().loadProject({
    tracks: [track('t0', { instrumentProgram: 1 }), track('t1', { instrumentProgram: 2 }), track('t2', { instrumentProgram: 3 })],
    clips: [part('a', 't0', 60), part('b', 't1', 62), part('c', 't2', 64)],
  });
  const scoped = await clipsWithMidiAudio((c) => c.trackId === 't1');
  assert.deepEqual(calls.map((c) => c.program), [2], 'a track stem renders that track\'s parts only');
  scoped.release();
  let stop = false;
  const called = await clipsWithMidiAudio(() => true, () => { stop = true; }, () => stop);
  assert.equal(calls.length, 2, 'called off after its first render, no more start');
  assert.equal(called.transient.length, 1);
  called.release();
}

/* ── an audio edit on a live part renders it and keeps the render ─────────── */
{
  reset();
  ed().loadProject({ tracks: [track('t0', { instrumentProgram: 40 })], clips: [part('a', 't0', 60), part('empty', 't0', 60, { sourcePianoRoll: [], sourceRollNotes: [] })] });
  const withAudio = await clipWithAudio('a');
  assert.ok(withAudio.audioBlob instanceof Blob);
  assert.ok(clip('a')!.audioBlob instanceof Blob, 'the edit asked for audio, so the part keeps it');
  const again = await clipWithAudio('a');
  assert.equal(again.audioBlob, withAudio.audioBlob, 'a current render is handed over as it is');
  assert.equal(calls.length, 1);
  // The track changes instrument: the next audio edit brings the render up to date first.
  ed().updateTrack('t0', { instrumentProgram: 41 });
  const fresh = await clipWithAudio('a');
  assert.notEqual(fresh.audioBlob, withAudio.audioBlob);
  assert.equal(fresh.renderedProgram, 41);
  await assert.rejects(clipWithAudio('empty'), /empty MIDI clip/);
}

/* ── clearing the queue drops what waits ──────────────────────────────────── */
{
  reset();
  ed().loadProject({ tracks: [track('t0'), track('t1')], clips: [part('a', 't0', 60), part('b', 't1', 62)] });
  gated = true;
  const a = requestMidiRender('a', 'cache');
  const b = requestMidiRender('b', 'cache');
  clearMidiRenderQueue('the project closed');
  assert.deepEqual(await b, { kind: 'skipped', reason: 'the project closed' });
  await gate();
  assert.equal((await a).kind, 'written', 'the render already running finishes');
}

console.log('midiRenderQueue: ok');
