/**
 * A track's voice select holds the instruments and the kits, and the kind of
 * the choice sets the track's drum flag (editorStore setTrackVoice), replayed
 * against the real editor store.
 *
 * Up to afd27bea a drum track's select listed only kits and a melodic track's
 * only instruments, and the assistant's instrument choice on a roll linked to a
 * drum track (lib/rollVoiceChoice) wrote its melodic program as a kit number:
 * choosing Electric Bass (program 33) left the track on the drum channel
 * playing kit 34. Now an instrument on a drum track turns the flag off, a kit
 * on a melodic track turns it on, each with a LOG line and one EDIT undo step.
 *
 * Run from `frontend/`:
 *   npx tsx src/state/trackVoice.test.tsx
 */
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { parseVoiceValue, voiceValue } from '../lib/voiceOptions.ts';

async function main(): Promise<void> {
  const { TrackInstrumentSelect } = await import('../components/audio/WaveformEditor.tsx');
  const { useEditorStore } = await import('./editorStore.ts');
  const { useLogStore } = await import('./logStore.ts');
  const { usePianoRollStore } = await import('./pianoRollStore.ts');
  const { chooseRollVoice } = await import('../lib/rollVoiceChoice.ts');
  const { getMidiSynth } = await import('../components/audio/vocal2midi/midiSynth.ts');
  const { clipRollLoad } = await import('../lib/rollClip.ts');
  type AudioClip = import('./editorStore.ts').AudioClip;
  type EditorTrack = import('./editorStore.ts').EditorTrack;

  // The option values.
  assert.equal(voiceValue(33, false), 'gm:33');
  assert.equal(voiceValue(0, true), 'kit:0');
  assert.equal(voiceValue(undefined, true), 'default');
  assert.deepEqual(parseVoiceValue('gm:33', true), { program: 33, drums: false });
  assert.deepEqual(parseVoiceValue('kit:40', false), { program: 40, drums: true });
  assert.deepEqual(parseVoiceValue('default', true), { program: undefined, drums: true });
  assert.deepEqual(parseVoiceValue('12', true), { program: 12, drums: true }, 'a bare number keeps the track kind');

  const ed = () => useEditorStore.getState();
  const logs = () => useLogStore.getState().entries.map((e) => e.msg);
  const trk = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
    id, name: id === 'kit' ? 'Kit' : 'Bass', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...extra,
  });
  const midi = (id: string, trackId: string, extra: Partial<AudioClip> = {}): AudioClip => ({
    id, trackId, label: id, audioBlob: new Blob([new Uint8Array(8)], { type: 'audio/wav' }), mimeType: 'audio/wav',
    sourceDuration: 1, offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff', peaks: new Float32Array(0),
    sourceKind: 'piano-roll', sourcePianoRoll: [{ id: 'm0', note: 36, step: 0, length: 4, velocity: 90 }], ...extra,
  });
  const track = (id: string) => ed().tracks.find((t) => t.id === id)!;
  const clip = (id: string) => ed().clips.find((c) => c.id === id)!;

  // The store: an instrument on a drum track turns drums off, one undo step.
  ed().loadProject({ tracks: [trk('kit', { isPercussion: true, instrumentProgram: 40 }), trk('bass', { instrumentProgram: 33 })], clips: [midi('beat', 'kit', { instrumentProgram: 40 }), midi('line', 'bass')] });
  useLogStore.getState().clear();
  ed().setTrackVoice('kit', 33, false);
  assert.equal(track('kit').isPercussion, undefined, 'the drum flag is off');
  assert.equal(track('kit').instrumentProgram, 33);
  assert.equal(clip('beat').instrumentProgram, undefined, "the clip's kit number is cleared with the flag");
  assert.ok(logs().some((m) => /Track "Kit": the melodic instrument .* turned its drum flag off/.test(m)), `a LOG line says so (${logs().join(' | ')})`);
  ed().undo();
  assert.equal(track('kit').isPercussion, true, 'one undo brings the drum flag back');
  assert.equal(track('kit').instrumentProgram, 40);
  assert.equal(clip('beat').instrumentProgram, 40);

  // A kit on a melodic track turns drums on.
  ed().setTrackVoice('bass', 0, true);
  assert.equal(track('bass').isPercussion, true);
  assert.equal(track('bass').instrumentProgram, 0);
  assert.ok(logs().some((m) => /Track "Bass": the drum kit Standard turned it into a drum track/.test(m)));
  ed().undo();
  assert.equal(track('bass').isPercussion, undefined);
  // A choice of the same kind is a plain program change, no LOG line.
  const before = logs().length;
  ed().setTrackVoice('bass', 34, false);
  assert.equal(track('bass').instrumentProgram, 34);
  assert.equal(logs().length, before, 'no flip, no LOG line');
  ed().undo();

  // The roll linked to the drum track: the assistant chooses Electric Bass.
  usePianoRollStore.getState().loadFromClip(...clipRollLoad(clip('beat')));
  assert.equal(usePianoRollStore.getState().editingClipId, 'beat');
  await getMidiSynth().setInstrument('bass');
  assert.equal(track('kit').isPercussion, undefined, 'the assistant instrument turns the drum flag off');
  assert.equal(track('kit').instrumentProgram, 33);
  ed().undo();
  assert.equal(track('kit').isPercussion, true, 'one undo step');
  // The Roll voice select's kit on the same track keeps drums and sets the kit.
  chooseRollVoice(25, true);
  assert.equal(track('kit').isPercussion, true);
  assert.equal(track('kit').instrumentProgram, 25);
  assert.equal(clip('beat').instrumentProgram, 25, 'a clip with its own kit takes the choice');
  ed().undo();

  // The assistant's editor_set_track: `drums` names the kind of the program, so a melodic program on the
  // drum track turns the flag off (it used to write 33 as a kit number and keep the drum channel).
  {
    const { handletheDAWActionResult } = await import('../orb-kit/actionHandlers.ts');
    const { summarizeEditor } = await import('../orb-kit/appContext.ts');
    const drumsOf = (id: string) => summarizeEditor(ed()).tracks.find((t) => t.id === id)?.drums;
    assert.equal(drumsOf('kit'), true, "the assistant's editorState shows the drum track");
    assert.equal(drumsOf('bass'), false);
    useLogStore.getState().clear();
    const r = await handletheDAWActionResult({ type: 'editor_set_track', payload: { track_id: 'kit', instrument_program: 33, drums: false } });
    assert.equal(r.ok, true, r.message);
    assert.match(r.message, /drums=false, instrument_program=33/);
    assert.equal(track('kit').isPercussion, undefined, 'the drum flag is off');
    assert.equal(track('kit').instrumentProgram, 33);
    assert.equal(clip('beat').instrumentProgram, undefined, "the clip's kit number goes with the flag");
    assert.ok(logs().some((m) => /turned its drum flag off/.test(m)), 'the LOG says so');
    assert.equal(drumsOf('kit'), false);
    ed().undo();
    assert.equal(track('kit').isPercussion, true, 'one undo step');
    assert.equal(track('kit').instrumentProgram, 40);
    assert.equal(clip('beat').instrumentProgram, 40);
    // A kit on the melodic track, with its volume, in one step.
    const k = await handletheDAWActionResult({ type: 'editor_set_track', payload: { track_id: 'bass', instrument_program: 0, drums: true, volume: 0.5 } });
    assert.equal(k.ok, true, k.message);
    assert.equal(track('bass').isPercussion, true);
    assert.equal(track('bass').instrumentProgram, 0);
    assert.equal(track('bass').volume, 0.5);
    ed().undo();
    assert.equal(track('bass').isPercussion, undefined, 'the kind and the volume undo together');
    assert.equal(track('bass').volume, 0.8);
    // drums alone turns the flag on with the standard kit (no program carried across kinds).
    await handletheDAWActionResult({ type: 'editor_set_track', payload: { track_id: 'bass', drums: true } });
    assert.equal(track('bass').isPercussion, true);
    assert.equal(track('bass').instrumentProgram, undefined, 'the default kit, not program 33 read as a kit');
    ed().undo();
    // Without drums the program is read in the track's kind, as before: a kit number on the drum track.
    await handletheDAWActionResult({ type: 'editor_set_track', payload: { track_id: 'kit', instrument_program: 25 } });
    assert.equal(track('kit').isPercussion, true);
    assert.equal(track('kit').instrumentProgram, 25);
    ed().undo();
    const bad = await handletheDAWActionResult({ type: 'editor_set_track', payload: { track_id: 'kit', instrument_program: 200, drums: false } });
    assert.equal(bad.ok, false);
    assert.equal(track('kit').isPercussion, true, 'a refused call changes nothing');
  }

  // The mounted select on a drum track.
  const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost/', pretendToBeVisual: true });
  const g = globalThis as unknown as Record<string, unknown>;
  for (const key of ['window', 'document', 'HTMLElement', 'HTMLSelectElement', 'Node', 'Event', 'getComputedStyle']) {
    Object.defineProperty(g, key, { value: (dom.window as unknown as Record<string, unknown>)[key], configurable: true, writable: true });
  }
  g.IS_REACT_ACT_ENVIRONMENT = true;
  const React = await import('react');
  const { createRoot } = await import('react-dom/client');
  const { act } = React;
  const doc = dom.window.document;
  const host = doc.createElement('div');
  doc.body.appendChild(host);
  const root = createRoot(host);
  const Live: React.FC = () => {
    const t = useEditorStore((s) => s.tracks.find((x) => x.id === 'kit'));
    return t ? React.createElement(TrackInstrumentSelect, { track: t }) : null;
  };
  await act(async () => { root.render(React.createElement(Live)); });
  const select = doc.getElementById('editor-track-instrument-kit') as HTMLSelectElement;
  assert.ok(select);
  assert.equal(doc.querySelector('label[for="editor-track-instrument-kit"]')?.textContent, 'Track Kit drum kit');
  assert.deepEqual([...select.querySelectorAll('optgroup')].map((o) => o.label), ['Drum kits', 'Instruments'], "the track's own kind first");
  assert.equal(select.value, 'kit:40');
  const setter = Object.getOwnPropertyDescriptor(dom.window.HTMLSelectElement.prototype, 'value')!.set!;
  await act(async () => {
    setter.call(select, 'gm:33');
    select.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
  });
  assert.equal(track('kit').isPercussion, undefined, 'choosing an instrument in the select turns drums off');
  assert.equal(track('kit').instrumentProgram, 33);
  const after = doc.getElementById('editor-track-instrument-kit') as HTMLSelectElement;
  assert.equal(doc.querySelector('label[for="editor-track-instrument-kit"]')?.textContent, 'Track Kit instrument');
  assert.deepEqual([...after.querySelectorAll('optgroup')].map((o) => o.label), ['Instruments', 'Drum kits']);
  assert.equal(after.value, 'gm:33');
  const drumKey = host.querySelector('button[aria-pressed]') as HTMLButtonElement;
  assert.equal(drumKey.getAttribute('aria-pressed'), 'false', 'the drum key shows the flag off');
  await act(async () => {
    setter.call(after, 'kit:0');
    after.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
  });
  assert.equal(track('kit').isPercussion, true, 'choosing a kit turns drums back on');
  assert.equal(drumKey.getAttribute('aria-pressed'), 'true');
  await act(async () => { root.unmount(); });

  console.log('trackVoice: ok');
}

main().then(
  () => process.exit(0),
  (err) => { console.error(err); process.exit(1); },
);
