/**
 * MIDI stage 4.7: a track's VST3 instrument plays live.
 *
 * The protocol side, against fakes: which tracks and clips the instrument
 * plays (planInstrumentTracks), how the scheduler's calls become `midi`
 * messages at timeline sample positions sent ahead by the entry's latency
 * (vstInstrumentSink), a whole pass on a fake clock (InstrumentLivePass: the
 * channel defaults, the notes, their controllers, the stop's `midi_panic`),
 * and the two bridge clients: the ops on the wire, sent only while the session
 * is ready, and `accepts_midi` read from `ready`. The host's side of the same
 * ops is tests/test_vst_host_midi.py.
 *
 *   cd frontend && npx tsx src/lib/vstLive/instrumentLive.test.ts
 */
import assert from 'node:assert/strict';
import type { AudioClip, EditorTrack } from '../../state/editorStore.ts';
import type { PianoNote, RollControl } from '../../state/pianoRollStore.ts';
import { planLiveMidi } from '../../state/liveMixer.ts';
import {
  InstrumentLivePass,
  instrumentClipIds,
  planInstrumentTracks,
  vstInstrumentSink,
  type InstrumentMidiPort,
  type VstMidiMessage,
} from './instrumentLive.ts';
import { VstBridgeClient, type BridgeSocketLike } from './bridgeClient.ts';
import { createBridgeWorker, type BridgeWorkerEvent } from './bridgeWorker.ts';
import { VstBridgeWorkerClient, type BridgeWorkerLike } from './bridgeWorkerClient.ts';

const blob = new Blob([new Uint8Array([1])], { type: 'audio/wav' });
const strings = { id: 'inst-vln', effect: 'vst3', params: {}, enabled: true, vst: { plugin_path: 'C:/VST3/Strings.vst3', plugin_name: 'Strings' } };
const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...extra,
});
const note = (step: number, pitch: number, length = 4, velocity = 100): PianoNote => ({ id: `n${step}-${pitch}`, note: pitch, step, length, velocity });
const clip = (id: string, trackId: string, startSec: number, notes: PianoNote[], extra: Partial<AudioClip> = {}): AudioClip => ({
  id, trackId, label: id, audioBlob: blob, mimeType: 'audio/wav', sourceDuration: 4, offsetIntoSource: 0, durationSec: 4, startSec,
  color: '#fff', sourceKind: 'piano-roll', sourcePianoRoll: notes, sourceBpm: 120, ...extra,
});
const part = (controls: RollControl[]) => ({ doc: 'd', id: 'p', order: 0, name: 'Violins', program: 40, bank: 0, channel: 0, color: '#fff', mute: false, solo: false, controls });

// ── which clips the instrument plays, and EDIT's synths leave alone ────────────
{
  const tracks = [track('vln', { instrument: strings, instrumentProgram: 40 }), track('pno', { instrumentProgram: 0 }), track('off', { instrument: { ...strings, id: 'x', enabled: false }, instrumentProgram: 1 })];
  const clips = [
    clip('v1', 'vln', 0, [note(0, 67)]),
    { ...clip('va', 'vln', 0, []), sourceKind: 'audio' as const, sourcePianoRoll: undefined },
    clip('p1', 'pno', 0, [note(0, 60)]),
    clip('o1', 'off', 0, [note(0, 62)]),
  ];
  const plan = planInstrumentTracks(clips, tracks);
  assert.deepEqual(plan.map((t) => [t.trackId, [...t.liveClipIds], t.channels]), [['vln', ['v1'], [0]]], 'only the switched-on slot, only its MIDI clips');
  assert.deepEqual([...instrumentClipIds(clips, tracks)], ['v1']);
  const synths = planLiveMidi(clips, tracks, { useSoundfont: true, activeProgram: 0 });
  assert.equal(synths.liveClipIds.has('v1'), false, "EDIT's synths do not also play the instrument's clip");
  assert.ok(synths.liveClipIds.has('p1') && synths.liveClipIds.has('o1'), 'the other tracks play on the synths as before');
}

// ── the sink: timeline sample positions, sent ahead by the latency ─────────────
{
  const batches: VstMidiMessage[][] = [];
  let flushNow: (() => void) | null = null;
  const sink = vstInstrumentSink({
    timelineSecAt: (ctx) => 10 + (ctx - 100), // context 100 s plays timeline 10 s
    sampleRate: () => 48000,
    latencySamples: () => 1536,
    send: (events) => batches.push(events),
    schedule: (fn) => { flushNow = fn; },
  });
  sink.control(0, 11, 90, 100.5);
  sink.noteOn(0, 40, 67, 100, 100.5, 0);
  sink.wheelRange(1, 2, 100.5);
  sink.wheel(1, 16383, 100.75);
  sink.noteOff(0, 67, 101);
  assert.equal(batches.length, 0, 'one op per tick: nothing goes until the batch is handed over');
  (flushNow as unknown as () => void)();
  const at = (sec: number) => Math.round(sec * 48000) - 1536;
  assert.deepEqual(batches[0], [
    { pos: at(10.5), data: [0xb0, 11, 90] },
    { pos: at(10.5), data: [0x90, 67, 100] },
    { pos: at(10.5), data: [0xb1, 101, 0] },
    { pos: at(10.5), data: [0xb1, 100, 0] },
    { pos: at(10.5), data: [0xb1, 6, 2] },
    { pos: at(10.5), data: [0xb1, 38, 0] },
    { pos: at(10.75), data: [0xe1, 0x7f, 0x7f] },
    { pos: at(11), data: [0x80, 67, 0] },
  ], 'each message at its timeline sample, the program number left out');
  sink.noteOn(0, 0, 60, 90, 89, 0); // timeline -1 s: before the timeline's start
  sink.flush();
  assert.deepEqual(batches[1], [{ pos: 0, data: [0x90, 60, 90] }], 'never before sample 0');
}

// ── a pass on a fake clock: defaults, notes, controllers, and the stop's panic ─
{
  let now = 50;
  const sent: VstMidiMessage[][] = [];
  let panics = 0;
  const port: InstrumentMidiPort = { sendMidi: (e) => sent.push([...e]), midiPanic: () => { panics += 1; } };
  const controls: RollControl[] = [{ tick: 0, controller: 11, value: 40 }, { tick: 960, controller: 11, value: 110 }];
  const tracks = [track('vln', { instrument: strings })];
  const clips = [clip('v1', 'vln', 0, [note(0, 67), note(8, 69)], { sourceRollPart: part(controls) })];
  const pass = new InstrumentLivePass({
    now: () => now,
    clips: () => clips,
    tracks: () => tracks,
    global: () => ({ useSoundfont: false, activeProgram: 0 }),
    projectBpm: () => 120,
    port: (id) => (id === strings.id ? port : null),
    sampleRate: () => 1000,
    latencySamples: () => 0,
    lookaheadSec: () => 0.2,
    schedule: (fn) => fn(),
  });
  // Timeline 0 s plays at context 50 s.
  pass.start(planInstrumentTracks(clips, tracks), 0, 50);
  assert.deepEqual(pass.trackIds, ['vln']);
  const first = sent.flat();
  assert.ok(first.some((m) => m.data[0] === 0xb0 && m.data[1] === 64 && m.data[2] === 0 && m.pos === 0), 'the pass opens the channel with the pedal up');
  assert.ok(first.some((m) => m.data[0] === 0xb0 && m.data[1] === 11 && m.data[2] === 40 && m.pos === 0), "the part's expression where the clip starts");
  assert.ok(first.some((m) => m.data[0] === 0x90 && m.data[1] === 67 && m.pos === 0), 'the first note at sample 0');
  assert.equal(first.some((m) => m.data[1] === 69 && m.data[0] === 0x90), false, 'the second note is past the lookahead');
  // The driving timer, every 25 ms of the clock.
  for (let i = 1; i <= 36; i += 1) {
    now = 50 + i * 0.025;
    pass.tick();
  }
  const later = sent.flat();
  assert.ok(later.some((m) => m.data[0] === 0x90 && m.data[1] === 69 && m.pos === 1000), 'the second note at 1 s, sample 1000');
  assert.ok(later.some((m) => m.data[0] === 0x80 && m.data[1] === 67 && m.pos === 500), 'the first note ends at 0.5 s');
  assert.ok(later.some((m) => m.data[0] === 0xb0 && m.data[1] === 11 && m.data[2] === 110 && m.pos === 500), 'the swell at 0.5 s');
  pass.stop();
  assert.equal(panics, 1, 'the stop releases what the plugin holds');
  assert.deepEqual(pass.trackIds, []);

  // A session that is not open yet takes nothing, and the pass does not fail.
  const idle = new InstrumentLivePass({
    now: () => 0, clips: () => clips, tracks: () => tracks, global: () => ({ useSoundfont: false, activeProgram: 0 }),
    projectBpm: () => 120, port: () => null, sampleRate: () => 1000, latencySamples: () => 0, schedule: (fn) => fn(),
  });
  idle.start(planInstrumentTracks(clips, tracks), 0, 0);
  idle.stop();
}

// ── the main-thread bridge client: ops on the wire only while ready ────────────
{
  const sockets: Array<BridgeSocketLike & { sent: string[]; open(): void; say(m: unknown): void }> = [];
  const client = new VstBridgeClient({
    url: 'ws://127.0.0.1:5000',
    handlers: {},
    socketFactory: () => {
      const s = {
        binaryType: 'blob', readyState: 0, sent: [] as string[],
        onopen: null as ((ev?: unknown) => void) | null, onclose: null, onerror: null,
        onmessage: null as ((ev: { data: unknown }) => void) | null,
        send(data: string | ArrayBuffer) { if (typeof data === 'string') this.sent.push(data); },
        close() { this.readyState = 3; },
        open() { this.readyState = 1; this.onopen?.(); },
        say(m: unknown) { this.onmessage?.({ data: JSON.stringify(m) }); },
      };
      sockets.push(s);
      return s;
    },
    schedule: () => 0,
    cancel: () => {},
    now: () => 0,
  });
  client.connect();
  const sock = sockets[0];
  sock.open();
  client.sendMidi([{ pos: 0, data: [0x90, 60, 100] }]);
  client.midiPanic();
  assert.equal(sock.sent.some((t) => t.includes('"midi')), false, 'nothing before ready: a held note would land late');
  sock.say({ ev: 'ready', protocol: 1, plugin: { name: 'S', vendor: '', version: '', category: 'Instrument', identifier: '', format: 'VST3' }, latency_samples: 0, tail_seconds: 0, sample_rate: 48000, block_size: 512, channels_in: 0, channels_out: 2, has_editor: true, state_compat: true, accepts_midi: true, warnings: [] });
  assert.equal(client.acceptsMidi, true);
  client.sendMidi([{ pos: 1536, data: [0x90, 60, 100] }]);
  client.sendMidi([]);
  client.midiPanic();
  const ops = sock.sent.map((t) => JSON.parse(t) as Record<string, unknown>).filter((o) => String(o.op).startsWith('midi'));
  assert.deepEqual(ops, [{ op: 'midi', events: [{ pos: 1536, data: [0x90, 60, 100] }] }, { op: 'midi_panic' }], 'one op per batch, none for an empty one');
  client.close();
}

// ── the worker path: main posts the op, the worker's client puts it on the wire ─
{
  const posted: unknown[] = [];
  const worker: BridgeWorkerLike = {
    postMessage: (msg: unknown) => posted.push(msg),
    terminate: () => {},
    onmessage: null,
  } as unknown as BridgeWorkerLike;
  const wc = new VstBridgeWorkerClient({ url: 'ws://127.0.0.1:5000', handlers: {} }, () => worker);
  wc.sendMidi([{ pos: 0, data: [0x90, 60, 100] }]);
  assert.equal(posted.some((m) => (m as { name?: string }).name === 'sendMidi'), false, 'not before the worker reports ready');
  const onmessage = (worker as unknown as { onmessage: ((ev: { data: BridgeWorkerEvent }) => void) | null }).onmessage;
  assert.ok(onmessage, 'the client listens to its worker');
  onmessage({ data: { ev: 'fields', fields: { ready: true, blockSize: 512, sampleRate: 48000, channelsOut: 2, pluginLatencySamples: 0, hasEditor: false } } as BridgeWorkerEvent });
  onmessage({ data: { ev: 'ready', ready: { accepts_midi: true } } as unknown as BridgeWorkerEvent });
  assert.equal(wc.acceptsMidi, true);
  wc.sendMidi([{ pos: 7, data: [0x80, 60, 0] }]);
  wc.midiPanic();
  const ops = posted.filter((m) => (m as { cmd?: string }).cmd === 'op') as Array<{ name: string; args: unknown[] }>;
  assert.deepEqual(ops.map((o) => [o.name, o.args]), [['sendMidi', [[{ pos: 7, data: [0x80, 60, 0] }]]], ['midiPanic', []]]);

  // Inside the worker: the op reaches the socket client.
  const calls: string[] = [];
  const handler = createBridgeWorker({
    post: () => {},
    makeClient: () => ({
      ready: true, blockSize: 512, sampleRate: 48000, channelsOut: 2, pluginLatencySamples: 0, hasEditor: false,
      stats: { lateBlocks: 0, maxProcessMs: 0, rttMs: -1, outOfOrder: 0, droppedIn: 0, badFrames: 0, badMessages: 0, reconnects: 0 },
      connect() {}, close() {}, retryNow() {}, sendAudio() {}, setParam() {}, getParams() {}, paramText() {}, setState() {}, getState() {},
      openEditor() {}, editorRect() {}, closeEditor() {}, bypass() {}, ping() {},
      sendMidi: (events) => calls.push(`midi:${events.length}`),
      midiPanic: () => calls.push('panic'),
    }),
  });
  handler.handle({ cmd: 'init', opts: { url: 'ws://127.0.0.1:5000' } });
  handler.handle({ cmd: 'op', name: 'sendMidi', args: [[{ pos: 1, data: [0x90, 1, 1] }, { pos: 2, data: [0x80, 1, 0] }]] });
  handler.handle({ cmd: 'op', name: 'midiPanic', args: [] });
  assert.deepEqual(calls, ['midi:2', 'panic']);
}

console.log('instrumentLive: all assertions passed');
