/**
 * An audio clip on a track whose instrument slot holds a VST3 plays DRY,
 * beside the instrument and never through it: live, and in the bounce.
 *
 * The instrument makes sound from the notes it is sent. Its input is a silent
 * source; the track's audio clips (a recorded take on the violins' track) go
 * straight into the track's fader, where the instrument's output joins them.
 * The bounce prints the instrument separately (lib/renderCore
 * printInstrumentTracks) and hands the print and the audio clip to the same
 * track strip, and the instrument is never an insert there.
 *
 * Stand-in audio graph: each node records what it connects to, so a test can
 * walk from a source to everything downstream of it. The per-clip wiring is
 * the shipped scheduleClipSources in both halves.
 *
 *   cd frontend && npx tsx src/lib/vstLive/instrumentDry.test.ts
 */
import assert from 'node:assert/strict';
import type { AudioClip, EditorTrack } from '../../state/editorStore.ts';
import type { ChainEntry } from '../../state/effectChainStore.ts';
import type { PianoNote } from '../../state/pianoRollStore.ts';
import { buildInstrumentBranch, scheduleClipSources } from '../../state/liveMixer.ts';
import type { ChainHandle } from '../rackEffects.ts';
import {
  BOUNCE_SAMPLE_RATE, printInstrumentTracks, renderBounce,
  type InstrumentRenderer, type RenderDeps,
} from '../renderCore.ts';
import { instrumentClipIds, planInstrumentTracks } from './instrumentLive.ts';

/* ── stand-in graph ─────────────────────────────────────────────────────────── */

interface Node {
  kind: string;
  outputs: Node[];
  gain: { value: number; setValueAtTime: () => void; linearRampToValueAtTime: () => void; setValueCurveAtTime: () => void; cancelScheduledValues: () => void };
  pan: Node['gain'];
  offset: { value: number };
  playbackRate: { value: number };
  buffer: unknown;
  onended: null;
  started: number;
  connect(to: Node): Node;
  disconnect(): void;
  start(): void;
  stop(): void;
}
const param = () => ({ value: 1, setValueAtTime: () => {}, linearRampToValueAtTime: () => {}, setValueCurveAtTime: () => {}, cancelScheduledValues: () => {} });
const node = (kind: string, created: Node[]): Node => {
  const n: Node = {
    kind, outputs: [], gain: param(), pan: param(), offset: { value: 1 }, playbackRate: { value: 1 }, buffer: null, onended: null, started: 0,
    connect(to) { n.outputs.push(to); return to; },
    disconnect() {},
    start() { n.started += 1; },
    stop() {},
  };
  created.push(n);
  return n;
};
const fakeBuffer = (seconds: number) => {
  const length = Math.round(seconds * BOUNCE_SAMPLE_RATE);
  return { duration: seconds, sampleRate: BOUNCE_SAMPLE_RATE, numberOfChannels: 2, length, getChannelData: () => new Float32Array(length) };
};
const fakeCtx = () => {
  const created: Node[] = [];
  const ctx = {
    sampleRate: BOUNCE_SAMPLE_RATE,
    currentTime: 0,
    length: BOUNCE_SAMPLE_RATE * 10,
    destination: node('destination', created),
    created,
    createGain: () => node('gain', created),
    createStereoPanner: () => node('panner', created),
    createBufferSource: () => node('source', created),
    createConstantSource: () => node('constant', created),
    createDelay: () => node('delay', created),
    suspend: () => Promise.resolve(),
    resume: () => Promise.resolve(),
    startRendering: async () => fakeBuffer(10),
  };
  return ctx;
};
/** Every node downstream of `from`, `from` included. */
const downstream = (from: Node): Set<Node> => {
  const seen = new Set<Node>();
  const walk = (n: Node) => {
    if (seen.has(n)) return;
    seen.add(n);
    for (const o of n.outputs) walk(o);
  };
  walk(from);
  return seen;
};
interface ChainCall { input: Node; output: Node; entries: ChainEntry[] }
const chainSpy = () => {
  const calls: ChainCall[] = [];
  const build = (_ctx: unknown, input: unknown, output: unknown, entries: ChainEntry[]): ChainHandle => {
    calls.push({ input: input as Node, output: output as Node, entries });
    (input as Node).connect(output as Node);
    return { rebuild: () => {}, updateParams: () => {}, instances: () => [], inertIds: () => [], dispose: () => {} } as unknown as ChainHandle;
  };
  return { calls, build };
};

/* ── the track: a violin part through a VST3, and a recorded take beside it ─── */

const instrument: ChainEntry = { id: 'inst-vln', effect: 'vst3', params: {}, enabled: true, vst: { plugin_path: 'C:/VST3/Strings.vst3', plugin_name: 'Strings' } };
const reverb: ChainEntry = { id: 'fx-verb', effect: 'reverb', params: {}, enabled: true };
const vln: EditorTrack = { id: 'vln', name: 'Violins', nameAutoGenerated: false, volume: 1, pan: 0, mute: false, solo: false, color: '#fff', instrument, fxChain: [reverb] };
const note = (step: number, pitch: number): PianoNote => ({ id: `n${step}`, note: pitch, step, length: 4, velocity: 100 });
const takeBlob = new Blob([new Uint8Array([7])], { type: 'audio/wav' });
const part: AudioClip = {
  id: 'part', trackId: 'vln', label: 'part', audioBlob: new Blob([new Uint8Array([1])]), mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0,
  durationSec: 2, startSec: 0, color: '#fff', sourceKind: 'piano-roll', sourcePianoRoll: [note(0, 67)], sourceBpm: 120,
};
const take: AudioClip = {
  id: 'take', trackId: 'vln', label: 'take', audioBlob: takeBlob, mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0,
  durationSec: 2, startSec: 1, color: '#fff', sourceKind: 'audio',
};

// ── live ────────────────────────────────────────────────────────────────────
{
  // The instrument plays the part; the take is not one of its clips, so the clip audio path schedules it.
  assert.deepEqual([...instrumentClipIds([part, take], [vln])], ['part']);
  assert.deepEqual(planInstrumentTracks([part, take], [vln]).map((t) => [...t.liveClipIds]), [['part']]);

  const ctx = fakeCtx();
  const trackGain = node('track-gain', ctx.created);
  const spy = chainSpy();
  const branch = buildInstrumentBranch(ctx as unknown as BaseAudioContext, trackGain as unknown as AudioNode, instrument, spy.build as never);
  assert.equal(spy.calls.length, 1);
  assert.deepEqual(spy.calls[0].entries.map((e) => e.id), ['inst-vln'], 'the branch holds the instrument alone');
  const instrumentIn = spy.calls[0].input;
  assert.equal(instrumentIn, branch.source as unknown as Node);
  assert.equal(instrumentIn.kind, 'constant');
  assert.equal(instrumentIn.offset.value, 0, "the instrument's input is silence: it plays notes, not audio");
  assert.ok(downstream(instrumentIn).has(trackGain), "the instrument's output reaches the track's fader");

  // The take, scheduled as liveMixer schedules every audio clip: into the track's fader.
  scheduleClipSources(ctx as never, take, () => fakeBuffer(2) as unknown as AudioBuffer, trackGain as never, 0, 0);
  const takeSources = ctx.created.filter((n) => n.kind === 'source');
  assert.ok(takeSources.length >= 1, 'the take is scheduled');
  for (const s of takeSources) {
    const reach = downstream(s);
    assert.ok(reach.has(trackGain), 'the take reaches the track fader');
    assert.equal(reach.has(instrumentIn), false, 'the take never enters the instrument');
    assert.equal(reach.has(branch.env as unknown as Node), false, "nor the instrument's envelope");
  }
  assert.equal(downstream(trackGain).has(instrumentIn), false, 'the fader feeds nothing back into the instrument');
}

// ── the bounce ──────────────────────────────────────────────────────────────
{
  const asked: string[][] = [];
  const printBlob = new Blob([new Uint8Array([9])], { type: 'audio/wav' });
  const render: InstrumentRenderer = async (req, rate) => {
    asked.push(req.events.map((e) => e.data.join(',')));
    return { trackId: req.track_id, audio: printBlob, frames: Math.round(req.duration * rate), sampleRate: rate, warnings: [] };
  };
  const print = await printInstrumentTracks({ bpm: 120, tracks: [vln], clips: [part, take] }, { kind: 'track', trackId: 'vln' }, render);
  assert.equal(asked.length, 1);
  assert.ok(asked[0].every((m) => /^(144|128|176|224),/.test(m)), 'the instrument is sent MIDI only, never the take');
  const takeInBounce = print.clips.find((c) => c.id === 'take');
  assert.equal(takeInBounce, take, 'the take goes to the bounce as it is');

  const ctxes: ReturnType<typeof fakeCtx>[] = [];
  const decoded = new Map<Blob, number>();
  const spy = chainSpy();
  const deps: RenderDeps = {
    clips: print.clips,
    tracks: [vln],
    masterFxChain: [],
    automationLanes: [],
    decode: async (_ctx, blob) => {
      decoded.set(blob, (decoded.get(blob) ?? 0) + 1);
      return fakeBuffer(blob === printBlob ? 6 : 2) as unknown as AudioBuffer;
    },
    buildChain: spy.build as never,
    scheduleSources: scheduleClipSources,
    makeContext: () => {
      const c = fakeCtx();
      ctxes.push(c);
      return c as unknown as OfflineAudioContext;
    },
    makeDecodeContext: () => ({ close: async () => {} }) as never,
    ensureChop: async () => {},
    sliceChunks: () => [],
  };
  await renderBounce({ scope: { kind: 'track', trackId: 'vln' }, sampleRate: BOUNCE_SAMPLE_RATE, includeFx: true, includeAutomation: false, includeTrackMix: false, float32: true }, deps);
  assert.ok(decoded.has(takeBlob) && decoded.has(printBlob), 'both the take and the print are in the bounce');
  assert.equal(spy.calls.some((c) => c.entries.some((e) => e.id === 'inst-vln')), false, 'the instrument is never an insert in the bounce');
  const trackChain = spy.calls.find((c) => c.entries.some((e) => e.id === 'fx-verb'));
  assert.ok(trackChain, "the track's own inserts are built");
  const sources = ctxes[0].created.filter((n) => n.kind === 'source');
  assert.equal(sources.length, 2, 'one source for the print, one for the take');
  for (const s of sources) {
    assert.ok(downstream(s).has(trackChain.input), 'the print and the take both reach the same track strip, side by side');
  }
}

console.log('instrumentDry: all assertions passed');
