/**
 * The Vocal2MIDI panel's voice reaches the roll it fills and nothing else.
 *
 * The sequence: the picker is on a program, EDIT holds a MIDI clip with no
 * program of its own (so it follows the picker), the panel's assistant picks
 * "strings", the panel's notes go to the (unlinked) roll, and the roll's EDIT
 * key bounces them. At 8039b45 setInstrument wrote the global picker (program
 * 48 and soundfonts on), so the EDIT clip was re-voiced and re-rendered as
 * strings. Keeping the picker alone must not lose what that write did for the
 * roll: the roll auditions and bounces the notes as strings, on a new track
 * that holds strings. Run from `frontend/`:
 *   npx tsx src/components/audio/vocal2midi/midiSynth.test.ts
 */
import assert from 'node:assert/strict';
import { getGlobalVoice, useSoundfontStore } from '../../../lib/soundfontEngine.ts';
import { getMidiSynth, vocalVoiceProgram } from './midiSynth.ts';
import { effectiveProgramFor, rollVoice } from '../../../lib/clipProgram.ts';
import { usePianoRollStore } from '../../../state/pianoRollStore.ts';
import { useEditorStore } from '../../../state/editorStore.ts';
import { bounceRollToEditor } from '../../../lib/rollBounce.ts';
import { chooseRollVoice, rollVoiceChoice } from '../../../lib/rollVoiceChoice.ts';
import { clipRollLoad } from '../../../lib/rollClip.ts';
import type { AudioClip, EditorTrack } from '../../../state/editorStore.ts';

function run(name: string, fn: () => void | Promise<void>): Promise<void> {
  return Promise.resolve(fn()).then(() => console.log(`  ok - ${name}`));
}

async function main(): Promise<void> {
  useSoundfontStore.getState().setActiveProgram(1);
  useSoundfontStore.getState().setUseSoundfont(false);
  const editClip = {};
  const editTrack = {};

  await run("the assistant's instrument sets the panel voice and leaves the picker alone", async () => {
    await getMidiSynth().setInstrument('strings');
    const sf = useSoundfontStore.getState();
    assert.equal(sf.activeProgram, 1, 'the picker keeps its program');
    assert.equal(sf.useSoundfont, false, 'the picker stays on Basic');
    assert.equal(vocalVoiceProgram(), 48, 'the panel previews strings');
    assert.equal(
      effectiveProgramFor(editClip, editTrack, { useSoundfont: sf.useSoundfont, activeProgram: sf.activeProgram }),
      undefined,
      'an EDIT clip following the picker is not re-voiced',
    );
  });

  await run('the roll the panel fills auditions and bounces as strings on a track that holds strings', async () => {
    const roll = usePianoRollStore.getState();
    useEditorStore.getState().loadProject({ tracks: [], clips: [] });
    roll.setEditingClip(null);
    roll.importNotes([{ id: 'v1', note: 60, step: 0, length: 4, velocity: 100 }], 120);
    const ed = useEditorStore.getState();
    assert.deepEqual(
      rollVoice(usePianoRollStore.getState().editingClipId, ed.clips, ed.tracks, getGlobalVoice(), usePianoRollStore.getState().voiceProgram),
      { program: 48, percussion: false },
      'the roll auditions strings',
    );
    const rendered: Array<number | undefined> = [];
    const done = await bounceRollToEditor({
      render: (_n, _b, _t, o) => {
        rendered.push(o.program);
        return Promise.resolve({ blob: new Blob([new Uint8Array(8)], { type: 'audio/wav' }), duration: 2 });
      },
      computePeaks: () => Promise.resolve({ peaks: new Float32Array(4) }),
      global: getGlobalVoice,
    });
    assert.ok(done && done.kind === 'created');
    assert.deepEqual(rendered, [48], 'the bounce renders strings');
    const clip = useEditorStore.getState().clips.find((c) => c.id === done.clipId)!;
    assert.equal(useEditorStore.getState().tracks.find((t) => t.id === clip.trackId)?.instrumentProgram, 48, 'the new track holds strings');
    assert.equal(useSoundfontStore.getState().activeProgram, 1, 'the picker still has its program');
  });

  await run('the Roll voice select back on "Same as the instrument" follows the picker', () => {
    // The bounce above linked the roll to the clip it made, whose track holds
    // strings; an unlinked roll is the one that plays its own voice.
    usePianoRollStore.getState().setEditingClip(null);
    usePianoRollStore.getState().setVoiceProgram(null);
    useSoundfontStore.getState().setActiveProgram(33);
    assert.equal(vocalVoiceProgram(), 33);
  });

  // The roll opens an EDIT clip ("Edit in Piano Roll"), then the assistant
  // picks an instrument. The roll plays its clip's voice, so the choice must
  // reach the clip's track: at 30a3edf it set only the roll's own voice, which
  // a linked roll never plays, and the Roll key was hidden while linked.
  await run("on a linked roll the assistant's instrument sets the clip's track instrument", async () => {
    const trk = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
      id, name: id === 't1' ? 'Lead' : id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...extra,
    });
    const midi = (id: string, trackId: string, extra: Partial<AudioClip> = {}): AudioClip => ({
      id, trackId, label: id, audioBlob: new Blob([new Uint8Array(8)], { type: 'audio/wav' }), mimeType: 'audio/wav',
      sourceDuration: 1, offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff', peaks: new Float32Array(0),
      sourceKind: 'piano-roll', sourcePianoRoll: [{ id: 'm0', note: 64, step: 0, length: 4, velocity: 90 }], ...extra,
    });
    useEditorStore.getState().loadProject({ tracks: [trk('t1'), trk('t2')], clips: [midi('lead', 't1'), midi('own', 't2', { instrumentProgram: 5 })] });
    usePianoRollStore.getState().setVoiceProgram(null);
    const lead = useEditorStore.getState().clips.find((c) => c.id === 'lead')!;
    usePianoRollStore.getState().loadFromClip(...clipRollLoad(lead));
    assert.equal(usePianoRollStore.getState().editingClipId, 'lead');

    await getMidiSynth().setInstrument('strings');
    const ed = () => useEditorStore.getState();
    assert.equal(ed().tracks.find((t) => t.id === 't1')?.instrumentProgram, 48, "the clip's track holds strings");
    assert.equal(usePianoRollStore.getState().voiceProgram, null, "the roll's own voice is left alone");
    assert.deepEqual(
      rollVoice('lead', ed().clips, ed().tracks, getGlobalVoice(), usePianoRollStore.getState().voiceProgram),
      { program: 48, percussion: false },
      'the linked roll auditions strings',
    );
    assert.equal(vocalVoiceProgram(), 48, 'the panel previews strings');
    const shown = rollVoiceChoice('lead', ed().clips, ed().tracks, null);
    assert.equal(shown.track?.name, 'Lead', 'the Roll voice select and key name the track');
    assert.equal(shown.program, 48);
    assert.equal(useSoundfontStore.getState().activeProgram, 33, 'the picker keeps its program');

    // The choice is one EDIT undo step, and redo puts it back.
    ed().undo();
    assert.equal(ed().tracks.find((t) => t.id === 't1')?.instrumentProgram, undefined, 'EDIT undo covers the choice');
    ed().redo();
    assert.equal(ed().tracks.find((t) => t.id === 't1')?.instrumentProgram, 48);

    // The roll's EDIT key re-renders the clip in place through strings.
    const rendered: Array<number | undefined> = [];
    const done = await bounceRollToEditor({
      render: (_n, _b, _t, o) => {
        rendered.push(o.program);
        return Promise.resolve({ blob: new Blob([new Uint8Array(8)], { type: 'audio/wav' }), duration: 2 });
      },
      computePeaks: () => Promise.resolve({ peaks: new Float32Array(4) }),
      global: getGlobalVoice,
    });
    assert.equal(done?.kind, 'updated');
    assert.deepEqual(rendered, [48]);
    assert.equal(ed().clips.find((c) => c.id === 'lead')?.renderedProgram, 48);
  });

  await run('a linked clip with its own program takes the choice too, and "Same as the instrument" clears both', () => {
    const own = useEditorStore.getState().clips.find((c) => c.id === 'own')!;
    usePianoRollStore.getState().loadFromClip(...clipRollLoad(own));
    assert.equal(chooseRollVoice(24), 'track');
    const ed = useEditorStore.getState();
    assert.equal(ed.tracks.find((t) => t.id === 't2')?.instrumentProgram, 24);
    assert.equal(ed.clips.find((c) => c.id === 'own')?.instrumentProgram, 24, 'the program that sounds is the one chosen');
    assert.equal(chooseRollVoice(null), 'track');
    const after = useEditorStore.getState();
    assert.equal(after.tracks.find((t) => t.id === 't2')?.instrumentProgram, undefined);
    assert.equal(after.clips.find((c) => c.id === 'own')?.instrumentProgram, undefined);
    // Unlinked again, the choice is the roll's own voice.
    usePianoRollStore.getState().setEditingClip(null);
    assert.equal(chooseRollVoice(40), 'roll');
    assert.equal(usePianoRollStore.getState().voiceProgram, 40);
  });

  await run('a drum track linked to the roll shows and takes a kit', () => {
    useEditorStore.getState().loadProject({
      tracks: [{ id: 'd1', name: 'Kit', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', isPercussion: true }],
      clips: [{
        id: 'beat', trackId: 'd1', label: 'beat', audioBlob: new Blob([new Uint8Array(8)]), mimeType: 'audio/wav', sourceDuration: 1,
        offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff', peaks: new Float32Array(0), sourceKind: 'piano-roll',
        sourcePianoRoll: [{ id: 'k', note: 36, step: 0, length: 1, velocity: 100 }],
      }],
    });
    usePianoRollStore.getState().loadFromClip(...clipRollLoad(useEditorStore.getState().clips[0]));
    chooseRollVoice(25);
    const ed = useEditorStore.getState();
    const shown = rollVoiceChoice('beat', ed.clips, ed.tracks, null);
    assert.deepEqual([shown.drums, shown.program], [true, 25]);
    assert.equal(ed.tracks[0].isPercussion, true, 'the track stays a drum track');
  });

  console.log('vocal2midi midiSynth: ok');
}

await main();
