/**
 * The EDIT arrangement as one type-1 MIDI file (lib/arrangementMidi), and the
 * assistant's editor_export_midi that writes it.
 *
 * Before: EDIT had no MIDI export at all; the roll wrote one roll, and the
 * Vocal export one take. The arrangement's parts could only leave as audio.
 *
 * The cases, each a thing the arrangement does that the file must keep:
 * clips at their offsets with their own tempo maps, a trimmed clip, a drum
 * track on channel 10 with its kit, a clip on its own program partway down a
 * track, a muted track and a soloed one, a part's pedal and volume (and the
 * fader and pan over them), more than fifteen melodic tracks, a clip whose
 * lane bends (and a trimmed one, and one on a drum track), two tracks whose
 * parts name one channel, the arrangement's own tempo and meter maps, a span
 * of the timeline, and the scopes the export dialog and the assistant ask for.
 *
 *   cd frontend && npx tsx src/lib/arrangementMidi.test.ts
 */
import assert from 'node:assert/strict';
import { arrangementToMidiFile, faderVolumeScale, meterMapFrom, panControlOffset, tempoMapFrom, type ArrangementMidiSource } from './arrangementMidi.ts';
import { encodeMidi, parseMidi } from './midi.ts';
import type { PolyLane } from './meterMap.ts';
import { bendValueToRaw, type LaneBend } from './pitchBend.ts';
import { clipRenderInput } from './rollClip.ts';
import { beatToTime } from './tempoMap.ts';
import type { AudioClip, EditorTrack } from '../state/editorStore.ts';
import { useEditorStore } from '../state/editorStore.ts';
import { exportMidi } from '../state/editorTools.ts';
import { handletheDAWAction, overrideEditorFacadeForTest } from '../orb-kit/actionHandlers.ts';
import type { PianoNote, RollControl } from '../state/pianoRollStore.ts';

const blob = new Blob([new Uint8Array([1])], { type: 'audio/wav' });
const track = (id: string, name: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#a855f7',
  ...extra,
});
const note = (step: number, pitch: number, length = 4): PianoNote => ({ id: `n${step}-${pitch}`, note: pitch, step, length, velocity: 90, tick: step * 240, ticks: length * 240 });
const clip = (id: string, trackId: string, startSec: number, notes: PianoNote[], extra: Partial<AudioClip> = {}): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: blob,
  mimeType: 'audio/wav',
  sourceDuration: 8,
  offsetIntoSource: 0,
  durationSec: 8,
  startSec,
  color: '#a855f7',
  sourceKind: 'piano-roll',
  sourcePianoRoll: notes,
  sourceBpm: 120,
  ...extra,
});
const secOf = (tick: number, map = [{ beat: 0, bpm: 120 }]) => beatToTime(map, tick / 960);

// ── clips at their offsets, programs, drums, mute and solo ─────────────────────
{
  const source: ArrangementMidiSource = {
    bpm: 120,
    timeSignature: { num: 4, den: 4 },
    tracks: [
      track('str', 'Strings', { instrumentProgram: 48 }),
      track('kit', 'Drums', { isPercussion: true, instrumentProgram: 16 }),
      track('mute', 'Muted horn', { mute: true, instrumentProgram: 60 }),
      track('aud', 'Vocal take'),
    ],
    clips: [
      clip('s1', 'str', 1, [note(0, 60), note(4, 64)]),
      // The second clip on the strings plays its own program: a program change where it starts.
      clip('s2', 'str', 9, [note(0, 67)], { instrumentProgram: 49 }),
      clip('k1', 'kit', 2, [note(0, 36, 1), note(2, 38, 1)]),
      clip('m1', 'mute', 0, [note(0, 55)]),
      { ...clip('a1', 'aud', 0, []), sourceKind: 'audio', sourcePianoRoll: undefined },
    ],
  };
  const out = arrangementToMidiFile(source, { global: { useSoundfont: true, activeProgram: 3 } });
  assert.deepEqual(out.file.tracks.map((t) => t.name), ['Strings', 'Drums'], 'the muted track and the audio track are not in the mix');
  const [strings, drums] = out.file.tracks;
  // A clip at 1 s: its notes at 1 s and 1.5 s (a quarter at 120), in ticks at 960 PPQ.
  assert.deepEqual(strings.notes.map((n) => [n.tick, n.durationTicks, n.note, n.channel]), [[1920, 960, 60, 0], [2880, 960, 64, 0], [17280, 960, 67, 0]]);
  assert.deepEqual(strings.programs, [{ tick: 0, channel: 0, program: 48 }, { tick: 17280, channel: 0, program: 49 }], 'program 48 from the start, 49 where the second clip starts');
  assert.ok(drums.notes.every((n) => n.channel === 9), 'the drum track on channel 10');
  assert.deepEqual(drums.programs, [{ tick: 0, channel: 9, program: 16 }], 'with its kit');
  // The muted horn is in a scope that names its track.
  const named = arrangementToMidiFile(source, { scope: { kind: 'tracks', trackIds: ['mute'] } });
  assert.deepEqual(named.file.tracks.map((t) => t.name), ['Muted horn'], 'a named track is taken, muted or not');
  // Soloing the drums leaves the strings out of the mix.
  const solo = arrangementToMidiFile({ ...source, tracks: source.tracks.map((t) => (t.id === 'kit' ? { ...t, solo: true } : t)) });
  assert.deepEqual(solo.file.tracks.map((t) => t.name), ['Drums']);
  // A clip scope takes those clips alone.
  const one = arrangementToMidiFile(source, { scope: { kind: 'clips', clipIds: ['s2'] } });
  assert.deepEqual(one.file.tracks.map((t) => [t.name, t.notes.length]), [['Strings', 1]]);
  assert.deepEqual(one.file.tracks[0].programs, [{ tick: 0, channel: 0, program: 49 }]);
  // A muted clip is never in it.
  const mutedClip = arrangementToMidiFile({ ...source, clips: source.clips.map((c) => (c.id === 's2' ? { ...c, muted: true } : c)) });
  assert.equal(mutedClip.mutedClips, 1);
  assert.equal(mutedClip.file.tracks[0].notes.length, 2);
}

// ── a trimmed clip, its own tempo map, and a part's controllers ──────────────
{
  const pedal: RollControl[] = [
    { tick: 0, controller: 7, value: 90 },
    { tick: 480, controller: 64, value: 127 },
    { tick: 3840, controller: 64, value: 0 },
    { tick: 5760, controller: 11, value: 70 },
  ];
  // The clip slows to 60 at beat 4; it is trimmed 1 s into its source and starts at 4 s on the timeline.
  const tempoMap = [{ beat: 0, bpm: 120 }, { beat: 4, bpm: 60 }];
  // The last note lasts three beats at 60 (to 10 s): longer than the clip, which ends at 9 s.
  const c = clip('p', 'pno', 4, [note(0, 48), note(8, 50), note(16, 52), note(24, 53, 12)], {
    offsetIntoSource: 1,
    durationSec: 5,
    sourceTempoMap: tempoMap,
    sourceRollPart: { doc: 'd', id: 'x', order: 0, name: 'Piano', program: 0, bank: 1, channel: 5, color: '#fff', mute: false, solo: false, controls: pedal },
  });
  const source: ArrangementMidiSource = { bpm: 120, tracks: [track('pno', 'Piano', { volume: 0.4, pan: -0.5 })], clips: [c] };
  const out = arrangementToMidiFile(source);
  const t = out.file.tracks[0];
  // Source seconds: step 0 at 0 s (trimmed away), step 8 at 1 s (the clip's left edge: 4 s), step 16 at 2 s
  // (beat 4, where 60 begins: 5 s), step 24 at 4 s (beat 6 at 60: 7 s, and the clip ends at 9 s).
  assert.deepEqual(t.notes.map((n) => [secOf(n.tick), n.note]), [[4, 50], [5, 52], [7, 53]], 'each note at the second EDIT plays it');
  assert.equal(secOf(t.notes[2].tick + t.notes[2].durationTicks), 9, 'a note running past the clip is cut at its end');
  assert.equal(t.notes[0].channel, 4, "the channel the clip's part names (5)");
  assert.deepEqual(t.programs, [{ tick: 0, channel: 4, program: 0, bank: 1 }], "the part's bank select");
  // The window starts at source second 1 (tick 960): the volume and the pedal set before it come in at the clip's start,
  // the pedal-up at source 1.5 s (tick 3840 = beat 4) at 5 s, the expression (tick 5760 = beat 6 = source 4 s) at 7 s.
  const ctl = t.controls ?? [];
  const at = (sec: number, controller: number) => ctl.filter((x) => Math.abs(secOf(x.tick) - sec) < 1e-9 && x.controller === controller).map((x) => x.value);
  // The fader at 0.4 is half the default's gain: CC 7 scales by sqrt(0.5) on the General MIDI curve; pan -0.5 moves CC 10.
  assert.deepEqual(at(4, 7), [Math.round(90 * Math.SQRT1_2)], 'volume at the clip start, scaled by the fader');
  assert.deepEqual(at(4, 64), [127], 'the pedal is down where the clip starts');
  assert.deepEqual(at(5, 64), [0]);
  assert.deepEqual(at(7, 11), [70]);
  assert.deepEqual(at(0, 10), [64 + panControlOffset(-0.5)], 'the pan as a controller at the start, the part having none');
  assert.equal(faderVolumeScale(0.8), 1);
  // Through the bytes and back.
  const back = parseMidi(encodeMidi(out.file));
  assert.deepEqual(back.tracks[0].controls?.map((x) => [x.tick, x.controller, x.value]), ctl.map((x) => [x.tick, x.controller, x.value]));
}

// ── a clip's controllers end with it, as its render does ─────────────────────
// EDIT renders each clip on its own, from a channel at the General MIDI
// defaults. A clip's pedal and volume used to stay in force in the file after
// the clip ended, so every note of the next clip on the track sustained at
// the earlier clip's volume.
{
  const part = (controls?: RollControl[]) => ({
    doc: 'd',
    id: 'x',
    order: 0,
    name: 'Piano',
    program: 0,
    bank: 0,
    channel: null,
    color: '#fff',
    mute: false,
    solo: false,
    ...(controls ? { controls } : {}),
  });
  // Clip A: volume 40 from its start, the pedal down at beat 1 (0.5 s) and up only at beat 8 (4 s), but A is
  // trimmed to end at 2 s. Clip B at 8 s has no controllers of its own.
  const pedal: RollControl[] = [
    { tick: 0, controller: 7, value: 40 },
    { tick: 960, controller: 64, value: 127 },
    { tick: 7680, controller: 64, value: 0 },
  ];
  const a = clip('a', 'pno', 0, [note(0, 48, 16)], { durationSec: 2, sourceRollPart: part(pedal) });
  const b = clip('b', 'pno', 8, [note(0, 60), note(8, 64)], { sourceRollPart: part() });
  /** Each controller's value in force when a note at `tick` sounds: changes at its tick come before it. */
  const stateAt = (controls: readonly { tick: number; controller: number; value: number }[] | undefined, tick: number) => {
    const state = new Map<number, number>([[1, 0], [7, 100], [10, 64], [11, 127], [64, 0]]);
    for (const c of [...(controls ?? [])].sort((x, y) => x.tick - y.tick)) if (c.tick <= tick) state.set(c.controller, c.value);
    return state;
  };
  const whole = parseMidi(encodeMidi(arrangementToMidiFile({ bpm: 120, tracks: [track('pno', 'Piano')], clips: [a, b] }).file)).tracks[0];
  const bFirst = whole.notes.find((x) => x.note === 60)!.tick;
  assert.equal(bFirst, 15360, 'clip B starts at 8 s');
  assert.equal(clipRenderInput(b, 16).controls, undefined, "B's render has no controllers: it plays at the defaults");
  assert.deepEqual([stateAt(whole.controls, bFirst).get(64), stateAt(whole.controls, bFirst).get(7)], [0, 100], 'the pedal is up and the volume back where B starts');
  // A's pedal comes up where A ends (2 s, tick 3840), after its note ends there, so nothing A held rings on past it.
  assert.deepEqual(whole.controls?.filter((c) => c.tick === 3840).map((c) => [c.controller, c.value]), [[64, 0], [7, 100]], 'pedal first, then the volume');
  assert.equal(whole.controls?.some((c) => c.tick === 7680), false, "A's pedal-up past its end is not written");

  // A span from 7 s: the file starts on the bar line at 6 s, and A, which ended at 2 s, leaves nothing in it.
  const span = arrangementToMidiFile({ bpm: 120, tracks: [track('pno', 'Piano')], clips: [a, b] }, { range: { startSec: 7, endSec: 12 } });
  const spanBack = parseMidi(encodeMidi(span.file)).tracks[0];
  assert.equal(span.startSec, 6);
  const spanFirst = spanBack.notes.find((x) => x.note === 60)!.tick;
  assert.equal(spanFirst, 3840, 'B at 8 s is two seconds into the span');
  assert.deepEqual([stateAt(spanBack.controls, spanFirst).get(64), stateAt(spanBack.controls, spanFirst).get(7)], [0, 100], 'a clip before the span holds no pedal or volume in it');
  assert.equal(spanBack.controls, undefined, 'no controller change at all');

  // Clip C right where A ends, with its own volume: its value takes over at that tick; the pedal still comes up.
  const c = clip('c', 'pno', 2, [note(0, 55)], { sourceRollPart: part([{ tick: 0, controller: 7, value: 60 }]) });
  const butt = parseMidi(encodeMidi(arrangementToMidiFile({ bpm: 120, tracks: [track('pno', 'Piano')], clips: [a, c] }).file)).tracks[0];
  assert.deepEqual(butt.controls?.filter((x) => x.tick === 3840).map((x) => [x.controller, x.value]), [[64, 0], [7, 60]], "the pedal up, then C's volume");
  // A clip that starts inside A owns the channel from its start: A's later changes and its reset stop there.
  const inside = clip('in', 'pno', 1, [note(0, 57)], { durationSec: 4, sourceRollPart: part([{ tick: 0, controller: 11, value: 90 }]) });
  const overlapped = parseMidi(encodeMidi(arrangementToMidiFile({ bpm: 120, tracks: [track('pno', 'Piano')], clips: [a, inside] }).file)).tracks[0];
  const insideAt = overlapped.notes.find((x) => x.note === 57)!.tick;
  assert.deepEqual([stateAt(overlapped.controls, insideAt).get(64), stateAt(overlapped.controls, insideAt).get(7), stateAt(overlapped.controls, insideAt).get(11)], [0, 100, 90]);
  assert.equal(overlapped.controls?.some((x) => x.tick === 3840), false, "nothing of A's at its own end, inside the later clip");

  // On a track off EDIT's default fader, a clip with no volume of its own plays at the fader's volume,
  // before a clip with volume changes as well as after one.
  const quiet = track('pno', 'Piano', { volume: 0.4 });
  const late = { ...a, startSec: 8 };
  const early = { ...b, startSec: 0 };
  const faded = parseMidi(encodeMidi(arrangementToMidiFile({ bpm: 120, tracks: [quiet], clips: [early, late] }).file)).tracks[0];
  const scaled = (v: number) => Math.round(v * Math.SQRT1_2);
  assert.equal(stateAt(faded.controls, 0).get(7), scaled(100), 'the first clip, with none of its own, at the fader');
  assert.equal(stateAt(faded.controls, 15360).get(7), scaled(40), "the second clip's own volume, scaled by the fader");
  assert.equal(stateAt(faded.controls, 15360 + 3840).get(7), scaled(100), 'back at the fader where it ends');
}

// ── more than fifteen melodic tracks share channels, and say so ──────────────
{
  const tracks = Array.from({ length: 18 }, (_, i) => track(`t${i}`, `Part ${i + 1}`, { instrumentProgram: i }));
  const clips = tracks.map((t, i) => clip(`c${i}`, t.id, 0, [note(0, 60 + i)]));
  const out = arrangementToMidiFile({ bpm: 100, tracks, clips });
  const channels = out.file.tracks.map((t) => t.notes[0].channel);
  assert.ok(!channels.includes(9), 'never the drum channel');
  assert.equal(new Set(channels.slice(0, 15)).size, 15, 'fifteen channels of their own');
  assert.deepEqual(out.sharedTracks.length, 6, 'the last three share with the first three, and the export names all six');
}

// ── a clip whose lane bends: the lane on a channel of its own, with its wheel ─
{
  const lanes: PolyLane[] = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: null }];
  const own = [{ ...note(0, 60, 8), lane: 0 }, { ...note(0, 64, 8), lane: 1 }, { ...note(8, 67, 8), lane: 1 }];
  // Lane B ramps from the centre at step 0 to its whole range up (2 semitones) at step 8, then holds.
  const sourceBends: LaneBend[] = [
    { lane: 1, range: 2, points: [{ id: 'p0', step: 0, value: 0, shape: 'linear' }, { id: 'p1', step: 8, value: 1, shape: 'hold' }] },
  ];
  const bentClip = (id: string, trackId: string, extra: Partial<AudioClip> = {}) =>
    clip(id, trackId, 2, own.map(({ lane: _lane, ...n }) => n), { sourceRollNotes: own, sourceLanes: lanes, sourceBends, sourceTotalSteps: 16, durationSec: 2, sourceDuration: 2, ...extra });
  const source: ArrangementMidiSource = { bpm: 120, tracks: [track('gtr', 'Guitar', { instrumentProgram: 25 })], clips: [bentClip('b', 'gtr')] };
  const out = arrangementToMidiFile(source);
  const t = out.file.tracks[0];
  // The clip starts at 2 s (tick 3840): lane A's note on the track's channel, lane B's two on a channel of their own.
  assert.deepEqual(t.notes.map((n) => [n.tick, n.note, n.channel]), [[3840, 60, 0], [3840, 64, 1], [5760, 67, 1]]);
  assert.deepEqual(t.programs, [{ tick: 0, channel: 0, program: 25 }, { tick: 0, channel: 1, program: 25 }], 'the voice on both channels');
  assert.deepEqual(t.bendRanges, [{ tick: 3840, channel: 1, semitones: 2 }], "lane B's range with its first message");
  const wheel = t.bends ?? [];
  assert.ok(wheel.length > 2 && wheel.every((b) => b.channel === 1), 'the wheel on the channel of lane B alone');
  assert.deepEqual([wheel[0].tick, wheel[0].value], [3840, 8192], 'centre where the clip starts');
  assert.deepEqual([wheel[wheel.length - 1].tick, wheel[wheel.length - 1].value], [5760, 16383], 'the whole range up at step 8 (3 s)');
  assert.ok(wheel.every((b, i) => i === 0 || (b.value >= wheel[i - 1].value && b.tick > wheel[i - 1].tick)), 'rising, one message to a tick');
  assert.equal(out.sharedTracks.length, 0);
  // Through the bytes and back: the wheel, its range and each note's channel.
  const back = parseMidi(encodeMidi(out.file)).tracks[0];
  assert.deepEqual(back.bends?.map((b) => [b.tick, b.channel, b.value]), wheel.map((b) => [b.tick, b.channel, b.value]));
  assert.deepEqual(back.bendRanges?.map((r) => [r.tick, r.channel, r.semitones]), [[3840, 1, 2]]);
  assert.deepEqual(back.notes.map((n) => [n.tick, n.note, n.channel]), [[3840, 60, 0], [3840, 64, 1], [5760, 67, 1]]);

  // Trimmed half a second (four steps) in: the wheel starts where the curve is there, halfway up.
  const trimmed = arrangementToMidiFile({ ...source, clips: [bentClip('b', 'gtr', { offsetIntoSource: 0.5, durationSec: 1.5 })] }).file.tracks[0];
  assert.deepEqual([trimmed.bends?.[0].tick, trimmed.bends?.[0].value], [3840, bendValueToRaw(0.5)], 'halfway up at the clip start');
  assert.equal(trimmed.bends?.[trimmed.bends.length - 1].tick, 3840 + 960, 'the top at step 8, half a second after the trimmed start');

  // A drum track has one wheel for every drum: its clip's lane bends are not written, as its render bends nothing.
  const drums = arrangementToMidiFile({ bpm: 120, tracks: [track('kit', 'Drums', { isPercussion: true })], clips: [bentClip('d', 'kit')] }).file.tracks[0];
  assert.equal(drums.bends, undefined);
  assert.ok(drums.notes.every((n) => n.channel === 9));

  // Fifteen melodic tracks and a bent lane need sixteen channels: the lane's track and the one it shares with are named.
  const many = Array.from({ length: 15 }, (_, i) => track(`m${i}`, `Part ${i + 1}`, { instrumentProgram: i }));
  const crowded = arrangementToMidiFile({
    bpm: 120,
    tracks: many,
    clips: [bentClip('c0', 'm0'), ...many.slice(1).map((m, i) => clip(`c${i + 1}`, m.id, 0, [note(0, 50 + i)]))],
  });
  assert.deepEqual(crowded.sharedTracks, ['Part 1', 'Part 15']);
}

// ── two tracks whose parts name the same channel: the second takes a free one ─
{
  const part = (name: string) => ({ doc: `d-${name}`, id: name, order: 0, name, program: 40, bank: 0, channel: 1, color: '#fff', mute: false, solo: false });
  const out = arrangementToMidiFile({
    bpm: 120,
    tracks: [track('a', 'Violin I'), track('b', 'Violin II')],
    // Two files imported as tracks, each with its part on channel 1.
    clips: [clip('ca', 'a', 0, [note(0, 76)], { sourceRollPart: part('Violin I') }), clip('cb', 'b', 0, [note(0, 72)], { sourceRollPart: part('Violin II') })],
  });
  assert.deepEqual(out.file.tracks.map((t) => t.notes[0].channel), [0, 1], 'channel 1 for the first, the next free one for the second');
  assert.deepEqual(out.sharedTracks, []);
}

// ── a file whose parts share channels keeps them shared on the same channels ──
// A 24-part orchestral file shares channels (Flute 1 and Flute 2 on channel 2).
// Imported as tracks and exported, the second of each pair used to go onto
// another part's channel in turn (Flute 2 onto the Piccolo's channel 1), where
// a player sounds both on one program and the Piccolo's volume and pan reach
// the flute; read back, the Piccolo part took the flutes' controllers.
{
  const part = (name: string, channel: number, program: number) =>
    ({ doc: 'orch', id: name, order: 0, name, program, bank: 0, channel, color: '#fff', mute: false, solo: false });
  // Channels 1-9 and 11-16 each named once, then two more parts on channels 2 and 14.
  const named = [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16];
  const specs = [...named.map((ch) => ({ name: `Part ch${ch}`, ch, program: ch })), { name: 'Flute 2', ch: 2, program: 2 }, { name: 'Violin II', ch: 14, program: 14 }];
  const tracks = specs.map((s, i) => track(`t${i}`, s.name));
  const clips = specs.map((s, i) => clip(`c${i}`, `t${i}`, 0, [note(0, 60 + i)], { instrumentProgram: s.program, sourceRollPart: part(s.name, s.ch, s.program) }));
  const out = arrangementToMidiFile({ bpm: 120, tracks, clips });
  assert.deepEqual(
    out.file.tracks.map((t) => t.notes[0].channel + 1),
    specs.map((s) => s.ch),
    'every part on the channel it names, the two late ones sharing as the file did',
  );
  assert.deepEqual([...out.sharedTracks].sort(), ['Flute 2', 'Part ch14', 'Part ch2', 'Violin II'], 'the export names the parts that share');
  // With a channel free, the second part to name channel 2 still moves to it.
  const roomy = arrangementToMidiFile({ bpm: 120, tracks: tracks.slice(0, 3), clips: [clips[0], clips[1], { ...clips[15], trackId: 't2' }] });
  assert.deepEqual(roomy.file.tracks.map((t) => t.notes[0].channel + 1), [1, 2, 3], 'a free channel for the second part on channel 2');
  // A drum track is on channel 10 whatever its part names: it takes channel 2 from no melodic part.
  const kit = arrangementToMidiFile({
    bpm: 120,
    tracks: [track('k', 'Kit', { isPercussion: true }), track('f', 'Flute')],
    clips: [clip('ck', 'k', 0, [note(0, 36)], { sourceRollPart: part('Kit', 2, 0) }), clip('cf', 'f', 0, [note(0, 72)], { instrumentProgram: 73, sourceRollPart: part('Flute', 2, 73) })],
  });
  assert.deepEqual(kit.file.tracks.map((t) => t.notes[0].channel + 1), [10, 2], 'the kit on 10, the flute on the channel its part names');
}

// ── a controller's default where a clip starts is not written ────────────────
// The value each controller holds where a clip's window starts is written at
// the clip's start, so a trimmed clip starts with its pedal and volume. A part
// whose expression first changes at bar 2 used to get an expression of 127 at
// tick 0 as well, so a file read back and exported again gained a change the
// part never made.
{
  const part = (controls: RollControl[]) => ({ doc: 'd', id: 'x', order: 0, name: 'Horn', program: 60, bank: 0, channel: 6, color: '#fff', mute: false, solo: false, controls });
  const own: RollControl[] = [
    { tick: 0, controller: 7, value: 96 },
    { tick: 3840, controller: 11, value: 70 },
    { tick: 5760, controller: 1, value: 40 },
    { tick: 7680, controller: 64, value: 127 },
    { tick: 9600, controller: 64, value: 0 },
  ];
  const c = clip('h', 'hn', 0, [note(0, 60, 64)], { sourceRollPart: part(own), durationSec: 8 });
  const out = arrangementToMidiFile({ bpm: 120, tracks: [track('hn', 'Horn')], clips: [c] });
  const ctl = out.file.tracks[0].controls ?? [];
  assert.deepEqual(
    ctl.filter((x) => x.tick < 16 * 960).map((x) => [x.tick, x.controller, x.value]),
    own.map((x) => [x.tick, x.controller, x.value]),
    "the part's own changes, and no default at tick 0",
  );
  // Read back and written again: the same changes.
  const again = parseMidi(encodeMidi(out.file)).tracks[0].controls ?? [];
  assert.deepEqual(again.map((x) => [x.tick, x.controller, x.value]), ctl.map((x) => [x.tick, x.controller, x.value]));
  // Trimmed past the pedal's release (source 5 s = tick 9600): the pedal is up there already and is not written;
  // the expression and modulation it holds, off their defaults, are.
  const trimmed = arrangementToMidiFile({ bpm: 120, tracks: [track('hn', 'Horn')], clips: [{ ...c, offsetIntoSource: 5.5, durationSec: 2 }] });
  assert.deepEqual(
    (trimmed.file.tracks[0].controls ?? []).filter((x) => x.tick === 0).map((x) => [x.controller, x.value]).sort((a, b) => a[0] - b[0]),
    [[1, 40], [7, 96], [11, 70]],
    'a trimmed clip starts with the values off their defaults',
  );
}

// ── the arrangement's own tempo and meter maps, and a span ───────────────────
{
  const tempoMap = [{ beat: 0, bpm: 120 }, { beat: 8, bpm: 90, curve: 'linear' as const }, { beat: 16, bpm: 60 }];
  const meterMap = [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }, { bar: 2, meter: { num: 7, den: 8, groups: [2, 2, 3] } }];
  const source: ArrangementMidiSource = {
    bpm: 120,
    tempoMap,
    meterMap,
    tracks: [track('a', 'Oboe', { instrumentProgram: 68 })],
    clips: [clip('o', 'a', 0, Array.from({ length: 16 }, (_, i) => note(i * 4, 70)), { durationSec: 60, sourceDuration: 60 })],
  };
  const out = arrangementToMidiFile(source);
  assert.deepEqual(out.file.timeSignatures?.map((s) => [s.tick, s.num, s.den, (s.groups ?? []).join('+')]), [[0, 4, 4, ''], [7680, 7, 8, '2+2+3']], 'the meter map, bar 3 in 7/8 (2+2+3)');
  assert.ok(out.file.dawTempoMap, 'the ramp rides in the tempo map text');
  assert.equal(out.file.tempos?.[0].bpm, 120);
  // Notes placed in seconds by the clip's own 120 come out at the ticks the arrangement's map gives those seconds.
  for (const n of out.file.tracks[0].notes) assert.ok(Math.abs(beatToTime(tempoMap, n.tick / 960) - Math.round(beatToTime(tempoMap, n.tick / 960) * 2) / 2) < 1e-3);
  // A span from 5 s (inside bar 3, the first 7/8 bar: beat 8, 4 s, into the ramp): the file starts
  // on that bar line, in 7/8, at the ramp's 90 running down to 60.
  const span = arrangementToMidiFile(source, { range: { startSec: 5, endSec: 20 } });
  assert.equal(span.startSec, beatToTime(tempoMap, 8), 'the bar line before 5 s');
  assert.equal(span.startSec, 4);
  assert.deepEqual(span.file.timeSignatures?.map((s) => [s.tick, s.num, s.den, (s.groups ?? []).join('+')]), [[0, 7, 8, '2+2+3']]);
  assert.equal(span.file.bpm, 90, 'the span starts at the ramp’s 90');
  // A ramp is written as a tempo every 32nd, each the tempo that gives its 32nd the ramp's seconds: just under 90 first.
  assert.ok((span.file.tempos?.[0].bpm ?? 0) > 89 && (span.file.tempos?.[0].bpm ?? 0) < 90);
  assert.ok(span.file.tracks[0].notes.every((n) => beatToTime(tempoMap, 8 + n.tick / 960) >= 5 - 1e-3), 'only notes that start in the span');
  assert.deepEqual(meterMapFrom(meterMap, 2), [{ bar: 0, meter: { num: 7, den: 8, groups: [2, 2, 3] } }]);
  assert.deepEqual(tempoMapFrom(tempoMap, 4).map((e) => [e.beat, e.bpm]), [[0, 120], [4, 90], [12, 60]]);
  assert.deepEqual(tempoMapFrom(tempoMap, 12).map((e) => [e.beat, e.bpm, e.curve]), [[0, 75, 'linear'], [4, 60, undefined]], 'halfway down the ramp it is 75 and still ramping');
}

// ── editor_export_midi: the assistant's tool, with the save passed in ────────
{
  useEditorStore.getState().loadProject({
    tracks: [track('v1', 'Violin'), track('vc', 'Cello', { instrumentProgram: 42 })],
    clips: [clip('cv', 'v1', 0, [note(0, 76)], { instrumentProgram: 40 }), clip('cc', 'vc', 2, [note(0, 48)]), { ...clip('au', 'vc', 0, []), sourceKind: 'audio', sourcePianoRoll: undefined, label: 'audio' }],
    bpm: 120,
  });
  const saved: Array<{ name: string; bytes: number }> = [];
  const save = async (b: Blob, name: string) => {
    saved.push({ name, bytes: b.size });
    return { path: `C:/Music/${name}`, cancelled: false, downloaded: false };
  };
  const ok = await exportMidi({ name: 'duo', save, global: { useSoundfont: true, activeProgram: 0 } });
  assert.equal(ok.ok, true);
  assert.equal(ok.message, 'Exported 2 notes on 2 tracks as MIDI to C:/Music/duo.mid');
  assert.deepEqual(saved.map((s) => s.name), ['duo.mid']);
  const named = await exportMidi({ track_ids: ['Cello'], start_sec: 0, end_sec: 10, save });
  assert.equal(named.ok, true);
  assert.deepEqual((named.data as { tracks: string[] }).tracks, ['Cello'], 'a track by its name');
  assert.equal((await exportMidi({ track_ids: ['v1'], clip_ids: ['cc'], save })).error, 'export_midi: pass track_ids or clip_ids, not both');
  assert.match((await exportMidi({ clip_ids: ['audio'], save })).error ?? '', /is an audio clip/);
  assert.equal((await exportMidi({ start_sec: 3, save })).error, 'export_midi: pass both start_sec and end_sec, or neither');
  assert.match((await exportMidi({ start_sec: 3, end_sec: 3, save })).error ?? '', /is empty/);
  const cancelled = await exportMidi({ save: async () => ({ path: null, cancelled: true, downloaded: false }) });
  assert.match(cancelled.error ?? '', /cancelled, so nothing was written/);
  // The tool's payload reaches the facade narrowed: a payload cannot pass the save or voice seams.
  let seen: Record<string, unknown> | null = null;
  const restore = overrideEditorFacadeForTest('exportMidi', async (args) => {
    seen = args as Record<string, unknown>;
    return { ok: true, message: 'stub' };
  });
  try {
    await handletheDAWAction({ type: 'editor_export_midi', payload: { track_ids: ['Cello'], name: 'x', save: 'evil', global: { activeProgram: 9 } } });
  } finally {
    restore();
  }
  assert.deepEqual(Object.keys(seen ?? {}).sort(), ['name', 'track_ids'], 'the arguments the tool declares, and no seam');
  assert.equal((seen as Record<string, unknown> | null)?.save, undefined);
  assert.equal((seen as Record<string, unknown> | null)?.global, undefined);
}

console.log('arrangementMidi: ok');
