// Autosave durability, one writer per origin (T57), and the project meter.
//
// The autosave is what recovers a crashed session, so the failure modes pinned
// here are the ones that lose work rather than merely annoy:
//
//   1. A TORN MANIFEST. `manifest.json` used to be written in place. A crash
//      partway through left a truncated file that `JSON.parse` rejects — and
//      with it, the only copy of the session. The write now stages
//      `manifest.json.tmp` and promotes it by rename, so the committed
//      manifest is either the old one or the new one and never half of
//      either. A leftover tmp is a promote that did not happen: it is adopted
//      on the next start if it parses, and set aside (never deleted) if it
//      does not.
//   2. TWO TABS, ONE DIRECTORY. Both used to save. The second tab's empty
//      startup document would overwrite the first tab's arrangement. The
//      driver now holds `navigator.locks` `thedaw-editor-autosave`; the tab
//      that does not get it is RECOVERY-ONLY and writes nothing at all.
//   3. A LOST METER. `timeSignature` is document state (it rides undo alongside
//      bpm), so a meter the user — or the assistant, via
//      `editor_set_time_signature` — sets has to survive a crash-recovery
//      restore exactly as the tempo does. It did not: the manifest never wrote
//      the field and the restore called `loadProject` without it, so a 7/8
//      session came back in whatever meter the fresh session happened to hold.
//
// Each phase gets its own copy of the module (query-suffixed dynamic import)
// because ownership and the `started` guard are module state, and its own fake
// OPFS root so one phase's driver cannot be mistaken for another's. Earlier
// drivers stay subscribed to the shared editor store, so every phase drains
// their pending debounce into a scratch root before asserting on its own.
//
// The meter phase runs FIRST and against its own harness (an immediate
// `window.setTimeout`, so it pins the real debounced save path rather than the
// explicit flush the durability phases use). Running it first is what keeps it
// honest: no other driver exists yet to write into the root it inspects. It
// drains itself on the way out so its debounce cannot land in phase 1's root.
//
// Run: npx tsx src/lib/editorAutosave.test.ts
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from '../state/editorStore.ts';
/** Bar 1's meter, as the single project meter read before the arrangement held a meter map. */
const barOneMeter = () => { const m = useEditorStore.getState().meterMap[0].meter; return { num: m.num, den: m.den }; };
import { isComped } from './clipComp.ts';

const flush = async (n = 8): Promise<void> => {
  for (let i = 0; i < n; i += 1) await new Promise((r) => setTimeout(r, 0));
};

const st = () => useEditorStore.getState();

const mkTrack = (id: string, name = id): EditorTrack => ({
  id,
  name,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#fff',
});

const trackIds = (): string[] => st().tracks.map((t) => t.id);

/** A manifest exactly as the module writes one, minus the clip/asset half —
 *  the durability rules are about the manifest file, not its payload. */
const manifestJson = (ids: string[]): string =>
  JSON.stringify({
    version: 1,
    savedAt: new Date().toISOString(),
    bpm: 120,
    tracks: ids.map((id) => mkTrack(id)),
    clips: [],
    masterFxChain: [],
    masterVstChain: [],
    automationLanes: [],
    markers: [],
    loop: { enabled: false, startSec: 0, endSec: 0 },
  });

/* ── fake OPFS ───────────────────────────────────────────────────────────────
   Richer than the harness in editorStore.routing.test.ts: it records the order
   of file operations (so "staged, then promoted" is provable rather than
   assumed), carries a modification time (so tmp-vs-manifest recency is
   testable), and can be built with or WITHOUT `move()` — the Chromium-only
   rename — to exercise both promote paths. `moveThrows` is the simulated crash
   between the staging write and the promote. */

interface FakeRecord {
  body: string;
  mtime: number;
}

let clock = 1000;

class FakeDir {
  files = new Map<string, FakeRecord>();
  dirs = new Map<string, FakeDir>();
  ops: string[] = [];
  /** Name whose `close()` is the last thing this "tab" ever does: everything
   *  after it throws. That is what a crash looks like — not a rejected call the
   *  module can recover from, but no further OPFS op landing at all. */
  freezeAfter: string | null = null;
  frozen = false;
  /** An engine whose `move()` refuses to overwrite an existing destination.
   *  Nothing specifies which way Chromium goes, so the module must survive
   *  both — hence this switch rather than an assumption. */
  moveRejectsOnExisting = false;
  constructor(readonly supportsMove: boolean = true) {}

  async getDirectoryHandle(name: string, opts?: { create?: boolean }): Promise<FakeDir> {
    let d = this.dirs.get(name);
    if (!d) {
      if (!opts?.create) throw new Error(`no dir ${name}`);
      d = new FakeDir(this.supportsMove);
      this.dirs.set(name, d);
    }
    return d;
  }

  async getFileHandle(name: string, opts?: { create?: boolean }): Promise<unknown> {
    if (!this.files.has(name)) {
      if (this.frozen) throw new Error('simulated crash: this tab is gone');
      if (!opts?.create) throw new Error(`no file ${name}`);
      clock += 1;
      this.files.set(name, { body: '', mtime: clock });
      this.ops.push(`create:${name}`);
    }
    const dir = this;
    let current = name;
    const handle: Record<string, unknown> = {
      async getFile() {
        const rec = dir.files.get(current);
        if (!rec) throw new Error(`gone ${current}`);
        return {
          lastModified: rec.mtime,
          async text() {
            return rec.body;
          },
          async arrayBuffer() {
            return new TextEncoder().encode(rec.body).buffer;
          },
        };
      },
      async createWritable() {
        let buf = '';
        return {
          async write(data: unknown) {
            // Assets are written as Blobs, the manifest as a string. Both are
            // kept as text here, which is enough for byte-identity checks.
            if (typeof data === 'string') buf += data;
            else if (data instanceof Blob) buf += await data.text();
          },
          async close() {
            if (dir.frozen) throw new Error('simulated crash: this tab is gone');
            clock += 1;
            dir.files.set(current, { body: buf, mtime: clock });
            dir.ops.push(`write:${current}`);
            if (dir.freezeAfter === current) dir.frozen = true;
          },
        };
      },
    };
    if (this.supportsMove) {
      handle.move = async (to: string): Promise<void> => {
        if (dir.frozen) throw new Error('simulated crash: this tab is gone');
        if (dir.moveRejectsOnExisting && dir.files.has(to)) {
          throw new DOMException(`${to} exists`, 'InvalidModificationError');
        }
        const rec = dir.files.get(current);
        if (!rec) throw new Error(`gone ${current}`);
        clock += 1;
        dir.files.delete(current);
        dir.files.set(to, { body: rec.body, mtime: clock });
        dir.ops.push(`move:${current}->${to}`);
        current = to;
      };
    }
    return handle;
  }

  async removeEntry(name: string): Promise<void> {
    if (this.frozen) throw new Error('simulated crash: this tab is gone');
    this.files.delete(name);
    this.dirs.delete(name);
    this.ops.push(`remove:${name}`);
  }

  async *keys(): AsyncIterable<string> {
    for (const k of this.files.keys()) yield k;
  }
}

const SAVE_DIR = 'thedaw-editor-autosave';
const MANIFEST = 'manifest.json';
const TMP = 'manifest.json.tmp';

const saveDirOf = (root: FakeDir): FakeDir => root.dirs.get(SAVE_DIR) as FakeDir;
const seed = async (root: FakeDir): Promise<FakeDir> =>
  root.dirs.get(SAVE_DIR) ?? (await root.getDirectoryHandle(SAVE_DIR, { create: true }));

/** 'grant' = this tab gets the lock, 'deny' = another tab holds it (the
 *  `ifAvailable` callback is handed null), 'none' = no Web Locks at all. */
type LockMode = 'grant' | 'deny' | 'none';

/** Hands back the control the handover test needs: a denied tab QUEUES an
 *  ordinary request behind the holder, and `grantQueued()` is the holder
 *  going away (a closed tab, or the previous document of a reload). */
interface LockControl {
  grantQueued: () => void;
}

function installGlobals(root: FakeDir, lockMode: LockMode): LockControl {
  const queued: ((lock: unknown) => unknown)[] = [];
  const locks =
    lockMode === 'none'
      ? undefined
      : {
          request: (name: string, a: unknown, b?: unknown) => {
            const cb = (typeof a === 'function' ? a : b) as (lock: unknown) => unknown;
            const opts = typeof a === 'function' ? {} : (a as { ifAvailable?: boolean });
            if (opts.ifAvailable) {
              // For 'grant' the callback returns a promise that never settles —
              // the lock is held for the life of the document — so this promise
              // never settles either, exactly like the real LockManager.
              return Promise.resolve(cb(lockMode === 'grant' ? { name, mode: 'exclusive' } : null));
            }
            queued.push(cb);
            return new Promise(() => undefined);
          },
        };
  const control: LockControl = {
    grantQueued: () => {
      for (const cb of queued.splice(0)) void cb({ name: 'thedaw-editor-autosave', mode: 'exclusive' });
    },
  };
  Object.defineProperty(globalThis, 'navigator', {
    value: { storage: { getDirectory: async () => root }, locks },
    configurable: true,
    writable: true,
  });
  Object.defineProperty(globalThis, 'window', {
    value: {
      setTimeout: (fn: () => void, ms: number) => setTimeout(fn, ms) as unknown as number,
      clearTimeout: (h: number) => clearTimeout(h as unknown as NodeJS.Timeout),
      addEventListener: () => undefined,
    },
    configurable: true,
    writable: true,
  });
  return control;
}

type AutosaveModule = typeof import('./editorAutosave.ts');

/** A fresh copy of the module: ownership and the `started` latch are module
 *  state, so one phase per copy. */
const loadAutosave = (tag: string): Promise<AutosaveModule> =>
  import(`./editorAutosave.ts?tab=${tag}`) as Promise<AutosaveModule>;

/** Land every earlier driver's pending debounce somewhere harmless, so a stale
 *  2 s timer cannot write into the root the next phase is about to inspect. */
async function drain(mods: AutosaveModule[]): Promise<void> {
  installGlobals(new FakeDir(true), 'grant');
  for (const m of mods) m.flushPendingAutosave();
  await flush(12);
}

/* ── Phase 0: the project meter round-trips ──────────────────────────────────
   Its own in-memory OPFS and an immediate `window.setTimeout`, so what is
   pinned is the actual debounced save/restore path rather than a
   re-implementation of it — and rather than the explicit `flushPendingAutosave`
   every later phase uses. */

class MeterFakeWritable {
  private chunks: Array<Uint8Array> = [];
  constructor(private readonly onClose: (bytes: Uint8Array) => void) {}
  async write(data: string | Blob | ArrayBuffer | Uint8Array): Promise<void> {
    if (typeof data === 'string') {
      this.chunks.push(new TextEncoder().encode(data));
    } else if (data instanceof Uint8Array) {
      this.chunks.push(data);
    } else if (data instanceof ArrayBuffer) {
      this.chunks.push(new Uint8Array(data));
    } else {
      this.chunks.push(new Uint8Array(await data.arrayBuffer()));
    }
  }
  async close(): Promise<void> {
    const total = this.chunks.reduce((n, c) => n + c.byteLength, 0);
    const out = new Uint8Array(total);
    let at = 0;
    for (const c of this.chunks) {
      out.set(c, at);
      at += c.byteLength;
    }
    this.onClose(out);
  }
}

class MeterFakeFileHandle {
  bytes = new Uint8Array();
  async getFile(): Promise<{ text(): Promise<string>; arrayBuffer(): Promise<ArrayBuffer> }> {
    const bytes = this.bytes;
    return {
      text: async () => new TextDecoder().decode(bytes),
      arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
    };
  }
  async createWritable(): Promise<MeterFakeWritable> {
    return new MeterFakeWritable((bytes) => {
      this.bytes = bytes;
    });
  }
}

class MeterFakeDir {
  files = new Map<string, MeterFakeFileHandle>();
  dirs = new Map<string, MeterFakeDir>();
  async getDirectoryHandle(name: string, opts?: { create?: boolean }): Promise<MeterFakeDir> {
    let d = this.dirs.get(name);
    if (!d) {
      if (!opts?.create) throw new Error(`NotFoundError: ${name}`);
      d = new MeterFakeDir();
      this.dirs.set(name, d);
    }
    return d;
  }
  async getFileHandle(name: string, opts?: { create?: boolean }): Promise<MeterFakeFileHandle> {
    let f = this.files.get(name);
    if (!f) {
      if (!opts?.create) throw new Error(`NotFoundError: ${name}`);
      f = new MeterFakeFileHandle();
      this.files.set(name, f);
    }
    return f;
  }
  async removeEntry(name: string, opts?: { recursive?: boolean }): Promise<void> {
    void opts;
    this.files.delete(name);
    this.dirs.delete(name);
  }
  async *keys(): AsyncIterable<string> {
    for (const k of this.files.keys()) yield k;
    for (const k of this.dirs.keys()) yield k;
  }
}

const meterOpfsRoot = new MeterFakeDir();

/** The module's own OPFS layout (module-private constants there). */
const AUTOSAVE_DIR_NAME = 'thedaw-editor-autosave';
const AUTOSAVE_MANIFEST_NAME = 'manifest.json';

const meterTrack = (id: string): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#8b5cf6',
});

const meterClip = (id: string, trackId: string): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: new Blob(['pcm'], { type: 'audio/wav' }),
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 4,
  startSec: 0,
  color: '#8b5cf6',
});

/** A piano-roll part that plays live and holds no render (lib/midiRender): no audio to store. */
const liveMidiClip = (id: string, trackId: string): AudioClip => ({
  id,
  trackId,
  label: id,
  mimeType: 'audio/wav',
  sourceDuration: 2,
  offsetIntoSource: 0,
  durationSec: 2,
  startSec: 4,
  color: '#8b5cf6',
  sourceKind: 'piano-roll',
  sourcePianoRoll: [{ id: 'n1', note: 67, step: 0, length: 4, velocity: 90 }, { id: 'n2', note: 71, step: 4, length: 4, velocity: 90 }],
  sourceRollNotes: [{ id: 'n1', note: 67, step: 0, length: 4, velocity: 90 }, { id: 'n2', note: 71, step: 4, length: 4, velocity: 90 }],
  sourceBpm: 132,
  sourceTotalSteps: 16,
  instrumentProgram: 40,
});

/** The same part holding a kept render: its audio and what the render was made from. */
const keptMidiClip = (id: string, trackId: string): AudioClip => ({
  ...liveMidiClip(id, trackId),
  startSec: 8,
  audioBlob: new Blob(['render'], { type: 'audio/wav' }),
  renderedProgram: 40,
  renderSig: '0123456789abcdef01234567',
});

const tick = (ms = 20) => new Promise((r) => setTimeout(r, ms));

async function meterManifestHandle(): Promise<MeterFakeFileHandle> {
  const dir = await meterOpfsRoot.getDirectoryHandle(AUTOSAVE_DIR_NAME, { create: true });
  return dir.getFileHandle(AUTOSAVE_MANIFEST_NAME, { create: true });
}

const readMeterManifestJson = async (): Promise<Record<string, unknown>> =>
  JSON.parse(new TextDecoder().decode((await meterManifestHandle()).bytes)) as Record<string, unknown>;

async function writeMeterManifest(bytes: Uint8Array): Promise<void> {
  const w = await (await meterManifestHandle()).createWritable();
  await w.write(bytes);
  await w.close();
}

const SAVED_METER_MAP = [
  { bar: 0, meter: { num: 7, den: 8, groups: [3, 2, 2] } },
  { bar: 8, meter: { num: 5, den: 4, groups: [] } },
];
const SAVED_TEMPO_MAP = [
  { beat: 0, bpm: 132, curve: 'step' as const },
  { beat: 28, bpm: 132, curve: 'linear' as const },
  { beat: 56, bpm: 90, curve: 'step' as const },
  { beat: 60, bpm: 132, fermata: { beats: 2, stretch: 3 } },
];

/** The 7/8 manifest the first block writes, reused by the legacy block. */
let meterSaved = new Uint8Array();

async function theMeterSurvivesASaveAndRestoreRoundTrip(): Promise<void> {
  Object.defineProperty(globalThis, 'navigator', {
    configurable: true,
    writable: true,
    value: { storage: { getDirectory: async () => meterOpfsRoot } },
  });

  // The save driver debounces through `window.setTimeout`; fire on the next tick
  // so the suite pins the save path itself, not the 2s debounce.
  Object.defineProperty(globalThis, 'window', {
    configurable: true,
    writable: true,
    value: {
      setTimeout: (fn: () => void) => setTimeout(fn, 0) as unknown as number,
      clearTimeout: (id: number) => clearTimeout(id as unknown as NodeJS.Timeout),
      // The driver arms its unload flush here; the durability harness stubs the
      // same method for the same reason.
      addEventListener: () => undefined,
    },
  });

  const meter = await loadAutosave('meter');
  meter.initEditorAutosave();
  await tick(); // let the "no manifest yet" probe resume saving

  useEditorStore.getState().loadProject({
    tracks: [meterTrack('t1')],
    // m3 holds a render EDIT made only so it could be heard (renderAuto).
    clips: [meterClip('c1', 't1'), liveMidiClip('m1', 't1'), keptMidiClip('m2', 't1'), { ...keptMidiClip('m3', 't1'), startSec: 16, renderAuto: true }],
    bpm: 132,
    timeSignature: { num: 7, den: 8 },
    // The arrangement's maps: 7/8 3+2+2 from bar 1, 5/4 from bar 9; 132 BPM
    // ramping from beat 28 to 90 at beat 56, and a fermata at beat 60.
    meterMap: SAVED_METER_MAP,
    tempoMap: SAVED_TEMPO_MAP,
  });

  // Wait for the debounced save to land the manifest.
  for (let i = 0; i < 60 && (await meterManifestHandle()).bytes.byteLength === 0; i += 1) await tick(10);
  const manifest = await readMeterManifestJson();
  assert.deepEqual(
    manifest.timeSignature,
    { num: 7, den: 8 },
    'the autosave manifest must carry the project meter',
  );
  assert.deepEqual(manifest.meterMap, SAVED_METER_MAP, 'the manifest carries the meter map');
  assert.deepEqual(
    (manifest.tempoMap as Array<Record<string, unknown>>).map((e) => [e.beat, e.bpm, e.curve ?? null, e.fermata ?? null]),
    [[0, 132, 'step', null], [28, 132, 'linear', null], [56, 90, 'step', null], [60, 132, null, { beats: 2, stretch: 3 }]],
    'the manifest carries the tempo map, ramp and fermata included',
  );
  // A MIDI part with no render stores its notes and no audio asset.
  const savedClips = manifest.clips as Array<Record<string, unknown>>;
  const savedMidi = savedClips.find((c) => c.id === 'm1');
  assert.ok(savedMidi, 'the live MIDI part is in the manifest');
  assert.equal(savedMidi.assetHash, null, 'with no audio asset');
  assert.equal((savedMidi.sourcePianoRoll as unknown[]).length, 2, 'and its notes');
  assert.equal(typeof savedClips.find((c) => c.id === 'c1')?.assetHash, 'string', 'the audio clip keeps its asset');

  // Keep the 7/8 document on disk, then land the session in a different meter
  // (the clip stays, so the asset GC keeps its bytes) and restore.
  meterSaved = (await meterManifestHandle()).bytes;
  useEditorStore.getState().setTimeSignature(3, 4);
  await tick(60);
  await writeMeterManifest(meterSaved);

  await meter.useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(
    barOneMeter(),
    { num: 7, den: 8 },
    'a restored autosave must bring its own meter back',
  );
  assert.deepEqual(useEditorStore.getState().meterMap, SAVED_METER_MAP, 'and its meter map');
  assert.deepEqual(
    useEditorStore.getState().tempoMap.map((e) => [e.beat, e.bpm, e.curve ?? null, e.fermata ?? null]),
    [[0, 132, 'step', null], [28, 132, 'linear', null], [56, 90, 'step', null], [60, 132, null, { beats: 2, stretch: 3 }]],
    'and its tempo map',
  );
  assert.equal(useEditorStore.getState().bpm, 132);
  const restoredMidi = useEditorStore.getState().clips.find((c) => c.id === 'm1');
  assert.ok(restoredMidi, 'the live MIDI part is restored');
  assert.equal(restoredMidi.audioBlob, undefined, 'still holding no render: it plays live');
  assert.equal(restoredMidi.sourceKind, 'piano-roll');
  assert.deepEqual(restoredMidi.sourcePianoRoll?.map((n) => n.note), [67, 71], 'with its notes');
  assert.equal(restoredMidi.instrumentProgram, 40, 'and its instrument');
  assert.ok(useEditorStore.getState().clips.find((c) => c.id === 'c1')?.audioBlob instanceof Blob, 'the audio clip comes back with its audio');
  const restoredKept = useEditorStore.getState().clips.find((c) => c.id === 'm2');
  assert.ok(restoredKept?.audioBlob instanceof Blob, 'a part with a kept render comes back with it');
  assert.equal(restoredKept?.renderSig, '0123456789abcdef01234567', 'and with what the render was made from');
  assert.equal(restoredKept?.renderedProgram, 40);
  assert.equal(restoredKept?.renderAuto, undefined, 'kept on purpose');
  const restoredAuto = useEditorStore.getState().clips.find((c) => c.id === 'm3');
  assert.ok(restoredAuto?.audioBlob instanceof Blob, 'a render made to be heard comes back');
  assert.equal(restoredAuto?.renderAuto, true, 'with the mark that lets EDIT drop it once the part plays live');

  /* ── a legacy manifest (no meter) restores as 4/4 ───────────────────────── */
  await tick(60); // let the restore's own autosave land before overwriting it
  const legacy = JSON.parse(new TextDecoder().decode(meterSaved)) as Record<string, unknown>;
  delete legacy.timeSignature;
  delete legacy.meterMap;
  delete legacy.tempoMap;
  await writeMeterManifest(new TextEncoder().encode(JSON.stringify(legacy)));

  await meter.useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(
    barOneMeter(),
    { num: 4, den: 4 },
    'a document written before the field existed is 4/4, not whatever the session held',
  );
  assert.deepEqual(useEditorStore.getState().meterMap.length, 1, 'one meter for a legacy document');
  assert.deepEqual(
    useEditorStore.getState().tempoMap.map((e) => [e.beat, e.bpm]),
    [[0, 132]],
    'and one tempo, its saved bpm, not the tempo changes the session held',
  );

  // This driver stays subscribed to the shared store for the rest of the run,
  // so its pending debounce goes somewhere harmless before phase 1 seeds a root
  // and starts asserting on the bytes in it.
  await drain([meter]);
}

/* ── Phase 1: the owner tab ─────────────────────────────────────────────── */

const root1 = new FakeDir(true);
const dir1 = await seed(root1);
let owner: AutosaveModule;

async function aLeftoverTmpThatParsesIsPromotedOnTheNextStart(): Promise<void> {
  // The previous session staged a manifest and died before the promote. Those
  // bytes are the NEWER, complete document; the committed manifest is a save
  // older than them.
  dir1.files.set(MANIFEST, { body: manifestJson(['old1', 'old2']), mtime: 100 });
  dir1.files.set(TMP, { body: manifestJson(['new1', 'new2', 'new3']), mtime: 200 });

  installGlobals(root1, 'grant');
  owner = await loadAutosave('owner');
  owner.initEditorAutosave();
  await flush();

  assert.equal(owner.autosaveOwnership(), 'owner', 'the first tab takes the lock');
  assert.equal(
    owner.useAutosaveRecoveryStore.getState().ownership,
    'owner',
    'and the store mirrors it for the notice',
  );
  assert.ok(!dir1.files.has(TMP), 'the leftover tmp is promoted, not left to rot');
  assert.deepEqual(
    (JSON.parse(dir1.files.get(MANIFEST)?.body as string) as { tracks: EditorTrack[] }).tracks.map(
      (t) => t.id,
    ),
    ['new1', 'new2', 'new3'],
    'and manifest.json now holds the staged bytes',
  );

  await owner.useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(trackIds(), ['new1', 'new2', 'new3'], 'so the staged work is what recovers');
}

async function aTornTmpIsSetAsideAndTheCommittedManifestSurvives(): Promise<void> {
  // The crash landed mid-write: the tmp is truncated JSON. The committed
  // manifest predates the failed save and is still whole — it must win, and
  // the evidence must not be deleted.
  const intact = manifestJson(['keep1', 'keep2']);
  const torn = manifestJson(['halfwritten']).slice(0, 40);
  dir1.files.set(MANIFEST, { body: intact, mtime: 300 });
  dir1.files.set(TMP, { body: torn, mtime: 400 });

  await owner.useAutosaveRecoveryStore.getState().restore();

  assert.equal(dir1.files.get(MANIFEST)?.body, intact, 'the committed manifest is byte-identical');
  assert.deepEqual(trackIds(), ['keep1', 'keep2'], 'and it is what recovers');
  assert.ok(!dir1.files.has(TMP), 'the torn tmp is out of the read path');
  const quarantined = [...dir1.files.keys()].filter((n) => n.startsWith(`${TMP}.corrupt-`));
  assert.equal(quarantined.length, 1, 'moved aside exactly once');
  assert.equal(dir1.files.get(quarantined[0])?.body, torn, 'with its bytes kept, never deleted');
}

async function aSaveStagesThenPromotesAndNeverWritesTheManifestInPlace(): Promise<void> {
  dir1.files.delete(MANIFEST);
  dir1.ops.length = 0;

  st().loadProject({ tracks: [mkTrack('live')], clips: [] });
  owner.flushPendingAutosave();
  await flush(12);

  const manifestOps = dir1.ops.filter((o) => o.includes(MANIFEST));
  assert.ok(dir1.files.has(MANIFEST), 'a manifest was committed');
  assert.ok(!dir1.files.has(TMP), 'and the staging file did not survive the promote');
  assert.ok(
    manifestOps.every((o) => !o.endsWith(`:${MANIFEST}`) || o.startsWith('move:')),
    `manifest.json is only ever created by the promote — saw ${manifestOps.join(', ')}`,
  );
  assert.ok(
    manifestOps.includes(`move:${TMP}->${MANIFEST}`),
    'the promote is a rename, so there is no window where manifest.json is empty',
  );
  assert.deepEqual(
    (JSON.parse(dir1.files.get(MANIFEST)?.body as string) as { tracks: EditorTrack[] }).tracks.map(
      (t) => t.id,
    ),
    ['live'],
    'holding the live document',
  );
}

async function aCrashDuringThePromoteLeavesTheOldManifestIntact(): Promise<void> {
  const committed = dir1.files.get(MANIFEST)?.body as string;
  // The tab dies the instant the staging write closes: neither promote path
  // gets to run, and nothing else lands either.
  dir1.freezeAfter = TMP;

  st().loadProject({ tracks: [mkTrack('doomed1'), mkTrack('doomed2')], clips: [] });
  owner.flushPendingAutosave();
  await flush(12);

  assert.equal(
    dir1.files.get(MANIFEST)?.body,
    committed,
    'a promote that never completed cannot damage the committed manifest',
  );
  assert.ok(dir1.files.has(TMP), 'the staged bytes are still on disk for the next start');

  // …and the next start — a live directory again — adopts them: that is the
  // whole point of staging.
  dir1.freezeAfter = null;
  dir1.frozen = false;
  await owner.useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(trackIds(), ['doomed1', 'doomed2'], 'the interrupted save is recovered in full');
  assert.ok(!dir1.files.has(TMP), 'and promoted on the way through');
}

async function thePromoteFallsBackToCopyAndDropWithoutMove(): Promise<void> {
  // `FileSystemFileHandle.move()` is a Chromium extension and is not on MDN.
  // Every other engine takes this path, as does the fake in
  // editorStore.routing.test.ts — which is why that suite must keep passing.
  const root = new FakeDir(false);
  installGlobals(root, 'grant');

  st().loadProject({ tracks: [mkTrack('nomove')], clips: [] });
  owner.flushPendingAutosave();
  await flush(12);

  const dir = saveDirOf(root);
  assert.ok(dir.files.has(MANIFEST), 'the manifest is committed without move()');
  assert.ok(!dir.files.has(TMP), 'and the staging file is dropped afterwards');
  assert.deepEqual(
    (JSON.parse(dir.files.get(MANIFEST)?.body as string) as { tracks: EditorTrack[] }).tracks.map(
      (t) => t.id,
    ),
    ['nomove'],
    'with the right bytes',
  );
}

async function aMoveThatRefusesAnExistingDestinationStillPromotes(): Promise<void> {
  // If `move()` rejects onto an existing manifest.json and that rejection were
  // allowed to surface, EVERY save after the first would fail and three of them
  // would latch autosave off for the session — silently, because the first save
  // (no destination yet) would look fine.
  const root = new FakeDir(true);
  const dir = await seed(root);
  dir.moveRejectsOnExisting = true;
  installGlobals(root, 'grant');

  st().loadProject({ tracks: [mkTrack('first')], clips: [] });
  owner.flushPendingAutosave();
  await flush(12);
  assert.ok(dir.files.has(MANIFEST), 'the first save lands (no destination to refuse yet)');
  assert.ok(
    dir.ops.includes(`move:${TMP}->${MANIFEST}`),
    'by rename, since there was nothing to overwrite',
  );

  // The second save is the one that exposes the bug.
  st().loadProject({ tracks: [mkTrack('second'), mkTrack('third')], clips: [] });
  owner.flushPendingAutosave();
  await flush(12);

  assert.deepEqual(
    (JSON.parse(dir.files.get(MANIFEST)?.body as string) as { tracks: EditorTrack[] }).tracks.map(
      (t) => t.id,
    ),
    ['second', 'third'],
    'a refused move falls back to copy+drop and the save still completes',
  );
  assert.ok(!dir.files.has(TMP), 'leaving no staging file behind');
  assert.ok(
    dir.ops.includes(`write:${MANIFEST}`),
    'by the copy path — which is the only way manifest.json is written directly',
  );
}

async function aTmpOlderThanTheManifestIsLitterNotDamage(): Promise<void> {
  // A tmp that PARSES but predates the committed manifest is not a torn write:
  // nothing was lost, so it must not be filed as `.corrupt-` or warned about.
  const older = manifestJson(['ancient']);
  const newer = manifestJson(['current1', 'current2']);
  dir1.files.set(TMP, { body: older, mtime: 700 });
  dir1.files.set(MANIFEST, { body: newer, mtime: 800 });

  installGlobals(root1, 'grant');
  await owner.useAutosaveRecoveryStore.getState().restore();

  assert.deepEqual(trackIds(), ['current1', 'current2'], 'the committed manifest wins');
  assert.ok(!dir1.files.has(TMP), 'and the older tmp is taken out of the read path');
  const stale = [...dir1.files.keys()].filter((n) => n.startsWith(`${TMP}.stale-`));
  assert.equal(stale.length, 1, 'filed as stale, not as corrupt');
  assert.equal(dir1.files.get(stale[0])?.body, older, 'with its bytes kept');
  assert.equal(
    [...dir1.files.keys()].filter((n) => n.startsWith(`${TMP}.corrupt-`)).length,
    1,
    'and the earlier torn tmp is still the only corrupt one',
  );
}

/* ── Phase 2: the second tab is recovery-only ───────────────────────────── */

async function aTabThatLosesTheLockNeverWrites(): Promise<void> {
  await drain([owner]);
  const root2 = new FakeDir(true);
  installGlobals(root2, 'deny');

  const observer = await loadAutosave('observer');
  observer.initEditorAutosave();
  await flush();

  assert.equal(observer.autosaveOwnership(), 'observer', 'the lock was already taken');
  assert.equal(observer.useAutosaveRecoveryStore.getState().ownership, 'observer');

  st().loadProject({ tracks: [mkTrack('observed')], clips: [] });
  observer.flushPendingAutosave();
  await flush(12);

  const dir2 = saveDirOf(root2);
  assert.ok(!dir2.files.has(MANIFEST), 'a recovery-only tab writes no manifest');
  assert.ok(!dir2.files.has(TMP), 'and stages nothing either');

  // Recovery-only, not read-only-and-useless: it still restores.
  dir2.files.set(MANIFEST, { body: manifestJson(['ro1', 'ro2']), mtime: 500 });
  dir2.files.set(TMP, { body: '{ truncated', mtime: 600 });
  dir2.ops.length = 0;

  await observer.useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(trackIds(), ['ro1', 'ro2'], 'the observer can still recover the session');
  assert.ok(dir2.files.has(TMP), 'it leaves even a torn tmp for the owner to resolve');
  assert.deepEqual(dir2.ops, [], 'having performed no OPFS mutation whatsoever');

  await observer.useAutosaveRecoveryStore.getState().discard();
  assert.ok(
    dir2.files.has(MANIFEST),
    'and discarding here cannot delete the owner tab’s autosave',
  );
  assert.equal(observer.useAutosaveRecoveryStore.getState().offer, null, 'the offer still clears');
  return await drain([owner, observer]);
}

/* ── Phase 2b: the lock comes free — the observer takes over ────────────── */

async function anObserverIsPromotedWhenTheLockIsReleased(): Promise<void> {
  // A LONE tab can be told "no" by `ifAvailable`: on a same-tab reload the old
  // document's lock release can land after the new document's request. If the
  // answer were final, that tab would autosave nothing for the rest of the
  // session. It queues an ordinary request instead, which is granted when the
  // previous holder goes away — the reload, or the owner tab being closed.
  await drain([owner]);
  const root = new FakeDir(true);
  const locks = installGlobals(root, 'deny');

  const tab = await loadAutosave('handover');
  tab.initEditorAutosave();
  await flush();

  assert.equal(tab.autosaveOwnership(), 'observer', 'it starts out denied');
  // Startup with NEITHER a manifest nor a tmp: nothing to recover, no crash.
  assert.equal(
    tab.useAutosaveRecoveryStore.getState().offer,
    null,
    'an empty directory offers no recovery',
  );
  assert.equal(saveDirOf(root).files.size, 0, 'and nothing is written on the way past');

  const expected = trackIds();
  locks.grantQueued(); // the previous holder went away
  await flush();

  assert.equal(tab.autosaveOwnership(), 'owner', 'the queued request promotes the tab');
  assert.equal(tab.useAutosaveRecoveryStore.getState().ownership, 'owner', 'in the store too');

  // Nothing touches the document between the handover and this flush, so a
  // manifest here can only come from the save the handover itself scheduled —
  // the edits made while it was an observer were all dropped.
  tab.flushPendingAutosave();
  await flush(12);
  const saved = saveDirOf(root).files.get(MANIFEST)?.body;
  assert.ok(saved, 'the handover scheduled a save of its own rather than waiting for an edit');
  assert.deepEqual(
    (JSON.parse(saved) as { tracks: EditorTrack[] }).tracks.map((t) => t.id),
    expected,
    'and the promoted tab saves the state it could not save before',
  );
  await drain([tab]);
}

/* ── Phase 3: no Web Locks — unchanged behaviour ────────────────────────── */

async function withoutWebLocksNothingChanges(): Promise<void> {
  const root3 = new FakeDir(true);
  installGlobals(root3, 'none');

  const plain = await loadAutosave('plain');
  plain.initEditorAutosave();
  await flush();

  assert.equal(plain.autosaveOwnership(), 'unsupported', 'no lock manager, no ownership');
  assert.equal(plain.useAutosaveRecoveryStore.getState().ownership, 'unsupported');

  st().loadProject({ tracks: [mkTrack('solo')], clips: [] });
  plain.flushPendingAutosave();
  await flush(12);

  const dir3 = saveDirOf(root3);
  assert.deepEqual(
    (JSON.parse(dir3.files.get(MANIFEST)?.body as string) as { tracks: EditorTrack[] }).tracks.map(
      (t) => t.id,
    ),
    ['solo'],
    'saving works exactly as it did before the lock existed',
  );
  await drain([plain]);
}

/* ── Phase 4: a comped clip's takes survive save → restore ──────────────── */

async function takesAndTheCompSurviveASaveAndRestore(): Promise<void> {
  // A `ClipTake` holds a Blob and a Float32Array. Spreading the live clip into
  // the manifest stringified each take to `{}`, so recovery handed the editor a
  // clip that still claimed to be comped while its takes held no audio at all —
  // `isComped` true, and a non-Blob on its way to decode. Takes go to the same
  // content-addressed asset store the clip's own audio does.
  await drain([owner]);
  const root = new FakeDir(true);
  installGlobals(root, 'grant');
  const mod = await loadAutosave('takes');
  mod.initEditorAutosave();
  await flush();

  const mk = (body: string): Blob => new Blob([body], { type: 'audio/wav' });
  const first = mk('AAAA');
  const active = mk('BBBBBB');
  const takes = [
    { id: 'tk0', label: 'Take 1', audioBlob: first, mimeType: 'audio/wav', sourceDuration: 4, offsetIntoSource: 0, peaks: new Float32Array([1, 0.5]) },
    { id: 'tk1', label: 'Take 2', audioBlob: active, mimeType: 'audio/wav', sourceDuration: 6, offsetIntoSource: 0.5 },
  ];
  st().loadProject({
    tracks: [mkTrack('t1')],
    clips: [
      {
        id: 'c1',
        trackId: 't1',
        label: 'Vocal',
        // The clip's own media IS the active take (the clipComp invariant).
        audioBlob: active,
        mimeType: 'audio/wav',
        startSec: 0,
        durationSec: 5.5,
        sourceDuration: 6,
        offsetIntoSource: 0.5,
        peaks: new Float32Array([0.25]),
        takes,
        comp: [{ startSec: 0, takeIndex: 1 }, { startSec: 2.5, takeIndex: 0, crossfadeSec: 0.02 }],
        activeTakeIndex: 1,
      },
    ] as never,
  });
  mod.flushPendingAutosave();
  await flush(16);

  const dir = saveDirOf(root);
  const manifest = JSON.parse(dir.files.get(MANIFEST)?.body as string) as {
    clips: Array<{ assetHash: string; takes?: Array<{ id: string; assetHash: string; mimeType: string; peaks?: unknown }> }>;
  };
  const stored = manifest.clips[0];
  assert.equal(stored.takes?.length, 2, 'both takes are in the manifest');
  assert.ok(
    stored.takes?.every((t) => typeof t.assetHash === 'string' && t.assetHash.length === 64),
    'each as an asset hash, not as an empty object',
  );
  assert.ok(stored.takes?.every((t) => t.peaks === undefined), 'take peaks are dropped, like the clip’s');
  assert.equal(stored.takes?.[1].assetHash, stored.assetHash, 'the active take and the clip share one asset');

  const assetDir = dir.dirs.get('assets') as FakeDir;
  assert.deepEqual(
    [...assetDir.files.values()].map((f) => f.body).sort(),
    ['AAAA', 'BBBBBB'],
    'both takes’ bytes are on disk — and the GC left the alternate one alone',
  );

  await mod.useAutosaveRecoveryStore.getState().restore();
  const clip = st().clips[0];
  assert.equal(clip.takes?.length, 2, 'the takes came back');
  assert.deepEqual(
    await Promise.all((clip.takes ?? []).map((t) => t.audioBlob.text())),
    ['AAAA', 'BBBBBB'],
    'each holding its own audio',
  );
  assert.ok((clip.takes ?? []).every((t) => t.audioBlob instanceof Blob), 'as real Blobs');
  assert.deepEqual((clip.takes ?? []).map((t) => t.mimeType), ['audio/wav', 'audio/wav']);
  assert.deepEqual((clip.takes ?? []).map((t) => t.label), ['Take 1', 'Take 2']);
  assert.deepEqual((clip.takes ?? []).map((t) => t.sourceDuration), [4, 6]);
  assert.equal(clip.activeTakeIndex, 1);
  assert.equal(clip.audioBlob, clip.takes?.[1].audioBlob, 'clip audio IS the active take, same Blob object');
  assert.deepEqual(clip.comp, [{ startSec: 0, takeIndex: 1 }, { startSec: 2.5, takeIndex: 0, crossfadeSec: 0.02 }]);
  assert.equal(isComped(clip), true, 'and the restored clip is comped, with audio to back it');

  // An asset that is not there costs THIS CLIP its takes, not the user the
  // whole recovery — and the comp goes with them, because a comp indexes takes
  // by position. The clip's own audio is a separate asset and still loads.
  {
    const missing = stored.takes?.[0].assetHash as string;
    assetDir.files.delete(`${missing}.bin`);
    await mod.useAutosaveRecoveryStore.getState().restore();
    const damaged = st().clips[0];
    assert.equal(damaged.takes, undefined, 'no half take list');
    assert.equal(damaged.comp, undefined, 'and no comp indexing into one');
    assert.equal(damaged.activeTakeIndex, undefined);
    assert.equal(await damaged.audioBlob.text(), 'BBBBBB', 'the clip still plays its own audio');
    assert.equal(st().tracks.length, 1, 'and the rest of the session recovered');
  }

  // A clip with no takes restores exactly as it always did.
  st().loadProject({
    tracks: [mkTrack('t1')],
    clips: [
      { id: 'c2', trackId: 't1', label: 'Plain', audioBlob: mk('ZZZ'), mimeType: 'audio/wav', startSec: 0, durationSec: 3, sourceDuration: 3, offsetIntoSource: 0 },
    ] as never,
  });
  mod.flushPendingAutosave();
  await flush(16);
  const plain = JSON.parse(saveDirOf(root).files.get(MANIFEST)?.body as string) as {
    clips: Array<Record<string, unknown>>;
  };
  assert.ok(!('takes' in plain.clips[0]), 'no takes key for a clip that has none');
  await mod.useAutosaveRecoveryStore.getState().restore();
  assert.equal(st().clips[0].takes, undefined);
  assert.equal(isComped(st().clips[0]), false);
  await drain([mod]);
}

await theMeterSurvivesASaveAndRestoreRoundTrip();
await aLeftoverTmpThatParsesIsPromotedOnTheNextStart();
await aTornTmpIsSetAsideAndTheCommittedManifestSurvives();
await aSaveStagesThenPromotesAndNeverWritesTheManifestInPlace();
await aCrashDuringThePromoteLeavesTheOldManifestIntact();
await thePromoteFallsBackToCopyAndDropWithoutMove();
await aMoveThatRefusesAnExistingDestinationStillPromotes();
await aTmpOlderThanTheManifestIsLitterNotDamage();
await aTabThatLosesTheLockNeverWrites();
await anObserverIsPromotedWhenTheLockIsReleased();
await withoutWebLocksNothingChanges();
await takesAndTheCompSurviveASaveAndRestore();

console.log('editorAutosave: ok (durability, ownership, takes, meter round-trip)');
