/**
 * Import as tracks and the arrangement's tempo and time signature, and the
 * LOG lines it writes.
 *
 * Before: the import left EDIT at whatever tempo and meter it held, so a
 * waltz at 90 imported into a new arrangement and exported from EDIT came
 * back in 4/4 at 120, every note on the wrong beat of the wrong bar; and the
 * LOG line printed the file's first tempo event (60 for the quartet) with no
 * tempo change, while its clips play 120 and then 60.
 *
 * Now an arrangement with no clips takes the file's start tempo and first time
 * signature in the import's one undo step; one with clips keeps its own; and
 * the LOG names the tempo the clips play from, their changes, what EDIT took,
 * and (as a warning) the changes EDIT's one tempo and one time signature
 * cannot hold yet.
 *
 *   cd frontend && npx tsx src/lib/midiImportTracks.timing.test.ts
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { useEditorStore, type EditorTrack } from '../state/editorStore.ts';
import { arrangementToMidiFile } from './arrangementMidi.ts';
import { encodeMidi, parseMidi, type MidiFileData } from './midi.ts';
import { importMidiAsTracks, importTracksReport, type MidiTracksDeps } from './midiImportTracks.ts';
import { midiFileToRollParts } from './rollMidi.ts';

const ed = () => useEditorStore.getState();
const deps: MidiTracksDeps = {
  render: async () => ({ blob: new Blob([new Uint8Array([1])], { type: 'audio/wav' }), duration: 4 }),
  computePeaks: () => Promise.resolve({ peaks: new Float32Array(4) }),
  global: () => ({ useSoundfont: true, activeProgram: 0 }),
};

// A waltz at 90: a melody and a bass, 3/4 all through, at 480 PPQ.
const waltz: MidiFileData = {
  ppq: 480,
  bpm: 90,
  tempos: [{ tick: 0, bpm: 90 }],
  timeSignatures: [{ tick: 0, num: 3, den: 4 }],
  tracks: [
    {
      name: 'Flute',
      programs: [{ tick: 0, channel: 0, program: 73 }],
      notes: [0, 480, 960, 1440, 1920, 2400].map((tick, i) => ({ tick, durationTicks: 480, note: 72 + i, velocity: 90, channel: 0 })),
    },
    {
      name: 'Bass',
      programs: [{ tick: 0, channel: 1, program: 32 }],
      notes: [0, 1440].map((tick) => ({ tick, durationTicks: 1440, note: 43, velocity: 90, channel: 1 })),
    },
  ],
};
const waltzBytes = parseMidi(encodeMidi(waltz));

// ── a new arrangement takes the file's tempo and meter, in the import's one undo step ─
{
  ed().loadProject({ tracks: [], clips: [], bpm: 120, timeSignature: { num: 4, den: 4 } });
  const undoBefore = ed()._undo.length;
  const done = importMidiAsTracks(waltzBytes, { label: 'waltz', atSec: 0 }, deps);
  assert.ok(done);
  await done.rendered;
  assert.equal(ed().bpm, 90, "EDIT plays at the file's 90");
  assert.deepEqual(ed().timeSignature, { num: 3, den: 4 }, 'in 3/4');
  assert.deepEqual(done.arrangement, { bpm: 90, timeSignature: { num: 3, den: 4 } });
  assert.equal(ed()._undo.length, undoBefore + 1, 'tempo, meter, tracks and clips in one undo step');
  // Back out as MIDI: 3/4 at 90, every note on the beat the file put it on (480 PPQ doubled to 960).
  const back = parseMidi(encodeMidi(arrangementToMidiFile(ed()).file));
  assert.deepEqual(back.timeSignatures?.map((s) => [s.tick, s.num, s.den]), [[0, 3, 4]], "the file's 3/4");
  assert.deepEqual(back.tempos?.map((t) => [t.tick, t.bpm]), [[0, 90]], 'at 90');
  assert.deepEqual(back.tracks.find((t) => t.name === 'Flute')?.notes.map((n) => n.tick), [0, 960, 1920, 2880, 3840, 4800]);
  const again = midiFileToRollParts(back, 'b');
  assert.deepEqual(again.meter.meterMap.map((s) => [s.bar, s.meter.num, s.meter.den]), [[0, 3, 4]], 'and reads back in 3/4');
  assert.deepEqual(again.tempoMap.map((e) => [e.beat, e.bpm]), [[0, 90]]);
  // One undo takes the tempo and meter back with the tracks.
  ed().undo();
  assert.equal(ed().bpm, 120);
  assert.deepEqual(ed().timeSignature, { num: 4, den: 4 });
  assert.equal(ed().clips.length, 0);
  const report = importTracksReport(done, 'waltz', 0);
  assert.deepEqual(report.info, [
    'Import as tracks: 2 parts of "waltz" on new tracks at 0.00s (8 notes, 90 BPM); rendering audio in the background',
    "Import as tracks: EDIT takes the file's 90 BPM and 3/4",
  ]);
  assert.deepEqual(report.warn, [], 'nothing EDIT cannot hold');
}

// ── an arrangement with clips keeps its own ─────────────────────────────────
{
  const track: EditorTrack = { id: 'keep', name: 'Keep', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff' };
  ed().loadProject({
    tracks: [track],
    clips: [{ id: 'k', trackId: 'keep', label: 'k', audioBlob: new Blob([new Uint8Array([1])]), mimeType: 'audio/wav', sourceDuration: 1, offsetIntoSource: 0, durationSec: 1, startSec: 0, color: '#fff' }],
    bpm: 100,
    timeSignature: { num: 4, den: 4 },
  });
  const done = importMidiAsTracks(waltzBytes, { label: 'waltz', atSec: 4 }, deps);
  assert.ok(done);
  await done.rendered;
  assert.equal(ed().bpm, 100);
  assert.deepEqual(ed().timeSignature, { num: 4, den: 4 });
  assert.equal(done.arrangement, null);
  assert.equal(importTracksReport(done, 'waltz', 4).info.length, 1, 'no line about EDIT taking anything');
}

// ── the quartet: 120 until its first mark, and changes EDIT cannot hold yet ──
{
  const bytes = new Uint8Array(readFileSync(fileURLToPath(new URL('../../../tests/fixtures/quartet/op132_m530-640.mid', import.meta.url))));
  const data = parseMidi(bytes);
  assert.equal(data.bpm, 60, "the file's first tempo event is 60, at beat 251.5");
  ed().loadProject({ tracks: [], clips: [], bpm: 120, timeSignature: { num: 4, den: 4 } });
  const done = importMidiAsTracks(data, { label: 'op132', atSec: 0 }, deps);
  assert.ok(done);
  await done.rendered;
  assert.deepEqual(done.tempoMap.map((e) => [e.beat, e.bpm]), [[0, 120], [251.5, 60]]);
  assert.equal(ed().bpm, 120, 'EDIT takes the tempo the clips start at');
  const report = importTracksReport(done, 'op132', 0);
  assert.match(report.info[0], /, 120 BPM with 1 tempo change, 4 time signatures\); rendering audio/, 'the tempo the clips play from, and its change');
  assert.equal(report.info[1], "Import as tracks: EDIT takes the file's 120 BPM and 4/4");
  assert.deepEqual(report.warn, [
    'Import as tracks: the clips play "op132" with its 1 tempo change and 4 time signatures, but EDIT holds one tempo and one time signature, ' +
      "so the arrangement's MIDI export writes EDIT's alone",
  ]);
}

console.log('midiImportTracks.timing: ok');
