/**
 * lib/midiRender — a piano-roll clip's audio as an optional cache: whether a
 * clip's render is missing, current or stale, what a render is made from, the
 * one render call, the fields a render writes, and the window of a clip with
 * no render.
 *
 * The staleness cases replay the edits that make a cached render wrong: a note
 * moved, a tempo change, a lane that starts to loop, a bend, a new grid length
 * and an instrument change. A render saved before signatures existed is
 * trusted for its notes, and a clip with no program is never voice-stale.
 *
 *   cd frontend && npx tsx src/lib/midiRender.test.ts
 */
import assert from 'node:assert/strict';
import type { AudioClip, EditorTrack } from '../state/editorStore.ts';
import type { PianoNote } from '../state/pianoRollStore.ts';
import {
  hasClipAudio,
  hasMidiNotes,
  midiClipBpm,
  midiClipNominalSec,
  midiClipTotalSteps,
  midiLiveWindowFields,
  midiRenderFields,
  midiRenderSig,
  midiRenderState,
  midiRenderStateText,
  renderMidiClipAudio,
  type MidiStepRender,
} from './midiRender.ts';
import { rollClipFields } from './rollClip.ts';

const near = (a: number, b: number, msg: string, eps = 1e-9): void => {
  assert.ok(Math.abs(a - b) <= eps, `${msg}: ${a} vs ${b}`);
};

const note = (id: string, pitch: number, step: number, length = 2, velocity = 100, lane?: number): PianoNote =>
  ({ id, note: pitch, step, length, velocity, ...(lane === undefined ? {} : { lane }) } as PianoNote);

/** A 2-bar 7/8 part at 90 BPM whose lane 1 loops a 3-16th figure: a real roll bounce. */
const rollFields = () => rollClipFields({
  notes: [note('a', 60, 0), note('b', 64, 4), note('c', 72, 0, 1, 90, 1)],
  bpm: 90,
  totalSteps: 28,
  meterMap: [{ bar: 0, meter: { num: 7, den: 8, groups: [3, 2, 2] } }],
  pickupSteps: 0,
  lanes: [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 3 }],
  bends: [],
});

const clipOf = (over: Partial<AudioClip> = {}): AudioClip => ({
  id: 'm1',
  trackId: 't1',
  label: 'Violin I',
  mimeType: 'audio/wav',
  sourceDuration: 0,
  offsetIntoSource: 0,
  durationSec: 0,
  startSec: 0,
  color: '#fff',
  sourceKind: 'piano-roll',
  ...rollFields(),
  ...over,
});

const track = (over: Partial<EditorTrack> = {}): EditorTrack => ({
  id: 't1', name: 'Violin I', nameAutoGenerated: false, volume: 1, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});
const noPicker = { useSoundfont: false, activeProgram: 0 };
const picker = (p: number) => ({ useSoundfont: true, activeProgram: p });
const wav = () => new Blob([new Uint8Array(16)], { type: 'audio/wav' });

// ── what a clip is ──────────────────────────────────────────────────────────
{
  assert.equal(hasMidiNotes(clipOf()), true);
  assert.equal(hasMidiNotes(clipOf({ sourcePianoRoll: [] })), false, 'an empty roll has nothing to render');
  assert.equal(hasMidiNotes({ sourceKind: 'audio', sourcePianoRoll: [note('x', 60, 0)] }), false, 'an audio clip is not a MIDI clip');
  assert.equal(hasClipAudio(clipOf()), false, 'a roll clip with no render has no audio');
  assert.equal(hasClipAudio(clipOf({ audioBlob: wav() })), true);
  // The grid: its own length, else the bar line after the last note in its meter.
  assert.equal(midiClipTotalSteps(clipOf()), 28);
  assert.equal(midiClipTotalSteps(clipOf({ sourceTotalSteps: undefined })), 28, 'the lane repeats run to step 28, a bar line of 7/8');
  assert.equal(
    midiClipTotalSteps(clipOf({ sourceTotalSteps: undefined, sourcePianoRoll: [note('a', 60, 0), note('b', 64, 4)] })),
    14,
    'one 7/8 bar holds a last note ending on step 6',
  );
  assert.equal(midiClipBpm(clipOf(), 120), 90);
  assert.equal(midiClipBpm(clipOf({ sourceBpm: undefined }), 120), 120, 'no tempo of its own: the arrangement\'s start tempo');
  near(midiClipNominalSec(clipOf(), 120), 28 * (60 / 90 / 4), 'two bars of 7/8 at 90 BPM');
  // A ritardando in the clip's own map stretches its seconds.
  const rit = clipOf({ sourceTempoMap: [{ beat: 0, bpm: 90, curve: 'linear' }, { beat: 7, bpm: 45 }] });
  assert.ok(midiClipNominalSec(rit, 120) > midiClipNominalSec(clipOf(), 120) + 0.5, 'the ritardando lengthens the clip');
}

// ── the render signature ─────────────────────────────────────────────────────
{
  const base = clipOf();
  const sig = midiRenderSig(base);
  assert.match(sig, /^[0-9a-f]{24}$/, 'three 8-digit hashes');
  assert.equal(midiRenderSig(clipOf()), sig, 'the same part signs the same');
  assert.equal(midiRenderSig({ ...base, label: 'Viola', startSec: 9, gain: 0.5 } as AudioClip), sig, 'where the clip sits and how loud does not change its render');
  const moved = base.sourcePianoRoll!.map((n) => (n.id === 'b' ? { ...n, step: 5 } : n));
  const edits: Array<[string, Partial<AudioClip>]> = [
    ['a moved note', { sourcePianoRoll: moved }],
    ['a velocity', { sourcePianoRoll: base.sourcePianoRoll!.map((n, i) => (i === 0 ? { ...n, velocity: 30 } : n)) }],
    ['a roll note in another lane', { sourceRollNotes: base.sourceRollNotes!.map((n) => (n.id === 'c' ? { ...n, lane: 0 } as PianoNote : n)) }],
    ['the tempo', { sourceBpm: 96 }],
    ['a tempo map', { sourceTempoMap: [{ beat: 0, bpm: 90 }, { beat: 4, bpm: 60 }] }],
    ['the grid length', { sourceTotalSteps: 42 }],
    ['a lane cycle', { sourceLanes: [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 5 }] }],
    ['a bend', { sourceBends: [{ lane: 1, range: 2, points: [{ id: 'p0', step: 0, value: 0.5, shape: 'hold' }] }] }],
  ];
  for (const [what, over] of edits) {
    assert.notEqual(midiRenderSig({ ...base, ...over }), sig, `${what} changes what the render is made from`);
  }
  // Hashed once per note list: the store replaces a list when it changes.
  const big = Array.from({ length: 96000 }, (_, i) => note(`n${i}`, 36 + (i % 60), i * 0.5, 0.5));
  const t0 = performance.now();
  const bigSig = midiRenderSig(clipOf({ sourcePianoRoll: big, sourceRollNotes: big, sourceTotalSteps: 48000 }));
  const first = performance.now() - t0;
  const t1 = performance.now();
  for (let i = 0; i < 100; i += 1) midiRenderSig(clipOf({ sourcePianoRoll: big, sourceRollNotes: big, sourceTotalSteps: 48000 }));
  const again = (performance.now() - t1) / 100;
  assert.equal(midiRenderSig(clipOf({ sourcePianoRoll: big, sourceRollNotes: big, sourceTotalSteps: 48000 })), bigSig);
  console.log(`  96,000-note part: first signature ${first.toFixed(2)} ms, then ${again.toFixed(3)} ms each (the note hash is cached on the list)`);
  assert.ok(again < first, 'a second signature of the same list does not hash its notes again');
}

// ── the cache state ──────────────────────────────────────────────────────────
{
  const live = track({ instrumentProgram: 40 });
  assert.equal(midiRenderState(clipOf(), live, noPicker), 'none', 'no render held');
  assert.equal(midiRenderState(clipOf({ sourcePianoRoll: [] }), live, noPicker), 'current', 'an empty roll has nothing to render');
  const rendered = clipOf({ audioBlob: wav(), renderedProgram: 40 });
  const withSig = { ...rendered, renderSig: midiRenderSig(rendered) };
  assert.equal(midiRenderState(withSig, live, noPicker), 'current', 'a render of these notes through this voice');
  assert.equal(midiRenderState({ ...withSig, sourceBpm: 100 }, live, noPicker), 'stale', 'a tempo edit that did not render');
  assert.equal(midiRenderState({ ...withSig, sourcePianoRoll: withSig.sourcePianoRoll!.slice(1) }, live, noPicker), 'stale', 'a note deleted without a render');
  assert.equal(midiRenderState(withSig, track({ instrumentProgram: 42 }), noPicker), 'stale', 'the track changed instrument');
  assert.equal(midiRenderState(withSig, track({ instrumentProgram: 40, isPercussion: true }), noPicker), 'stale', 'melodic audio on a drum track');
  // Saved before renderSig existed: trusted for its notes, still checked for its voice.
  assert.equal(midiRenderState(rendered, live, noPicker), 'current', 'an old render is trusted for the notes saved beside it');
  assert.equal(midiRenderState({ ...rendered, sourceBpm: 100 }, live, noPicker), 'current', 'with no signature there is nothing to compare notes against');
  assert.equal(midiRenderState(rendered, track({ instrumentProgram: 56 }), noPicker), 'stale', 'but a voice change still shows');
  // A clip with no program plays the audio it was rendered with: never voice-stale.
  const unvoiced = clipOf({ audioBlob: wav() });
  assert.equal(midiRenderState(unvoiced, track(), noPicker), 'current');
  assert.equal(midiRenderState(unvoiced, track(), picker(48)), 'stale', 'until the picker gives it a program its audio was not rendered with');
}

// ── the words ────────────────────────────────────────────────────────────────
{
  assert.equal(midiRenderStateText('none', true), 'Plays live; renders when exported');
  assert.equal(midiRenderStateText('none', false), 'Needs a render to be heard');
  assert.equal(midiRenderStateText('stale', true), 'Rendered audio is out of date; re-rendering');
  assert.equal(midiRenderStateText('current', true), 'Plays live; rendered audio kept');
  assert.equal(midiRenderStateText('current', false), 'Plays its rendered audio');
}

// ── the one render call and the fields it writes ─────────────────────────────
{
  const calls: Array<{ notes: number; bpm: number; totalSteps: number; program?: number; percussion?: boolean; bends: boolean; tempoMap: boolean }> = [];
  const render: MidiStepRender = async (notes, bpm, totalSteps, opts) => {
    calls.push({ notes: notes.length, bpm, totalSteps, program: opts.program, percussion: opts.percussion, bends: !!opts.bends, tempoMap: !!opts.tempoMap });
    return { blob: wav(), duration: (totalSteps * 60) / bpm / 4 + 1.5 };
  };
  const clip = clipOf();
  const out = await renderMidiClipAudio(clip, { program: 40, percussion: false }, render, 120);
  // Lane B loops a 3-16th figure over 28 steps: 10 repeats; lane A holds 2 notes.
  assert.deepEqual(calls[0], { notes: 12, bpm: 90, totalSteps: 28, program: 40, percussion: false, bends: false, tempoMap: false });
  // A bent lane renders the roll's own notes in their lanes with the bend.
  const bent = clipOf({ sourceBends: [{ lane: 1, range: 2, points: [{ id: 'p0', step: 0, value: 0.5, shape: 'hold' }] }] });
  await renderMidiClipAudio(bent, { program: 40, percussion: false }, render, 120);
  assert.equal(calls[1].bends, true, 'the bend reaches the render');
  assert.equal(calls[1].notes, 12, 'every note, lane repeats written out');
  const rit = clipOf({ sourceTempoMap: [{ beat: 0, bpm: 90, curve: 'linear' }, { beat: 7, bpm: 45 }] });
  await renderMidiClipAudio(rit, { program: 40, percussion: false }, render, 120);
  assert.equal(calls[2].tempoMap, true, 'the tempo map reaches the render');

  // The fields: an untrimmed clip takes the render's length, ring-out included.
  const whole = { ...clip, sourceDuration: 28 * (60 / 90 / 4), durationSec: 28 * (60 / 90 / 4) };
  const fields = midiRenderFields(whole, out, { program: 40, percussion: false });
  assert.equal(fields.audioBlob, out.blob);
  assert.equal(fields.mimeType, 'audio/wav');
  near(fields.sourceDuration!, out.duration, 'the source is the whole render');
  near(fields.durationSec!, out.duration, 'and the clip grows to hold the ring-out');
  assert.equal(fields.renderedProgram, 40);
  assert.equal(fields.renderedPercussion, undefined);
  assert.equal(fields.renderSig, midiRenderSig(clip), 'the render records what it was made from');
  // A trimmed clip keeps its window.
  const trimmed = midiRenderFields({ ...whole, durationSec: 1 }, out, { program: 40, percussion: false });
  assert.equal(trimmed.durationSec, undefined, 'a trimmed window is left alone');
  const drums = midiRenderFields(whole, out, { program: 0, percussion: true });
  assert.equal(drums.renderedPercussion, true, 'a drum render says so');
}

// ── the window of a clip with no render ──────────────────────────────────────
{
  const whole = { durationSec: 4, sourceDuration: 4, offsetIntoSource: 0, timeStretchRate: undefined };
  assert.deepEqual(midiLiveWindowFields(whole, 6), { sourceDuration: 6, durationSec: 6 }, 'a clip showing its whole grid shows the new grid');
  assert.deepEqual(midiLiveWindowFields({ ...whole, durationSec: 2 }, 6), { sourceDuration: 6 }, 'a trimmed clip keeps its trim');
  assert.deepEqual(midiLiveWindowFields({ ...whole, durationSec: 3, offsetIntoSource: 0.5 }, 2), { sourceDuration: 2, durationSec: 1.5 }, 'shortened only where the grid now ends first');
}

console.log('midiRender: ok');
