// Generated by `python -m backend.modules.notation.instruments` from
// backend/modules/notation/instruments.py. Do not edit by hand:
// tests/test_orchestra_registry.py fails when this file and the backend differ.
export const ORCHESTRA_DATA = {
  "matchPattern": "[^a-z0-9äöüéè♭ -]+",
  "families": [
    {
      "id": "woodwinds",
      "label": "Woodwinds"
    },
    {
      "id": "brass",
      "label": "Brass"
    },
    {
      "id": "percussion",
      "label": "Percussion"
    },
    {
      "id": "keyboards",
      "label": "Harp and keyboards"
    },
    {
      "id": "band",
      "label": "Band"
    },
    {
      "id": "voices",
      "label": "Voices"
    },
    {
      "id": "strings",
      "label": "Strings"
    }
  ],
  "instruments": [
    {
      "id": "piccolo",
      "family": "woodwinds",
      "order": 0,
      "name": "Piccolo",
      "abbreviation": "Picc.",
      "music21Class": "Piccolo",
      "transposition": "P8",
      "semitones": 12,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 74,
      "rangeHigh": 106,
      "program": 72,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "ottavino",
        "petite flute"
      ],
      "matchKeys": [
        "ottavino",
        "petite flute",
        "picc",
        "piccolo"
      ]
    },
    {
      "id": "flute",
      "family": "woodwinds",
      "order": 1,
      "name": "Flute",
      "abbreviation": "Fl.",
      "music21Class": "Flute",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 60,
      "rangeHigh": 96,
      "program": 73,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "flauto",
        "flöte",
        "flote"
      ],
      "matchKeys": [
        "flauto",
        "flote",
        "flute",
        "flöte"
      ]
    },
    {
      "id": "oboe",
      "family": "woodwinds",
      "order": 2,
      "name": "Oboe",
      "abbreviation": "Ob.",
      "music21Class": "Oboe",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 58,
      "rangeHigh": 91,
      "program": 68,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "hautbois",
        "oboi"
      ],
      "matchKeys": [
        "hautbois",
        "oboe",
        "oboi"
      ]
    },
    {
      "id": "english-horn",
      "family": "woodwinds",
      "order": 3,
      "name": "English Horn",
      "abbreviation": "E.H.",
      "music21Class": "EnglishHorn",
      "transposition": "P-5",
      "semitones": -7,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 52,
      "rangeHigh": 84,
      "program": 69,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "cor anglais",
        "corno inglese",
        "englischhorn"
      ],
      "matchKeys": [
        "cor anglais",
        "corno inglese",
        "englischhorn",
        "english horn"
      ]
    },
    {
      "id": "clarinet-bb",
      "family": "woodwinds",
      "order": 4,
      "name": "Clarinet in B♭",
      "abbreviation": "Cl.",
      "music21Class": "Clarinet",
      "transposition": "M-2",
      "semitones": -2,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 50,
      "rangeHigh": 91,
      "program": 71,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "clarinet",
        "clarinetto",
        "klarinette",
        "clarinette",
        "clarinet in b-flat",
        "clarinet in bb",
        "b-flat clarinet",
        "bb clarinet"
      ],
      "matchKeys": [
        "b-flat clarinet",
        "bb clarinet",
        "clarinet",
        "clarinet bb",
        "clarinet in b-flat",
        "clarinet in bb",
        "clarinet in b♭",
        "clarinette",
        "clarinetto",
        "klarinette"
      ]
    },
    {
      "id": "clarinet-a",
      "family": "woodwinds",
      "order": 5,
      "name": "Clarinet in A",
      "abbreviation": "Cl.",
      "music21Class": "Clarinet",
      "transposition": "m-3",
      "semitones": -3,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 49,
      "rangeHigh": 89,
      "program": 71,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "clarinet in a",
        "a clarinet"
      ],
      "matchKeys": [
        "a clarinet",
        "clarinet a",
        "clarinet in a"
      ]
    },
    {
      "id": "bass-clarinet",
      "family": "woodwinds",
      "order": 6,
      "name": "Bass Clarinet",
      "abbreviation": "B. Cl.",
      "music21Class": "BassClarinet",
      "transposition": "M-9",
      "semitones": -14,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 1,
      "rangeLow": 34,
      "rangeHigh": 77,
      "program": 71,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "clarinetto basso",
        "bassklarinette",
        "clarinette basse"
      ],
      "matchKeys": [
        "b cl",
        "bass clarinet",
        "bassklarinette",
        "clarinette basse",
        "clarinetto basso"
      ]
    },
    {
      "id": "soprano-sax",
      "family": "woodwinds",
      "order": 7,
      "name": "Soprano Saxophone",
      "abbreviation": "S. Sax.",
      "music21Class": "SopranoSaxophone",
      "transposition": "M-2",
      "semitones": -2,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 56,
      "rangeHigh": 88,
      "program": 64,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "soprano sax"
      ],
      "matchKeys": [
        "s sax",
        "soprano sax",
        "soprano saxophone"
      ]
    },
    {
      "id": "alto-sax",
      "family": "woodwinds",
      "order": 8,
      "name": "Alto Saxophone",
      "abbreviation": "A. Sax.",
      "music21Class": "AltoSaxophone",
      "transposition": "M-6",
      "semitones": -9,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 49,
      "rangeHigh": 81,
      "program": 65,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "alto sax",
        "saxophone",
        "sax"
      ],
      "matchKeys": [
        "a sax",
        "alto sax",
        "alto saxophone",
        "sax",
        "saxophone"
      ]
    },
    {
      "id": "tenor-sax",
      "family": "woodwinds",
      "order": 9,
      "name": "Tenor Saxophone",
      "abbreviation": "T. Sax.",
      "music21Class": "TenorSaxophone",
      "transposition": "M-9",
      "semitones": -14,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 44,
      "rangeHigh": 76,
      "program": 66,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "tenor sax"
      ],
      "matchKeys": [
        "t sax",
        "tenor sax",
        "tenor saxophone"
      ]
    },
    {
      "id": "baritone-sax",
      "family": "woodwinds",
      "order": 10,
      "name": "Baritone Saxophone",
      "abbreviation": "Bar. Sax.",
      "music21Class": "BaritoneSaxophone",
      "transposition": "M-13",
      "semitones": -21,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 37,
      "rangeHigh": 69,
      "program": 67,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "baritone sax",
        "bari sax"
      ],
      "matchKeys": [
        "bar sax",
        "bari sax",
        "baritone sax",
        "baritone saxophone"
      ]
    },
    {
      "id": "bassoon",
      "family": "woodwinds",
      "order": 11,
      "name": "Bassoon",
      "abbreviation": "Bsn.",
      "music21Class": "Bassoon",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass",
        "tenor",
        "treble"
      ],
      "staves": 1,
      "rangeLow": 34,
      "rangeHigh": 75,
      "program": 70,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "fagotto",
        "fagott",
        "basson"
      ],
      "matchKeys": [
        "basson",
        "bassoon",
        "bsn",
        "fagott",
        "fagotto"
      ]
    },
    {
      "id": "contrabassoon",
      "family": "woodwinds",
      "order": 12,
      "name": "Contrabassoon",
      "abbreviation": "Cbsn.",
      "music21Class": "Contrabassoon",
      "transposition": "P-8",
      "semitones": -12,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 22,
      "rangeHigh": 55,
      "program": 70,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "contrafagotto",
        "kontrafagott",
        "double bassoon"
      ],
      "matchKeys": [
        "cbsn",
        "contrabassoon",
        "contrafagotto",
        "double bassoon",
        "kontrafagott"
      ]
    },
    {
      "id": "horn",
      "family": "brass",
      "order": 13,
      "name": "Horn in F",
      "abbreviation": "Hn.",
      "music21Class": "Horn",
      "transposition": "P-5",
      "semitones": -7,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 1,
      "rangeLow": 35,
      "rangeHigh": 77,
      "program": 60,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "french horn",
        "corno",
        "horn",
        "cor"
      ],
      "matchKeys": [
        "cor",
        "corno",
        "french horn",
        "horn",
        "horn in f"
      ]
    },
    {
      "id": "trumpet-bb",
      "family": "brass",
      "order": 14,
      "name": "Trumpet in B♭",
      "abbreviation": "Tpt.",
      "music21Class": "Trumpet",
      "transposition": "M-2",
      "semitones": -2,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 52,
      "rangeHigh": 82,
      "program": 56,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "trumpet",
        "tromba",
        "trompete",
        "trompette",
        "trumpet in b-flat",
        "trumpet in bb",
        "b-flat trumpet"
      ],
      "matchKeys": [
        "b-flat trumpet",
        "tpt",
        "tromba",
        "trompete",
        "trompette",
        "trumpet",
        "trumpet bb",
        "trumpet in b-flat",
        "trumpet in bb",
        "trumpet in b♭"
      ]
    },
    {
      "id": "trumpet-c",
      "family": "brass",
      "order": 15,
      "name": "Trumpet in C",
      "abbreviation": "Tpt.",
      "music21Class": "Trumpet",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 54,
      "rangeHigh": 84,
      "program": 56,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "trumpet in c",
        "c trumpet"
      ],
      "matchKeys": [
        "c trumpet",
        "tpt",
        "trumpet c",
        "trumpet in c"
      ]
    },
    {
      "id": "trombone",
      "family": "brass",
      "order": 16,
      "name": "Trombone",
      "abbreviation": "Tbn.",
      "music21Class": "Trombone",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass",
        "tenor"
      ],
      "staves": 1,
      "rangeLow": 40,
      "rangeHigh": 74,
      "program": 57,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "trombone",
        "posaune",
        "tenor trombone"
      ],
      "matchKeys": [
        "posaune",
        "tbn",
        "tenor trombone",
        "trombone"
      ]
    },
    {
      "id": "bass-trombone",
      "family": "brass",
      "order": 17,
      "name": "Bass Trombone",
      "abbreviation": "B. Tbn.",
      "music21Class": "BassTrombone",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 34,
      "rangeHigh": 70,
      "program": 57,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "bassposaune",
        "trombone basso"
      ],
      "matchKeys": [
        "b tbn",
        "bass trombone",
        "bassposaune",
        "trombone basso"
      ]
    },
    {
      "id": "tuba",
      "family": "brass",
      "order": 18,
      "name": "Tuba",
      "abbreviation": "Tba.",
      "music21Class": "Tuba",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 28,
      "rangeHigh": 65,
      "program": 58,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "basstuba"
      ],
      "matchKeys": [
        "basstuba",
        "tba",
        "tuba"
      ]
    },
    {
      "id": "timpani",
      "family": "percussion",
      "order": 19,
      "name": "Timpani",
      "abbreviation": "Timp.",
      "music21Class": "Timpani",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 38,
      "rangeHigh": 60,
      "program": 47,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "timpano",
        "pauken",
        "timbales",
        "kettledrums"
      ],
      "matchKeys": [
        "kettledrums",
        "pauken",
        "timbales",
        "timp",
        "timpani",
        "timpano"
      ]
    },
    {
      "id": "glockenspiel",
      "family": "percussion",
      "order": 20,
      "name": "Glockenspiel",
      "abbreviation": "Glock.",
      "music21Class": "Glockenspiel",
      "transposition": "P15",
      "semitones": 24,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 79,
      "rangeHigh": 108,
      "program": 9,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "campanelli",
        "orchestra bells"
      ],
      "matchKeys": [
        "campanelli",
        "glock",
        "glockenspiel",
        "orchestra bells"
      ]
    },
    {
      "id": "xylophone",
      "family": "percussion",
      "order": 21,
      "name": "Xylophone",
      "abbreviation": "Xyl.",
      "music21Class": "Xylophone",
      "transposition": "P8",
      "semitones": 12,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 65,
      "rangeHigh": 108,
      "program": 13,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "xilofono",
        "xylophon"
      ],
      "matchKeys": [
        "xilofono",
        "xyl",
        "xylophon",
        "xylophone"
      ]
    },
    {
      "id": "vibraphone",
      "family": "percussion",
      "order": 22,
      "name": "Vibraphone",
      "abbreviation": "Vib.",
      "music21Class": "Vibraphone",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 53,
      "rangeHigh": 89,
      "program": 11,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "vibes",
        "vibrafono"
      ],
      "matchKeys": [
        "vib",
        "vibes",
        "vibrafono",
        "vibraphone"
      ]
    },
    {
      "id": "marimba",
      "family": "percussion",
      "order": 23,
      "name": "Marimba",
      "abbreviation": "Mar.",
      "music21Class": "Marimba",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 36,
      "rangeHigh": 96,
      "program": 12,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "marimbaphone"
      ],
      "matchKeys": [
        "mar",
        "marimba",
        "marimbaphone"
      ]
    },
    {
      "id": "tubular-bells",
      "family": "percussion",
      "order": 24,
      "name": "Tubular Bells",
      "abbreviation": "T. Bells",
      "music21Class": "TubularBells",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 60,
      "rangeHigh": 77,
      "program": 14,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "chimes",
        "campane",
        "röhrenglocken"
      ],
      "matchKeys": [
        "campane",
        "chimes",
        "röhrenglocken",
        "t bells",
        "tubular bells"
      ]
    },
    {
      "id": "snare-drum",
      "family": "percussion",
      "order": 25,
      "name": "Snare Drum",
      "abbreviation": "S.D.",
      "music21Class": "SnareDrum",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 38,
      "rangeHigh": 38,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 38,
      "aliases": [
        "snare",
        "tamburo",
        "caisse claire",
        "kleine trommel",
        "side drum"
      ],
      "matchKeys": [
        "caisse claire",
        "kleine trommel",
        "side drum",
        "snare",
        "snare drum",
        "tamburo"
      ]
    },
    {
      "id": "bass-drum",
      "family": "percussion",
      "order": 26,
      "name": "Bass Drum",
      "abbreviation": "B.D.",
      "music21Class": "BassDrum",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 36,
      "rangeHigh": 36,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 36,
      "aliases": [
        "gran cassa",
        "grosse caisse",
        "große trommel",
        "grosse trommel"
      ],
      "matchKeys": [
        "bass drum",
        "gran cassa",
        "gro e trommel",
        "grosse caisse",
        "grosse trommel"
      ]
    },
    {
      "id": "crash-cymbals",
      "family": "percussion",
      "order": 27,
      "name": "Crash Cymbals",
      "abbreviation": "Cym.",
      "music21Class": "CrashCymbals",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 59,
      "rangeHigh": 59,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 59,
      "aliases": [
        "cymbals",
        "piatti",
        "becken",
        "cymbales"
      ],
      "matchKeys": [
        "becken",
        "crash cymbals",
        "cym",
        "cymbales",
        "cymbals",
        "piatti"
      ]
    },
    {
      "id": "suspended-cymbal",
      "family": "percussion",
      "order": 28,
      "name": "Suspended Cymbal",
      "abbreviation": "Sus. Cym.",
      "music21Class": "SuspendedCymbal",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 57,
      "rangeHigh": 57,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 57,
      "aliases": [
        "sus cym",
        "piatto sospeso"
      ],
      "matchKeys": [
        "piatto sospeso",
        "sus cym",
        "suspended cymbal"
      ]
    },
    {
      "id": "triangle",
      "family": "percussion",
      "order": 29,
      "name": "Triangle",
      "abbreviation": "Tri.",
      "music21Class": "Triangle",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 81,
      "rangeHigh": 81,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 81,
      "aliases": [
        "triangolo",
        "triangel"
      ],
      "matchKeys": [
        "tri",
        "triangel",
        "triangle",
        "triangolo"
      ]
    },
    {
      "id": "tambourine",
      "family": "percussion",
      "order": 30,
      "name": "Tambourine",
      "abbreviation": "Tamb.",
      "music21Class": "Tambourine",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 54,
      "rangeHigh": 54,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 54,
      "aliases": [
        "tamburino",
        "tambour de basque",
        "tamburin"
      ],
      "matchKeys": [
        "tamb",
        "tambour de basque",
        "tambourine",
        "tamburin",
        "tamburino"
      ]
    },
    {
      "id": "woodblock",
      "family": "percussion",
      "order": 31,
      "name": "Wood Block",
      "abbreviation": "W.B.",
      "music21Class": "Woodblock",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 76,
      "rangeHigh": 76,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 76,
      "aliases": [
        "wood block",
        "blocco di legno",
        "holzblock"
      ],
      "matchKeys": [
        "blocco di legno",
        "holzblock",
        "wood block",
        "woodblock"
      ]
    },
    {
      "id": "castanets",
      "family": "percussion",
      "order": 32,
      "name": "Castanets",
      "abbreviation": "Cast.",
      "music21Class": "Castanets",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 39,
      "rangeHigh": 39,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 39,
      "aliases": [
        "castagnette",
        "kastagnetten",
        "castagnettes"
      ],
      "matchKeys": [
        "cast",
        "castagnette",
        "castagnettes",
        "castanets",
        "kastagnetten"
      ]
    },
    {
      "id": "sleigh-bells",
      "family": "percussion",
      "order": 33,
      "name": "Sleigh Bells",
      "abbreviation": "Sl. B.",
      "music21Class": "SleighBells",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 83,
      "rangeHigh": 83,
      "program": 48,
      "bank": 128,
      "percussion": true,
      "kitPitch": 83,
      "aliases": [
        "jingle bells",
        "sonagli",
        "schellen"
      ],
      "matchKeys": [
        "jingle bells",
        "schellen",
        "sl b",
        "sleigh bells",
        "sonagli"
      ]
    },
    {
      "id": "harp",
      "family": "keyboards",
      "order": 34,
      "name": "Harp",
      "abbreviation": "Hp.",
      "music21Class": "Harp",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 23,
      "rangeHigh": 104,
      "program": 46,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "arpa",
        "harfe",
        "harpe"
      ],
      "matchKeys": [
        "arpa",
        "harfe",
        "harp",
        "harpe"
      ]
    },
    {
      "id": "celesta",
      "family": "keyboards",
      "order": 35,
      "name": "Celesta",
      "abbreviation": "Cel.",
      "music21Class": "Celesta",
      "transposition": "P8",
      "semitones": 12,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 60,
      "rangeHigh": 108,
      "program": 8,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "celeste"
      ],
      "matchKeys": [
        "cel",
        "celesta",
        "celeste"
      ]
    },
    {
      "id": "piano",
      "family": "keyboards",
      "order": 36,
      "name": "Piano",
      "abbreviation": "Pno.",
      "music21Class": "Piano",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 21,
      "rangeHigh": 108,
      "program": 0,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "pianoforte",
        "klavier",
        "grand piano",
        "keys"
      ],
      "matchKeys": [
        "grand piano",
        "keys",
        "klavier",
        "piano",
        "pianoforte",
        "pno"
      ]
    },
    {
      "id": "harpsichord",
      "family": "keyboards",
      "order": 37,
      "name": "Harpsichord",
      "abbreviation": "Hpd.",
      "music21Class": "Harpsichord",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 29,
      "rangeHigh": 89,
      "program": 6,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "cembalo",
        "clavecin"
      ],
      "matchKeys": [
        "cembalo",
        "clavecin",
        "harpsichord",
        "hpd"
      ]
    },
    {
      "id": "organ",
      "family": "keyboards",
      "order": 38,
      "name": "Organ",
      "abbreviation": "Org.",
      "music21Class": "PipeOrgan",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 36,
      "rangeHigh": 96,
      "program": 19,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "organo",
        "orgel",
        "orgue",
        "pipe organ"
      ],
      "matchKeys": [
        "org",
        "organ",
        "organo",
        "orgel",
        "orgue",
        "pipe organ"
      ]
    },
    {
      "id": "electric-guitar",
      "family": "band",
      "order": 39,
      "name": "Electric Guitar",
      "abbreviation": "E. Gtr.",
      "music21Class": "ElectricGuitar",
      "transposition": "P-8",
      "semitones": -12,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 40,
      "rangeHigh": 88,
      "program": 26,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "electric guitar",
        "e-gitarre",
        "guitar"
      ],
      "matchKeys": [
        "e gtr",
        "e-gitarre",
        "electric guitar",
        "guitar"
      ]
    },
    {
      "id": "acoustic-guitar",
      "family": "band",
      "order": 40,
      "name": "Acoustic Guitar",
      "abbreviation": "Gtr.",
      "music21Class": "AcousticGuitar",
      "transposition": "P-8",
      "semitones": -12,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 40,
      "rangeHigh": 83,
      "program": 24,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "classical guitar",
        "chitarra",
        "gitarre",
        "nylon guitar"
      ],
      "matchKeys": [
        "acoustic guitar",
        "chitarra",
        "classical guitar",
        "gitarre",
        "gtr",
        "nylon guitar"
      ]
    },
    {
      "id": "electric-bass",
      "family": "band",
      "order": 41,
      "name": "Electric Bass",
      "abbreviation": "E. Bass",
      "music21Class": "ElectricBass",
      "transposition": "P-8",
      "semitones": -12,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 28,
      "rangeHigh": 67,
      "program": 33,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "bass guitar",
        "e-bass",
        "electric bass"
      ],
      "matchKeys": [
        "bass guitar",
        "e bass",
        "e-bass",
        "electric bass"
      ]
    },
    {
      "id": "drum-kit",
      "family": "band",
      "order": 42,
      "name": "Drum Kit",
      "abbreviation": "D. Kit",
      "music21Class": "UnpitchedPercussion",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "percussion"
      ],
      "staves": 1,
      "rangeLow": 35,
      "rangeHigh": 81,
      "program": 0,
      "bank": 128,
      "percussion": true,
      "kitPitch": null,
      "aliases": [
        "drums",
        "drum set",
        "drumset",
        "kit",
        "schlagzeug"
      ],
      "matchKeys": [
        "d kit",
        "drum kit",
        "drum set",
        "drums",
        "drumset",
        "kit",
        "schlagzeug"
      ]
    },
    {
      "id": "voice",
      "family": "voices",
      "order": 43,
      "name": "Voice",
      "abbreviation": "Vo.",
      "music21Class": "Vocalist",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 48,
      "rangeHigh": 84,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "vocals",
        "vocal",
        "lead vocal",
        "singer",
        "voce"
      ],
      "matchKeys": [
        "lead vocal",
        "singer",
        "vocal",
        "vocals",
        "voce",
        "voice"
      ]
    },
    {
      "id": "soprano",
      "family": "voices",
      "order": 44,
      "name": "Soprano",
      "abbreviation": "S.",
      "music21Class": "Soprano",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 60,
      "rangeHigh": 84,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "sopran"
      ],
      "matchKeys": [
        "sopran",
        "soprano"
      ]
    },
    {
      "id": "mezzo-soprano",
      "family": "voices",
      "order": 45,
      "name": "Mezzo-soprano",
      "abbreviation": "Mez.",
      "music21Class": "MezzoSoprano",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 57,
      "rangeHigh": 81,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "mezzo"
      ],
      "matchKeys": [
        "mez",
        "mezzo",
        "mezzo soprano",
        "mezzo-soprano"
      ]
    },
    {
      "id": "alto",
      "family": "voices",
      "order": 46,
      "name": "Alto",
      "abbreviation": "A.",
      "music21Class": "Alto",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 53,
      "rangeHigh": 77,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "contralto",
        "alt"
      ],
      "matchKeys": [
        "alt",
        "alto",
        "contralto"
      ]
    },
    {
      "id": "tenor",
      "family": "voices",
      "order": 47,
      "name": "Tenor",
      "abbreviation": "T.",
      "music21Class": "Tenor",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble8vb",
        "bass"
      ],
      "staves": 1,
      "rangeLow": 48,
      "rangeHigh": 72,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "tenore",
        "ténor"
      ],
      "matchKeys": [
        "tenor",
        "tenore",
        "ténor"
      ]
    },
    {
      "id": "baritone",
      "family": "voices",
      "order": 48,
      "name": "Baritone",
      "abbreviation": "Bar.",
      "music21Class": "Baritone",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 43,
      "rangeHigh": 67,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "baritono",
        "bariton"
      ],
      "matchKeys": [
        "bar",
        "bariton",
        "baritone",
        "baritono"
      ]
    },
    {
      "id": "bass-voice",
      "family": "voices",
      "order": 49,
      "name": "Bass",
      "abbreviation": "B.",
      "music21Class": "Bass",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 40,
      "rangeHigh": 64,
      "program": 53,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "basso",
        "bass voice"
      ],
      "matchKeys": [
        "bass",
        "bass voice",
        "basso"
      ]
    },
    {
      "id": "choir",
      "family": "voices",
      "order": 50,
      "name": "Choir",
      "abbreviation": "Ch.",
      "music21Class": "Choir",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble",
        "bass"
      ],
      "staves": 2,
      "rangeLow": 40,
      "rangeHigh": 84,
      "program": 52,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "chorus",
        "coro",
        "chor",
        "choeur",
        "satb"
      ],
      "matchKeys": [
        "choeur",
        "choir",
        "chor",
        "chorus",
        "coro",
        "satb"
      ]
    },
    {
      "id": "violin",
      "family": "strings",
      "order": 51,
      "name": "Violin",
      "abbreviation": "Vln.",
      "music21Class": "Violin",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "treble"
      ],
      "staves": 1,
      "rangeLow": 55,
      "rangeHigh": 100,
      "program": 40,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "violino",
        "violine",
        "violon",
        "geige",
        "vl"
      ],
      "matchKeys": [
        "geige",
        "violin",
        "violine",
        "violino",
        "violon",
        "vl",
        "vln"
      ]
    },
    {
      "id": "viola",
      "family": "strings",
      "order": 52,
      "name": "Viola",
      "abbreviation": "Vla.",
      "music21Class": "Viola",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "alto",
        "treble"
      ],
      "staves": 1,
      "rangeLow": 48,
      "rangeHigh": 88,
      "program": 41,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "bratsche",
        "alto (viola)"
      ],
      "matchKeys": [
        "alto viola",
        "bratsche",
        "viola",
        "vla"
      ]
    },
    {
      "id": "cello",
      "family": "strings",
      "order": 53,
      "name": "Violoncello",
      "abbreviation": "Vc.",
      "music21Class": "Violoncello",
      "transposition": "P1",
      "semitones": 0,
      "clefs": [
        "bass",
        "tenor",
        "treble"
      ],
      "staves": 1,
      "rangeLow": 36,
      "rangeHigh": 81,
      "program": 42,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "cello",
        "violoncelle",
        "vc"
      ],
      "matchKeys": [
        "cello",
        "vc",
        "violoncelle",
        "violoncello"
      ]
    },
    {
      "id": "contrabass",
      "family": "strings",
      "order": 54,
      "name": "Contrabass",
      "abbreviation": "Cb.",
      "music21Class": "Contrabass",
      "transposition": "P-8",
      "semitones": -12,
      "clefs": [
        "bass"
      ],
      "staves": 1,
      "rangeLow": 28,
      "rangeHigh": 67,
      "program": 43,
      "bank": 0,
      "percussion": false,
      "kitPitch": null,
      "aliases": [
        "double bass",
        "contrabbasso",
        "kontrabass",
        "string bass",
        "upright bass",
        "kb"
      ],
      "matchKeys": [
        "contrabass",
        "contrabbasso",
        "double bass",
        "kb",
        "kontrabass",
        "string bass",
        "upright bass"
      ]
    }
  ]
} as const;
