/**
 * A MIDI part's render survives SAVE and OPEN as what it is: current, out of
 * date, or made only so the part could be heard.
 *
 * The review's sequence: a Violin part holds a kept render of notes 60 and 64;
 * its notes are transposed to 67 and 71 and the re-render has not landed (it
 * waits behind other parts, or it failed). SAVE embeds that WAV. At 057f7499
 * the reopened part recomputed its signature from the saved notes, read the
 * old render as current, and every export, stem and freeze printed 60 and 64
 * while live playback played 67 and 71. The file now says the render was out
 * of date (`render_stale`), the part reopens stale, and the export renders it
 * again. A current render reopens current and exports with no render; a render
 * EDIT made because the part could not play live (`render_auto`) reopens with
 * that mark, so it is dropped once the part plays live; a file written before
 * the two keys opens its renders current and kept, as it always did.
 *
 * The save runs through projectStore.save (the SAVE button's own action) and
 * the open through loadProjectIntoEditor, with fetch standing in for the
 * backend as projectImport.tempo.test does.
 *
 *   cd frontend && npx tsx src/lib/projectImport.renderState.test.ts
 */
import assert from 'node:assert/strict';
import { useEditorStore, type AudioClip, type EditorTrack } from '../state/editorStore.ts';
import { useProjectStore } from '../state/projectStore.ts';
import { clipsWithMidiAudio, configureMidiRenderQueue, requestMidiRender } from '../state/midiRenderQueue.ts';
import { liveMidiIfHeard } from '../state/liveMixer.ts';
import { loadProjectIntoEditor } from './projectImport.ts';
import type { TasmoProjectLoaded } from './projectClient.ts';
import { rollClipFields } from './rollClip.ts';
import { midiRenderSig, midiRenderState, type MidiStepRender } from './midiRender.ts';

// computePeaks needs an AudioContext. The fake decodes any blob to a short tone.
class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, numberOfChannels: 1, length: 64, sampleRate: 44100, getChannelData: () => new Float32Array(64).fill(0.25) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const OFF = { useSoundfont: false, activeProgram: 0 };
const renders: number[][] = [];
const render: MidiStepRender = async (notes, bpm, totalSteps) => {
  renders.push(notes.map((n) => n.note));
  return { blob: new Blob([new Uint8Array(64 + notes.length)], { type: 'audio/wav' }), duration: (totalSteps * 60) / bpm / 4 + 1 };
};
configureMidiRenderQueue({
  render,
  computePeaks: async (_b, bins) => ({ peaks: new Float32Array(bins ?? 240) }),
  global: () => OFF,
  ensureReady: async () => true,
  livePlan: liveMidiIfHeard,
});

const ed = () => useEditorStore.getState();
const track = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id, name: id, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff', ...over,
});
const part = (id: string, trackId: string, pitches: number[]): AudioClip => ({
  id, trackId, label: id, mimeType: 'audio/wav', sourceDuration: 2, offsetIntoSource: 0, durationSec: 2, startSec: 0, color: '#fff',
  sourceKind: 'piano-roll',
  ...rollClipFields({
    notes: pitches.map((note, i) => ({ id: `${id}${i}`, note, step: i * 4, length: 4, velocity: 100 })),
    bpm: 120, totalSteps: 16, meterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }], pickupSteps: 0,
    lanes: [{ id: 0, name: 'A', cycleSteps: null }], bends: [],
  }),
});
const clipOf = (id: string) => ed().clips.find((c) => c.id === id)!;
const trackOf = (id: string) => ed().tracks.find((t) => t.id === clipOf(id).trackId);
const stateOf = (id: string) => midiRenderState(clipOf(id), trackOf(id), OFF);
const transpose = (id: string, by: number) => {
  const moved = clipOf(id).sourcePianoRoll!.map((n) => ({ ...n, note: n.note + by }));
  ed().updateClip(id, { sourcePianoRoll: moved, sourceRollNotes: moved });
};

/** SAVE through the store's own action; the posted project and its files. */
async function save(): Promise<{ project: TasmoProjectLoaded; files: File[] }> {
  useProjectStore.setState({ projectName: 'P', savePath: 'P.tasmo', pendingTracks: [] });
  let posted: FormData | null = null;
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: RequestInfo | URL, init?: RequestInit) => {
    if (String(url).includes('/api/project/save-session')) {
      posted = init?.body as FormData;
      return new Response(JSON.stringify({ status: 'saved', path: 'P.tasmo', manifest: { audio_mode: 'embedded' } }), { status: 200 });
    }
    return new Response('[]', { status: 200 });
  }) as typeof fetch;
  try {
    await useProjectStore.getState().save();
  } finally {
    globalThis.fetch = realFetch;
  }
  assert.ok(posted, 'SAVE posted to /save-session');
  const form = posted as FormData;
  const project = JSON.parse(await (form.get('project') as Blob).text()) as TasmoProjectLoaded;
  return { project, files: form.getAll('files') as File[] };
}

/** OPEN a saved project, its files served as the backend's /clip-audio does. */
async function open(project: TasmoProjectLoaded, files: File[]): Promise<void> {
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: RequestInfo | URL) => {
    const path = decodeURIComponent(String(url).split('path=')[1] ?? '');
    const hit = files.find((f) => path.endsWith(f.name));
    return hit ? new Response(hit, { status: 200 }) : new Response('', { status: 404 });
  }) as typeof fetch;
  try {
    ed().loadProject({ tracks: [], clips: [] });
    await loadProjectIntoEditor(project);
  } finally {
    globalThis.fetch = realFetch;
  }
}

const savedClip = (project: TasmoProjectLoaded, id: string) => project.tracks.flatMap((t) => t.clips).find((c) => c.id === id)!;

async function main(): Promise<void> {
  // ── a stale kept render reopens stale, and the export prints the new notes ──
  ed().loadProject({
    tracks: [track('vn', { instrumentProgram: 40 }), track('va', { instrumentProgram: 41 })],
    clips: [part('violin', 'vn', [60, 64]), part('viola', 'va', [55, 59])],
  });
  // "Keep rendered audio" on both.
  await requestMidiRender('violin', 'keep');
  await requestMidiRender('viola', 'keep');
  assert.equal(stateOf('violin'), 'current');
  transpose('violin', 7);
  assert.equal(stateOf('violin'), 'stale', 'the notes moved and the re-render has not landed');
  assert.equal(stateOf('viola'), 'current');
  const first = await save();
  assert.equal(first.files.length, 2, 'both renders are embedded');
  assert.equal(savedClip(first.project, 'violin').render_stale, true, 'the file says the violin render is out of date');
  assert.equal(savedClip(first.project, 'viola').render_stale, false);
  assert.equal(savedClip(first.project, 'violin').render_auto, false, 'kept on purpose');

  await open(first.project, first.files);
  assert.ok(clipOf('violin').audioBlob instanceof Blob, 'the violin reopens holding its render');
  assert.deepEqual(clipOf('violin').sourcePianoRoll!.map((n) => n.note), [67, 71], 'and its new notes');
  assert.equal(stateOf('violin'), 'stale', 'the render reopens stale');
  assert.equal(stateOf('viola'), 'current', 'a current render reopens current');
  renders.length = 0;
  const out = await clipsWithMidiAudio();
  assert.deepEqual(renders, [[67, 71]], 'the export renders the violin again, with the notes it has, and nothing else');
  assert.equal(stateOf('violin'), 'current', 'and keeps the fresh render');
  assert.equal(clipOf('violin').renderAuto, undefined, 'still kept');
  out.release();

  // A SAVE after that writes it current, and it reopens current: nothing renders.
  const second = await save();
  assert.equal(savedClip(second.project, 'violin').render_stale, false);
  await open(second.project, second.files);
  renders.length = 0;
  (await clipsWithMidiAudio()).release();
  assert.deepEqual(renders, [], 'every render reopens current');

  // ── a render made so a part could be heard keeps its mark through the file ──
  ed().loadProject({ tracks: [track('bare')], clips: [part('hum', 'bare', [48, 52])] });
  await requestMidiRender('hum', 'cache'); // EDIT's upkeep: the part cannot play live
  assert.equal(clipOf('hum').renderAuto, true);
  const third = await save();
  assert.equal(savedClip(third.project, 'hum').render_auto, true, 'the file says why the render is there');
  await open(third.project, third.files);
  assert.equal(clipOf('hum').renderAuto, true, 'it reopens with the mark');
  assert.equal(stateOf('hum'), 'current');
  // Given an instrument, the part plays live and the upkeep drops the render.
  ed().updateTrack(trackOf('hum')!.id, { instrumentProgram: 71 });
  renders.length = 0;
  assert.equal((await requestMidiRender('hum', 'cache')).kind, 'skipped');
  assert.deepEqual(renders, []);
  assert.equal(clipOf('hum').audioBlob, undefined, 'the render made to be heard is dropped');
  // Saved again, the part holds no audio and writes no render marks.
  const fourth = await save();
  assert.equal(fourth.files.length, 0);
  assert.equal(savedClip(fourth.project, 'hum').audio_file, null);
  assert.equal(savedClip(fourth.project, 'hum').render_auto, false);

  // ── a file written before the two keys opens its renders current and kept ──
  const legacy = JSON.parse(JSON.stringify(first.project)) as TasmoProjectLoaded;
  for (const t of legacy.tracks) for (const c of t.clips) { delete c.render_stale; delete c.render_auto; }
  await open(legacy, first.files);
  assert.equal(stateOf('violin'), 'current', 'an older file is trusted for the notes saved beside its render');
  assert.equal(clipOf('violin').renderAuto, undefined, 'and its renders are kept');
  assert.equal(clipOf('violin').renderSig, midiRenderSig(clipOf('violin')));

  console.log('projectImport.renderState: ok');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
