// A saved project reopens with every part on its own instrument, in its own
// folder, at its own tempo, and with every note it had.
//
// Before this, captureEditorSession wrote no track or clip instrument program,
// no rendered program, no clip tempo and no folder, so a reopened arrangement
// put every MIDI part on the global instrument, rendered them all again, played
// each clip at the project tempo and laid every track flat at the root. The
// save also sent the project JSON as a multipart TEXT field, which the backend's
// form parser holds to 1 MB: about 9,000 notes filled it and the save failed.
//
// Each block replays the app's own order: the EDIT store holds the session,
// captureEditorSession builds the payload, projectApi.saveSession posts it,
// the JSON comes back from the backend, and loadProjectIntoEditor opens it.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { captureEditorSession, loadProjectIntoEditor, tasmoTrackTree } from './projectImport.ts';
import { projectApi, type TasmoProjectInput, type TasmoProjectLoaded } from './projectClient.ts';
import { clipRollLoad } from './rollClip.ts';
import { stretchPlan } from './clipOps/timeline.ts';
import { beatMatchPlan } from './beatMatch.ts';
import { bounceMidiClip } from './clipOps/audioOps.ts';
import { noteEndStep } from './clipNotes/units.ts';
import { tasmoLoadedToDawProject } from './tasmoToSession.ts';
import { clipRenderIsStale, clipVoice, renderedVoiceFields } from './clipProgram.ts';
import { useEditorStore, type AudioClip, type EditorTrack } from '../state/editorStore.ts';
import * as tools from '../state/editorTools.ts';
import { useProjectStore } from '../state/projectStore.ts';
import { useLogStore } from '../state/logStore.ts';
import { tickOfStep, usePianoRollStore, type PianoNote } from '../state/pianoRollStore.ts';

// computePeaks needs an AudioContext. The fake decodes any blob to one second.
class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, getChannelData: () => new Float32Array(64).fill(0.5) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const withoutIds = (notes: readonly PianoNote[] = []) => notes.map(({ id: _id, ...n }) => n);
const blob = () => new Blob([new Uint8Array([1, 2, 3])], { type: 'audio/wav' });

const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#fff',
  ...extra,
});

const rollClip = (id: string, trackId: string, extra: Partial<AudioClip>): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: blob(),
  mimeType: 'audio/wav',
  sourceDuration: 1,
  offsetIntoSource: 0,
  durationSec: 1,
  startSec: 0,
  color: '#fff',
  peaks: new Float32Array(0),
  sourceKind: 'piano-roll',
  sourceTotalSteps: 16,
  sourceMeterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }],
  sourcePickupSteps: 0,
  sourceLanes: [{ id: 0, name: 'A', cycleSteps: null }],
  ...extra,
});

/** A plain audio clip: no notes, no roll fields. */
const audioClip = (id: string, trackId: string, extra: Partial<AudioClip> = {}): AudioClip => ({
  ...rollClip(id, trackId, {}),
  sourceKind: undefined,
  sourceTotalSteps: undefined,
  sourceMeterMap: undefined,
  sourcePickupSteps: undefined,
  sourceLanes: undefined,
  ...extra,
});

/** A note as the store holds it: ticks that agree with its steps. */
const note = (id: string, pitch: number, step: number, length: number, extra: Partial<PianoNote> = {}): PianoNote => ({
  id,
  note: pitch,
  step,
  length,
  velocity: 100,
  tick: tickOfStep(step),
  ticks: tickOfStep(length),
  ...extra,
});

/** Save the live session the way projectStore does, with the transport stubbed
 *  at fetch: returns the multipart body projectApi.saveSession really posted. */
async function saveThroughTheWire(): Promise<{ form: FormData; files: Array<{ name: string; blob: Blob }> }> {
  const session = captureEditorSession();
  const project: TasmoProjectInput = { project_name: 'Symphony', tempo: session.bpm, tracks: session.tracks, buses: session.buses };
  let posted: FormData | null = null;
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (_url: RequestInfo | URL, init?: RequestInit) => {
    posted = init?.body as FormData;
    return new Response(JSON.stringify({ status: 'saved', path: 'S.tasmo', manifest: {} }), { status: 200 });
  }) as typeof fetch;
  try {
    await projectApi.saveSession(project, 'S.tasmo', session.files);
  } finally {
    globalThis.fetch = realFetch;
  }
  assert.ok(posted, 'saveSession posted a body');
  return { form: posted as FormData, files: session.files };
}

/** The project part as the backend reads it back out of the archive: the JSON
 *  the frontend sent, then the embedded files served by name. */
async function projectFrom(form: FormData): Promise<TasmoProjectLoaded> {
  const part = form.get('project');
  // A FILE part. As a text field the backend's parser refuses it past 1 MB.
  assert.ok(part instanceof Blob, 'the project JSON goes out as a file part, not a text field');
  return JSON.parse(await (part as Blob).text()) as TasmoProjectLoaded;
}

async function openWithFiles(project: TasmoProjectLoaded, files: Array<{ name: string; blob: Blob }>): Promise<void> {
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: RequestInfo | URL) => {
    const path = decodeURIComponent(String(url).split('path=')[1] ?? '');
    const file = files.find((f) => path.endsWith(f.name));
    return file ? new Response(file.blob, { status: 200 }) : new Response('', { status: 404 });
  }) as typeof fetch;
  try {
    await loadProjectIntoEditor(project);
  } finally {
    globalThis.fetch = realFetch;
  }
}

const st = () => useEditorStore.getState();

// ── Instruments, clip tempo and folders survive save -> open ─────────────────
{
  const strings: PianoNote[] = [note('s0', 55, 0, 4), note('s1', 59, 4, 4)];
  useEditorStore.setState({
    bpm: 120,
    tracks: [
      track('f1', { isFolder: true, collapsed: true, name: 'Strings' }),
      track('t1', { parentTrackId: 'f1', instrumentProgram: 40 }),
      track('t2', { instrumentProgram: 71 }),
      track('t3'),
    ],
    clips: [
      // Its own program over its track's, rendered with it, written at 90 BPM.
      rollClip('c1', 't1', { sourcePianoRoll: strings, sourceRollNotes: strings, instrumentProgram: 42, renderedProgram: 42, sourceBpm: 90 }),
      // No program of its own: its track's (71) is what it was rendered with.
      rollClip('c2', 't2', { sourcePianoRoll: [note('w0', 72, 0, 2)], renderedProgram: 71, sourceBpm: 120 }),
      // Audio clips carry none of the MIDI fields. c3 gets a tempo tag below;
      // c4 was dropped from the library and beat-matched to 124.
      audioClip('c3', 't3'),
      audioClip('c4', 't3', { startSec: 1, libraryEntryId: 'lib-7', bpm: 124 }),
    ],
  });
  // The user tags the audio loop as 92 bpm, the way the assistant's
  // editor_set_clip_source_bpm does, so it can be stretched to a tempo later.
  assert.ok(tools.setClipSourceBpm({ clip_id: 'c3', bpm: 92 }).ok);
  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);

  const byTrack = new Map(project.tracks.map((t) => [t.id, t]));
  assert.equal(byTrack.get('t1')?.instrument_program, 40);
  assert.equal(byTrack.get('t1')?.parent_track_id, 'f1');
  assert.equal(byTrack.get('f1')?.is_folder, true);
  assert.equal(byTrack.get('f1')?.collapsed, true);
  assert.equal(byTrack.get('t3')?.instrument_program, null);
  const c1 = byTrack.get('t1')?.clips[0];
  assert.equal(c1?.instrument_program, 42);
  assert.equal(c1?.rendered_program, 42);
  assert.equal(c1?.source_bpm, 90);
  const [c3, c4] = byTrack.get('t3')?.clips ?? [];
  assert.ok(c3 && !('instrument_program' in c3) && !('rendered_program' in c3), 'an audio clip writes no program');
  assert.equal(c3.source_bpm, 92, "the audio clip's tempo tag is saved");
  assert.equal(c4?.source_bpm, null, 'an untagged audio clip saves no tempo');
  assert.equal(c4?.bpm, 124, 'the beat-matched tempo is saved');
  assert.equal(c4?.library_entry_id, 'lib-7');
  assert.equal(c3.bpm, null);
  assert.equal(c3.library_entry_id, null);

  // Reopen over a different session, so nothing is left over from the save.
  useEditorStore.setState({ bpm: 100, tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);

  const tracks = new Map(st().tracks.map((t) => [t.id, t]));
  assert.equal(tracks.get('t1')?.instrumentProgram, 40, 'the track reopens on its own instrument');
  assert.equal(tracks.get('t2')?.instrumentProgram, 71);
  assert.equal(tracks.get('t3')?.instrumentProgram, undefined);
  assert.equal(tracks.get('t1')?.parentTrackId, 'f1', 'the track is back in its folder');
  assert.equal(tracks.get('f1')?.isFolder, true);
  assert.equal(tracks.get('f1')?.collapsed, true);
  // A folder is an arrangement row with no audio node, after a reopen as when made.
  assert.equal(st().routing.nodes.some((n) => n.id === 'f1'), false, 'the folder has no routing node');
  assert.equal(st().routing.nodes.some((n) => n.id === 't1'), true);

  const clips = new Map(st().clips.map((c) => [c.id, c]));
  const r1 = clips.get('c1');
  assert.equal(r1?.instrumentProgram, 42, 'the clip reopens on its own instrument');
  assert.equal(r1?.renderedProgram, 42);
  assert.equal(r1?.sourceBpm, 90, 'the clip keeps the tempo its notes were written at');
  const r2 = clips.get('c2');
  assert.equal(r2?.instrumentProgram, undefined);
  assert.equal(r2?.renderedProgram, 71);
  // The tagged loop reopens tagged, so stretch-to-tempo still has its source
  // tempo; the untagged one stays untagged.
  const a3 = clips.get('c3') as AudioClip;
  assert.equal(a3.sourceKind, undefined);
  assert.equal(a3.sourceBpm, 92, 'the audio clip keeps its tempo tag');
  const plan = stretchPlan(a3, { targetBpm: 115 });
  assert.ok(plan.ok, `stretch-to-tempo works after a reopen: ${plan.ok ? '' : plan.error}`);
  assert.equal(plan.value.ratio, 92 / 115);
  assert.equal(clips.get('c4')?.sourceBpm, undefined, 'an untagged audio clip gets no tempo from the project');
  // The beat-matched clip reopens at 124 with its library entry, so SYNC to a
  // new tempo stretches it from 124; with neither it had no tempo and SYNC
  // skipped it.
  const a4 = clips.get('c4') as AudioClip;
  assert.equal(a4.bpm, 124);
  assert.equal(a4.libraryEntryId, 'lib-7');
  assert.deepEqual(beatMatchPlan([{ id: a4.id, bpm: a4.bpm ?? null }], 128).map((s) => s.bpm), [128]);
  assert.equal(a3.bpm, undefined);
  assert.equal(a3.libraryEntryId, undefined);
  // EDIT's instrument sync re-renders a roll clip whose effective program is not
  // the one its audio holds. After a reopen none of them is stale.
  for (const c of st().clips.filter((x) => x.sourceKind === 'piano-roll')) {
    const effective = c.instrumentProgram ?? tracks.get(c.trackId)?.instrumentProgram;
    assert.equal(effective, c.renderedProgram, `${c.id} would be rendered again on open`);
  }
}

// ── A file written before these fields opens as it always did ────────────────
{
  const legacy: TasmoProjectLoaded = {
    project_name: 'Old',
    tempo: 110,
    sample_rate: 48000,
    tracks: [
      {
        id: 'o1',
        name: 'Piano',
        type: 'audio',
        clips: [
          {
            id: 'oc1',
            name: 'riff',
            clip_type: 'midi',
            audio_file: 'audio/oc1.wav',
            midi_notes: [{ note: 60, step: 0, length: 2, velocity: 90 }],
          },
        ],
      },
    ],
  };
  await openWithFiles(legacy, [{ name: 'oc1.wav', blob: blob() }]);
  const [t] = st().tracks;
  assert.equal(t.instrumentProgram, undefined);
  assert.equal(t.parentTrackId, undefined);
  assert.equal(t.isFolder, undefined);
  const [c] = st().clips;
  assert.equal(c.sourceKind, 'piano-roll');
  assert.equal(c.sourceBpm, 110, 'a clip with no tempo of its own takes the project tempo');
  assert.equal(c.instrumentProgram, undefined);
  assert.equal(c.renderedProgram, undefined);
  assert.deepEqual(withoutIds(c.sourcePianoRoll).map((n) => [n.note, n.step, n.length]), [[60, 0, 2]]);
}

// ── A folder link the file cannot keep is cut, not fatal ─────────────────────
{
  const tree = tasmoTrackTree([
    track('a', { isFolder: true, parentTrackId: 'b' }),
    track('b', { isFolder: true, parentTrackId: 'a' }),
    track('c', { parentTrackId: 'gone' }),
    track('d', { parentTrackId: 'c' }),
    track('e', { parentTrackId: 'a' }),
    track('p', { instrumentProgram: 300 as number }),
  ]);
  const parents = Object.fromEntries(tree.map((t) => [t.id, t.parentTrackId ?? null]));
  // The loop is cut at one link; the rest of the tree stays.
  assert.equal([parents.a, parents.b].filter((p) => p === null).length, 1);
  assert.equal(parents.c, null, 'a parent that is not in the project');
  assert.equal(parents.d, null, 'a parent that is not a folder');
  assert.equal(parents.e, 'a', 'a good link is kept');
  // The LOG names what was wrong with each cut link.
  const warned = useLogStore.getState().entries.filter((e) => e.level === 'warn').map((e) => e.msg);
  assert.ok(warned.includes('Track "c" names a folder that is not in this project; placed at the root'), warned.join('\n'));
  assert.ok(warned.includes('Track "d" sits under "c", a track that is not a folder; placed at the root'), warned.join('\n'));
  // Nothing to cut: the same array.
  const clean = [track('f', { isFolder: true }), track('g', { parentTrackId: 'f' })];
  assert.equal(tasmoTrackTree(clean), clean);

  // Through the real reader: a program outside 0-127 names no instrument.
  await openWithFiles(
    {
      project_name: 'Hand-edited',
      tempo: 120,
      sample_rate: 48000,
      tracks: [
        { id: 'h1', name: 'x', type: 'audio', clips: [], instrument_program: 300, parent_track_id: 'h1' },
        { id: 'h2', name: 'y', type: 'audio', clips: [], instrument_program: 12.5 },
      ],
    },
    [],
  );
  assert.equal(st().tracks[0].instrumentProgram, undefined);
  assert.equal(st().tracks[0].parentTrackId, undefined, 'a track cannot sit inside itself');
  assert.equal(st().tracks[1].instrumentProgram, undefined);
}

// ── Each note stored once, and every note's fields kept ──────────────────────
{
  const expr = { pressure: 0.25, timbre: 0.75, pitchBend: -0.5 };
  // Lane A only, no bend: the roll notes ARE the played notes. A triplet
  // sixteenth (2/3 of a step) and a note on channel 3 with expression.
  const plain: PianoNote[] = [note('p0', 60, 0, 2 / 3), note('p1', 64, 2 / 3, 2 / 3, { channel: 3, expr }), note('p2', 67, 4, 4)];
  // Lane B loops every 4 steps across 16: the played notes are its repeats.
  const lanes = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 4 }];
  const looped: PianoNote[] = [note('l0', 36, 0, 1, { lane: 1, channel: 10 }), note('l1', 48, 8, 2)];
  const loopedPlayed: PianoNote[] = [
    note('q0', 36, 0, 1, { channel: 10 }),
    note('q1', 36, 4, 1, { channel: 10 }),
    note('q2', 48, 8, 2),
    note('q3', 36, 8, 1, { channel: 10 }),
    note('q4', 36, 12, 1, { channel: 10 }),
  ];
  // EDIT's note tools changed a played note: the roll notes no longer rebuild it.
  const editedPlayed = [note('e0', 60, 0, 1, { velocity: 30 })];
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('n1'), track('n2'), track('n3')],
    clips: [
      rollClip('plain', 'n1', { sourcePianoRoll: plain, sourceRollNotes: plain }),
      rollClip('looped', 'n2', { sourcePianoRoll: loopedPlayed, sourceRollNotes: looped, sourceLanes: lanes }),
      rollClip('edited', 'n3', { sourcePianoRoll: editedPlayed, sourceRollNotes: [note('r0', 60, 0, 1)] }),
    ],
  });
  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);
  const saved = new Map(project.tracks.map((t) => [t.clips[0].id, t.clips[0]]));

  // Plain: stored once as midi_notes, the list every build reads, so an older
  // build still opens it as a roll clip. Its audio is embedded for any reader.
  assert.equal(saved.get('plain')?.midi_notes?.length, 3);
  assert.equal(saved.get('plain')?.roll_notes, undefined);
  // Looped: the roll notes with their lane, and the repeats written out as
  // midi_notes, so a build that predates roll_notes opens it as a MIDI clip.
  assert.equal(saved.get('looped')?.roll_notes?.length, 2);
  assert.equal(saved.get('looped')?.midi_notes?.length, 5);
  // Edited apart: both, so the edit is not lost.
  assert.equal(saved.get('edited')?.midi_notes?.length, 1);
  assert.equal(saved.get('edited')?.roll_notes?.length, 1);
  for (const c of saved.values()) assert.ok(c.audio_file, `${c.id} embeds its audio`);

  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  const clips = new Map(st().clips.map((c) => [c.id, c]));

  const p = clips.get('plain');
  assert.deepEqual(withoutIds(p?.sourcePianoRoll), withoutIds(plain), 'lengths under a step, channel and expression all reload');
  // Opened in the roll: the triplet keeps 2/3 of a step (160 ticks), not a whole step.
  const [, rollNotes] = clipRollLoad(p as AudioClip);
  usePianoRollStore.getState().loadFromClip(...clipRollLoad(p as AudioClip));
  assert.deepEqual(withoutIds(rollNotes), withoutIds(plain));
  assert.deepEqual(usePianoRollStore.getState().notes.map((n) => n.ticks), [160, 160, 960]);
  assert.deepEqual(usePianoRollStore.getState().notes[1].expr, expr);
  assert.equal(usePianoRollStore.getState().notes[1].channel, 3);

  const l = clips.get('looped');
  assert.equal(l?.sourceKind, 'piano-roll');
  const sortKey = (n: Omit<PianoNote, 'id'>) => `${n.step}|${n.note}`;
  // Each rebuilt note with the tick it came back with: a repeat carrying the
  // first cycle's tick would open in the roll at the wrong place.
  assert.deepEqual(
    withoutIds(l?.sourcePianoRoll).sort((a, b) => sortKey(a).localeCompare(sortKey(b))),
    withoutIds(loopedPlayed).sort((a, b) => sortKey(a).localeCompare(sortKey(b))),
    'the repeats come back',
  );
  for (const n of l?.sourcePianoRoll ?? []) assert.equal(n.tick, tickOfStep(n.step), `the repeat at step ${n.step} keeps its own tick`);
  assert.deepEqual(withoutIds(l?.sourceRollNotes), withoutIds(looped));

  const e = clips.get('edited');
  assert.deepEqual(withoutIds(e?.sourcePianoRoll), withoutIds(editedPlayed));
  assert.deepEqual(withoutIds(e?.sourceRollNotes), [withoutIds([note('r0', 60, 0, 1)])[0]]);
}

// ── A build that predates roll_notes opens a looping lane and a lane bend as MIDI ──
{
  // A build before roll_notes reads only midi_notes (8039b45's buildClip: a
  // clip with none opens as an audio clip, its bounce). A roll clip whose
  // played notes were its roll notes unrolled, or whose lane bends, was saved
  // with roll_notes alone, so that build opened it as audio with no notes.
  const lanes = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 4 }];
  const loopRoll = [note('l0', 36, 0, 1, { lane: 1 }), note('l1', 60, 8, 2)];
  const loopPlayed = [note('q0', 36, 0, 1), note('q1', 36, 4, 1), note('q2', 60, 8, 2), note('q3', 36, 8, 1), note('q4', 36, 12, 1)];
  const bendNotes = [note('b0', 64, 0, 4), note('b1', 67, 4, 4)];
  const bend = [{ lane: 0, range: 2, points: [{ id: 'x', step: 0, value: 0, shape: 'linear' as const }, { id: 'y', step: 4, value: 1, shape: 'linear' as const }] }];
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('o1'), track('o2')],
    clips: [
      rollClip('loop', 'o1', { sourcePianoRoll: loopPlayed, sourceRollNotes: loopRoll, sourceLanes: lanes }),
      rollClip('bend', 'o2', { sourcePianoRoll: bendNotes, sourceRollNotes: bendNotes, sourceBends: bend }),
    ],
  });
  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);
  // What that build reads of each clip: every key it knew, none of the roll's own.
  const older: TasmoProjectLoaded = {
    ...project,
    tracks: project.tracks.map((t) => ({
      ...t,
      clips: t.clips.map(({ roll_notes: _r, roll_bends: _b, lanes: _l, total_steps: _s, meter_map: _m, pickup_steps: _p, ...c }) => c),
    })),
  };
  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(older, files);
  const byId = new Map(st().clips.map((c) => [c.id, c]));
  const at = (c: AudioClip | undefined) => (c?.sourcePianoRoll ?? []).map((n) => [n.note, n.step, n.length]).sort((a, b) => a[1] - b[1] || a[0] - b[0]);
  assert.equal(byId.get('loop')?.sourceKind, 'piano-roll', 'the looping lane opens as a MIDI clip');
  assert.deepEqual(at(byId.get('loop')), [[36, 0, 1], [36, 4, 1], [36, 8, 1], [60, 8, 2], [36, 12, 1]], 'with every repeat of the lane');
  assert.equal(byId.get('bend')?.sourceKind, 'piano-roll', 'the bent lane opens as a MIDI clip');
  assert.deepEqual(at(byId.get('bend')), [[64, 0, 4], [67, 4, 4]]);

  // This build still opens the roll on its own notes, lanes and bend.
  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  const loop = st().clips.find((c) => c.id === 'loop');
  assert.deepEqual(withoutIds(loop?.sourceRollNotes), withoutIds(loopRoll));
  assert.deepEqual(st().clips.find((c) => c.id === 'bend')?.sourceBends?.[0]?.points.map((p) => p.value), [0, 1]);
}

// ── 100,000 notes: the save goes out, and every note comes back ──────────────
{
  const N = 100_000;
  const big: PianoNote[] = [];
  for (let i = 0; i < N; i += 1) {
    big.push(note(`b${i}`, 36 + (i % 60), i / 4, 1 / 4, i % 7 === 0 ? { channel: 1 + (i % 16), expr: { pressure: (i % 10) / 10 } } : {}));
  }
  const total = Math.ceil(N / 4 / 16) * 16;
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('big', { instrumentProgram: 48 })],
    clips: [rollClip('bigclip', 'big', { sourcePianoRoll: big, sourceRollNotes: big, sourceTotalSteps: total, renderedProgram: 48, sourceBpm: 120 })],
  });
  const { form, files } = await saveThroughTheWire();
  const part = form.get('project');
  assert.ok(part instanceof Blob);
  // Past the 1 MB the backend holds a text part to, so only a file part gets through.
  assert.ok((part as Blob).size > 1024 * 1024, `the payload is ${(part as Blob).size} bytes`);
  const project = await projectFrom(form);
  const clip = project.tracks[0].clips[0];
  assert.equal((clip.midi_notes ?? clip.roll_notes ?? []).length, N);
  assert.ok(!(clip.midi_notes && clip.roll_notes), 'the notes are in the file once');

  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  const back = st().clips[0];
  assert.equal(back.sourcePianoRoll?.length, N, 'all 100,000 notes reload');
  assert.deepEqual(withoutIds(back.sourcePianoRoll?.slice(0, 50)), withoutIds(big.slice(0, 50)));
  assert.deepEqual(withoutIds(back.sourcePianoRoll?.slice(N - 50)), withoutIds(big.slice(N - 50)));
  assert.equal(back.sourcePianoRoll?.filter((n) => n.channel !== undefined).length, big.filter((n) => n.channel !== undefined).length);
  assert.equal(back.renderedProgram, 48);
  assert.equal(st().tracks[0].instrumentProgram, 48);
}

// ── PERFORM opens the same save: roll-only clips, own tempo, sub-step lengths ─
{
  // Lane B loops every 4 steps across 16 at 90 BPM; both notes are triplet
  // sixteenths, 2/3 of a step. The file stores the two roll notes and the five
  // notes they play.
  const lanes = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 4 }];
  const T = 2 / 3;
  const roll: PianoNote[] = [note('g0', 60, 1, T), note('g1', 38, 0, T, { lane: 1 })];
  const played: PianoNote[] = [
    note('h0', 38, 0, T),
    note('h1', 60, 1, T),
    note('h2', 38, 4, T),
    note('h3', 38, 8, T),
    note('h4', 38, 12, T),
  ];
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('g')],
    clips: [rollClip('grid', 'g', { sourcePianoRoll: played, sourceRollNotes: roll, sourceLanes: lanes, sourceBpm: 90 })],
  });
  const { form } = await saveThroughTheWire();
  const project = await projectFrom(form);
  const saved = project.tracks[0].clips[0];
  assert.equal(saved.midi_notes?.length, 5, 'the played notes are in the file');
  assert.equal(saved.roll_notes?.length, 2);

  const grid = tasmoLoadedToDawProject(project).tracks[0].clips[0];
  assert.equal(grid.file_path, null, 'PERFORM opens the clip as MIDI, not as its bounce');
  // Steps are sixteenths at the clip's own 90 BPM, not the project's 120.
  const stepSec = 60 / 90 / 4;
  // The grid clip's notes, in the seconds shape tasmoLoadedToDawProject writes.
  const gridNotes = (grid.midi_notes ?? []) as Array<{ pitch: number; start: number; duration: number }>;
  const got = gridNotes.map((n) => [n.pitch, n.start, n.duration]).sort((a, b) => a[1] - b[1] || a[0] - b[0]);
  const want = played.map((n) => [n.note, n.step * stepSec, T * stepSec]);
  assert.equal(got.length, want.length, 'every repeat of the looped lane is in the grid clip');
  got.forEach((g, i) => {
    assert.equal(g[0], want[i][0]);
    assert.ok(Math.abs(g[1] - want[i][1]) < 1e-9, `note ${i} starts at ${want[i][1]}s, got ${g[1]}s`);
    assert.ok(Math.abs(g[2] - want[i][2]) < 1e-9, `note ${i} lasts 2/3 of a step, got ${g[2]}s`);
  });
}

// ── A symphony-sized part: saved, reopened, then edited by EDIT's note tools ─
{
  // Past the ~125,000 arguments `Math.max(...notes)` can take.
  const N = 200_000;
  const huge: PianoNote[] = [];
  for (let i = 0; i < N; i += 1) huge.push(note(`s${i}`, 36 + (i % 60), i / 4, 1 / 4));
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('sym')],
    clips: [rollClip('sym', 'sym', { sourcePianoRoll: huge, sourceRollNotes: huge, sourceTotalSteps: N / 4, renderedProgram: 0, sourceBpm: 120 })],
  });
  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);
  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  assert.equal(st().clips[0].sourcePianoRoll?.length, N);

  // set_clip_instrument re-renders through commitNotes, which measured the
  // clip with a spread over every note and threw a RangeError.
  const renders: number[] = [];
  const render = async (_notes: readonly unknown[], _bpm: number, totalSteps: number) => {
    renders.push(totalSteps);
    return { blob: blob(), duration: 1 };
  };
  const r = await tools.setClipInstrument({ clip_id: 'sym', program: 48, render });
  assert.ok(r.ok, `the note tool runs on a 200,000-note part: ${r.ok ? '' : r.error}`);
  assert.equal(st().clips[0].instrumentProgram, 48);
  assert.equal(st().clips[0].sourceTotalSteps, N / 4);
  assert.equal(renders.at(-1), N / 4);
  // The render fallback for a clip with no grid length of its own.
  await bounceMidiClip({ ...st().clips[0], sourceTotalSteps: undefined }, { render });
  assert.equal(renders.at(-1), N / 4, 'the render fallback measures the clip without a spread');
  assert.equal(noteEndStep([], 16), 16);
}

// ── A drum track reopens as a drum track, on its kit ─────────────────────────
// The drum key (setTrackPercussion) puts a track on the drum channel, the
// track's program becomes its kit, and its clip is rendered on that kit. The
// file wrote neither flag, so the reopened track was melodic: live playback put
// the kit's program on a melodic channel and the clip's bounce read as stale.
{
  const hits: PianoNote[] = [note('k0', 36, 0, 1), note('k1', 38, 4, 1), note('k2', 42, 2, 0.5)];
  useEditorStore.setState({ bpm: 120, tracks: [track('d1', { name: 'Drums' })], clips: [rollClip('kit', 'd1', { sourcePianoRoll: hits })] });
  st().setTrackPercussion('d1', true);
  st().updateTrack('d1', { instrumentProgram: 25 });
  const voiceBefore = clipVoice(st().clips[0], st().tracks[0], { useSoundfont: true, activeProgram: 0 });
  assert.deepEqual(voiceBefore, { program: 25, percussion: true });
  useEditorStore.setState({ clips: st().clips.map((c) => ({ ...c, ...renderedVoiceFields(voiceBefore) })) });

  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);
  assert.equal(project.tracks[0].is_percussion, true, 'the drum flag is written');
  assert.equal(project.tracks[0].instrument_program, 25, 'and the kit');
  assert.equal(project.tracks[0].clips[0].rendered_percussion, true, "the clip's render is marked as a kit render");

  useEditorStore.setState({ bpm: 100, tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  const drums = st().tracks.find((t) => t.id === 'd1');
  const kit = st().clips.find((c) => c.id === 'kit');
  assert.equal(drums?.isPercussion, true, 'the track reopens as a drum track');
  assert.equal(drums?.instrumentProgram, 25);
  assert.ok(kit);
  const global = { useSoundfont: true, activeProgram: 0 };
  assert.deepEqual(clipVoice(kit, drums, global), { program: 25, percussion: true }, 'the clip plays its kit on the drum channel');
  assert.equal(clipRenderIsStale(kit, drums, global), false, 'the reopened bounce is not rendered again');

  // A file written before the flag reads every track as melodic, as it did.
  const { is_percussion: _flag, ...older } = project.tracks[0];
  const olderClips = older.clips.map(({ rendered_percussion: _r, ...c }) => c);
  useEditorStore.setState({ bpm: 100, tracks: [track('other')], clips: [] });
  await openWithFiles({ ...project, tracks: [{ ...older, clips: olderClips }] }, files);
  assert.equal(st().tracks.find((t) => t.id === 'd1')?.isPercussion, undefined, 'an older file opens the track melodic');
}

// ── The payload the backend validates is the one the app really sends ────────
// The save runs through projectStore.save, the SAVE button's own action. The
// parsed project part and the file names are compared with
// tests/fixtures/tasmo_session_from_frontend.json, which
// tests/test_tasmo_instruments_and_size.py posts to /save-session and reads
// back through the Track and Clip models. A field this writer renames, or
// writes in a shape the models refuse, fails one side or the other. After an
// intended change to the payload, rewrite the fixture with
// WRITE_TASMO_FIXTURE=1 npx tsx src/lib/projectImport.instruments.test.ts
{
  const fixturePath = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'tests', 'fixtures', 'tasmo_session_from_frontend.json');
  const lanes = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 4 }];
  const plain: PianoNote[] = [note('p0', 60, 0, 2 / 3), note('p1', 64, 2 / 3, 2 / 3, { channel: 3, expr: { pressure: 0.25, timbre: 0.75, pitchBend: -0.5 } })];
  useEditorStore.setState({
    bpm: 120,
    tracks: [
      track('f1', { isFolder: true, collapsed: true, name: 'Strings' }),
      track('t1', { parentTrackId: 'f1', instrumentProgram: 40 }),
      // A program the store should never hold: written as none, so the save
      // is not refused over it.
      track('t2', { instrumentProgram: 40.5 as number }),
      track('t3'),
      track('d1', { isPercussion: true, instrumentProgram: 25 }),
    ],
    clips: [
      rollClip('plain', 't1', {
        sourcePianoRoll: plain,
        sourceRollNotes: plain,
        instrumentProgram: 42,
        renderedProgram: 42,
        sourceBpm: 90,
        // A tempo change, a ramp and a fermata: the clip's tempo map goes out as `tempo_map`.
        sourceTempoMap: [
          { beat: 0, bpm: 90, curve: 'step' },
          { beat: 2, bpm: 90, curve: 'linear' },
          { beat: 4, bpm: 60, curve: 'step' },
          { beat: 4, bpm: 60, fermata: { beats: 1, stretch: 2 } },
        ],
        // The ruler's markers go out as `roll_markers`: a movement, a FORM section and the user's own.
        sourceMarkers: [
          { id: 'mk-1', tick: 0, name: 'I. Allegro', kind: 'movement' },
          { id: 'form-0', tick: 960, name: 'Intro', kind: 'section', origin: 'form' },
          { id: 'mk-2', tick: 3840, name: 'B', kind: 'section' },
        ],
      }),
      rollClip('looped', 't2', {
        sourcePianoRoll: [note('q0', 36, 0, 1), note('q1', 36, 4, 1), note('q2', 36, 8, 1), note('q3', 36, 12, 1)],
        sourceRollNotes: [note('l0', 36, 0, 1, { lane: 1 })],
        sourceLanes: lanes,
        renderedProgram: 7.5 as number,
        sourceBpm: 120,
      }),
      rollClip('edited', 't2', { sourcePianoRoll: [note('e0', 60, 0, 1, { velocity: 30 })], sourceRollNotes: [note('r0', 60, 0, 1)], startSec: 2 }),
      audioClip('tagged', 't3', { sourceBpm: 92, bpm: 124, libraryEntryId: 'lib-7' }),
      audioClip('untagged', 't3', { startSec: 1 }),
      rollClip('kit', 'd1', { sourcePianoRoll: [note('k0', 36, 0, 1)], renderedProgram: 25, renderedPercussion: true }),
    ],
  });
  useProjectStore.setState({ projectName: 'Fixture', savePath: 'S.tasmo', pendingTracks: [] });
  let posted: FormData | null = null;
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: RequestInfo | URL, init?: RequestInit) => {
    if (String(url).includes('/api/project/save-session')) {
      posted = init?.body as FormData;
      return new Response(JSON.stringify({ status: 'saved', path: 'S.tasmo', manifest: { audio_mode: 'embedded' } }), { status: 200 });
    }
    return new Response('[]', { status: 200 });
  }) as typeof fetch;
  try {
    await useProjectStore.getState().save();
  } finally {
    globalThis.fetch = realFetch;
  }
  assert.equal(useProjectStore.getState().error, null, 'the save went through');
  assert.ok(posted, 'the SAVE action posted to /save-session');
  const form = posted as FormData;
  const payload = {
    project: await projectFrom(form),
    files: form.getAll('files').map((f) => (f as File).name),
  };
  const byTrack = new Map(payload.project.tracks.map((t) => [t.id, t]));
  assert.equal(byTrack.get('t2')?.instrument_program, null, 'a program outside 0-127 is written as none');
  assert.equal(byTrack.get('t2')?.clips.find((c) => c.id === 'looped')?.rendered_program, null);
  if (process.env.WRITE_TASMO_FIXTURE) {
    writeFileSync(fixturePath, `${JSON.stringify(payload, null, 2)}\n`);
  }
  assert.deepEqual(
    payload,
    JSON.parse(readFileSync(fixturePath, 'utf8')),
    'the payload changed: check tests/test_tasmo_instruments_and_size.py, then rewrite the fixture',
  );
}

console.log('projectImport.instruments: ok');
