// A saved project reopens with its track and bus inserts sounding as they were
// dialled in: a VST3 insert keeps the state its window captured and the host
// that captured it, in EDIT and in PERFORM.
//
// The app's order: the EDIT store holds the session, captureEditorSession
// builds the payload, the JSON comes back as the backend returns it, and
// loadProjectIntoEditor opens it; PERFORM opens the same JSON through
// tasmoLoadedToDawProject and hosts each device as dawDeviceToChainEntry
// builds it.
//
//   cd frontend && npx tsx src/lib/projectSave.inserts.test.ts
import assert from 'node:assert/strict';
import { captureEditorSession, loadProjectIntoEditor } from './projectImport.ts';
import type { TasmoProjectLoaded } from './projectClient.ts';
import { dawDeviceToChainEntry, dawDeviceToEffectNode } from './dawEffectMap.ts';
import { tasmoLoadedToDawProject } from './tasmoToSession.ts';
import { useEditorStore, type EditorBus, type EditorTrack } from '../state/editorStore.ts';
import { addBus, emptyGraph, ensureTrackNode } from '../state/routingGraph.ts';
import type { ChainEntry } from '../state/effectChainStore.ts';

class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, getChannelData: () => new Float32Array(64).fill(0.5) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#fff',
  ...extra,
});
const st = () => useEditorStore.getState();

/** The payload a save sends, read back the way the backend returns it. */
function saveThenReload(name: string): TasmoProjectLoaded {
  const session = captureEditorSession();
  return JSON.parse(
    JSON.stringify({ project_name: name, tempo: session.bpm, sample_rate: 48000, tracks: session.tracks, buses: session.buses }),
  ) as TasmoProjectLoaded;
}

const vstEntry = (id: string, rawState?: string, host?: 'thedaw' | 'pedalboard'): ChainEntry => ({
  id,
  effect: 'vst3',
  params: { 3: 0.25 },
  enabled: true,
  vst: {
    plugin_path: 'C:/VST3/FabFilter Pro-Q 3.vst3',
    plugin_name: 'Pro-Q 3',
    ...(rawState ? { raw_state: rawState } : {}),
    ...(host ? { state_host: host } : {}),
  },
  label: 'Pro-Q 3',
});

// ── A VST3 insert on a track and on a bus keeps its dialled-in state ─────────
{
  const buses: EditorBus[] = [
    { id: 'bus-1', name: 'Drum Bus', fxChain: [vstEntry('fx-bus', 'QlVTU1RBVEU=', 'pedalboard')], volume: 0.9, mute: false },
  ];
  let g = emptyGraph();
  g = ensureTrackNode(g, 'vox', 'vox');
  g = addBus(g, 'bus-1', 'Drum Bus');
  useEditorStore.setState({
    bpm: 110,
    tracks: [track('vox', { fxChain: [vstEntry('fx-vox', 'VFJBQ0tTVEFURQ==', 'thedaw'), vstEntry('fx-fresh')] })],
    clips: [],
    buses,
    routing: g,
  });

  const file = saveThenReload('Inserts');
  const node = file.tracks[0].effect_chain?.[0];
  assert.equal(node?.vst_state?.raw_state, 'VFJBQ0tTVEFURQ==', 'the payload carries the track insert state');
  assert.equal(node?.vst_state?.state_host, 'thedaw', 'and the host that captured it');
  assert.equal(file.tracks[0].effect_chain?.[1].vst_state?.raw_state, undefined, 'a plugin never opened writes no state');
  assert.equal(file.buses?.[0].effect_chain?.[0].vst_state?.raw_state, 'QlVTU1RBVEU=', 'the payload carries the bus insert state');

  useEditorStore.setState({ tracks: [track('other')], clips: [], buses: [], routing: emptyGraph() });
  await loadProjectIntoEditor(file);

  const vox = st().tracks.find((t) => t.id === 'vox');
  assert.deepEqual(
    vox?.fxChain?.[0].vst,
    { plugin_path: 'C:/VST3/FabFilter Pro-Q 3.vst3', plugin_name: 'Pro-Q 3', raw_state: 'VFJBQ0tTVEFURQ==', state_host: 'thedaw' },
    'the track insert reopens with its state and host',
  );
  assert.equal(vox?.fxChain?.[0].id, 'fx-vox', 'under the id automation and controllers key off');
  assert.deepEqual(vox?.fxChain?.[1].vst, { plugin_path: 'C:/VST3/FabFilter Pro-Q 3.vst3', plugin_name: 'Pro-Q 3' });
  const bus = st().buses.find((b) => b.id === 'bus-1');
  assert.equal(bus?.fxChain[0].vst?.raw_state, 'QlVTU1RBVEU=', 'the bus insert reopens with its state');
  assert.equal(bus?.fxChain[0].vst?.state_host, 'pedalboard');

  // PERFORM opens the same file and hosts the insert at that state.
  const perform = tasmoLoadedToDawProject(file);
  const device = perform.tracks[0].devices[0];
  assert.deepEqual(
    dawDeviceToChainEntry(device, 'perform-0-0').vst,
    { plugin_path: 'C:/VST3/FabFilter Pro-Q 3.vst3', plugin_name: 'Pro-Q 3', raw_state: 'VFJBQ0tTVEFURQ==', state_host: 'thedaw' },
    'the PERFORM chain entry carries the saved state and its host',
  );
  assert.deepEqual(
    dawDeviceToChainEntry(perform.tracks[0].devices[1], 'perform-0-1').vst,
    { plugin_path: 'C:/VST3/FabFilter Pro-Q 3.vst3', plugin_name: 'Pro-Q 3' },
    'a plugin never opened is hosted at its defaults',
  );
}

// ── A file written before insert state was saved, and a hand-edited host ─────
{
  await loadProjectIntoEditor({
    project_name: 'Legacy',
    tempo: 100,
    sample_rate: 48000,
    tracks: [
      {
        id: 'gtr',
        name: 'Gtr',
        type: 'audio',
        clips: [],
        effect_chain: [
          { id: 'fx-a', node_type: 'vst3', effect_name: 'Amp', vst_state: { plugin_path: 'C:/Amp.vst3', plugin_name: 'Amp' } },
          {
            id: 'fx-b',
            node_type: 'vst3',
            effect_name: 'Amp',
            vst_state: { plugin_path: 'C:/Amp.vst3', plugin_name: 'Amp', raw_state: 'QUJD', state_host: 'somewhere-else' },
          },
        ],
      },
    ],
  });
  const chain = st().tracks[0].fxChain ?? [];
  assert.deepEqual(chain[0].vst, { plugin_path: 'C:/Amp.vst3', plugin_name: 'Amp' }, 'an old insert opens at its defaults');
  assert.deepEqual(
    chain[1].vst,
    { plugin_path: 'C:/Amp.vst3', plugin_name: 'Amp', raw_state: 'QUJD' },
    'a host the app does not know is left out, so the state reads as the default host',
  );
}

// ── A DAW import's own preset chunk is not taken for theDAW's state ──────────
{
  const node = dawDeviceToEffectNode({
    name: 'Pro-Q 3',
    plugin_type: 'vst3',
    plugin_path: 'C:/VST3/Pro-Q 3.vst3',
    state: 'QUJMRVRPTkNIVU5L',
  });
  assert.equal(node.vst_state?.raw_state, undefined, 'neither host reads a source DAW chunk');
}

// An Audio Unit insert opens in PERFORM as the plugin it is, never matched to
// a rack effect by its name.
{
  const perform = tasmoLoadedToDawProject({
    project_name: 'AU',
    tempo: 120,
    sample_rate: 48000,
    tracks: [
      {
        id: 't',
        name: 'T',
        type: 'audio',
        clips: [],
        effect_chain: [
          {
            id: 'fx-au',
            node_type: 'audiounit',
            effect_name: 'ValhallaVintageVerb',
            vst_state: { plugin_path: '/Library/Audio/Plug-Ins/Components/ValhallaVintageVerb.component', plugin_name: 'ValhallaVintageVerb', raw_state: 'QVU=' },
          },
        ],
      },
    ],
  });
  const entry = dawDeviceToChainEntry(perform.tracks[0].devices[0], 'perform-0-0');
  assert.equal(entry.effect, 'vst3', 'hosted, not the reverb rack effect');
  assert.equal(entry.vst?.raw_state, 'QVU=');
}

console.log('projectSave.inserts: ok');
