// A saved project reopens with every routing edge the mixer can build: a bus
// keeps its sends, and a track or a bus keeps the sidechain keys it feeds.
//
// The app's order: the EDIT store holds the session, captureEditorSession
// builds the payload, the JSON comes back as the backend returns it, and
// loadProjectIntoEditor opens it.
//
//   cd frontend && npx tsx src/lib/projectSave.routing.test.ts
import assert from 'node:assert/strict';
import { captureEditorSession, loadProjectIntoEditor, tasmoToRouting } from './projectImport.ts';
import type { TasmoProjectLoaded } from './projectClient.ts';
import { useEditorStore, type EditorBus, type EditorTrack } from '../state/editorStore.ts';
import {
  addBus,
  addSend,
  CONN_SIDECHAIN,
  emptyGraph,
  ensureTrackNode,
  MASTER_ID,
  outputOf,
  sendsFrom,
  setOutput,
  setSidechain,
  sidechainsInto,
  validateGraph,
  type RoutingGraph,
} from '../state/routingGraph.ts';

class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, getChannelData: () => new Float32Array(64).fill(0.5) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#fff',
  ...extra,
});
const st = () => useEditorStore.getState();
const ok = (r: { ok: boolean; graph?: RoutingGraph; reason?: string }): RoutingGraph => {
  assert.equal(r.ok, true, `mutator refused: ${r.reason}`);
  return r.graph as RoutingGraph;
};

/** The payload a save sends, read back the way the backend returns it. */
function saveThenReload(name: string): TasmoProjectLoaded {
  const session = captureEditorSession();
  return JSON.parse(
    JSON.stringify({ project_name: name, tempo: session.bpm, sample_rate: 48000, tracks: session.tracks, buses: session.buses }),
  ) as TasmoProjectLoaded;
}

// ── Bus sends and sidechain keys survive save -> open ────────────────────────
{
  // kick -> drums bus; drums sends into the verb bus and keys the bass
  // compressor; kick keys the verb bus gate.
  let g = emptyGraph();
  g = ensureTrackNode(g, 'kick', 'Kick');
  g = ensureTrackNode(g, 'bass', 'Bass');
  g = addBus(g, 'drums', 'Drums');
  g = addBus(g, 'verb', 'Verb');
  g = ok(setOutput(g, 'kick', 'drums'));
  g = ok(addSend(g, 'drums', 'verb', 0.3));
  g = ok(setSidechain(g, 'drums', 'bass', 'fx-bass-comp'));
  g = ok(setSidechain(g, 'kick', 'verb', 'fx-verb-gate'));
  const buses: EditorBus[] = [
    { id: 'drums', name: 'Drums', fxChain: [], volume: 1, mute: false },
    { id: 'verb', name: 'Verb', fxChain: [{ id: 'fx-verb-gate', effect: 'gater', params: {}, enabled: true }], volume: 0.7, mute: false },
  ];
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('kick'), track('bass', { fxChain: [{ id: 'fx-bass-comp', effect: 'compressor', params: {}, enabled: true }] })],
    clips: [],
    buses,
    routing: g,
  });

  const file = saveThenReload('Routing');
  const drums = file.buses?.find((b) => b.id === 'drums');
  assert.deepEqual(drums?.send_amounts, { verb: 0.3 }, 'the bus writes its send');
  assert.deepEqual(drums?.sidechain_keys, [{ target: 'bass', entry_id: 'fx-bass-comp' }], 'and the key it feeds');
  const kick = file.tracks.find((t) => t.id === 'kick');
  assert.deepEqual(kick?.sidechain_keys, [{ target: 'verb', entry_id: 'fx-verb-gate' }], 'a track writes the key it feeds');
  assert.equal(file.tracks.find((t) => t.id === 'bass')?.sidechain_keys, undefined, 'a track that keys nothing writes no list');

  useEditorStore.setState({ tracks: [track('other')], clips: [], buses: [], routing: emptyGraph() });
  await loadProjectIntoEditor(file);

  const r = st().routing;
  assert.equal(outputOf(r, 'kick'), 'drums');
  assert.deepEqual(sendsFrom(r, 'drums').map((e) => [e.to, e.gain]), [['verb', 0.3]], 'the bus send reopens');
  assert.deepEqual(
    sidechainsInto(r, 'bass').map((e) => [e.from, e.targetEntryId]),
    [['drums', 'fx-bass-comp']],
    'the bus keys the bass compressor again',
  );
  assert.deepEqual(
    sidechainsInto(r, 'verb').map((e) => [e.from, e.targetEntryId]),
    [['kick', 'fx-verb-gate']],
    'the kick keys the verb gate again',
  );
  assert.deepEqual(validateGraph(r), []);
}

// ── A hand-edited file: keys that name nothing, or close a loop, are dropped ─
{
  const read = tasmoToRouting(
    [
      {
        id: 't1',
        name: 'T1',
        output_routing: 'a',
        effect_chain: [{ id: 'fx-t1', node_type: 'builtin', effect_name: 'compressor' }],
        sidechain_keys: [
          { target: 'a', entry_id: 'fx-missing' },
          { target: 'ghost', entry_id: 'fx-a' },
          { target: MASTER_ID, entry_id: 'fx-a' },
          { target: '', entry_id: '' },
          { target: 'a', entry_id: 'fx-a' },
        ],
      },
    ],
    [
      {
        id: 'a',
        name: 'A',
        effect_chain: [{ id: 'fx-a', node_type: 'builtin', effect_name: 'compressor' }],
        // a -> t1 closes a loop with t1 -> a, so it is refused.
        sidechain_keys: [{ target: 't1', entry_id: 'fx-t1' }],
        send_amounts: { t1: 0.5 },
      },
    ],
  );
  const keys = read.routing.edges.filter((e) => e.connType === CONN_SIDECHAIN).map((e) => [e.from, e.to, e.targetEntryId]);
  assert.deepEqual(keys, [['t1', 'a', 'fx-a']], 'only the key naming a real entry on a real strip is kept');
  assert.deepEqual(sendsFrom(read.routing, 'a'), [], 'a bus send that closes a loop is refused');
  assert.deepEqual(validateGraph(read.routing), []);
}

console.log('projectSave.routing: ok');
