// A saved project reopens with every part on its own instrument, in its own
// folder, at its own tempo, and with every note it had.
//
// Before this, captureEditorSession wrote no track or clip instrument program,
// no rendered program, no clip tempo and no folder, so a reopened arrangement
// put every MIDI part on the global instrument, rendered them all again, played
// each clip at the project tempo and laid every track flat at the root. The
// save also sent the project JSON as a multipart TEXT field, which the backend's
// form parser holds to 1 MB: about 9,000 notes filled it and the save failed.
//
// Each block replays the app's own order: the EDIT store holds the session,
// captureEditorSession builds the payload, projectApi.saveSession posts it,
// the JSON comes back from the backend, and loadProjectIntoEditor opens it.
import assert from 'node:assert/strict';
import { captureEditorSession, loadProjectIntoEditor, tasmoTrackTree } from './projectImport.ts';
import { projectApi, type TasmoProjectInput, type TasmoProjectLoaded } from './projectClient.ts';
import { clipRollLoad } from './rollClip.ts';
import { useEditorStore, type AudioClip, type EditorTrack } from '../state/editorStore.ts';
import { tickOfStep, usePianoRollStore, type PianoNote } from '../state/pianoRollStore.ts';

// computePeaks needs an AudioContext. The fake decodes any blob to one second.
class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, getChannelData: () => new Float32Array(64).fill(0.5) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const withoutIds = (notes: readonly PianoNote[] = []) => notes.map(({ id: _id, ...n }) => n);
const blob = () => new Blob([new Uint8Array([1, 2, 3])], { type: 'audio/wav' });

const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#fff',
  ...extra,
});

const rollClip = (id: string, trackId: string, extra: Partial<AudioClip>): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: blob(),
  mimeType: 'audio/wav',
  sourceDuration: 1,
  offsetIntoSource: 0,
  durationSec: 1,
  startSec: 0,
  color: '#fff',
  peaks: new Float32Array(0),
  sourceKind: 'piano-roll',
  sourceTotalSteps: 16,
  sourceMeterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }],
  sourcePickupSteps: 0,
  sourceLanes: [{ id: 0, name: 'A', cycleSteps: null }],
  ...extra,
});

/** A note as the store holds it: ticks that agree with its steps. */
const note = (id: string, pitch: number, step: number, length: number, extra: Partial<PianoNote> = {}): PianoNote => ({
  id,
  note: pitch,
  step,
  length,
  velocity: 100,
  tick: tickOfStep(step),
  ticks: tickOfStep(length),
  ...extra,
});

/** Save the live session the way projectStore does, with the transport stubbed
 *  at fetch: returns the multipart body projectApi.saveSession really posted. */
async function saveThroughTheWire(): Promise<{ form: FormData; files: Array<{ name: string; blob: Blob }> }> {
  const session = captureEditorSession();
  const project: TasmoProjectInput = { project_name: 'Symphony', tempo: session.bpm, tracks: session.tracks, buses: session.buses };
  let posted: FormData | null = null;
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (_url: RequestInfo | URL, init?: RequestInit) => {
    posted = init?.body as FormData;
    return new Response(JSON.stringify({ status: 'saved', path: 'S.tasmo', manifest: {} }), { status: 200 });
  }) as typeof fetch;
  try {
    await projectApi.saveSession(project, 'S.tasmo', session.files);
  } finally {
    globalThis.fetch = realFetch;
  }
  assert.ok(posted, 'saveSession posted a body');
  return { form: posted as FormData, files: session.files };
}

/** The project part as the backend reads it back out of the archive: the JSON
 *  the frontend sent, then the embedded files served by name. */
async function projectFrom(form: FormData): Promise<TasmoProjectLoaded> {
  const part = form.get('project');
  // A FILE part. As a text field the backend's parser refuses it past 1 MB.
  assert.ok(part instanceof Blob, 'the project JSON goes out as a file part, not a text field');
  return JSON.parse(await (part as Blob).text()) as TasmoProjectLoaded;
}

async function openWithFiles(project: TasmoProjectLoaded, files: Array<{ name: string; blob: Blob }>): Promise<void> {
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: RequestInfo | URL) => {
    const path = decodeURIComponent(String(url).split('path=')[1] ?? '');
    const file = files.find((f) => path.endsWith(f.name));
    return file ? new Response(file.blob, { status: 200 }) : new Response('', { status: 404 });
  }) as typeof fetch;
  try {
    await loadProjectIntoEditor(project);
  } finally {
    globalThis.fetch = realFetch;
  }
}

const st = () => useEditorStore.getState();

// ── Instruments, clip tempo and folders survive save -> open ─────────────────
{
  const strings: PianoNote[] = [note('s0', 55, 0, 4), note('s1', 59, 4, 4)];
  useEditorStore.setState({
    bpm: 120,
    tracks: [
      track('f1', { isFolder: true, collapsed: true, name: 'Strings' }),
      track('t1', { parentTrackId: 'f1', instrumentProgram: 40 }),
      track('t2', { instrumentProgram: 71 }),
      track('t3'),
    ],
    clips: [
      // Its own program over its track's, rendered with it, written at 90 BPM.
      rollClip('c1', 't1', { sourcePianoRoll: strings, sourceRollNotes: strings, instrumentProgram: 42, renderedProgram: 42, sourceBpm: 90 }),
      // No program of its own: its track's (71) is what it was rendered with.
      rollClip('c2', 't2', { sourcePianoRoll: [note('w0', 72, 0, 2)], renderedProgram: 71, sourceBpm: 120 }),
      // An audio clip carries none of the MIDI fields.
      { ...rollClip('c3', 't3', {}), sourceKind: undefined, sourceTotalSteps: undefined, sourceMeterMap: undefined, sourcePickupSteps: undefined, sourceLanes: undefined },
    ],
  });
  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);

  const byTrack = new Map(project.tracks.map((t) => [t.id, t]));
  assert.equal(byTrack.get('t1')?.instrument_program, 40);
  assert.equal(byTrack.get('t1')?.parent_track_id, 'f1');
  assert.equal(byTrack.get('f1')?.is_folder, true);
  assert.equal(byTrack.get('f1')?.collapsed, true);
  assert.equal(byTrack.get('t3')?.instrument_program, null);
  const c1 = byTrack.get('t1')?.clips[0];
  assert.equal(c1?.instrument_program, 42);
  assert.equal(c1?.rendered_program, 42);
  assert.equal(c1?.source_bpm, 90);
  const c3 = byTrack.get('t3')?.clips[0];
  assert.ok(c3 && !('instrument_program' in c3) && !('source_bpm' in c3), 'an audio clip writes no MIDI fields');

  // Reopen over a different session, so nothing is left over from the save.
  useEditorStore.setState({ bpm: 100, tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);

  const tracks = new Map(st().tracks.map((t) => [t.id, t]));
  assert.equal(tracks.get('t1')?.instrumentProgram, 40, 'the track reopens on its own instrument');
  assert.equal(tracks.get('t2')?.instrumentProgram, 71);
  assert.equal(tracks.get('t3')?.instrumentProgram, undefined);
  assert.equal(tracks.get('t1')?.parentTrackId, 'f1', 'the track is back in its folder');
  assert.equal(tracks.get('f1')?.isFolder, true);
  assert.equal(tracks.get('f1')?.collapsed, true);
  // A folder is an arrangement row with no audio node, after a reopen as when made.
  assert.equal(st().routing.nodes.some((n) => n.id === 'f1'), false, 'the folder has no routing node');
  assert.equal(st().routing.nodes.some((n) => n.id === 't1'), true);

  const clips = new Map(st().clips.map((c) => [c.id, c]));
  const r1 = clips.get('c1');
  assert.equal(r1?.instrumentProgram, 42, 'the clip reopens on its own instrument');
  assert.equal(r1?.renderedProgram, 42);
  assert.equal(r1?.sourceBpm, 90, 'the clip keeps the tempo its notes were written at');
  const r2 = clips.get('c2');
  assert.equal(r2?.instrumentProgram, undefined);
  assert.equal(r2?.renderedProgram, 71);
  // EDIT's instrument sync re-renders a roll clip whose effective program is not
  // the one its audio holds. After a reopen none of them is stale.
  for (const c of st().clips.filter((x) => x.sourceKind === 'piano-roll')) {
    const effective = c.instrumentProgram ?? tracks.get(c.trackId)?.instrumentProgram;
    assert.equal(effective, c.renderedProgram, `${c.id} would be rendered again on open`);
  }
}

// ── A file written before these fields opens as it always did ────────────────
{
  const legacy: TasmoProjectLoaded = {
    project_name: 'Old',
    tempo: 110,
    sample_rate: 48000,
    tracks: [
      {
        id: 'o1',
        name: 'Piano',
        type: 'audio',
        clips: [
          {
            id: 'oc1',
            name: 'riff',
            clip_type: 'midi',
            audio_file: 'audio/oc1.wav',
            midi_notes: [{ note: 60, step: 0, length: 2, velocity: 90 }],
          },
        ],
      },
    ],
  };
  await openWithFiles(legacy, [{ name: 'oc1.wav', blob: blob() }]);
  const [t] = st().tracks;
  assert.equal(t.instrumentProgram, undefined);
  assert.equal(t.parentTrackId, undefined);
  assert.equal(t.isFolder, undefined);
  const [c] = st().clips;
  assert.equal(c.sourceKind, 'piano-roll');
  assert.equal(c.sourceBpm, 110, 'a clip with no tempo of its own takes the project tempo');
  assert.equal(c.instrumentProgram, undefined);
  assert.equal(c.renderedProgram, undefined);
  assert.deepEqual(withoutIds(c.sourcePianoRoll).map((n) => [n.note, n.step, n.length]), [[60, 0, 2]]);
}

// ── A folder link the file cannot keep is cut, not fatal ─────────────────────
{
  const tree = tasmoTrackTree([
    track('a', { isFolder: true, parentTrackId: 'b' }),
    track('b', { isFolder: true, parentTrackId: 'a' }),
    track('c', { parentTrackId: 'gone' }),
    track('d', { parentTrackId: 'c' }),
    track('e', { parentTrackId: 'a' }),
    track('p', { instrumentProgram: 300 as number }),
  ]);
  const parents = Object.fromEntries(tree.map((t) => [t.id, t.parentTrackId ?? null]));
  // The loop is cut at one link; the rest of the tree stays.
  assert.equal([parents.a, parents.b].filter((p) => p === null).length, 1);
  assert.equal(parents.c, null, 'a parent that is not in the project');
  assert.equal(parents.d, null, 'a parent that is not a folder');
  assert.equal(parents.e, 'a', 'a good link is kept');
  // Nothing to cut: the same array.
  const clean = [track('f', { isFolder: true }), track('g', { parentTrackId: 'f' })];
  assert.equal(tasmoTrackTree(clean), clean);

  // Through the real reader: a program outside 0-127 names no instrument.
  await openWithFiles(
    {
      project_name: 'Hand-edited',
      tempo: 120,
      sample_rate: 48000,
      tracks: [
        { id: 'h1', name: 'x', type: 'audio', clips: [], instrument_program: 300, parent_track_id: 'h1' },
        { id: 'h2', name: 'y', type: 'audio', clips: [], instrument_program: 12.5 },
      ],
    },
    [],
  );
  assert.equal(st().tracks[0].instrumentProgram, undefined);
  assert.equal(st().tracks[0].parentTrackId, undefined, 'a track cannot sit inside itself');
  assert.equal(st().tracks[1].instrumentProgram, undefined);
}

// ── Each note stored once, and every note's fields kept ──────────────────────
{
  const expr = { pressure: 0.25, timbre: 0.75, pitchBend: -0.5 };
  // Lane A only, no bend: the roll notes ARE the played notes. A triplet
  // sixteenth (2/3 of a step) and a note on channel 3 with expression.
  const plain: PianoNote[] = [note('p0', 60, 0, 2 / 3), note('p1', 64, 2 / 3, 2 / 3, { channel: 3, expr }), note('p2', 67, 4, 4)];
  // Lane B loops every 4 steps across 16: the played notes are its repeats.
  const lanes = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: 4 }];
  const looped: PianoNote[] = [note('l0', 36, 0, 1, { lane: 1, channel: 10 }), note('l1', 48, 8, 2)];
  const loopedPlayed: PianoNote[] = [
    note('q0', 36, 0, 1, { channel: 10 }),
    note('q1', 36, 4, 1, { channel: 10 }),
    note('q2', 48, 8, 2),
    note('q3', 36, 8, 1, { channel: 10 }),
    note('q4', 36, 12, 1, { channel: 10 }),
  ];
  // EDIT's note tools changed a played note: the roll notes no longer rebuild it.
  const editedPlayed = [note('e0', 60, 0, 1, { velocity: 30 })];
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('n1'), track('n2'), track('n3')],
    clips: [
      rollClip('plain', 'n1', { sourcePianoRoll: plain, sourceRollNotes: plain }),
      rollClip('looped', 'n2', { sourcePianoRoll: loopedPlayed, sourceRollNotes: looped, sourceLanes: lanes }),
      rollClip('edited', 'n3', { sourcePianoRoll: editedPlayed, sourceRollNotes: [note('r0', 60, 0, 1)] }),
    ],
  });
  const { form, files } = await saveThroughTheWire();
  const project = await projectFrom(form);
  const saved = new Map(project.tracks.map((t) => [t.clips[0].id, t.clips[0]]));

  // Plain: stored once as midi_notes, the list every build reads, so an older
  // build still opens it as a roll clip. Its audio is embedded for any reader.
  assert.equal(saved.get('plain')?.midi_notes?.length, 3);
  assert.equal(saved.get('plain')?.roll_notes, undefined);
  // Looped: stored once as roll_notes; the repeats are rebuilt on load.
  assert.equal(saved.get('looped')?.roll_notes?.length, 2);
  assert.equal(saved.get('looped')?.midi_notes, undefined);
  // Edited apart: both, so the edit is not lost.
  assert.equal(saved.get('edited')?.midi_notes?.length, 1);
  assert.equal(saved.get('edited')?.roll_notes?.length, 1);
  for (const c of saved.values()) assert.ok(c.audio_file, `${c.id} embeds its audio`);

  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  const clips = new Map(st().clips.map((c) => [c.id, c]));

  const p = clips.get('plain');
  assert.deepEqual(withoutIds(p?.sourcePianoRoll), withoutIds(plain), 'lengths under a step, channel and expression all reload');
  // Opened in the roll: the triplet keeps 2/3 of a step (160 ticks), not a whole step.
  const [, rollNotes] = clipRollLoad(p as AudioClip);
  usePianoRollStore.getState().loadFromClip(...clipRollLoad(p as AudioClip));
  assert.deepEqual(withoutIds(rollNotes), withoutIds(plain));
  assert.deepEqual(usePianoRollStore.getState().notes.map((n) => n.ticks), [160, 160, 960]);
  assert.deepEqual(usePianoRollStore.getState().notes[1].expr, expr);
  assert.equal(usePianoRollStore.getState().notes[1].channel, 3);

  const l = clips.get('looped');
  assert.equal(l?.sourceKind, 'piano-roll');
  const sortKey = (n: Omit<PianoNote, 'id'>) => `${n.step}|${n.note}`;
  assert.deepEqual(
    withoutIds(l?.sourcePianoRoll).map((n) => ({ ...n, tick: tickOfStep(n.step) })).sort((a, b) => sortKey(a).localeCompare(sortKey(b))),
    withoutIds(loopedPlayed).sort((a, b) => sortKey(a).localeCompare(sortKey(b))),
    'the repeats come back from the roll notes',
  );
  assert.deepEqual(withoutIds(l?.sourceRollNotes), withoutIds(looped));

  const e = clips.get('edited');
  assert.deepEqual(withoutIds(e?.sourcePianoRoll), withoutIds(editedPlayed));
  assert.deepEqual(withoutIds(e?.sourceRollNotes), [withoutIds([note('r0', 60, 0, 1)])[0]]);
}

// ── 100,000 notes: the save goes out, and every note comes back ──────────────
{
  const N = 100_000;
  const big: PianoNote[] = [];
  for (let i = 0; i < N; i += 1) {
    big.push(note(`b${i}`, 36 + (i % 60), i / 4, 1 / 4, i % 7 === 0 ? { channel: 1 + (i % 16), expr: { pressure: (i % 10) / 10 } } : {}));
  }
  const total = Math.ceil(N / 4 / 16) * 16;
  useEditorStore.setState({
    bpm: 120,
    tracks: [track('big', { instrumentProgram: 48 })],
    clips: [rollClip('bigclip', 'big', { sourcePianoRoll: big, sourceRollNotes: big, sourceTotalSteps: total, renderedProgram: 48, sourceBpm: 120 })],
  });
  const { form, files } = await saveThroughTheWire();
  const part = form.get('project');
  assert.ok(part instanceof Blob);
  // Past the 1 MB the backend holds a text part to, so only a file part gets through.
  assert.ok((part as Blob).size > 1024 * 1024, `the payload is ${(part as Blob).size} bytes`);
  const project = await projectFrom(form);
  const clip = project.tracks[0].clips[0];
  assert.equal((clip.midi_notes ?? clip.roll_notes ?? []).length, N);
  assert.ok(!(clip.midi_notes && clip.roll_notes), 'the notes are in the file once');

  useEditorStore.setState({ tracks: [track('other')], clips: [] });
  await openWithFiles(project, files);
  const back = st().clips[0];
  assert.equal(back.sourcePianoRoll?.length, N, 'all 100,000 notes reload');
  assert.deepEqual(withoutIds(back.sourcePianoRoll?.slice(0, 50)), withoutIds(big.slice(0, 50)));
  assert.deepEqual(withoutIds(back.sourcePianoRoll?.slice(N - 50)), withoutIds(big.slice(N - 50)));
  assert.equal(back.sourcePianoRoll?.filter((n) => n.channel !== undefined).length, big.filter((n) => n.channel !== undefined).length);
  assert.equal(back.renderedProgram, 48);
  assert.equal(st().tracks[0].instrumentProgram, 48);
}

console.log('projectImport.instruments: ok');
