// A saved project reopens with each track's VST3 instrument slot: its plugin,
// its on/off, the state its window captured and the host that captured it
// (the live host prints a state it captured). A track with no slot, and every
// file written before the slot was saved, reopens on the soundfont synths.
//
// The app's order: the EDIT store holds the session, captureEditorSession
// builds the payload, the JSON comes back as the backend returns it, and
// loadProjectIntoEditor opens it.
//
//   cd frontend && npx tsx src/lib/projectImport.vstInstrument.test.ts
import assert from 'node:assert/strict';
import { captureEditorSession, loadProjectIntoEditor } from './projectImport.ts';
import type { TasmoProjectLoaded } from './projectClient.ts';
import { activeTrackInstrument, useEditorStore, type EditorTrack } from '../state/editorStore.ts';

class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, getChannelData: () => new Float32Array(64).fill(0.5) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#fff',
  ...extra,
});
const st = () => useEditorStore.getState();

function roundTrip(): TasmoProjectLoaded {
  const session = captureEditorSession();
  return JSON.parse(JSON.stringify({ project_name: 'Slots', tempo: session.bpm, tracks: session.tracks })) as TasmoProjectLoaded;
}

{
  useEditorStore.setState({
    bpm: 100,
    tracks: [
      track('lead', {
        instrumentProgram: 81,
        instrument: {
          id: 'inst-lead',
          effect: 'vst3',
          params: {},
          enabled: true,
          vst: { plugin_path: 'C:/VST3/Surge XT.vst3', plugin_name: 'Surge XT', raw_state: 'c3RhdGU=', state_host: 'thedaw' },
        },
      }),
      // Switched off: kept, and still off.
      track('pad', {
        instrument: { id: 'inst-pad', effect: 'vst3', params: {}, enabled: false, vst: { plugin_path: 'C:/VST3/Vital.vst3', plugin_name: 'Vital' } },
      }),
      track('bass', { instrumentProgram: 33 }),
    ],
    clips: [],
  });
  const project = roundTrip();
  const byId = new Map(project.tracks.map((t) => [t.id, t]));
  assert.deepEqual(byId.get('lead')?.instrument, {
    id: 'inst-lead',
    effect: 'vst3',
    params: {},
    enabled: true,
    vst: { plugin_path: 'C:/VST3/Surge XT.vst3', plugin_name: 'Surge XT', raw_state: 'c3RhdGU=', state_host: 'thedaw' },
  });
  assert.equal(byId.get('bass')?.instrument, undefined, 'a track with no slot writes none');

  useEditorStore.setState({ bpm: 120, tracks: [track('other')], clips: [] });
  await loadProjectIntoEditor(project);
  const lead = st().tracks.find((t) => t.id === 'lead');
  assert.equal(activeTrackInstrument(lead)?.vst?.plugin_name, 'Surge XT', 'the lead plays through its instrument again');
  assert.equal(lead?.instrument?.vst?.raw_state, 'c3RhdGU=', 'with the state its window captured');
  assert.equal(lead?.instrument?.vst?.state_host, 'thedaw', 'and the host that captured it');
  const pad = st().tracks.find((t) => t.id === 'pad');
  assert.equal(pad?.instrument?.enabled, false, 'a slot switched off stays off');
  assert.equal(activeTrackInstrument(pad), null);
  assert.equal(st().tracks.find((t) => t.id === 'bass')?.instrument, undefined);
}

// A file written before the slot was saved, and a slot naming no plugin, open on the synths.
{
  const project = roundTrip();
  for (const t of project.tracks) delete t.instrument;
  const broken = project.tracks.find((t) => t.id === 'pad')!;
  broken.instrument = { id: 'inst-pad', effect: 'vst3', enabled: true, vst: null };
  await loadProjectIntoEditor(project);
  assert.ok(st().tracks.every((t) => t.instrument === undefined), 'no track opens with a slot');
}

console.log('projectImport.vstInstrument: ok');
