/**
 * A bounce whose clips play a sound bank preset lifted above unity sends its
 * whole master through the safety limiter (lib/renderCore `safetyLimiter`,
 * lib/synthOutputStage): the master rack, or the master bus with no rack,
 * plays into the limiter and the limiter into the destination. A bounce with
 * no such clip, or where the limiter cannot load, is wired as before.
 *
 *   cd frontend && npx tsx src/lib/renderCore.safety.test.ts
 */
import assert from 'node:assert/strict';
import type { AudioClip, EditorTrack } from '../state/editorStore.ts';
import { BOUNCE_SAMPLE_RATE, renderBounce, type BounceRequest, type RenderDeps } from './renderCore.ts';

interface Node { id: string; to: string[]; connect(n: Node): Node; disconnect(): void }
let made = 0;
const fakeNode = (id = `n${made++}`): Node => {
  const param = () => ({ value: 1, setValueAtTime: () => param(), linearRampToValueAtTime: () => param(), setValueCurveAtTime: () => param(), cancelScheduledValues: () => param() });
  const n = new Proxy({ id, to: [] as string[] } as unknown as Record<string, unknown>, {
    get(target, key: string) {
      if (key in target) return target[key];
      if (key === 'connect') return (t: Node) => { (target.to as string[]).push(t.id); return t; };
      if (key === 'disconnect' || key === 'start' || key === 'stop') return () => {};
      const p = param();
      target[key] = p;
      return p;
    },
  });
  return n as unknown as Node;
};

function harness(safety?: RenderDeps['safetyLimiter']) {
  const ctxes: Array<{ destination: Node; nodes: Node[] }> = [];
  const clip: AudioClip = {
    id: 'c1', trackId: 't1', label: 'c1', audioBlob: new Blob(['x']), mimeType: 'audio/wav',
    sourceDuration: 4, offsetIntoSource: 0, durationSec: 4, startSec: 0, color: '#fff',
  };
  const track: EditorTrack = { id: 't1', name: 't1', nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#fff' };
  const deps: RenderDeps = {
    clips: [clip],
    tracks: [track],
    masterFxChain: [],
    automationLanes: [],
    decode: async () => ({ duration: 4, sampleRate: BOUNCE_SAMPLE_RATE, numberOfChannels: 2, length: 4, getChannelData: () => new Float32Array(4) }) as unknown as AudioBuffer,
    buildChain: ((_ctx: unknown, input: Node, output: Node) => {
      input.connect(output);
      return { rebuild: () => {}, updateParams: () => {}, instances: () => [], inertIds: () => [], dispose: () => {} };
    }) as unknown as RenderDeps['buildChain'],
    scheduleSources: (() => {}) as unknown as RenderDeps['scheduleSources'],
    makeContext: (channels, length, rate) => {
      const entry = { destination: fakeNode('destination'), nodes: [] as Node[] };
      ctxes.push(entry);
      return new Proxy({ sampleRate: rate, length, currentTime: 0, destination: entry.destination } as Record<string, unknown>, {
        get(target, key: string) {
          if (key in target) return target[key];
          if (key.startsWith('create')) return () => { const n = fakeNode(); entry.nodes.push(n); return n; };
          if (key === 'suspend' || key === 'resume') return () => Promise.resolve();
          if (key === 'startRendering') return async () => ({ duration: length / rate, sampleRate: rate, numberOfChannels: channels, length, getChannelData: () => new Float32Array(length) });
          return undefined;
        },
      }) as unknown as OfflineAudioContext;
    },
    makeDecodeContext: () => ({ close: async () => {} }) as unknown as BaseAudioContext & { close(): Promise<void> },
    makeCompDelay: () => fakeNode() as unknown as DelayNode,
    ensureChop: async () => {},
    ensureHallIrs: async () => {},
    sliceChunks: () => [],
    ...(safety ? { safetyLimiter: safety } : {}),
  };
  return { deps, ctxes };
}

const request = (includeFx: boolean): BounceRequest => ({
  scope: { kind: 'master' },
  sampleRate: BOUNCE_SAMPLE_RATE,
  includeFx,
  includeAutomation: true,
  includeTrackMix: true,
  float32: false,
});

/** The nodes that play straight into the destination. */
const intoDestination = (ctx: { nodes: Node[] }, extra: Node[] = []) => [...ctx.nodes, ...extra].filter((n) => n.to.includes('destination')).map((n) => n.id);

for (const includeFx of [true, false]) {
  const limiter = fakeNode('limiter');
  const { deps, ctxes } = harness(async () => limiter as unknown as AudioNode);
  await renderBounce(request(includeFx), deps);
  assert.deepEqual(intoDestination(ctxes[0], [limiter]), ['limiter'], `with ${includeFx ? 'the master rack' : 'no rack'}: only the limiter reaches the destination`);
  assert.ok(ctxes[0].nodes.some((n) => n.to.includes('limiter')), 'the master plays into the limiter');

  const plain = harness();
  await renderBounce(request(includeFx), plain.deps);
  assert.ok(!plain.ctxes[0].nodes.some((n) => n.to.includes('limiter')), 'no lifted voice: no limiter');
  assert.equal(intoDestination(plain.ctxes[0]).length, 1, 'the master reaches the destination itself');

  const failed = harness(async () => null);
  await renderBounce(request(includeFx), failed.deps);
  assert.equal(intoDestination(failed.ctxes[0]).length, 1, 'a limiter that cannot load leaves the master as it was');
}

console.log('renderCore.safety: ok');
