/**
 * An external-only track (EditorTrack externalOnly) plays its MIDI on the
 * device at its MIDI out port, so theDAW's own audio has no sound of it: the
 * offline bounce (lib/renderCore renderBounce) decodes and schedules none of
 * its MIDI clips, the VST3 print path (printInstrumentTracks) prints no
 * instrument for it, and the arrangement's MIDI export still writes its notes.
 * Its audio clips play as any track's do.
 *
 *   cd frontend && npx tsx src/lib/renderCore.externalOnly.test.ts
 */
import assert from 'node:assert/strict';
import type { AudioClip, EditorTrack } from '../state/editorStore.ts';
import type { ChainEntry } from '../state/effectChainStore.ts';
import type { PianoNote } from '../state/pianoRollStore.ts';
import { arrangementToMidiFile } from './arrangementMidi.ts';
import {
  BOUNCE_SAMPLE_RATE, instrumentTracksInScope, isExternalMidiClip, printInstrumentTracks, renderBounce, withoutExternalMidi,
  type BounceRequest, type RenderDeps,
} from './renderCore.ts';

let blobs = 0;
const note = (step: number, pitch: number): PianoNote => ({ id: `n${step}-${pitch}`, note: pitch, step, length: 4, velocity: 90, tick: step * 240, ticks: 960 });
const rollClip = (id: string, trackId: string, notes: PianoNote[]): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: new Blob([`roll-${blobs++}`]),
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 4,
  startSec: 0,
  color: '#a855f7',
  sourceKind: 'piano-roll',
  sourcePianoRoll: notes,
  sourceBpm: 120,
});
const audioClip = (id: string, trackId: string): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: new Blob([`audio-${blobs++}`]),
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 4,
  startSec: 0,
  color: '#22c55e',
});
const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#a855f7',
  ...extra,
});
const strings: ChainEntry = {
  id: 'inst-1',
  effect: 'vst3',
  params: {},
  enabled: true,
  vst: { plugin_path: 'C:/VST3/Strings.vst3', plugin_name: 'Strings', raw_state: 'c3RhdGU=' },
} as ChainEntry;

// A synth part sent out to a hardware module, with an audio take of it on the same track,
// and a piano part theDAW plays.
const tracks = [
  track('ext', { externalOnly: true, midiOut: { id: 'port-1', label: 'Hardware synth', channel: 1 }, instrument: strings }),
  track('pno', { instrumentProgram: 0 }),
];
const extMidi = rollClip('ext-midi', 'ext', [note(0, 60), note(4, 64)]);
const extAudio = audioClip('ext-audio', 'ext');
const pnoMidi = rollClip('pno-midi', 'pno', [note(0, 48)]);
const clips = [extMidi, extAudio, pnoMidi];

// ── which clips are the external device's ────────────────────────────────────
{
  assert.equal(isExternalMidiClip(extMidi, tracks), true, 'a MIDI clip on an external-only track');
  assert.equal(isExternalMidiClip(extAudio, tracks), false, 'an audio clip on the same track plays in theDAW');
  assert.equal(isExternalMidiClip(pnoMidi, tracks), false, 'a MIDI clip on an ordinary track');
  assert.deepEqual(withoutExternalMidi(clips, tracks).map((c) => c.id), ['ext-audio', 'pno-midi']);
  assert.equal(withoutExternalMidi(clips, [track('ext'), track('pno')]).length, 3, 'no external-only track leaves every clip');
}

// ── the offline bounce decodes and schedules none of them ────────────────────
{
  /** A context whose every `create*` hands out a node that records nothing and connects anywhere. */
  const fakeNode = (): unknown => {
    const param = () => ({ value: 1, setValueAtTime: () => param(), linearRampToValueAtTime: () => param(), setValueCurveAtTime: () => param(), cancelScheduledValues: () => param() });
    return new Proxy({} as Record<string, unknown>, {
      get(target, key: string) {
        if (key in target) return target[key];
        if (key === 'connect') return (to: unknown) => to;
        if (key === 'disconnect' || key === 'start' || key === 'stop') return () => {};
        const p = param();
        target[key] = p;
        return p;
      },
    });
  };
  const makeContext = (channels: number, length: number, rate: number) =>
    new Proxy({ sampleRate: rate, length, currentTime: 0, destination: fakeNode() } as Record<string, unknown>, {
      get(target, key: string) {
        if (key in target) return target[key];
        if (key.startsWith('create')) return () => fakeNode();
        if (key === 'suspend' || key === 'resume') return () => Promise.resolve();
        if (key === 'startRendering') {
          return async () => ({ duration: length / rate, sampleRate: rate, numberOfChannels: channels, length, getChannelData: () => new Float32Array(length) });
        }
        return undefined;
      },
    }) as unknown as OfflineAudioContext;
  const decoded: Blob[] = [];
  const scheduled: string[] = [];
  const deps: RenderDeps = {
    clips,
    tracks,
    masterFxChain: [],
    automationLanes: [],
    decode: async (_ctx, blob) => {
      decoded.push(blob);
      return { duration: 4, sampleRate: BOUNCE_SAMPLE_RATE, numberOfChannels: 2, length: 4 * BOUNCE_SAMPLE_RATE, getChannelData: () => new Float32Array(4 * BOUNCE_SAMPLE_RATE) } as unknown as AudioBuffer;
    },
    buildChain: ((_ctx: unknown, input: { connect(o: unknown): unknown }, output: unknown) => {
      input.connect(output);
      return { rebuild: () => {}, updateParams: () => {}, instances: () => [], inertIds: () => [], dispose: () => {} };
    }) as unknown as RenderDeps['buildChain'],
    scheduleSources: ((_ctx: unknown, clip: AudioClip) => {
      scheduled.push(clip.id);
    }) as unknown as RenderDeps['scheduleSources'],
    makeContext,
    makeDecodeContext: () => ({ close: async () => {} }) as unknown as BaseAudioContext & { close(): Promise<void> },
    makeCompDelay: () => fakeNode() as DelayNode,
    ensureChop: async () => {},
    ensureHallIrs: async () => {},
    sliceChunks: () => [],
  };
  const request = (scope: BounceRequest['scope']): BounceRequest => ({
    scope,
    sampleRate: BOUNCE_SAMPLE_RATE,
    includeFx: true,
    includeAutomation: true,
    includeTrackMix: true,
    float32: false,
  });

  await renderBounce(request({ kind: 'master' }), deps);
  assert.deepEqual(scheduled.sort(), ['ext-audio', 'pno-midi'], 'the master bounce plays the audio take and the piano, not the external part');
  assert.ok(!decoded.includes(extMidi.audioBlob), 'the external part is never decoded');

  scheduled.length = 0;
  await renderBounce(request({ kind: 'track', trackId: 'ext' }), deps);
  assert.deepEqual(scheduled, ['ext-audio'], 'a freeze stem of the external track holds its audio take alone');

  scheduled.length = 0;
  await renderBounce(request({ kind: 'selection', clipIds: ['ext-midi'] }), deps);
  assert.deepEqual(scheduled, [], 'a selection of the external part alone is silent');
}

// ── the VST3 print path prints no instrument for it ──────────────────────────
{
  assert.deepEqual(instrumentTracksInScope(clips, tracks, { kind: 'master' }), [], 'its instrument slot is not printed');
  let renders = 0;
  const print = await printInstrumentTracks(
    { tracks, clips, bpm: 120 },
    { kind: 'master' },
    async () => {
      renders += 1;
      throw new Error('no instrument print expected');
    },
  );
  assert.equal(renders, 0, 'no render request goes to the VST host');
  assert.deepEqual(print.clips.map((c) => c.id), clips.map((c) => c.id), 'the clips pass through untouched');
  // The same track switched back to theDAW's sound prints through its instrument.
  const inside = [{ ...tracks[0], externalOnly: undefined }, tracks[1]];
  assert.deepEqual(instrumentTracksInScope(clips, inside, { kind: 'master' }).map((t) => t.id), ['ext']);
}

// ── the arrangement's MIDI export still writes its notes ─────────────────────
{
  const out = arrangementToMidiFile({ tracks, clips, bpm: 120, timeSignature: { num: 4, den: 4 } });
  assert.equal(out.trackCount, 2, 'both tracks are in the file');
  assert.equal(out.noteCount, 3, 'the external part\'s two notes and the piano\'s one');
}

console.log('renderCore.externalOnly: ok');
