/**
 * A roll part's record on its EDIT clip (AudioClip `sourceRollPart`) through
 * the app's own SAVE and back: its controller changes and its bank select LSB
 * go out in the .tasmo payload, the backend keeps them, and a reopen gives the
 * clip its part back.
 *
 * The save runs through projectStore.save, the SAVE button's own action, with
 * the transport stubbed at fetch. The records it posts are compared with
 * tests/fixtures/roll_part_session_from_frontend.json, which
 * tests/test_roll_parts_io.py posts to /save-session and reads back through
 * the models, so the two suites check the same bytes. After an intended change
 * to the part record, rewrite the fixture with
 *   WRITE_ROLL_PART_FIXTURE=1 npx tsx src/lib/rollPartSave.test.ts
 *
 *   cd frontend && npx tsx src/lib/rollPartSave.test.ts
 */
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadProjectIntoEditor } from './projectImport.ts';
import type { TasmoProjectLoaded } from './projectClient.ts';
import { useEditorStore, type AudioClip, type EditorTrack } from '../state/editorStore.ts';
import { useProjectStore } from '../state/projectStore.ts';
import type { PianoNote, RollControl, RollPartRef } from '../state/pianoRollStore.ts';

// computePeaks needs an AudioContext. The fake decodes any blob to one second.
class FakeAudioContext {
  async decodeAudioData() {
    return { duration: 1, getChannelData: () => new Float32Array(64).fill(0.5) };
  }
  async close() {}
}
(globalThis as { window?: unknown }).window = { AudioContext: FakeAudioContext };

const FIXTURE = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'tests', 'fixtures', 'roll_part_session_from_frontend.json');
const ed = () => useEditorStore.getState();

const PEDAL: RollControl[] = [
  { tick: 0, controller: 7, value: 96 },
  { tick: 0, controller: 10, value: 40 },
  { tick: 480, controller: 64, value: 127 },
  { tick: 1920, controller: 64, value: 0 },
  { tick: 1920, controller: 11, value: 80 },
];
const note = (id: string, pitch: number, step: number): PianoNote => ({ id, note: pitch, step, length: 4, velocity: 90, tick: step * 240, ticks: 960 });
const track = (id: string, name: string): EditorTrack => ({ id, name, nameAutoGenerated: false, volume: 0.8, pan: 0, mute: false, solo: false, color: '#a855f7' });
const part = (id: string, order: number, name: string, extra: Partial<RollPartRef>): RollPartRef => ({
  doc: 'roll-quartet',
  id,
  order,
  name,
  program: 40,
  bank: 0,
  channel: order + 1,
  color: '#a855f7',
  mute: false,
  solo: false,
  ...extra,
});
const clip = (id: string, trackId: string, ref: RollPartRef, notes: PianoNote[]): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: new Blob([new Uint8Array([1, 2, 3])], { type: 'audio/wav' }),
  mimeType: 'audio/wav',
  sourceDuration: 2,
  offsetIntoSource: 0,
  durationSec: 2,
  startSec: 0,
  color: '#a855f7',
  peaks: new Float32Array(0),
  sourceKind: 'piano-roll',
  sourcePianoRoll: notes,
  sourceBpm: 120,
  sourceTotalSteps: 16,
  sourceMeterMap: [{ bar: 0, meter: { num: 4, den: 4, groups: [] } }],
  sourcePickupSteps: 0,
  sourceLanes: [{ id: 0, name: 'A', cycleSteps: null }],
  instrumentProgram: ref.program ?? undefined,
  renderedProgram: ref.program ?? undefined,
  sourceRollPart: ref,
});

// Two parts of one roll document: a violin with its pedal, volume, pan, expression and an XG variation (LSB 3), and a cello with neither.
useEditorStore.setState({
  bpm: 120,
  tracks: [track('v1', 'Violin I'), track('vc', 'Violoncello')],
  clips: [
    clip('violin', 'v1', part('p-violin', 0, 'Violin I', { instrumentId: 'violin', bankLsb: 3, controls: PEDAL }), [note('a', 76, 0), note('b', 79, 4)]),
    clip('cello', 'vc', part('p-cello', 1, 'Violoncello', { program: 42, instrumentId: 'cello' }), [note('c', 36, 0)]),
  ],
});
useProjectStore.setState({ projectName: 'Parts', savePath: 'P.tasmo', pendingTracks: [] });

let posted: FormData | null = null;
const realFetch = globalThis.fetch;
globalThis.fetch = (async (url: RequestInfo | URL, init?: RequestInit) => {
  if (String(url).includes('/api/project/save-session')) {
    posted = init?.body as FormData;
    return new Response(JSON.stringify({ status: 'saved', path: 'P.tasmo', manifest: { audio_mode: 'embedded' } }), { status: 200 });
  }
  return new Response('[]', { status: 200 });
}) as typeof fetch;
try {
  await useProjectStore.getState().save();
} finally {
  globalThis.fetch = realFetch;
}
assert.equal(useProjectStore.getState().error, null, 'the save went through');
assert.ok(posted, 'the SAVE action posted to /save-session');
const form = posted as FormData;
const projectPart = form.get('project');
assert.ok(projectPart instanceof Blob, 'the project JSON goes out as a file part');
const project = JSON.parse(await (projectPart as Blob).text()) as TasmoProjectLoaded;
const payload = { project, files: form.getAll('files').map((f) => (f as File).name) };

// ── what the app writes ─────────────────────────────────────────────────────
const records = project.tracks.flatMap((t) => t.clips.map((c) => c.roll_part ?? null));
assert.deepEqual(records.map((r) => r?.bank_lsb), [3, undefined], 'the violin writes bank_lsb; the cello writes no key');
assert.equal(records[1] && 'bank_lsb' in records[1], false);
assert.deepEqual(records[0]?.controls, PEDAL, 'the violin writes its controller changes');
assert.equal(records[1] && 'controls' in records[1], false);
if (process.env.WRITE_ROLL_PART_FIXTURE) writeFileSync(FIXTURE, `${JSON.stringify(payload, null, 2)}\n`);
const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8')) as typeof payload;
assert.deepEqual(
  records,
  fixture.project.tracks.flatMap((t) => t.clips.map((c) => c.roll_part ?? null)),
  'the part records changed: check tests/test_roll_parts_io.py, then rewrite the fixture',
);

// ── and what a reopen gives back ────────────────────────────────────────────
useEditorStore.setState({ tracks: [track('other', 'other')], clips: [] });
const files = new Map<string, Blob>(form.getAll('files').map((f) => [(f as File).name, f as File]));
globalThis.fetch = (async (url: RequestInfo | URL) => {
  const path = decodeURIComponent(String(url).split('path=')[1] ?? '');
  const hit = [...files].find(([name]) => path.endsWith(name));
  return hit ? new Response(hit[1], { status: 200 }) : new Response('', { status: 404 });
}) as typeof fetch;
try {
  await loadProjectIntoEditor(project);
} finally {
  globalThis.fetch = realFetch;
}
const violin = ed().clips.find((c) => c.id === 'violin');
const cello = ed().clips.find((c) => c.id === 'cello');
assert.deepEqual(violin?.sourceRollPart?.controls, PEDAL, 'the reopened violin has its controllers');
assert.equal(violin?.sourceRollPart?.bankLsb, 3, 'and its LSB');
assert.equal(violin?.sourceRollPart?.instrumentId, 'violin');
assert.equal(cello?.sourceRollPart && 'bankLsb' in cello.sourceRollPart, false, 'the cello reopens with none');
assert.equal(cello?.sourceRollPart?.controls, undefined);

console.log('rollPartSave: ok');
