/**
 * MIDI stage 4.6: the instrument slot. An EDIT track's MIDI as its VST3
 * instrument plays it (lib/vstInstrumentMidi), the print every bounce makes of
 * it (lib/renderCore printInstrumentTracks), the client that asks the backend
 * for it (lib/vstClient renderInstrumentTrack), and the slot in the store
 * (editorStore setTrackInstrument, freeze and unfreeze).
 *
 *   cd frontend && npx tsx src/lib/vstInstrumentMidi.test.ts
 */
import assert from 'node:assert/strict';
import type { AudioClip, EditorTrack } from '../state/editorStore.ts';
import { activeTrackInstrument, trackSoundChain, useEditorStore } from '../state/editorStore.ts';
import type { PianoNote, RollControl } from '../state/pianoRollStore.ts';
import type { PolyLane } from './meterMap.ts';
import type { LaneBend } from './pitchBend.ts';
import { instrumentTracksInScope, printInstrumentTracks, type InstrumentRenderer } from './renderCore.ts';
import { renderInstrumentTrack } from './vstClient.ts';
import { readWavSamples, writeFloatWav } from './wavSamples.ts';
import {
  INSTRUMENT_TAIL_SEC,
  instrumentGainAt,
  instrumentPrintPlan,
  parseInstrumentRender,
  shapeInstrumentPrint,
  trackInstrumentMessages,
  type InstrumentRenderTrack,
} from './vstInstrumentMidi.ts';

const blob = new Blob([new Uint8Array([1])], { type: 'audio/wav' });
const strings = { id: 'inst-1', effect: 'vst3', params: {}, enabled: true, vst: { plugin_path: 'C:/VST3/Strings.vst3', plugin_name: 'Strings', raw_state: 'c3RhdGU=' } };
const track = (id: string, extra: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#a855f7',
  ...extra,
});
const note = (step: number, pitch: number, length = 4, velocity = 90): PianoNote => ({ id: `n${step}-${pitch}`, note: pitch, step, length, velocity, tick: step * 240, ticks: length * 240 });
const clip = (id: string, trackId: string, startSec: number, notes: PianoNote[], extra: Partial<AudioClip> = {}): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: blob,
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 4,
  startSec,
  color: '#a855f7',
  sourceKind: 'piano-roll',
  sourcePianoRoll: notes,
  sourceBpm: 120,
  ...extra,
});
const part = (controls: RollControl[]) => ({ doc: 'd', id: 'p', order: 0, name: 'Violins', program: 40, bank: 0, channel: 0, color: '#fff', mute: false, solo: false, controls });
const close = (a: number, b: number) => Math.abs(a - b) < 1e-6;

// ── notes, controllers and bends at their seconds, no program changes, no fader ──
{
  // A crescendo on expression and a modulation swell under a two-note line, on a track whose fader is down and panned.
  const controls: RollControl[] = [
    { tick: 0, controller: 11, value: 40 },
    { tick: 960, controller: 11, value: 110 },
    { tick: 480, controller: 1, value: 64 },
  ];
  const c = clip('v1', 'vln', 2, [note(0, 67), note(8, 69)], { sourceRollPart: part(controls) });
  const source = { bpm: 120, tracks: [track('vln', { instrument: strings, instrumentProgram: 40, volume: 0.3, pan: 0.7 })], clips: [c] };
  const msgs = trackInstrumentMessages(source, 'vln', { useSoundfont: true, activeProgram: 0 });
  const kinds = msgs.map((m) => m.data[0] & 0xf0);
  assert.equal(kinds.includes(0xc0), false, 'no program change: the instrument plays its own preset');
  assert.equal(msgs.some((m) => (m.data[0] & 0xf0) === 0xb0 && m.data[1] === 0), false, 'no bank select');
  assert.equal(msgs.some((m) => (m.data[0] & 0xf0) === 0xb0 && (m.data[1] === 7 || m.data[1] === 10)), false, 'the fader and pan stay on the strip, not in CC 7 / CC 10');
  const ons = msgs.filter((m) => (m.data[0] & 0xf0) === 0x90);
  assert.deepEqual(ons.map((m) => [m.t, m.data[1], m.data[2]]), [[2, 67, 90], [3, 69, 90]], 'each note at the second EDIT plays it');
  const offs = msgs.filter((m) => (m.data[0] & 0xf0) === 0x80);
  assert.deepEqual(offs.map((m) => [m.t, m.data[1]]), [[2.5, 67], [3.5, 69]]);
  const cc = msgs.filter((m) => (m.data[0] & 0xf0) === 0xb0).map((m) => [m.t, m.data[1], m.data[2]]);
  assert.deepEqual(cc.filter(([, n]) => n === 11).slice(0, 2), [[2, 11, 40], [2.5, 11, 110]], 'the expression swell, CC 11');
  assert.ok(cc.some(([t, n, v]) => close(t, 2.25) && n === 1 && v === 64), 'the modulation, CC 1');
  // Time order, and at one instant the controllers ahead of the note they shape.
  assert.ok(msgs.every((m, i) => i === 0 || m.t >= msgs[i - 1].t), 'time order');
  const at2 = msgs.filter((m) => m.t === 2).map((m) => m.data[0] & 0xf0);
  assert.equal(at2[at2.length - 1], 0x90, 'the note-on after its controllers');
}

// ── a bent lane: its RPN 0/0 range and wheel on the lane's own channel ─────────
{
  const lanes: PolyLane[] = [{ id: 0, name: 'A', cycleSteps: null }, { id: 1, name: 'B', cycleSteps: null }];
  const own = [{ ...note(0, 60, 8), lane: 0 }, { ...note(0, 64, 8), lane: 1 }];
  const sourceBends: LaneBend[] = [
    { lane: 1, range: 2, points: [{ id: 'p0', step: 0, value: 0, shape: 'linear' }, { id: 'p1', step: 8, value: 1, shape: 'hold' }] },
  ];
  const c = clip('b', 'gtr', 0, own.map(({ lane: _lane, ...n }) => n), { sourceRollNotes: own, sourceLanes: lanes, sourceBends, sourceTotalSteps: 16, durationSec: 2, sourceDuration: 2 });
  const msgs = trackInstrumentMessages({ bpm: 120, tracks: [track('gtr', { instrument: strings })], clips: [c] }, 'gtr', { useSoundfont: false, activeProgram: 0 });
  const rpn = msgs.filter((m) => m.data[0] === 0xb1).map((m) => [m.data[1], m.data[2]]);
  assert.deepEqual(rpn, [[101, 0], [100, 0], [6, 2], [38, 0]], 'the bend range, two semitones, on channel 2');
  const wheel = msgs.filter((m) => m.data[0] === 0xe1);
  assert.ok(wheel.length > 2, 'the wheel on the bent lane channel');
  assert.deepEqual(wheel[0].data, [0xe1, 0, 64], 'centre (8192) where the clip starts');
  assert.deepEqual(wheel[wheel.length - 1].data, [0xe1, 0x7f, 0x7f], 'the whole range up');
  assert.equal(msgs.some((m) => (m.data[0] & 0xf0) === 0xe0 && (m.data[0] & 0x0f) === 0), false, 'the lane that does not bend has no wheel');
}

// ── the print plan: from the first clip, messages relative, the tail after ─────
{
  const a = clip('a', 'vln', 10, [note(0, 60)]);
  const b = clip('b', 'vln', 14, [note(0, 62)]);
  const muted = clip('m', 'vln', 20, [note(0, 64)], { muted: true });
  const t = track('vln', { instrument: strings });
  const source = { bpm: 120, tracks: [t], clips: [a, b, muted] };
  const plan = instrumentPrintPlan(source, t, source.clips, { useSoundfont: false, activeProgram: 0 });
  assert.ok(plan);
  assert.equal(plan.startSec, 10, 'renders from the first clip, not from the top of the song');
  assert.equal(plan.request.events[0].t, 0);
  assert.equal(plan.request.duration, 4.5 + INSTRUMENT_TAIL_SEC, 'the last note-off (14.5 s) plus the release tail');
  assert.equal(plan.request.events.some((e) => e.data[1] === 64), false, 'a muted clip plays nothing');
  assert.equal(plan.request.plugin_path, strings.vst.plugin_path);
  assert.equal(plan.request.raw_state, strings.vst.raw_state, 'the state captured from the editor rides along');
  assert.equal(plan.request.state_host, '', 'an offline-editor state prints through pedalboard');
  const liveState = { ...strings, vst: { ...strings.vst, state_host: 'thedaw' as const } };
  assert.equal(instrumentPrintPlan(source, track('vln', { instrument: liveState }), source.clips, { useSoundfont: false, activeProgram: 0 })?.request.state_host, 'thedaw', "a live-host state says so, and prints through our own host");
  assert.equal(instrumentPrintPlan(source, track('vln', { instrument: { ...strings, enabled: false } }), source.clips, { useSoundfont: false, activeProgram: 0 }), null, 'a switched-off slot prints nothing');
  assert.equal(instrumentPrintPlan(source, track('vln'), source.clips, { useSoundfont: false, activeProgram: 0 }), null, 'no instrument, nothing to print');
}

// ── printInstrumentTracks: the print takes the place of the track's MIDI clips ─
{
  const withInstr = track('vln', { instrument: strings });
  const plain = track('pno', { instrumentProgram: 0 });
  const vln = clip('v', 'vln', 2, [note(0, 67)]);
  const pno = clip('p', 'pno', 0, [note(0, 60)]);
  const audio: AudioClip = { ...clip('au', 'vln', 0, []), sourceKind: 'audio', sourcePianoRoll: undefined };
  const source = { bpm: 120, tracks: [withInstr, plain], clips: [vln, pno, audio] };
  const asked: InstrumentRenderTrack[] = [];
  const printedAudio = new Blob([new Uint8Array([9])], { type: 'audio/wav' });
  const render: InstrumentRenderer = async (req, sampleRate) => {
    asked.push(req);
    return { trackId: req.track_id, audio: printedAudio, frames: Math.round(req.duration * sampleRate), sampleRate, warnings: ['state rejected'] };
  };
  const warned: string[] = [];
  const print = await printInstrumentTracks(source, { kind: 'master' }, render, { sampleRate: 1000, onWarning: (n, w) => warned.push(`${n}: ${w}`) });
  assert.equal(asked.length, 1, 'only the track with an instrument prints');
  assert.deepEqual(print.clips.map((c) => c.id).sort(), ['au', 'instrument-print:vln', 'p'], "the violin's MIDI clip is replaced; its audio clip and the piano stay");
  const printed = print.clips.find((c) => c.id === 'instrument-print:vln');
  assert.ok(printed);
  assert.equal(printed.trackId, 'vln', 'on its own track, so its inserts, fader and pan act on it');
  assert.equal(printed.startSec, 2);
  assert.equal(printed.audioBlob, printedAudio);
  assert.equal(printed.durationSec, asked[0].duration);
  assert.deepEqual(print.printed, [printedAudio]);
  assert.deepEqual(warned, ['vln: state rejected'], 'the backend warnings reach the LOG');

  // A stem of the piano track prints nothing; a selection prints only what it selects.
  assert.equal(instrumentTracksInScope(source.clips, source.tracks, { kind: 'track', trackId: 'pno' }).length, 0);
  assert.equal(instrumentTracksInScope(source.clips, source.tracks, { kind: 'selection', clipIds: ['p'] }).length, 0);
  assert.equal(instrumentTracksInScope(source.clips, source.tracks, { kind: 'selection', clipIds: ['v'] }).length, 1);

  // A failed print names the track and never lands as silence.
  await assert.rejects(
    printInstrumentTracks(source, { kind: 'master' }, async () => { throw new Error('the instrument failed to render'); }),
    /Track "vln" could not be printed through its instrument: the instrument failed to render/,
  );
  // Called off: no track renders.
  const none = await printInstrumentTracks(source, { kind: 'master' }, render, { isCancelled: () => true });
  assert.equal(none.clips.some((c) => c.id.startsWith('instrument-print:')), false);
}

// ── the print carries each clip's gain and fades, as live playback does ───────
{
  const rate = 1000;
  /** What a plugin that holds every note at full scale would print: 1.0 on both channels. */
  const fullScale = (seconds: number): Blob => {
    const frames = Math.round(seconds * rate);
    const ones = new Float32Array(frames).fill(1);
    return writeFloatWav({ sampleRate: rate, frames, channels: [ones, ones.slice()] });
  };
  const render: InstrumentRenderer = async (req) => ({
    trackId: req.track_id, audio: fullScale(req.duration), frames: Math.round(req.duration * rate), sampleRate: rate, warnings: [],
  });
  const minus6 = 10 ** (-6 / 20);
  // A two-second clip at -6 dB with a one-second linear fade-out, starting at 1 s.
  const faded = clip('f', 'vln', 1, [note(0, 60, 16)], { durationSec: 2, gain: minus6, fadeOutSec: 1 });
  const print = await printInstrumentTracks({ bpm: 120, tracks: [track('vln', { instrument: strings })], clips: [faded] }, { kind: 'master' }, render, { sampleRate: rate });
  const printed = print.clips.find((c) => c.id === 'instrument-print:vln');
  assert.ok(printed?.audioBlob);
  const got = readWavSamples(await printed.audioBlob.arrayBuffer());
  const at = (sec: number) => got.channels[0][Math.round((sec - printed.startSec) * rate)];
  assert.equal(printed.startSec, 1);
  assert.ok(Math.abs(at(1.25) - minus6) < 1e-6, 'the body prints at -6 dB');
  assert.ok(Math.abs(20 * Math.log10(at(1.9)) - -6) < 0.01, 'still -6 dB right up to the fade');
  assert.ok(Math.abs(at(2.5) - minus6 * 0.5) < 1e-3, 'half way down the fade-out');
  assert.ok(at(2.99) < minus6 * 0.02, 'nearly silent at the end of the fade');
  assert.equal(at(3.5), 0, "the release tail past a faded clip's end is silent, as live");
  assert.equal(got.channels[1][Math.round(0.25 * rate)], got.channels[0][Math.round(0.25 * rate)], 'both channels');
  assert.equal(printed.gain, undefined, 'the print itself plays at unity: the gain is in its samples, not applied twice');

  // A clip with gain and no fade-out: the tail rings on at the clip's gain; the next clip takes over at its start.
  const a = clip('a', 'vln', 0, [note(0, 60, 4)], { durationSec: 1, gain: 0.5, fadeInSec: 0.5 });
  const b = clip('b', 'vln', 2, [note(0, 62, 4)], { durationSec: 1, gain: 0.25 });
  const two = await printInstrumentTracks({ bpm: 120, tracks: [track('vln', { instrument: strings })], clips: [a, b] }, { kind: 'master' }, render, { sampleRate: rate });
  const p2 = two.clips.find((c) => c.id === 'instrument-print:vln');
  assert.ok(p2?.audioBlob);
  const s2 = readWavSamples(await p2.audioBlob.arrayBuffer());
  const at2 = (sec: number) => s2.channels[0][Math.round(sec * rate)];
  assert.ok(Math.abs(at2(0.25) - 0.25) < 1e-3, "half way up A's fade-in, at A's gain");
  assert.ok(Math.abs(at2(1.5) - 0.5) < 1e-6, "A's release rings at A's gain");
  assert.ok(Math.abs(at2(2.5) - 0.25) < 1e-6, 'B owns the envelope from its start');
  assert.equal(instrumentGainAt([a, b], -1), 1, 'before any clip: unity');

  // All clips at unity with no fades: the print is handed on untouched.
  const flat = await shapeInstrumentPrint(fullScale(1), 0, [clip('u', 'vln', 0, [note(0, 60)])]);
  assert.equal(readWavSamples(await flat.arrayBuffer()).channels[0][10], 1);
}

// ── the client: one track per request, the multipart answer read back ─────────
{
  let sent: { url: string; body: unknown } | null = null;
  const fakeFetch = (async (url: string, init: RequestInit) => {
    sent = { url, body: JSON.parse(String(init.body)) };
    const form = new FormData();
    form.append('report', JSON.stringify({ tracks: [{ track_id: 'vln', part: 'track-0', frames: 44100, sample_rate: 44100, warnings: [] }] }));
    form.append('track-0', new Blob([new Uint8Array([1, 2, 3])], { type: 'audio/wav' }), 'track-0.wav');
    return new Response(form);
  }) as unknown as typeof fetch;
  const req: InstrumentRenderTrack = { track_id: 'vln', plugin_path: 'C:/VST3/Strings.vst3', raw_state: '', state_host: '', params: {}, duration: 1, events: [{ t: 0, data: [0x90, 60, 100] }] };
  const out = await renderInstrumentTrack(req, 44100, fakeFetch);
  assert.ok(sent);
  assert.equal((sent as { url: string }).url, '/api/vst/render-midi');
  assert.deepEqual((sent as { body: unknown }).body, { sample_rate: 44100, channels: 2, tracks: [req] });
  assert.equal(out.trackId, 'vln');
  assert.equal(out.frames, 44100);
  assert.equal((await out.audio.arrayBuffer()).byteLength, 3);

  const refusing = (async () => new Response(JSON.stringify({ detail: 'Track vln: Strings is not an instrument plugin, so it cannot play MIDI' }), { status: 400, headers: { 'Content-Type': 'application/json' } })) as unknown as typeof fetch;
  await assert.rejects(renderInstrumentTrack(req, 44100, refusing), /not an instrument plugin/);

  const noReport = new FormData();
  await assert.rejects(parseInstrumentRender(noReport), /without a report/);
}

// ── the slot in the store: set, switch off, state, freeze and unfreeze ─────────
{
  const ed = useEditorStore.getState();
  const tid = ed.addTrack({ name: 'Violins I' });
  useEditorStore.setState((s) => ({ clips: [...s.clips, clip('sv', tid, 0, [note(0, 67)])] }));
  ed.setTrackInstrument(tid, { plugin_path: 'C:/VST3/Strings.vst3', plugin_name: 'Strings' });
  const t1 = useEditorStore.getState().tracks.find((t) => t.id === tid);
  assert.ok(t1?.instrument?.vst);
  assert.equal(t1.instrument.effect, 'vst3');
  assert.ok(activeTrackInstrument(t1));
  assert.equal(trackSoundChain(t1)[0].id, t1.instrument.id, 'the instrument sits ahead of the inserts');
  useEditorStore.getState().setTrackInstrumentRawState(tid, 'bmV3', 'thedaw');
  const t2 = useEditorStore.getState().tracks.find((t) => t.id === tid);
  assert.equal(t2?.instrument?.vst?.raw_state, 'bmV3');
  assert.equal(t2?.instrument?.vst?.state_host, 'thedaw');
  useEditorStore.getState().toggleTrackInstrument(tid);
  assert.equal(activeTrackInstrument(useEditorStore.getState().tracks.find((t) => t.id === tid)), null, 'switched off');
  useEditorStore.getState().toggleTrackInstrument(tid);

  useEditorStore.getState().freezeTrack(tid, { audioBlob: blob, durationSec: 4 });
  const frozen = useEditorStore.getState().tracks.find((t) => t.id === tid);
  assert.equal(frozen?.instrument, undefined, 'a frozen track plays its stem, not its instrument');
  assert.equal(frozen?.frozenOriginal?.instrument?.vst?.raw_state, 'bmV3', 'the instrument waits for the unfreeze with its state');
  useEditorStore.getState().unfreezeTrack(tid);
  const back = useEditorStore.getState().tracks.find((t) => t.id === tid);
  assert.equal(back?.instrument?.vst?.plugin_path, 'C:/VST3/Strings.vst3', 'unfreeze puts it back');

  useEditorStore.getState().setTrackInstrument(tid, null);
  assert.equal(useEditorStore.getState().tracks.find((t) => t.id === tid)?.instrument, undefined, 'the slot empties');
}

console.log('vstInstrumentMidi: all assertions passed');
